### ISSUE TITLE
Error while confirming trades

### ISSUE THREAD

**Issue by AdamWTS** [Jessecar96/SteamDesktopAuthenticator#10]
Hello,
I've set up my account successfully, entered the email and phone message correctly, started receiving random token codes every 30 seconds or so.
But, whenever I click the "Trade confirmations" button, the app encounters an error:

"An unhandled exception has occured. If you click Continue, the app will ignore the error and try to continue the operation"
[...]
The value cannot be zero
Parameter name: input.
Error details
    System.ArgumentNullException: The value cannot be zero.
    parameter name: input
       in System.Text.RegularExpressions.Regex.IsMatch(String input)
       in SteamAuth.SteamGuardAccount.FetchConfirmations()
       in Steam_Desktop_Authenticator.ConfirmationForm.loadConfirmations()
       in Steam_Desktop_Authenticator.ConfirmationForm..ctor(SteamGuardAccount account)
       in Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
       in System.Windows.Forms.Control.OnClick(EventArgs e)
       in System.Windows.Forms.Button.OnClick(EventArgs e)
       in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       in System.Windows.Forms.Control.WndProc(Message& m)
       in System.Windows.Forms.ButtonBase.WndProc(Message& m)
       in System.Windows.Forms.Button.WndProc(Message& m)
       in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This doesn't let me confirm my trades. Can you please help me find the solution?

**Comment by Z8pn** [comment]
got the same issue

**Comment by lavaraba** [comment]
Same issue, it was working fine a few days ago. Maybe Valve found a way to block this app? I hope not :(

**Comment by Jessecar96** [comment]
I get this too intermittently. Haven't looked into it yet.

**Comment by Momchoto** [comment]
It was working fine for a while, but today it too started showing that error!

**Comment by Bkira** [comment]
Yep. Suddenly the app is only showing this error no matter what.

**Comment by geel9** [comment]
The newest version should resolve this issue.

**Comment by Momchoto** [comment]
So i downloaded the new version and now what? I tried entering my old login info, but it said that it was already active!

**Comment by AdamWTS** [comment]
I updated to the 0.2.3 build and now it works correctly. Thank you for the help!

**Comment by Momchoto** [comment]
Nevermind, just had to remove the mobile authenticator from steam. Thanks again!
