### ISSUE TITLE
Can't Confirm Trades (Confirmation Message Keeps popping up)

### ISSUE THREAD

**Issue by Tw1nzer** [Jessecar96/SteamDesktopAuthenticator#1007]
Each time I click on confirm on the Trade Confirmation tab, the trade doesn't actually gets confirmed and the confirmation message just keeps on reappearing again and again without confirming the trade. Revoking the trade works but confirming it doesn't work. please fix!!

**Comment by Tw1nzer** [comment]
Update: I tried to login again and also tried to auto-confirm trades, but nothing seems to work anyone else facing the same issue, or is it just me?

**Comment by peralp61** [comment]
Same thing for me...

**Comment by Tw1nzer** [comment]
fixed I guess it was a problem with steam itself
