### ISSUE TITLE
STEAM NEW EMAIL VERIFICATION CODE please check desc

### ISSUE THREAD

**Issue by lilkajt** [Jessecar96/SteamDesktopAuthenticator#1018]
![new emails](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/87129505/302dba84-6e1e-4b1f-b128-ceb4f72737b9)

When adding a new account to the SDA, first we receive an email with a code to log in.
log in.
Socondly Steam sends another email that looks like my pic.

The SDA doesn't ask for a second code so you cant add new accounts at the moment.

**Comment by globart** [comment]
There is version 1.0.14, which is in "pre-release" status for some reason, but it works, just tested. You can just unpack the files to your SDA folder with option to replace existing ones. Here is the link - https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.14

**Comment by lilkajt** [comment]
Yes, rn you dont need sms code just code from email and it works but only on SDA 1.0.14.
