### ISSUE TITLE
set Cookies Error:  HTTP error 429

### ISSUE THREAD

**Issue by Kizzuwatnaa** [Jessecar96/SteamDesktopAuthenticator#1026]
![helpme](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/154545455/f97afbad-b102-44ac-9454-97425f67a195)
I get this error every time I try to log in, how can I add a rate limit?

**Comment by dyc3** [comment]
You cannot "add rate limit." Rate limiting is a limitation imposed by Valve. There is no possible way for you to get "more rate limit." Just wait like 2 days and try again.
