### ISSUE TITLE
error adding your authenticator 

### ISSUE THREAD

**Issue by kodzip115** [Jessecar96/SteamDesktopAuthenticator#1035]
every time itry to add my account it says error adding your authenticator i tried turning off my steam guard didnt work someone said turn off my internet and try it nothings working 
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/160136690/f65b31e4-5941-4b2e-8321-18e24f285853)

**Comment by MiguelX413** [comment]
I'm getting the same issue.
