### ISSUE TITLE
Sms doesn't work

### ISSUE THREAD

**Issue by MarcosLSS** [Jessecar96/SteamDesktopAuthenticator#104]
I put my phone number from Brazil (+555197******) and return this error: Error adding your phone number. Steam returned "GeneralFailure".

**Comment by routemasters** [comment]
more like an issue with your password if it has currency symbols in it.

**Comment by hyt47** [comment]
use steam 
 - Open Steam > settings > (in the top right) view Account Details > Add a phone number

or use the browser
- https://store.steampowered.com/account/

Setup your Account on Steam Desktop Authenticator

**Comment by voltij** [comment]
one note i have is that even if i add the phone number (and confirm it) using the browser, SMA still asks for a phone number. this is on a new account.

**Comment by smsisghetto** [comment]
Yep same issue as the voltji guy. Even have the phone number

**Comment by MarcosLSS** [comment]
my phone number is already on steam...

**Comment by MarcosLSS** [comment]
the problem is Family View ;)
