### ISSUE TITLE
Awesomium instead of CefSharp

### ISSUE THREAD

**Issue by pipe01** [Jessecar96/SteamDesktopAuthenticator#105]
I was thinking, why did you choose CefSharp over other browsers like Awesomium? Does it contain any special feature? Also, if I'm not mistaken, it supports Mono.

**Comment by Jessecar96** [comment]
CefSharp looked like the most used. I'm not really interested in switching because it took a lot of work to get trade confirmations working on it. Handling the steammobile:// links was pretty annoying.

**Comment by pipe01** [comment]
That's totally up to you.
