### ISSUE TITLE
"Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found. File name: 'CefSharp.Core.dll'"

### ISSUE THREAD

**Issue by k9delta** [Jessecar96/SteamDesktopAuthenticator#106]
I have all of the files in a folder, when i click "Trade Confirmations" it gives me this:
![bug](https://cloud.githubusercontent.com/assets/16328517/11856715/e7d6ec12-a420-11e5-9f38-616da5b60c88.png)

**Comment by k9delta** [comment]
And yes, the file is in that folder

**Comment by Jessecar96** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/wiki/CefSharp-Troubleshooting
