### ISSUE TITLE
Question (about Steam web API revocation)

### ISSUE THREAD

**Issue by AsadAlrafidain** [Jessecar96/SteamDesktopAuthenticator#1063]
Forgive me if this is not the right place... I don't know where else to ask.
I want to revoke the steam web API associated with my account..will that affect SDA (which is currently working fine)?

**Comment by dyc3** [comment]
No, revoking the steam web api key won't affect how SDA works. SDA uses your account credentials to authenticate with the API, and your API key is not used.
