### ISSUE TITLE
The program is not responding.

### ISSUE THREAD

**Issue by valeriy-efimov** [Jessecar96/SteamDesktopAuthenticator#107]
![sdasd](https://cloud.githubusercontent.com/assets/5989188/11857008/79ed8642-a45d-11e5-9186-9705880c8561.png)
Tell me what's wrong. This screen not react to my actions, just stuck it.
Windows 8.1 x64
In the code, I have not changed anything.

**Comment by Jessecar96** [comment]
You probably don't have ADB installed. Importing from Android is still a WIP
Try this easy adb installer: http://forum.xda-developers.com/showthread.php?p=48915118#post48915118

**Comment by valeriy-efimov** [comment]
@Jessecar96  Thank you very much! Working!

**Comment by pipe01** [comment]
That shouldn't happen, I'm gonna take a look later.
