### ISSUE TITLE
Error with differense computers

### ISSUE THREAD

**Issue by DonHexagon** [Jessecar96/SteamDesktopAuthenticator#11]
When I create maFile on my own PC and move it to another one, I get the following error "Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones" when pressing "Trade Confirmation" button. When I create maFile on the other computer, I have not this problem. But in case when I try to copy the files 2 → 1, I get the same error

**Comment by Jessecar96** [comment]
I can confirm this happens with me too, don't know why yet.

**Comment by DonHexagon** [comment]
0.2.3 release solve this bug, thx

**Comment by Zignixx** [comment]
had this bug and i think it was the cookie. #8 

But it's fixed now :)
