### ISSUE TITLE
Lag in the new code

### ISSUE THREAD

**Issue by hyt47** [Jessecar96/SteamDesktopAuthenticator#110]
@Jessecar96
I was testing the last update, (the source code not the official release), and the app has a lot of lag when i try to move it.
The buttons are the same with lag a few milliseconds.
I guess it's because, it automatically checks for incoming trade confirmations. 
To have an app that checks for stuff is nice, but I prefer a responsive GUI app

The rest looks great :)

**Comment by pipe01** [comment]
Why did you close?

**Comment by hyt47** [comment]
because i assumed @Jessecar96 will compile the code and get the same results

**Comment by pipe01** [comment]
Yes, and I did have lag when coding it, but I thought it was my sheety PC, so I ignored it. I am gonna fix it now.

**Comment by pipe01** [comment]
The reason is, as you said, it checks for conformations every 5 Sec, so it lags a bit. I'll just make it into a thread, which should fix it.

**Comment by hyt47** [comment]
yea that's a good ideea

**Comment by pipe01** [comment]
For some strange reason, the UI lags even when using Threads and BackgroundWorkers, so I guess Jesse or anyone else would have to fix it.

**Comment by Jessecar96** [comment]
It's already fixed. Had to make async methods in SteamAuth

**Comment by hyt47** [comment]
Cool
