### ISSUE TITLE
Finding Identity_secret

### ISSUE THREAD

**Issue by IcarusRising** [Jessecar96/SteamDesktopAuthenticator#111]
I searched if this had been asked before, but didn't find it.

For trade automation it is needed to have my identity_secret.
There are ways of finding it with a rooted android or Iphone, but I would have to change authenticator for that. (and be subject to another 7 day escrow)
So I would prefer to use the desktop authenticator to find my identity_secret.

Is this possible?
If so how?

Thank you!

**Comment by JabLuszko** [comment]
everything is in files in maFiles directory, just open it with some text editor and copy-paste what you need.

**Comment by IcarusRising** [comment]
Naturally I have it encrypted and it's a jumble of random characters..

**Comment by pipe01** [comment]
#103

**Comment by Jessecar96** [comment]
You have to decrypt it to read the file. You can re-encrypt it afterwards.

**Comment by wanderjarra** [comment]
"You have to decrypt it to read the file. You can re-encrypt it afterwards."

Could you explain to me how I can decrypt to get the Identity_secret ????
