### ISSUE TITLE
Version 1.0 suggestions & plans

### ISSUE THREAD

**Issue by Jessecar96** [Jessecar96/SteamDesktopAuthenticator#116]
I'm getting ready to release version 1.0 of SDA and here's what I have planned for this release:

- New update/distribution mechanism. Using [Squirrel](https://github.com/Squirrel/Squirrel.Windows) as an installer and updater. The program will install to a user's AppData folder and keep all files there. The user should not have to deal with maFiles and this leaves them out of the way so they don't accidently delete them. I will host the installer and update files on an Amazon S3 bucket. 
- On first run of a new install in AppData, a WelcomeForm dialog shows up asking to import any previous install's config file, or if this is the first time they're using SDA they can import from Android or just sign in.
- Importing from an Android device will be finalized. It should be very easy for a user to use. I will be packaging adb along with SDA so they don't have to get it themselves.
- Also on first run SDA will automatically download and install Visual C++ Redistributable 2013 for CefSharp to function. If they ignore this they will just be prompted again when they open trade confirmations.
- Trade confirmation popups.
- A settings form to control if they want periodic checking for confirmations.
- Still really need an icon :/

I think this is enough for v1.0. Any other suggestions?

**Comment by ItsHipsterNoah** [comment]
Here are a few suggestions:

**Functionality:**
* A button that says "Report an Issue" with a link to the issues page on GitHub.
* When a new version is available, the notification popup should appear after the user logs in with their encryption passkey.
* Auto-accept trade confirmations (#32) 

**Cosmetic:**
* The app should definitely have an icon. This is a minor addition, but it would definitely add to the UX. @hyt47 and I designed a couple in #75.
* General UI changes to match that of the trade confirmation window. 

*I'll update this comment with more ideas when I come up with them.*

**Comment by pipe01** [comment]
I think ADB can't be redistributed, as it's part of Android Studio.

**Comment by pipe01** [comment]
Also, I think it should be more portable, unless it's not your fault but mono's.

**Comment by hyt47** [comment]
Trade confirmation popups on / off from settings

**Comment by hyt47** [comment]
enable / disable auto check for updates from settings

**Comment by wazerstar** [comment]
Could you at least leave an option to use it as portable, I REALLY HATE splitting up settings/important files from the original place, I know many uses this program also exact because of this.

**Comment by ItsHipsterNoah** [comment]
The old trade confirmation list is way less secure. Plus the new one looks much better.

I personally think it should be left as is. Plus, readding the old one means all of Jesse's work on the new one just goes to waste.

**Comment by pipe01** [comment]
As it's giving so many compatibility issues, I think it wouldn't be that bad if the old trade list activated only when CefSharp fails, so the user can still have most of the functionality.

**Comment by ItsHipsterNoah** [comment]
@pipe01 I wouldn't have a problem if it was a backup. That actually sounds like a great idea. But the new one should stay as is unless there is an error.

**Comment by hyt47** [comment]
did u compile the new code ?

**Comment by voltij** [comment]
stretch suggestions: (won't mind if they aren't implemented for any reason but ideas nonetheless)

1. auto copy-to-clipboard of currently active 5-digit code when you click on an account (with option of turning this on/off)
2. show the number of pending trades to be confirmed in main window next to each account name
3. add automation that will confirm but only if there is a single trade waiting to be confirmed. explanation: many times when you go to confirm a trade it's because you just had accepted a single trade request (or sent a trade request). so user will click account name, then a button "confirm trade request" on main window. kind of a halfway point / stepping stone between current process and automatic accept.

**Comment by pipe01** [comment]
@voltij Gonna try 3 and 2

**Comment by pipe01** [comment]
Wait, isn't your 3rd idea already implemented by the popups? When you accept a trade offer, the popup will appear and you just have to accept it, right?

**Comment by routemasters** [comment]
@pipe01 he means an auto-accept button so he can accept the trade with just one click.

**Comment by pipe01** [comment]
Oh, in that case I don't know if it's possible.

**Comment by voltij** [comment]
I do a lot of trading to and from my main to my many alts (CSGO betting)

The last time I did any significant trading the process was:

1. click account name
2. click trade offers button (new window loads)
3. click on trade offer to confirm
4. click accept (some time elapses while trade completes, then popup prompt with OK button)
5. click OK or [x] to close prompt
6. click [x] on trade offers 
7. repeat from step 1 with next account

my suggested process would be

1. click account name
2. click confirm trade offer (some time elapses while trade completes, then popup prompt with OK button)
3. click OK or [x] to close prompt (or remove prompt entirely)
4. repeat from step 1 with next account

it may sound like a minor time savings but it would really streamline the use of the program

**Comment by routemasters** [comment]
@pipe01 the other standalone steam authenticator has this feature, but tbh i prefer to double-check, in case i missed something on the steam screen.

but copy-to-clipboard would make it easier to manage multiple accounts.

**Comment by pipe01** [comment]
It's really insecure to accept confirmations without knowing who it's from, so I will put a dialog asking you or something.

**Comment by routemasters** [comment]
well yea i agree on that. instead this i would prefer a steamrep plugin which highlights in bold red a trade offer coming from a steamrep-marked account.

**Comment by pipe01** [comment]
That's way too complicated, I don't think it's worth it to implement all of that, although I don't know how hard it is.

**Comment by voltij** [comment]
I agree that it's insecure, BUT if you limit the functionality to making sure there's only one trade waiting to be confirmed, the chances that the trade is something you don't expect are 0%.

The least you could do is have an option for the user to disable any security check that is "for the user's protection". <insert joke about Steam forcing escrow here>

**Comment by pipe01** [comment]
If you are the one making the trade offer then it's 100% safe, but if it's incoming then it could be from anyone and you wouldn't know.

**Comment by voltij** [comment]
Trades only show up in the "awaiting confirmations" list after you've either attempted to send an offer or attempted to accept an offer (using browser or steam client).

So if you're accepting an offer, you'd have to be in browser or client and hit Accept, then go to SDA. If there's only one trade offer there, there is 0% chance that it's anything but the offer you just attempted to accept.

What's your thoughts on this?

**Comment by pipe01** [comment]
That's right, although, just to be sure, I will still make the message box to appear, and maybe add a config option to disable it as well.

**Comment by Jessecar96** [comment]
I won't be adding auto-accepting confirmations for 1.0. It puts way too much liability on us if users leave it on and get scammed.

**Comment by hyt47** [comment]
@Jessecar96
add copy to clipboard button next to Login Token

button script `System.Windows.Forms.Clipboard.SetText("String to add to clipboard");`

**Comment by pipe01** [comment]
You can already copy the code with the tray icon

**Comment by pipe01** [comment]
Maybe upload the maFiles to the user's custom server, which is very unsafe if someone breaks in to your server, but if you somehow lose or accidentally break your maFiles, you can download them.

**Comment by hyt47** [comment]
Thx guys, for all your hard work, code & ideas, I finished compiling a version **for me.**
I removed the trade popups & the tray icon.
The trade popups I think, i'm gonna add part of the code, and transform it in auto accept.

![1](https://cloud.githubusercontent.com/assets/10192561/11912584/c39608ec-a64b-11e5-8c2d-e494f2ee86b3.png)

Everyone has different expectation from this program, there is no bad version. Cool that we have the source code to modify it as we want.

**Comment by novikk** [comment]
+1 for having https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/32 in v1.0

**Comment by YeowLikeWhoa** [comment]
@Jessecar96 So does that mean that Auto-Accept confirmations are completely off the table or solely for version 1.0? You guys already warn pretty heavily about using this, might as well throw in a warning about the auto-accept confirmations as well.

**Comment by hyt47** [comment]
I guess there will be some code for auto accept, in the future, but the code will not be integrated in a release. And you will have to add it to the app and compile it, because it's a big security risk, and only those who know what they are doing, will have access to that feature.

**Comment by routemasters** [comment]
@YeowLikeWhoa not like they can't or not able to add it, it is because of the users. I have people all time coming back to me saying that they want to reverse the trade because they found another trader or their friends told them they overpaid, or their friends found someone else with a lower price etc etc etc. People lie and it is more common in the trading scene.

If they add auto-accept trades, I can assure you, there will be people calling names and even demanding compensation for a trade they accepted after checking on the client or browser. That's why it wont be added.

**Comment by pipe01** [comment]
@hyt47 Why did you remove the tray icon? 
@routemasters Copy to clipboard is already available.

**Comment by routemasters** [comment]
@pipe01 not on the 0.3.1

**Comment by YeowLikeWhoa** [comment]
@routemasters I'm well aware of why they are hesitant to add it, but I was simply asking for clarification on Jesse's statements. There are already people calling names and spreading misinformation about this program because they think that the big bad Geel is the one that requires a phone number and not Steam, or that Geel himself is responsible for escrow somehow. Using this program already comes with a magnified risk of getting your account stolen, but perhaps the auto-accept could be added behind a password protected menu to prevent people from casually enabling it.

**Comment by pipe01** [comment]
@routemasters Oh, I meant in the repo

**Comment by hyt47** [comment]
@pipe01 
I don't really like to use the try right click menu to do regular stuff, (I feel that try menu is for options that are rarely used)
I might add in the future the try icon back, if I add auto accept,
but for now I like to use the main form, and I don't mind keeping the app opened on the taskbar.
Your code (popups) is awesome, but I don't know if I will use it.
I wanted a basic form with almost all the upgrades.
I will try the popups again when the v1.0 is released :)

Thx @pipe01, for your code. You keep adding stuff you like. It's awesome to see new stuff ^_^

I will publish my `new mod` soon!

**Comment by wazerstar** [comment]
It's really simple, just add auto accept for incoming trades without you offering anything and make a warning options if you want to have auto accept on for in/out + your offerings.

**Comment by ItsHipsterNoah** [comment]
For those who liked the old confirmations list, maybe there could be a checkbox that could enable the old one.

**Comment by wazerstar** [comment]
@hyt47 
You should let us login to steam via the app and add the 2fa code by it self whenever the asking window shows up.

Kinda like when using steam -login username password

Show linking steam account to ma profile
Pressing steam launching steam when dir added via option.
logging into steam via steam.exe -login %username% %password%
waiting and scan for 2fa %window%
get %2fa% code from app
add it to steam 2fa %window% hit ok..

Make that happend,

That would be cool ;)

**Comment by hyt47** [comment]
I will not do that. 

For multiple accounts I use Opera portable browser, so I can trade. 
For each account I have a separate browser stored in my email folder.
Also Opera can remember my username & password & is only asking for the Authenticator code. 

I also have a clean installation of steam for each account (archived, I don't use it, unless i'm on a virtual machine).

Anyway, I like to keep the accounts separately.

**Comment by Fl4ilinat0r** [comment]
I would like
Auto-accept trade confirmations (#32)
to be added

**Comment by pipe01** [comment]
To do that, you would need to know when an offer is made and if the receiver has steam guard enabled, which, if even possible, would be a lot of changes to SteamAuth

**Comment by hyt47** [comment]
If the app is encrypted:
- disable `Import Account`
- rename `Import Account` to `Import Account - Disable the Encryption First`

If encryption is disabled, reverse

**Comment by Nonickn** [comment]
Please add Auto-accept trade confirmations (#32)

**Comment by ItsHipsterNoah** [comment]
@Fl4ilinat0r @Nonickn They won't be added.
![capture](https://cloud.githubusercontent.com/assets/13893647/11921441/c60c8450-a73d-11e5-80dc-461c2696e08a.JPG)

**Comment by Nonickn** [comment]
I have read it, I'm just disagree. It's a Valve's way "5% of our users are stupid so let's make life harder for all whole community". Make Auto-accepting trade confirmations optional, warn people when they will turn it on, but don't take your users as kind of imbeciles.

**Comment by ItsHipsterNoah** [comment]
@Nonickn I see what you're saying. But if it is implemented, imagine the incredible amount of issue reports that'll be posted complaining about lost items. It's practically guaranteed to happen, even if the most obvious warning signs are placed. People will say, "Oh, well I didn't know that's what it did. It's your guys' fault for making that stupid feature!' or something along those lines.

And to be honest, is going to the Authenticator and accepting the trade *really* that big of a hassle? Unless you trade *very* frequently, it only takes (literally) two minutes to accept a trade. And with out automated confirmation, it gives you one more chance to rethink a deal. You might think (after looking at the trade in SDA) that maybe it isn't such a great deal, or that you're getting underpaid, or maybe you don't want to trade that item after all.

**Comment by voltij** [comment]
@ItsHipsterNoah for one account and one trade, sure it's not a hassle. but for example i am routinely processing 50+ trades 3 to 5 times per day between my accounts. 

adding auto-confirm to SDA will not make you any less secure than you were one month ago when escrow/restrictions weren't active.

are you afraid that idiots are going to get scammed and blame SDA?

* make it default off in an options screen with big red popup that says "DONT DO THIS IF YOU ARE AN IDIOT" when you try to turn it on
* make it so it's only enabled when you use a secret launch option via a shortcut
* make it so you have to launch the program with CTRL and ALT held to enable it

i really don't like the "we are doing this to protect you from you" line of reasoning.

for every 1 person that gets scammed, there will be 1,000 people that are thankful for no longer being inconvenienced by trade restrictions.

**Comment by YeowLikeWhoa** [comment]
@ItsHipsterNoah If the intent of this program was to protect everyone from themselves, then the best course of action would be to remove this program and force everyone to either use an actual phone or wait the 3 days. There is already a massive warning on this program and Geel specifically states that this program is not secure at all. Trading existed just fine for many years without giving people the need to second guess their trades, I don't see why that should matter now.

**Comment by novikk** [comment]
@ItsHipsterNoah Also, in our case, it is a big hassle actually. We have a "network" of steam accounts that trade frequently between them to balance their inventories, manage trades with other users, etc.
It would be just great if we had to do nothing at all, just like it was before this phone confirmation thingy.

@Jessecar96 If you really don't want to add it to SDA, maybe you could just provide a piece of code and some instructions so that we compile our own version with auto-accept enabled?

**Comment by hyt47** [comment]
@Jessecar96 add code

MainForm
`Minimum Size` for the GUI the same as default size

**Comment by pipe01** [comment]
I think I'm gonna do so, but I will hide the option to enable it so you can only enable it by searching in the source code or hide it in your PC or something like that. Then, it's up to Jesse to accept it or not.

**Comment by hyt47** [comment]
yeah that's a good idea, code disabled
