### ISSUE TITLE
Error logging in. Steam returned "General Failure" .

### ISSUE THREAD

**Issue by Denix-spb** [Jessecar96/SteamDesktopAuthenticator#121]
Lately if setup new account after entering login and password gives an error message - Error logging in. Steam returned "General Failure" . 
Who knows what to do ?

**Comment by hyt47** [comment]
did u use a released version ?

**Comment by fiveofeight** [comment]
Getting the same issue here, v0.3.1

**Comment by Denix-spb** [comment]
i use  v0.3.1

**Comment by routemasters** [comment]
i am getting these as well, its either a password error if you use a currency symbol in it or added and removed the same phone number in short periods. it's an issue with steam.

**Comment by MarcosLSS** [comment]
make sure the Family view it's off

**Comment by vparitskiy** [comment]
Same issue, fresh install 0.3.1
