### ISSUE TITLE
Add other confirmations

### ISSUE THREAD

**Issue by MetalRuller** [Jessecar96/SteamDesktopAuthenticator#122]
Things like disable-confirmations of market stuff or the likes can't really be changed since we can't confirm them on this app.
Adding them would be cool, I personally wanted to sell my stuff on market and couldn't because I get neither the "Disable market confirmations" confirmation nor do I get the actual market selling confirmations.
Thanks.

Edit : Also, the Remove Authenticator button doesn't seem to work in 0.31

**Comment by Ps1d3r** [comment]
On earlier versions you had market confirmations just by using the "trade confirmation" button

**Comment by MetalRuller** [comment]
After disabling market/trade confirmations on steam you need to confirm doing so in your email/app.

**Comment by Ps1d3r** [comment]
Oh i see... Try enabling it back on, and use one of the previous versions.. You should get the market confirmation on the trade confirmations dialog.

To use previous versions you just have to download them, then copy the maFiles folder in to the older version app folder, then open the app. 
See if it works for you.

**Comment by MetalRuller** [comment]
I didn't post here due to my own problems, I compiled my own version of fixed code of this, I posted merely to let geel/jesse know of potential future ideas to add, thanks though.

**Comment by Ps1d3r** [comment]
Oh ok

**Comment by Jessecar96** [comment]
I tested this with setting "Confirmation of Community Market Actions" to disabled and it worked fine in the latest version.
