### ISSUE TITLE
Keep having to setup new account?

### ISSUE THREAD

**Issue by volovikariel** [Jessecar96/SteamDesktopAuthenticator#123]
I had the program open for about 5-6 days.. I had to restart pc because it was spasing out, so  I did. I reopen the program and it tells me to setup new account... How can I re-access my previous one?

**Comment by hyt47** [comment]
your steam data was encrypted ?
Do you have in the `maFiles` folder the file with the extension `.maFile` ?

**Comment by volovikariel** [comment]
mafiles has .json and that's it. It was encrypted indeed.

**Comment by pipe01** [comment]
It was somehow removed,which is not good at all. If you have your revocation code, you can recover it. If not, you may have to contact steam support. Although first of all do a .mafile search on the explorer just in case it got moved or something.

**Comment by volovikariel** [comment]
I mean I can recover it... but I'll have to redo the 7 day wait right? :/ Sigh I'm never gonna be able to trade. And it's like the 4th time it happens, it always goes away. I run windows 7, maybe disable my antivirus ( bitdefender) ??

**Comment by pipe01** [comment]
If you get the mafile again, back it up to a pen drive or something where you know you'll always have and it will be safe. And I have no idea what the cause may be, sorry.

**Comment by volovikariel** [comment]
When I try to setup new account it says "error loging in. Steam returned "generalfailure" D:

**Comment by vlogerM** [comment]
"General failure" means the Steam servers are busy now. You need to wait, and try again later.

**Comment by volovikariel** [comment]
Alright thanks a lot :+1:

**Comment by pipe01** [comment]
Well, a general failure is that, general, which means it can have many reasons. In some cases the message may contain more information.

**Comment by volovikariel** [comment]
I just setup a new account and the mafile wasn't actually even created!!!!
 only json file, turned of antivirus as well???? what's going on.

**Comment by pipe01** [comment]
Try with a clean installation.

**Comment by volovikariel** [comment]
Did, installed a new one. Still general failure and such.

**Comment by pipe01** [comment]
If you have any smurf account, try to do it with that one. If not, just wait a while and try again.

**Comment by pipe01** [comment]
Also, are you using the latest version (v3.1.0) or did you compile by yourself?

**Comment by volovikariel** [comment]
I downloaded a new one, it finally let me do stuff and I made an account, encrypted etc (using 3.1) and still only a manifest.json file.

**Comment by hyt47** [comment]
next time backup your app or the `maFiles` folder, preferably in an archive

**Comment by volovikariel** [comment]
?? backup the app? When I setup an account it asks wether i wanna do something (modified files or smthin) into the archive, I say yes.. there's never a mafile, it just isn't created D:

**Comment by pipe01** [comment]
Do you have the steam app on your phone?

**Comment by volovikariel** [comment]
I do but it's a deactivated phone so I can't receive sms, I used an sms receive , (maybe that's why? )

**Comment by pipe01** [comment]
Is your steam guard account activated on your phone?

**Comment by volovikariel** [comment]
No. Only way to do that I believe is if I can receive an sms, and I cannot so I used an sms receiver website where I use somebodie elses phone or something, I basically only use the program, never touch my phone

**Comment by pipe01** [comment]
Sorry, I have no idea on how to fix your problem :/

**Comment by volovikariel** [comment]
Soooooooooooooo - what can I do? XD

**Comment by pipe01** [comment]
You can use the official app on your phone.

**Comment by volovikariel** [comment]
the official steam one? Alright i'll try  it out... maybe I can download a sms receiver directly on a phone or something, thanks anyways. :/

**Comment by pipe01** [comment]
You can try Google Voice, it seems like it does the job.

**Comment by volovikariel** [comment]
google voice? I can download it on the phone so i can receive sms?

**Comment by vlogerM** [comment]
You don't need to recive SMS on the same device as you use for Steam Mobile app.

**Comment by volovikariel** [comment]
Oh really? :O

**Comment by pipe01** [comment]
Never used it, but I think you just create an account either on your computer or phone and it gives you a phone number.

**Comment by vlogerM** [comment]
SMS code is for phone number verification. Not for device verification.

**Comment by pipe01** [comment]
Yes, I thought you already knew that

**Comment by volovikariel** [comment]
I don't have a phone number, it's a desactivated phone, it's not rly a phone anymore actually... hmm

**Comment by volovikariel** [comment]
they said there wont abe anymore mafiles enxt update so ill consider it fixed

**Comment by pipe01** [comment]
Who said that?

**Comment by volovikariel** [comment]
I read up somewhere, I think jessicar posted it in issues or something talking about what's gonna be new ( something about squirrels replacing mafiles etc.)

**Comment by volovikariel** [comment]
it was posted 3 days ago  or so

**Comment by volovikariel** [comment]
I'm getting ready to release version 1.0 of SDA and here's what I have planned for this release:

New update/distribution mechanism. Using Squirrel as an installer and updater. The program will install to a user's AppData folder and keep all files there. The user should not have to deal with maFiles and this leaves them out of the way so they don't accidently delete them. I will host the installer and update files on an Amazon S3 bucket.

**Comment by pipe01** [comment]
That means there will still be maFiles but they will be completely managed by Squirrel so you don't even have to touch them.

**Comment by volovikariel** [comment]
For me they don't even get created.. :/ and I keep getting general failure even after deleting program and restarting pc and reinstalling
