### ISSUE TITLE
SDA can bypass 3 days hold ?

### ISSUE THREAD

**Issue by athanh8807** [Jessecar96/SteamDesktopAuthenticator#127]
Both accounts are activated SDA, so we can bypass 72 hours trade hold by steam ?
Because I see the warning when send offers: "Trade will be held for: 72 hours. <User> has not been using the Mobile Authenticator for 7 days or has turned off trade confirmations"

**Comment by voltij** [comment]
you have to authenticate with SDA then wait 7 days. then you should not experience a 3 day hold.

SDA basically is a replacement for the steam app regarding authentication and trade confirmations.

**Comment by Ps1d3r** [comment]
Unless the other person you're trading with doesn't have it, it's what voltij said
