### ISSUE TITLE
Trade confirmations suddenly not working on only one account

### ISSUE THREAD

**Issue by muchael100** [Jessecar96/SteamDesktopAuthenticator#129]
My authenticator just from another day to another stopped showing trade confirmations. Steam says the normal things about that i should accept on my phone and all that. But then i go into trade confirmations, there's nothing. https://gyazo.com/17b5dfd3f939fbc090115f2f5dd53d5e
I have 2 alternative accounts linked to it and on them i can accept trade offers perfectly.
I've had this for about 5 days now. I have tried to replace the programs files with a new set, and that doesn't help. I think the progem has screwed up the account in some way.

**Comment by muchael100** [comment]
I also couldn't remove authenticator from my account, i had to use my recovery code to do so.

**Comment by pipe01** [comment]
This seems to be an issue that has occured to some users, so it may be a bug.

**Comment by routemasters** [comment]
did you change your password or deauthorize other devices?

**Comment by muchael100** [comment]
Haven't changed anything of that.

**Comment by TheIcyStar** [comment]
I'm having the same problem.

**Comment by Thugnificent1** [comment]
Try moving the Ma files to a newly downloaded program. It may very well be a cache problem i guess.

**Comment by iFantz7E** [comment]
Same problem blank window.

SDA 0.3.1 at debug.log
[1222/160709:ERROR:renderer_main.cc(200)] Running without renderer sandbox

and SDA 0.2.9 same as #119

**Comment by pipe01** [comment]
Try  building the latest code from the repo.

**Comment by Jessecar96** [comment]
Should be fixed in the next version

**Comment by iFantz7E** [comment]
I found it still be Blank window on SDA 1.0.0
When I try reload session by press 'Force session refresh' button, it's error as this image.
http://i.imgur.com/FdMG0jm.png

**Comment by iFantz7E** [comment]
Now I can use Confirmation again.
I try press 'Login again' and retype password, then I can use Confirmation.

Please update your README.md
From: "Added a menu item to reload session, use this if your trade confirmations window starts showing blank."
To "Added a menu item to reload session, use 'Force session refresh' or 'Login again' if your trade confirmations window starts showing blank."
