### ISSUE TITLE
Once i enter the captcha code, another one pops up

### ISSUE THREAD

**Issue by BlobbyTroll** [Jessecar96/SteamDesktopAuthenticator#131]
![capture](https://cloud.githubusercontent.com/assets/16395241/11947004/0a6ef5be-a816-11e5-8c46-abde8b1ac38d.PNG)

That code is correct but once i press submit i just opens another one. And because of this i can't log back into my account so help ASAP

**Comment by vlogerM** [comment]
If you can't wait for fix, you can recover your account by using this link:
https://help.steampowered.com/#HelpWithLoginInfo?nav=authenticator
It will remove your mobile auhenticator.

**Comment by DygL** [comment]
Same is happening to me. Please help guys.

**Comment by Jessecar96** [comment]
This could actually mean that your password is incorrect. It's fixed in the latest commits.
