### ISSUE TITLE
[Error] Import from Android 4.4.4

### ISSUE THREAD

**Issue by VitamantPT** [Jessecar96/SteamDesktopAuthenticator#135]
After stage 5/5 of import i got an error:

**System.IO.DirectoryNotFoundException: "C:\Steam.Desktop.Authenticator.v1.0.0\steamguard"**

Folders do not appear. How do I fix this?

**Comment by pipe01** [comment]
Try to run the app as administrator or move the folder to another location.

**Comment by VitamantPT** [comment]
Done. Got the same error

**Comment by pipe01** [comment]
Could you please wait a moment? I still haven't tested v1.0.0.

**Comment by pipe01** [comment]
It does work for me. Is your phone rooted?

**Comment by VitamantPT** [comment]
Yes, but there is a line in the logs "Using no-root method". I do not know why

**Comment by pipe01** [comment]
I'm gonna create a fork to add console logging so I can see exactly what's wrong.

**Comment by pipe01** [comment]
I hate NuGet, it's gonna take a while.

**Comment by VitamantPT** [comment]
OK

**Comment by pipe01** [comment]
Done. Do you want me to upload a prebuilt version or do you wanna compile it by yourself?

**Comment by VitamantPT** [comment]
Prebuilt I think

**Comment by pipe01** [comment]
Uploading.

**Comment by pipe01** [comment]
https://www.dropbox.com/s/jguono66uoq3ssj/Release.zip?dl=0
Run it, do the same steps as you did with the original version and upload to www.pastebin.com the "adblog.txt" file. Hopefully that will help.

**Comment by VitamantPT** [comment]
http://pastebin.com/q04Qq7MV

**Comment by pipe01** [comment]
For some reason, it outputted a different string when checking for root, although the no-root method shouldn't have failed anyways. Gonna look onto it.

**Comment by pipe01** [comment]
Does your phone have a folder called "sdcard" on "/"?

**Comment by VitamantPT** [comment]
Yes

**Comment by pipe01** [comment]
Write this to a .bat file and run it: http://pastebin.com/6qYsschZ

**Comment by VitamantPT** [comment]
Sorry, but I do not understand where I have to run .bat

**Comment by pipe01** [comment]
Create a file on Note Pad, copy and paste the pastebin that i sent before to it, save it as anyname.bat, and double click it.

**Comment by VitamantPT** [comment]
http://pastebin.com/VERWrPcm

**Comment by pipe01** [comment]
Is there a backup.ab in your folder?

**Comment by VitamantPT** [comment]
Yes

**Comment by pipe01** [comment]
Is there a /sdcard/steamauth folder on your phone with backup.ab and another folder called apps?

**Comment by VitamantPT** [comment]
No

**Comment by pipe01** [comment]
Oh, I got it. The no-root method requires BusyBox to be installed. I didn't think of that. For now, you should be able to use the root method. Thanks for helping me discover this!

**Comment by pipe01** [comment]
I will fix the root method on my fork.

**Comment by VitamantPT** [comment]
I look forward to your fork. Thank you

**Comment by pipe01** [comment]
Done. Please try it again and post results.

**Comment by VitamantPT** [comment]
Can I get Release again please?

**Comment by pipe01** [comment]
Sure.

**Comment by pipe01** [comment]
Replace the old exe with this one: https://www.dropbox.com/s/nkgllvi3ynra9wa/Steam%20Desktop%20Authenticator.exe?dl=0

**Comment by VitamantPT** [comment]
Same error http://pastebin.com/ccdxdtWx

**Comment by pipe01** [comment]
I think I uploaded the wrong exe

**Comment by pipe01** [comment]
https://www.dropbox.com/s/nkgllvi3ynra9wa/Steam%20Desktop%20Authenticator.exe?dl=0

**Comment by VitamantPT** [comment]
It stuck http://pastebin.com/NRemuNPQ

**Comment by pipe01** [comment]
Can you add me on steam to talk faster? My name is pipe01

**Comment by VitamantPT** [comment]
The problem was solved thanks to pipe01!

**Comment by pipe01** [comment]
Fixed #139
