### ISSUE TITLE
Minor Suggestions will make it better

### ISSUE THREAD

**Issue by mohamademad** [Jessecar96/SteamDesktopAuthenticator#136]
Can you make the tray icon an optional thing when you minimize ?

Also change the time interval between trade confirmation check ups for minutes or increase the limit, since it is limited to 100 seconds for the current v1

**Comment by pipe01** [comment]
I will look onto it.

**Comment by hyt47** [comment]
I'm working on version 1.0.1, there will be a lot of options added
- optional tray icon already added
- I will increase the limit for confirmation check ups
- In a few hours it will be released ^_^

**Comment by mohamademad** [comment]
Awesome, thanks to all for your great help, you guys are doing awesome job.
