### ISSUE TITLE
Accounts list filter issues and confirmations checking

### ISSUE THREAD

**Issue by voltij** [Jessecar96/SteamDesktopAuthenticator#137]
Tagging @pipe01 because i think he was the primary contributor for these issues...

1. the search bar doesnt scale properly with window size https://i.imgur.com/WiZPxVX.png
2. typing something into the search bar functions incorrectly if you start typing right after clicking on an account http://i.imgur.com/hMs70P7.png (typing the word "Example")
3. if i'm doing it right, trade confirmations checking only works for the selected account. possibility to expand to all accounts? for example, is there a risk of discipline/loss of functionality from Steam if you send too many requests too often?

**Comment by Ps1d3r** [comment]
The search bar scale bug only happens to me if i reduce the size of the window (from original size), if i only expand it and reduce to a size not smaller than original, it will remain normal

**Comment by pipe01** [comment]
1. Fixed
2. I don't get how to reproduce it
3. I will try, but I have no idea about Steam

**Comment by voltij** [comment]
for (2) my method of reproducing is:

1. click on any account in the account list
2. start typing a word.

The first letter is written but then the text cursor moves to the left of that letter, causing the rest of the letters typed to be inserted to the left of the first letter -> attempting to type "Example" becomes "xampleE"

**Comment by pipe01** [comment]
Still don't get it. I click on an account and then click on the box to type.

**Comment by voltij** [comment]
After you click on an account, don't click on the filter box, Just type - the letters show up in the filter box still, but in the wrong order. I thought you had intended for typing to work regardless of if you clicked into the filter box or not

**Comment by pipe01** [comment]
2. Fixed #139

**Comment by voltij** [comment]
you are fast. awesome.

and then for (3) my half-brained idea is for me to run multiple instances of SDA (yes i will have to rename the .exe to SDA1.exe, SDA2.exe, SDA3.exe, etc... and running multiple instances (1 per account).

i would make a VM, run all SDA's at the same time, and set an autoclicker to click the "YES" button on the popup notifications that you set up. so i'd have many SDA's in the tray. this would be my personal method of autoconfirming trades...

**Comment by pipe01** [comment]
I guess I will add an option in config to check for all accounts or just the selected one.

**Comment by voltij** [comment]
if you do this and i will try to test for us to see if sending so many requests would cause a problem. i could see something like this getting rate-limited by steam if you have more than X requests per minute

**Comment by pipe01** [comment]
That's cool.

**Comment by pipe01** [comment]
#140
