### ISSUE TITLE
Installing VC++  pop-up on each run

### ISSUE THREAD

**Issue by Ps1d3r** [Jessecar96/SteamDesktopAuthenticator#138]
Each time i open the app, it installs the VC++ 2013 (even though i had it installed already)
I tried deleting the vcredist package from the app's folder, and still does the installing, showing a temporary vcredist with 0 kb.
http://imgur.com/W8ISNrM
I know it's an install and not an install check because it moved the VC++ to the top of installed programs in control panel.

Also, this happens just before it asks for the encryption passkey: http://imgur.com/s7ZuwnY
Don't know if it is normal or not.

EDIT: Just noticed, it doesn't save the trading confirmations pop-up for me. I tick the little box (or change the timer) then hit "save", i reopen the settings dialog and the box is un-ticked.

EDIT 2: I uninstalled VC++ 2013 so the app could install it, i still get the installation pop up every time i open the app. Also i installed the App on my friend's PC and this didn't happen which is weird.. 

Thanks for all your work on this great app.

**Comment by tarun200897** [comment]
It is not normal for this to happen every time. The program has some problem writing to the manifest inside your maFiles folder. The VC is only installed if the FirstRun parameter in the manifest is true. Similarly those settings you mentioned are saved in the manifest. Try checking if your maFiles folder contents are writeable.

**Comment by Ps1d3r** [comment]
@tarun200897 they are writable, but i made them Hidden.. Maybe that is the problem?

**Comment by Ps1d3r** [comment]
@tarun200897 Geez, i made them not hidden and it opened normally (no VC install)... 
It's weird, cause everything else works fine with the hidden maFiles and this doesn't. 
Thanks for helping man, finally after 11 days with this thread open hehehe

**Comment by tarun200897** [comment]
Yeah that's the problem because hidden files fail the File.Exists check. Glad that to have fixed it for you. Just use the inbuilt encryption. No need to hide the files.
