### ISSUE TITLE
retrieving the secrets from this program.

### ISSUE THREAD

**Issue by magicftw** [Jessecar96/SteamDesktopAuthenticator#141]
i think this is a great program works well and all. But how can i get my shared secret and identity secret out of it? the files it created when i added an account dont have this information. is it possible to add a feature or explain to me how i can get my secrets from the accounts i setup mobile auth on with this client.

**Comment by Ps1d3r** [comment]
??

**Comment by magicftw** [comment]
when you have a mobile authenticator you have a shared_secret which is what generates the auth code. It's used for steambots to generate the code to auth into the account. Thats the same way this program generates the code for us. But i need the shared_secret to generate codes on the bot.

**Comment by Ps1d3r** [comment]
Oh ok, i misunderstood, thought you wanted to extract the login data.

**Comment by Jessecar96** [comment]
in maFiles/[steamid].maFile is where all the data is stored.
However if you turned on encryption these files are obviously just garbage text. Turn off encryption to read them.
