### ISSUE TITLE
A lot of stuff Added

### ISSUE THREAD

**Issue by hyt47** [Jessecar96/SteamDesktopAuthenticator#145]
Hi, 
I added alot of stuff, can u @Jessecar96 download & merge if needed your project with this update
Or take some code from it, do as u wish ^_^

- Fixed a few small stuff in the GUI
- Added alot of options in the settings
  - System Tray:(choose)
    - Close button minimizes the app to tray
	- if activated, Quit button will appear under X button for Fast Exit, if u ever need it
    - minimize button minimizes the app to tray
    - none - show try icon
    - none - hide tray icon

  - Poput Notification max Limit increased to 99999 sec
    - Added CheckBox Check all accounts for confirmations @pipe01

  - Confirmation List
    - You can enable it and a button will appear on the main GUI
	- I also added a refresh button for Confirmation List

  - Auto check for updates on / off

- maFile replaced with saFile
  - you now have more security with encrypted accounts
  - IV & Salt & Account data all are stored inside the saFile
  - IV & Salt have been removed from manifest
  - using saFiles now you can remove an account from manifest
  - you can import it back easy even if is encrypted (if u know the passkey)

- you can still import your old maFilesand they will be converted to saFile
- You can export a saFile as maFile

- at startup verify accounts & maFile & if a problem is detected it will try to fix it (this is a safeguard)
  - if a problem is detected and the app can't fix it it will unlink the accounts from manifest and move them to folder "SDA Folder/accounts to import again"

- accounts removed from manifest now are stored in folder: accounts removed from manifest

- Fixed typing on the accounts list @pipe01 https://github.com/pipe01/SteamDesktopAuthenticator/commit/2657a6e3b47870b07e2e9b29864cff5b901fdc16
- Added option to check for all accounts each X seconds @pipe01 https://github.com/pipe01/SteamDesktopAuthenticator/commit/bf7d619113ccae6a9e4797cf0d99d8af0e0d108f

- WelcomeForm it a bit of a mess, but it works

Problems detected https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/143

## [Download](https://github.com/hyt47/SteamDesktopAuthenticator-Modded/releases/tag/000000)

**Comment by Jessecar96** [comment]
You can make a pull request if you'd like to add anything.
