### ISSUE TITLE
Unhandled Exception when checking trade confirmations

### ISSUE THREAD

**Issue by charredgrass** [Jessecar96/SteamDesktopAuthenticator#15]
http://i.imgur.com/8G87XLv.png

I have no trade confirmations pending, I was just testing to see if this would work.

**Comment by Jessecar96** [comment]
Are you using the latest version from https://github.com/Jessecar96/SteamDesktopAuthenticator/releases?

**Comment by charredgrass** [comment]
Crap. Did not even realize there was a new version. Sorry!
