### ISSUE TITLE
Spamming thru different accounts causing the program to crash.

### ISSUE THREAD

**Issue by wazerstar** [Jessecar96/SteamDesktopAuthenticator#151]
Really simple to do, just click thru many different accounts, and it will hang/crash.

This was not an issue within 0.3.1.

Might be an issue with the refreshing session first time you click account name.

Maybe set to refresh all sessions to all linked accounts during startup?

**Comment by hyt47** [comment]
I will set that as an option, & test it out

**Comment by pipe01** [comment]
Or disable the listbox for 1 sec when switching account.

**Comment by hyt47** [comment]
that is a better ideea
