### ISSUE TITLE
Please add new method adding auth.

### ISSUE THREAD

**Issue by GreeMoz** [Jessecar96/SteamDesktopAuthenticator#152]
I have steam file with info about authenticator. Can i just put data to your programm? <3

**Comment by pipe01** [comment]
If you already have a maFile, you can import it.

**Comment by DDragones** [comment]
I have android-steam file
"Steamguard-MY_STEAMID"
I cannot open it in authentificator.

**Comment by ch4o5** [comment]
Would love that feature aswell.

I have an iPhone and the only way for me was to get the "Steamguard_MY_STEAMID" file out of a backup, then use a tool like "plist Editor" to see the content and build my own maFile based on that info.

Wasn't sure what to put in as the "device_id" though...

**Comment by pipe01** [comment]
To import from an Android device use the import from Android device option. iPhone support us planned.

**Comment by tarun200897** [comment]
@ch4o5  the device id for iPhones is the IdentifierForVendor value in  /private/var/db/lsd/com.apple.lsdidentifiers.plist

**Comment by ch4o5** [comment]
@tarun200897 Thanks for that info! One more question:

The maFile looks like this:
"device_id":"android:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

What would be the equivalent to an iPhone here? "ios:xxxx"? "iphone:xxxx"?

Maybe it's not even possible with the current version of Steam Desktop Authenticator. But it looks like any random ID with "android:" is working anyway ;)
