### ISSUE TITLE
Mouse auto focus problem

### ISSUE THREAD

**Issue by iFantz7E** [Jessecar96/SteamDesktopAuthenticator#153]
I use auto focus mouse as this image. And you can test this problem too.
http://i.imgur.com/0IJhMx8.png

When program return from minimized, mouse auto focus is changed to top left of screen. 
It really annoy users who set auto focus mouse.

Please make your 'Copy' token button as default focus button or don't control mouse auto focus.

Thanks.

**Comment by hyt47** [comment]
ok

**Comment by Jessecar96** [comment]
Done in 6f24fea50ad9be1ecca664cbfdae3c37b8ca961f

**Comment by iFantz7E** [comment]
It still has this problem in 1.0.8.1
Please test with auto focus option in Windows.
