### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by firesourcee** [Jessecar96/SteamDesktopAuthenticator#154]
So I signed out of my steam account and it asked me for a code to get from my mobile app , not having the app or the phone I used the SDA , I don't know where to get the code from , I cant log into my account...Please help...

**Comment by hyt47** [comment]
If u have SDA then u can see that code (Login tocken)

**Comment by Whalemstr** [comment]
I have the SDA as well but it wont let me log in to my Steam Account on it. Please help me. I need mt Steam Code too, but cant get it.

**Comment by pipe01** [comment]
To both: if you have your revocation codes, deactivate the authenticator
via web steam and try again. If not, contact steam support.

**Comment by Whalemstr** [comment]
Web Steam?

**Comment by pipe01** [comment]
Yes, you don't need to log in.

**Comment by Whalemstr** [comment]
You mean the Steam Web Site?

**Comment by pipe01** [comment]
Yes.

**Comment by Whalemstr** [comment]
OMG Thank you SO MUCH

**Comment by pipe01** [comment]
Did it work?

**Comment by Whalemstr** [comment]
Yes. Thank you. I can now get back into Steam. You have Saved me!

**Comment by pipe01** [comment]
No problem! Although it's weird that it locked you out in the first place.
