### ISSUE TITLE
Steam desktop authenticator

### ISSUE THREAD

**Issue by XxGodly** [Jessecar96/SteamDesktopAuthenticator#155]
Can someone help me I had the authenticator for more than a week but i still had to wait 7 days so i decided to remove the authenticator and now i got the version 1.00 every time i try it i put in the code it sent to my email it keeps saying general failure for about 20 times in a row and I cant do any trading cuz ppl dont want to wait 7 days and the bots get clogged up so anyone have answers ?

**Comment by pipe01** [comment]
You should report this to [SteamAuth](https://www.github.com/geel9/SteamAuth)

**Comment by XxGodly** [comment]
I posted this on scrap.tf but then they sent me here

**Comment by pipe01** [comment]
Oh wait sorry, nvm, wrong issue.
