### ISSUE TITLE
Steam login response steamobile://nologin

### ISSUE THREAD

**Issue by TiREX69** [Jessecar96/SteamDesktopAuthenticator#156]
hi,
i use fetchConfirmation from your API and i have a problem because steam server response to me "steammobile://nologin" i'm a login and this problem is every time (1 day after login)

Thanks for help
Szymon / Simon

**Comment by pipe01** [comment]
You should report this to [SteamAuth](https://www.github.com/geel9/SteamAuth)

**Comment by TiREX69** [comment]
yes, i thought reported this on SteamAuth

**Comment by pipe01** [comment]
I can't, but you can.
