### ISSUE TITLE
Trade confirmations don't appear

### ISSUE THREAD

**Issue by pokey97** [Jessecar96/SteamDesktopAuthenticator#157]
http://i.imgur.com/6JULhv6.jpg 
accepted the offer but the confirmation doesn't appear on the desktop authenticator app.

**Comment by Ps1d3r** [comment]
Have you tried to click on the "refresh" button?

**Comment by pokey97** [comment]
yup i did but still it doesn't show

**Comment by pokey97** [comment]
Re login on the authenticator resolved the issue

**Comment by Ps1d3r** [comment]
Must have been some Steam issue, Steam has being all crazy these days

**Comment by Ps1d3r** [comment]
If solved can you close the post pls? Thanks

**Comment by pokey97** [comment]
it still happens from time to time, i have to keep re login. it's not a practical solution
