### ISSUE TITLE
Problem with S.D.A [.Net Framwork] related

### ISSUE THREAD

**Issue by codeduph** [Jessecar96/SteamDesktopAuthenticator#158]
This problem occur when I try to click different account. The Authenticator hangs and give me this .Net related error.

The text is to long so I put it here: http://pastebin.com/s8tyARMn

Here is the SS: http://imgur.com/RAx2UcE

Note: that this problem occur only today. just in case I use Microsoft .NET Framework Repair Tool (https://www.microsoft.com/en-us/download/details.aspx?id=30135) and .NET Framework Setup Verification Tool (http://blogs.msdn.com/b/astebner/archive/2008/10/13/8999004.aspx) to verify that my .NET Framework is ok.

**Comment by Rerinha** [comment]
I'm having the exact same problem. And it started a couple of hours ago.

**Comment by pokey97** [comment]
Install the framework 4.5.2  and run the verdict.exe? in the folder and restart your computer, should work after that

**Comment by codeduph** [comment]
I just like to mention: I re-install .NET and restart my PC and the problem is still there. 

However, after I re-install "vcredist_x86" it fixed the problem.

In anyrate thanks pokey97 it FIX my problem.
.

**Comment by Rerinha** [comment]
Yep, no need to restart the PC, just reinstalling vcredist will do. Thanks a lot for the help, guys. :)

**Comment by codeduph** [comment]
It seems that I have to re-install "vcredist_x86" from time to time. is there any particular reason for this?

**Comment by pokey97** [comment]
not sure, i have to repair vcredist and microsoft framework from time to time or restart the program too to fix the same issue

**Comment by routemasters** [comment]
@pokey97 if so then more like an issue with your hardware, maybe faulty memory sticks.

**Comment by pokey97** [comment]
that can't be, i don't have any issue with the previous versions till this one
