### ISSUE TITLE
Trade confirmations not appearing. Getting an error when I refresh session or log in again.

### ISSUE THREAD

**Issue by Seelkadoom** [Jessecar96/SteamDesktopAuthenticator#163]
So if I accept a trade and go to the desktop authenticator app and trade confirmations, I get absolutely nothing. I read in an issue forum before this one that re-logging in fixed it but it didn't for me. when I try to re-log in it says "Error logging in: Steam returned "GeneralFailure"."

If I try to force session refresh, it says: "Failed to refresh your session. Try again soon."

EDIT: I forgot to say that I clicked "Deauthorize all other devices" in the steam guard page. Does this have an effect on the app?

Any help will be appreciated.
Thanks in advance,
Seel

**Comment by Ps1d3r** [comment]
But can you login on the authenticator?

**Comment by pipe01** [comment]
Steam servers have been a bit crazy these days, so you may wanna wait a few
days until it becomes stable.

**Comment by Seelkadoom** [comment]
I can log in to the authenticator but confirmations don't appear.

**Comment by Seelkadoom** [comment]
I've deleted the authenticator and re-downloaded it again, now it works but i have to wait 7 days in order for it to take effect. damn you valve :/

**Comment by Seelkadoom** [comment]
Closing.
