### ISSUE TITLE
Importing from Winauth?

### ISSUE THREAD

**Issue by megablue** [Jessecar96/SteamDesktopAuthenticator#164]
Can SDA do it? how?

thanks!

**Comment by pipe01** [comment]
As far as I know, it can't, although it's nice to see people switching to
SDA (or at least trying to).

**Comment by Blaze5145** [comment]
I think I might be able to code this. I've made some progress on parsing the export txt of winauth. Will keep you posted.

**Comment by tarun200897** [comment]
I'm working on this in my fork, branch: winauth-import. I hope to be done in a few days hopefully if I'm free. I'll probably be pretty busy this week though.

**Comment by tarun200897** [comment]
It was much easier than I expected. I'm done. Her you go :https://github.com/tarun200897/SteamDesktopAuthenticator/tree/winauth-import

**Comment by tarun200897** [comment]
I've added some more features in the latest commit. Check it out.

**Comment by Floyd77** [comment]
Hi, I found a method to manually import from WinAuth:

1. Paste this template in notepad++ or similar:
`{
  "shared_secret":"",
  "serial_number":"",
  "revocation_code":"",
  "uri":"",
  "server_time":,
  "account_name":"",
  "token_gid":"",
  "identity_secret":"",
  "secret_1":"",
  "status":1,
  "device_id":"",
  "fully_enrolled":true,
  "Session":{"SessionID":"",
  "SteamLogin":"",
  "SteamLoginSecure":"",
  "WebCookie":"",
  "OAuthToken":"",
  "SteamID":}
}`

2. Open Winauth, right-click, "Show Steamguard and Recovery Code"

3. Fill the data between the "" of each line in the template (don't add the "" in the fields where they are missing). Also, you don't need to fill these ones:
`"Session":{"SessionID":"",
  "SteamLogin":"",
  "SteamLoginSecure":"",
  "WebCookie":"",
  "OAuthToken":"",`

4. Save the file as: "anyname.maFile"

5. Open SDA: File, Import Account, From maFile.

Enjoy!

**Comment by SHJordan** [comment]
> Hi, I found a method to manually import from WinAuth:
> 
> 1. Paste this template in notepad++ or similar:
> 
> > {
> > "shared_secret":"",
> > "serial_number":"",
> > "revocation_code":"",
> > "uri":"",
> > "server_time":,
> > "account_name":"",
> > "token_gid":"",
> > "identity_secret":"",
> > "secret_1":"",
> > "status":1,
> > "device_id":"",
> > "fully_enrolled":true,
> > "Session":{"SessionID":"",
> > "SteamLogin":"",
> > "SteamLoginSecure":"",
> > "WebCookie":"",
> > "OAuthToken":"",
> > "SteamID":}
> > }
> 
> 2. Open Winauth, right-click, "Show Steamguard and Recovery Code"
> 3. Fill the data between the "" of each line in the template (don't add the "" in the fields where they are missing). Also, you don't need to fill these ones:
> 
> > "Session":{"SessionID":"",
> > "SteamLogin":"",
> > "SteamLoginSecure":"",
> > "WebCookie":"",
> > "OAuthToken":"",
> 
> 4. Save the file as: "anyname.maFile"
> 5. Open SDA: File, Import Account, From maFile.
> 
> Enjoy!

What should i input on device_id? That's the only line I'm missing from the .ma file that seems mandatory...

**Comment by dyc3** [comment]
You can probably put anything tbh I'm not sure if they validate it. If you can check the source code, there's a constant somewhere IIRC.

**Comment by Extroom** [comment]
https://github.com/wanips7/WAtoSDA
I used it and it worked. Now I can use SDA instead of WinAuth
