### ISSUE TITLE
"Null object cannot be converted to a value type." when trying to import from Android device

### ISSUE THREAD

**Issue by pasomnica** [Jessecar96/SteamDesktopAuthenticator#168]
Unfortunately, I am not so tech-savvy to understand what could went wrong. Authenticator works normally on my phone (Acer Z500, 4.4.2). Here is the error log:

Checking for ADB
Starting
Checking requirements...
Checking for ADB
Checking for device
Checking for ADB
Checking for Steam app
Checking root
Using root method
Extracting (1/2)
Extracting _long number here, not sure if important_ (2/2)

Then the error pop-up window shows up with following info in details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

Steam Desktop Authenticator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0
##     CodeBase: file:///C:/Users/david_000/Documents/auth/Steam%20Desktop%20Authenticator.exe

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
##     CodeBase: file:///C:/Users/david_000/Documents/auth/Newtonsoft.Json.DLL

SteamAuth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/david_000/Documents/auth/SteamAuth.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Blaze5145** [comment]
Connect your phone. Execute this command on a command prompt open from the directory of SDA and comment the output.
adb shell su -c 'ls /data/data/com.valvesoftware.android.steam.community/files'

**Comment by pasomnica** [comment]
I got the output, what should I do with it?

**Comment by pipe01** [comment]
Paste it here

**Comment by pasomnica** [comment]
Here is it (I hope it does not contain any personal info ^^)

http://pastie.org/10664787

**Comment by pasomnica** [comment]
I removed the thing that might be personal (like revocation code and so on)

http://pastie.org/10664788

**Comment by Blaze5145** [comment]
Mine is similar except for the status. It's '1' for me and 'null' for you.

**Comment by pasomnica** [comment]
And that might be the source of error that is occurring to me. At least I still can authenticate trades on phone.

**Comment by pasomnica** [comment]
Anything that I can do?

**Comment by tarun200897** [comment]
You can try manually overriding the status to 1 though I have no idea what it'll result in.

**Comment by pasomnica** [comment]
"Account extracted sucessfully! Please login to it."

Then I tried to log in, Steam returned with GeneralFailure error. Couldn't do the second try, as the app was not responding anymore and crashes after data import.

**Comment by tarun200897** [comment]
Did you try restarting the app and importing again?

**Comment by pasomnica** [comment]
Yes, no luck whatsoever.

**Comment by tarun200897** [comment]
Then we gotta figure out why the status is null and fix that.

**Comment by tarun200897** [comment]
Are you sure that the two factor authentication is enabled in your steam account?

**Comment by pasomnica** [comment]
Yes. I confirm all trades and all sign-ups from my phone.
