### ISSUE TITLE
Generate DeviceID during Android Import

### ISSUE THREAD

**Issue by Blaze5145** [Jessecar96/SteamDesktopAuthenticator#169]
The android import fails in importing the DeviceID properly. This results in the deviceID being saved as ERROR. This is not handled by the SteamAuth library (It only handles empty IDs). I suggest we call AuthenticatorLinker.GenerateDeviceID() from the SteamAuth library whenever a import is being done. The mobile confirmations will not work for android imports without this change.

**Comment by pipe01** [comment]
The point of importing from a phone with Steam Guard activated is to have
both SDA and the app working at the same time. I don't know what would
happen if you linked the authenticator with a different device ID.
Anyways, please compile my fork on SDA, import from your phone and upload
the adblog.txt and post it here so I can see what went wrong.

**Comment by pipe01** [comment]
Oh, I was browsing the code and found what caused the error. I'm going to
fix it later.

**Comment by Blaze5145** [comment]
SDA can't extract the deviceID properly. Hence the deviceID is saved as "ERROR" (the default one). The SteamAuth library doesn't handle it and hence the trade confirmation fails silently. Just generating a new deviceID would do and it works.

**Comment by Blaze5145** [comment]
Oh can you share what's wrong? I can fix it in my end as well.

**Comment by pipe01** [comment]
I added a method for no root extracting that didn't require busybox, you
can find it in the branch patch1 of my fork (sorry, can't put links)

**Comment by Blaze5145** [comment]
I had root.

**Comment by pipe01** [comment]
In the line 143 of PhoneBridge add " su -c " (without quotes and with
spaces) after "adb shell". That should work

**Comment by Blaze5145** [comment]
Thanks a ton. It works :+1:

**Comment by pipe01** [comment]
No problem! Please close the issue.

**Comment by Blaze5145** [comment]
It'll close automatically when Jessecar96 merges in the bugfix. Nice to see people contributing to SDA :D
