### ISSUE TITLE
Provide 32 bit binaries

### ISSUE THREAD

**Issue by lisacvuk** [Jessecar96/SteamDesktopAuthenticator#171]
So, I used to have 64bit windows 7 installed, till my HDD failed. Hopefully, I had backup of my files. Then today when I installed windows xp 32bit (due to limited HDD space...) I cannot compile this app. I've got 0% expirience with compiling C# apps, especialy on Windows. Please, I really need 32bit binary.

**Comment by hyt47** [comment]
32 bits u can find here https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47

**Comment by lisacvuk** [comment]
Thank you very much, sir!
