### ISSUE TITLE
General failure error. 

### ISSUE THREAD

**Issue by Victolabs** [Jessecar96/SteamDesktopAuthenticator#172]
Hi. When ever i try to use SDA i keep getting a [general failure error](http://prntscr.com/9kszqp) Can anyone help? this error happens at 2 different places. One place it can happen is when i try to log in. but when i CAN log in i get the error after i input my phone number. Help?

**Comment by RoboMWM** [comment]
I'm getting this as well, but only when attempting to add phone number

**Comment by pipe01** [comment]
Add your phone number via steam (sorry, can't give any instructions)

**Comment by RoboMWM** [comment]
And why is that? Does this need to be done via the "official" app or can it be done on the web?

**Comment by pipe01** [comment]
On why, I don't know, but it worked for some. And you can do it both ways I
think.

**Comment by RoboMWM** [comment]
To add your phone number via Steam, just visit https://store.steampowered.com/phone/add

(and I don't see what's wrong with sharing that...)

**Comment by pipe01** [comment]
I said that because I was on my phone and I couldn't find the link.

**Comment by RoboMWM** [comment]
Oh ok. Didn't seem to work though, getting the same issue regardless.

**Comment by remoses** [comment]
Is there any fix to this issue?

**Comment by remoses** [comment]
Never mind, I fixed it. Besides adding a phone number to the account(This solution didn't work for me) I went here http://store.steampowered.com/twofactor/manage and enabled "Get Steam Guard codes from the Steam app on my phone".

**Comment by RoboMWM** [comment]
@remoses: Did you have the app prior to changing that? Selecting that option just tells me to download the app to set it up there... and unless I waste my time with an Android emulator, I can't do that -_-

**Comment by guygardner007** [comment]
A familya ccountw as getting login issues not realizing server  as culprit due to failed logins ended up deactivating steam authenticator on SDA. Reset passwords phone multiple times in steam server error. Finally password is set on steam. I deleted and reset mafile by importing from back up also but keep getting generic failure message trying to login id fresh on SDA.

**Comment by CzarnaMamba** [comment]
I have this problem
