### ISSUE TITLE
No Trade Confirmations

### ISSUE THREAD

**Issue by cetoke** [Jessecar96/SteamDesktopAuthenticator#174]
I just started a trade and wanted to confirm it with the Desktop Authenticator but for some reason it looks like this: http://puu.sh/mgOQ8/f28941d961.png
I've already seen another thread with a similar title but this can't help me since I am not experienced in programming at all. What do I have to do in order to fix this? Thanks in advance.

**Comment by Blaze5145** [comment]
Please give more info like how you configured the SDA, etc. Did you use mobile import? If so, root or no root?

**Comment by cetoke** [comment]
http://puu.sh/mgWPm/91eb104f15.png
I've imported the files from an older version of the program (0.2.3). I have root permissions on my device.

**Comment by Blaze5145** [comment]
i think this has already been discussed in https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/169 and https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/170 . Since you don't have any programming experience, you can either wait for @Jessecar96  to apply a hotfix or check out @pipe01 's fork. I don't know if he has patched it there but he has a working no-root method here: https://github.com/pipe01/SteamDesktopAuthenticator/tree/patch-1

**Comment by pipe01** [comment]
If you didn't import the account from your phone, then my patch is useless.

**Comment by Blaze5145** [comment]
I think he imported from his phone to an older version of SDA. At least that's what I understood :|

**Comment by pipe01** [comment]
Well, phone importing was implemented on v1.0.0 :v

**Comment by Blaze5145** [comment]
Oh yeah. I completely forgot. Then @cetoke I think you should use the official app and then import since that way, you at least have a back up on your phone and it has worked for many people.

**Comment by SunriseM** [comment]
that sometimes happens to me, just press refresh and wait.

**Comment by judgegr** [comment]
Just a confirmation that the device-id error can be manually fixed until an update comes along.

I have a rooted device and just used a root explorer to copy the correct device-id from steam.uuid.xml file and paste it to my accounts' maFile. Now all trades are showing almost instantly. !

**Comment by Blaze5145** [comment]
That can only be done if you're not encrypted.

**Comment by judgegr** [comment]
True, but you can easily unencrypt + fix + encrypt again.

**Comment by Blaze5145** [comment]
Agreed.

**Comment by cetoke** [comment]
Where can I find the steam.uuid.xml or the Steam folder in general?

**Comment by cetoke** [comment]
In the maFiles folder there is one file with the following content (...) "device_id":"android:D2A..." (...)
And in steam.uuid.xml there is only the "uuidKey">android:-09...
Is this the same thing although the device_id contains letters and numbers and the uuidKey contains only numbers and hyphens ?

**Comment by Blaze5145** [comment]
It should actually contain letters,numbers and hyphens. Try using the deviceid from your phone if that's different.

**Comment by cetoke** [comment]
Is the uuidKey = device_id ?

**Comment by Blaze5145** [comment]
Yes.

**Comment by pipe01** [comment]
It's already fiexed in my fork, in case you don't wanna do that.

**Comment by cetoke** [comment]
Thanks for the help so far! I decided to completely reinstall the Authenticator. When I chose the option to import files from my Android device I followed the instructions (actually I just plugged the phone because I had already enabled USB Debugging) but the console just shows me this: http://puu.sh/mi9iA/ed30fbf694.png
I think this could have something to do with the fact that I installed other adb drivers in order to flash a new ROM onto my device a few months ago. I use the Kingzone K1 Turbo Android 4.4.2.  What do I have to?
(Sorry if this is not the right thread.)

**Comment by pipe01** [comment]
Can you run "adb devices" while the phone is connected and show the
input?

**Comment by cetoke** [comment]
Ok I've fixed everything related to the driver problem. Now I "just" have to wait in order to test trading. Thanks GabeN.

**Comment by Ps1d3r** [comment]
@pipe01 Sorry for off topic, but i've sent you an email some days ago, maybe you didn't get it... It's regarding this https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/138
Do you have any idea what could be causing it?

**Comment by cetoke** [comment]
It's still not working unlike on my phone. :(

**Comment by impman** [comment]
Just got this issue about an hour ago. Trade confirmations were working this morning, but broke around 2PM PST. It simply shows 
Nothing to confirm
You don't have anything to confirm right now.
