### ISSUE TITLE
I FORGOT MY PASSWORD! 

### ISSUE THREAD

**Issue by TheHeavenlyMinx** [Jessecar96/SteamDesktopAuthenticator#177]
Please add an option to retrieve your password.

**Comment by tarun200897** [comment]
I guess a way to implement this would be to hash and store the revocation code in the manifest and use it for reset. We use the revocation code simply because the user is instructed to copy it down during setup. But that wouldn't help this user because he has already lost his password.

**Comment by tarun200897** [comment]
On second thought, I don't think it'll be possible because the data has to be decrypted before encrypting with the new password again. The old password would be required for the decryption.

**Comment by pipe01** [comment]
Maybe it's possible to scramble the passkey and put letters of it with an
algotithm that's hidden and only Jesse knows, so you can send the file to
him and he would send you the passkey back.

**Comment by PFCKrutonium** [comment]
Perhaps the revocation code could be written to a file and encrypted using somthing that is hardware unique? Like perhaps a Mac Address or the ID of the Processor.

**Comment by TheHeavenlyMinx** [comment]
PLEASE. I CAN'T TRADE.

**Comment by codeduph** [comment]
if you can't remember your password next time use this: http://keepass.info/.

caution: http://imgur.com/8VrX8XH

**Comment by pipe01** [comment]
Your maFile is already pretty much lost, so just disable the authenticator
via steam, and re add it on a new installation of SDA. This time make sure
to use a passkey you will remember.

**Comment by lowkey4** [comment]
@Jessecar96 can you please help to get my encryption key?

**Comment by Krutonium** [comment]
Did you completely ignore *everything* that was written here?

**Comment by lowkey4** [comment]
yes

вс, 15 дек. 2019 г. в 14:07, Krutonium <notifications@github.com>:

**Comment by lowkey4** [comment]
you know, nevermind, i got my steam accounts back

вс, 15 дек. 2019 г. в 14:07, Krutonium <notifications@github.com>:
