### ISSUE TITLE
from bluestacks to SteamDesktopAuthenticator

### ISSUE THREAD

**Issue by aIpGaming** [Jessecar96/SteamDesktopAuthenticator#178]
I use bluestacks, can I transfer my data SteamDesktopAutnentikator?
I do not want to wait 7 days

**Comment by pipe01** [comment]
There needs to be an ADB connection to the phone, so I don't think
bluestacks can do that.

**Comment by aIpGaming** [comment]
gg :<

**Comment by pipe01** [comment]
I'm sorry :/

**Comment by pipe01** [comment]
I've done a quick search and bluestacks seems to have adb implenented. You
can check by opening a windows shell and running 'adb devices' after
opening bluestacks. If it doesn't show up on the list, run 'adb connect
localhost:5555' and run the previous command again.
I've never done this so I don't know if it will work, but it's worth a try.

**Comment by aIpGaming** [comment]
I do not understand :D

**Comment by pipe01** [comment]
Do you know how to run the windows shell?
Sorry I fell asleep lol

**Comment by aIpGaming** [comment]
so I need to do and what to download please explain

**Comment by tarun200897** [comment]
Yep bluestacks has adb. I remember because I had to close it every time before I sideloaded anything to my phone. Just install rooted bluestacks (more about that here: http://forum.xda-developers.com/wiki/BlueStacks_App_Player); download either @pipe01 or my fork and extract your Steam App data using mobile import.

**Comment by aIpGaming** [comment]
When copying data
i have error .NET framework
could not find any of the way D:\Steam dekskop\steam guard 
:C

**Comment by pipe01** [comment]
Have you used my fork or the original?
