### ISSUE TITLE
Shared_Secret and identity_secret

### ISSUE THREAD

**Issue by krysti500** [Jessecar96/SteamDesktopAuthenticator#179]
Where i can find this?

**Comment by pipe01** [comment]
Unencrypt the maFile and open it with  text editor.

**Comment by krysti500** [comment]
Hot to unencrypt :/?

**Comment by pipe01** [comment]
Hit Manage Encryption on the main form and hit cancel to not encrypt it.

**Comment by krysti500** [comment]
Ohh thanks :)
