### ISSUE TITLE
"View Trade Confirmations" Tab blank

### ISSUE THREAD

**Issue by RichTree** [Jessecar96/SteamDesktopAuthenticator#180]
http://puu.sh/mqphZ/562479f9a0.png

I've been having this problem for a few days now,and since then I can't make any trades.
I've imported my maFiles from an older SDA version (also worth noting that these maFiles were created on the SDA itself, and weren't imported from the Steam App), and since then I've also changed my phone number, so I'm in a rather delicate position, what should I do?

**Comment by pipe01** [comment]
With changed phone number you mean that you got a new number right? If so, have you already changed it in steam?

**Comment by RichTree** [comment]
Yep, a new number, I haven't changed it on steam with fear that it requires the old number (didn't changed it while I had the 2 numbers).

**Comment by pipe01** [comment]
It shouldn't cause anything, but just to be safe, you can remove the authenticator, change the number via steam web and readd it.

**Comment by RichTree** [comment]
Sadly, I can only remove the old number if I had said number, since steam only removes it via an SMS code.

**Comment by Toff-kun** [comment]
Try either "login again" or "refresh session" options.

**Comment by ZeHat** [comment]
@Toff-kun Thanks, man. I've been having this issue for a while and it's nice to finally be able to trade again.
