### ISSUE TITLE
Get Shared_Secret and Identity_Secret

### ISSUE THREAD

**Issue by christmannx3** [Jessecar96/SteamDesktopAuthenticator#182]
Hello Guys,
I´ve a quick question. I use the SDA for my Steam Bot. But i need the two codes shared_secret and identity_secret. I know their are in the .mafile. But in this file you can see soo many codes and now "word". Can someone help me to find these two codes ?

**Comment by pipe01** [comment]
You have to unencrypt it by clicking on Manage Encryption and then cancel.

**Comment by pipe01** [comment]
Then it should be plain text.

**Comment by christmannx3** [comment]
Oh my god :D Thank you mate.
It´s working right now :)

**Comment by pipe01** [comment]
No problem!
