### ISSUE TITLE
Can I use 2 different mobile numbers for 2 different accounts

### ISSUE THREAD

**Issue by Nonickn** [Jessecar96/SteamDesktopAuthenticator#184]
in this program?

**Comment by pipe01** [comment]
Of course, but that's how steam does it, not SDA.

**Comment by Nonickn** [comment]
Nice I was just thought can program handle it or not. Better ask than sorry hehe. Thank you for the answer.

**Comment by pipe01** [comment]
No problem! Please close the issue.
