### ISSUE TITLE
[Feature Request] Auto accept [Feature Request]

### ISSUE THREAD

**Issue by waL1u** [Jessecar96/SteamDesktopAuthenticator#186]
The title says a lot. Good feature to use with bots or if you have youself tradebot account. Thx! :)

**Comment by pipe01** [comment]
#32 ^^

**Comment by waL1u** [comment]
oh thx

**Comment by pipe01** [comment]
Close the issue, please :d

**Comment by tarun200897** [comment]
If you'd like a quick solution and you know programming, enable periodic confirmation check, remove the part where the confirmation pop-up is opened and call the confirmation function directly. Note that this accepts all incoming confirmations and defeats the whole purpose of the mobile authentication. To make it a little better, I'd suggest you use some trade bot to filter your incoming trade requests and then auto accept.

**Comment by pipe01** [comment]
This has already been discussed on #32

**Comment by tarun200897** [comment]
I was just extending upon that discussion.

**Comment by pipe01** [comment]
Then you should have commented on the other issue so more people get to
know it.

**Comment by tarun200897** [comment]
Okay.

**Comment by pipe01** [comment]
Don't worry, me steaks were made lol

**Comment by tarun200897** [comment]
Yeah lol
