### ISSUE TITLE
You can't add New Account if you already run Steam Client of another Steam user

### ISSUE THREAD

**Issue by Nonickn** [Jessecar96/SteamDesktopAuthenticator#187]
There's always fail on last step. Don't know is it program's bug though or it's something as it should be.

**Comment by Ps1d3r** [comment]
Do you have the app on your phone?
Earlier i helped my friend setup his SDA, and it took a few tries to get it to work, it kept failing on last step too, but we tried until it went through...

**Comment by Nonickn** [comment]
No I don't and the program works fine for me. I can add new account without any problem if there's no Steam Client running of another user. I have checked that 3 times with the same result.

**Comment by pipe01** [comment]
I think this is more of a geel9's SteamAuth issue.
