### ISSUE TITLE
Block SDA internet access?

### ISSUE THREAD

**Issue by 4funz** [Jessecar96/SteamDesktopAuthenticator#190]
Hello,

I would like to block internet access for SDA when PC is connected to private network and only allow it when PC is connected to public network.
It would be too long to go into reasons on why i want to do this, but i need this done.

When i want to do this i usually just add firewall inbound and outbound rules for specific .exe and it blocks it.
But for SDA it is not working. Adding rule for Steam Desktop Authenticator exe does not block it from gaining internet access.

Any suggestions on how i could do this?

**Comment by PFCKrutonium** [comment]
Get a better firewall?

**Comment by codeduph** [comment]
try to block all the *.exe

**Comment by pipe01** [comment]
Don't do that lol

**Comment by 4funz** [comment]
@PFCKrutonium - i am afraid i have to use windows firewall :(

@codeduph - If you mean all .exe in SDA folder it does not work, i tired. If you mean blocking all exe in the OS, while that works, it does not solve my issue i am afraid as it blocks apps which i want to have internet access.

@All - No solutions? :( i am willing to chip in a key or two, or five for the working solution to my issue.

**Comment by 4funz** [comment]
@codeduph 

>BTW, why do you have to block the whole *.exe. you can simple just use the Block all connection feature in your firewall if that is your point.

Issue is i need vpn working. I would like SDA to lose internet access if vpn goes down.
For this i have created two networks. Private for normal connection and Public for vpn
I want to make it so SDA works only over Public network. 
I can make this just fine for other applications, just not for SDA :(
I have posted on the forum which you suggested.

**Comment by 4funz** [comment]
Solution:

I have fixed my issue. When you click on "browse" to find .exe path you want to add the rule for. Windows selected path which was looking like: %USERPROFILE%\Downloads\Steam.Desktop.Authenticator.v1.0.0\Steam Desktop Authenticator.exe and this path did not work
While correct path would be: C:\Users\*username*\Downloads\Steam.Desktop.Authenticator.v1.0.0\Steam Desktop Authenticator.exe

**Comment by pipe01** [comment]
Nice. Anyways, please don't post things like this, as this is the issue
tracker, so only SDA issues should be posted. This is a general windows
'issue'.

**Comment by 4funz** [comment]
True, but how was i to know it was? I was guessing that due to way SDA was coded that this was not possible to do.
I am sorry for taking your time.

**Comment by pipe01** [comment]
Don't worry! Just for the future.
