### ISSUE TITLE
error adding account

### ISSUE THREAD

**Issue by Rachevsky** [Jessecar96/SteamDesktopAuthenticator#193]
After entering code from sms and recovation code soft again asks code from sms and this is repeated. I tried different phone numbers, problem not in it.

**Comment by Denix-spb** [comment]
+1 this problem too.

**Comment by goomonster3** [comment]
+1 I have tried this on multiple accounts and computers with no luck. Is this a steam issue?

**Comment by Shmeeb** [comment]
I am also experiencing this.

**Comment by 808dkaneohe** [comment]
could just be the steam servers.

**Comment by Spektakel** [comment]
Same here. After playing arounf for an hour or such I suddenly got it working. Dunno exactly what made it happen but I am pretty sure I got a different revocation code on the last try than the tries before.

Things I also did which seem to not help: Log into website, setup phone number on website, restart Authenticator, retry several times getting the same revocation code.
