### ISSUE TITLE
shared secret and shared identity

### ISSUE THREAD

**Issue by cymruu** [Jessecar96/SteamDesktopAuthenticator#195]
Hello! 
It's possible to extract shared secret and shared identity from configured account somehow? I need this to confirm trades using node steamcommunity library.
Thanks!

**Comment by pipe01** [comment]
Check any of the 9000 closed issues about this.

**Comment by cymruu** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/189#issuecomment-172088855
