### ISSUE TITLE
I lost my steam account :(

### ISSUE THREAD

**Issue by CoolSkeleton96** [Jessecar96/SteamDesktopAuthenticator#196]
So,i was making something,then i decided to go on steam,i went in,it asked for the steam authenticator code,after that,the authenticator just doesn't seem to run... it was working well yesterday,and now it doesn't run,i tried double clicking it a bunch of times but it just said another instance of the app is already running,i searched the toolbar as well,and nothing,i also tried downloading another steam desktop authenticator and import from the old one,but it just said Unhandled Exception or that the manifest.json has invalid content

Update: Fixed it,i had to restore my account with my credit card and disable steam authenticator

**Comment by CoolSkeleton96** [comment]
Infact,i tried pressing I can't sign in on steam,and it's just transparent now, nothing whatsoever

**Comment by pipe01** [comment]
Have you tried turning it off and on?

**Comment by CoolSkeleton96** [comment]
Yes, i tried restarting,hibernating,and shutting down

**Comment by pipe01** [comment]
If you have written down your revocation code, you can disable the
authenticator via the steam web page. If not, its your own fault and you'll
have to contact steam support.

**Comment by CoolSkeleton96** [comment]
..what do you mean by revocation? I only have control of it through scrap.tf now..

**Comment by CoolSkeleton96** [comment]
Scrap.tf only

**Comment by pipe01** [comment]
When you first configured SDA and added you account, popup would show
telling you to write down your revocation code.

**Comment by CoolSkeleton96** [comment]
OH

**Comment by CoolSkeleton96** [comment]
Fuck

**Comment by CoolSkeleton96** [comment]
Thanks alot,geel

**Comment by pipe01** [comment]
I'm not geel lol. Anyways, try opening the task manager and search for any
Steam Desktop Authenticator.exe entry.

**Comment by CoolSkeleton96** [comment]
Ik

**Comment by CoolSkeleton96** [comment]
Nope,but when i click on steam desktop authenticator alot it will just say an instant of the app is already running and as soon as i close that window it dissapears from the task manager
Like if the manifest.json file got corrupted somehow,any way i can find an new one and use it?

**Comment by CoolSkeleton96** [comment]
and i can acces it on my android phone(No,it cant text)

**Comment by CoolSkeleton96** [comment]
Fixed it :+1:

**Comment by PapiDimmi** [comment]
How did you fix it?!
