### ISSUE TITLE
Confirmation error

### ISSUE THREAD

**Issue by 4funz** [Jessecar96/SteamDesktopAuthenticator#197]
Often i am getting following two errors:

Confirmation error
There was a problem loading details for that confirmation. You must be logged in to perform that action.

Confirmation error
There was a problem canceling that confirmation, Please try your request again later.

Second error is even more strange, as i am trying to confirm not cancel.

Is there any way to solve this?

**Comment by pipe01** [comment]
Try to refresh the session. If it continues to occur, log again (in the
menu)

**Comment by 4funz** [comment]
I am already doing refresh after each confirmation. But still every 3rd, 4th time i get an error. And always last few confirmations have loads of issues. I usually end up canceling them from the browser.
It is very annoying, would this be SDA issue or steam issue? I am guessing SDA?

**Comment by 4funz** [comment]
Also i question:

I saw that it was told that auto confirmation will not happen, but what about bulk confirmation?
manual way to confirm all pending, or select (with select all) specific offers to confirm?

**Comment by pipe01** [comment]
It may be a steam issue, as I've never seen it happening. About auto
accepting, its avaiable in my fork.

**Comment by 4funz** [comment]
I am afraid i am new to github. How do i download your version? When i go to your repo i see "download" here which leads to jesse's one.
