### ISSUE TITLE
What's the point of it if you still need a phone that has SMS?

### ISSUE THREAD

**Issue by steampunko** [Jessecar96/SteamDesktopAuthenticator#198]
What's the point of it if you still need a phone that has SMS?

I wanted to use this program because my phone is a home phone, not a mobile phone. And it can't get SMS messages

**Comment by routemasters** [comment]
you only need that for the one-time activation.

**Comment by Ps1d3r** [comment]
Yeah.. You can do it with one of those Google numbers, don't know how that works though, but I've seen ppl talking about it on Reddit and here i think

**Comment by Ps1d3r** [comment]
Or just ask someone at home or a friend to use their phone for 5 minutes, you just need it to receive 1 text message

**Comment by PFCKrutonium** [comment]
I just used TextNow. Send a message to the number Steam texts you from every couple day and you can even keep the number.
