### ISSUE TITLE
Nothing to confirm You don't have anything to confirm right now.

### ISSUE THREAD

**Issue by valeriy-efimov** [Jessecar96/SteamDesktopAuthenticator#199]
I add account using the "import account -> Android device"
but all time have message "Nothing to confirm You don't have anything to confirm right now."
refresh botton dont work
But on the my phone I get a confirmation.Turning off the phone also did not help

Help solve the problem ..

**Comment by Ps1d3r** [comment]
Probably steam issues,...
Got to app's menu and try "login again" or "force session refresh"

**Comment by valeriy-efimov** [comment]
I also try this, don't work...
