### ISSUE TITLE
Trouble with Entering Phone Number

### ISSUE THREAD

**Issue by BroKeN00** [Jessecar96/SteamDesktopAuthenticator#220]
I follow through the steps exactly and when the part of adding your number pops up, it never finds my Google Voice number, which has already been verified. I only end up with the general error? I do not understand what has gone wrong with it but I am here addressing the situation for me and for others who may have this same problem.
thanks, BroKeN

**Comment by Jessecar96** [comment]
This is a problem with Steam, and it doesn't have anything to do with SDA.
