### ISSUE TITLE
Confirmations not working

### ISSUE THREAD

**Issue by SpookyGhostMan** [Jessecar96/SteamDesktopAuthenticator#223]
When I open the confirmations tab, it's just empty

**Comment by CroN0x** [comment]
same

**Comment by djosepaci** [comment]
Same here, this really needs to fixed soon.

**Comment by Greatwally** [comment]
same

**Comment by kingga** [comment]
Heres the error that I'm getting [1103/174616:ERROR:renderer_main.cc(200)] Running without renderer sandbox. I haven't been able to trade in days now ):

**Comment by Jessecar96** [comment]
Re-login to your account using the option in the "Selected Account" menu. This fixes it 99% of the time.

**Comment by kingga** [comment]
Thank you!
