### ISSUE TITLE
Cant import from maFile

### ISSUE THREAD

**Issue by illuminati1337** [Jessecar96/SteamDesktopAuthenticator#224]
i accedentally moved the maFiles from maFile folder to other folder, and then moved back, now i started the program and all my Authenticators where removed. i moved the maFiles back to their folder, and i tryed adding Authenticator again by maFile, but it give me this error: 'This is not a valid SteamAuth maFile Import failed' ,even tho those are valid files =(
Any way i can get my Authenticators back without having to remove first from steam account?

**Comment by Jessecar96** [comment]
Most likely they are encrypted. Open the file in a text editor. If you see just gibberish it's encrypted, if it's readable text then there's something else wrong.

To import an encrypted maFile you need to the manifest.json (from when you first encrypted it) file in the same folder as the maFIle you're importing.
