### ISSUE TITLE
Error Auto-Confirm Trades: "personaname": "็"

### ISSUE THREAD

**Issue by maxla93** [Jessecar96/SteamDesktopAuthenticator#227]
![screenshot_1](https://cloud.githubusercontent.com/assets/23719223/20596540/b27387f2-b247-11e6-8287-a69936805e2f.png)
If the user has nickname "็็็็็็็็็็" Auto-Confirm Trades not available!

personaname:"็็็็็็็็็็

**Comment by Jessecar96** [comment]
Well maybe you shouldn't use that username then.
