### ISSUE TITLE
Can't confirm trades.

### ISSUE THREAD

**Issue by Thewanildo** [Jessecar96/SteamDesktopAuthenticator#229]
I know a lot of people have the same issue I'm having. I can't auto-confirm trades, my confirmations tab is white and even tho I tried re-installing the Authenticator, it won't work.

**Comment by Igzibed** [comment]
Same problem

**Comment by Ps1d3r** [comment]
Still not working for you? This is happening to me only today...

**Comment by Nonickn** [comment]
This shit started yesterday for me, just blank (white) window whenever I trying to confirm.
 Have using SDA from release without any problem and did change nothing so it's not on my side.

**Comment by B00gi3man** [comment]
Same here.  I have 5 accounts and it is only doing it on one.

**Comment by Ps1d3r** [comment]
I managed to get it to work, just go to "selected Account" then hit "login again" and enter your password, it worked for me as the previous session was expired somehow.

**Comment by Nonickn** [comment]
Oh so much thank you good sir Ps1d3r!

**Comment by Thewanildo** [comment]
OOOOOOOOOOH!
Thank you so much!

**Comment by Ps1d3r** [comment]
Glad i could help :)
