### ISSUE TITLE
Locked out of trading

### ISSUE THREAD

**Issue by JayTehRainbowNinja** [Jessecar96/SteamDesktopAuthenticator#23]
So I got desktop because i dont own a smartphone. worked fine then the following day i got tons of errors, so i removed it and reinstalled it, i had to do this everyday and eventaully i didnt want to make my account secure so i simply didnt bother to enter a code. i was unable to remove my account from  the authenticator because i couldnt log in without this code that didnt exist, i am now completely screwed and i cant even trade anymore, any help would be greatly appreciated, as far as i know my account id still associated with it, i just cant access anything

**Comment by hyt47** [comment]
I used this program today, and it works great for me. If nothing works u can try submitting a ticket to steam, also read the section "Help, I lost (or sold) my phone and can't log in! What do I do?" https://support.steampowered.com/kb_article.php?ref=8625-WRAH-9030#sold

**Comment by hyt47** [comment]
Did u add the old maFiles? If the program asks u for the passkey at startup, then your data is encrypted. Try using your last passkey

**Comment by JayTehRainbowNinja** [comment]
i dont have a renovation code :/

**Comment by hyt47** [comment]
Your only option is to send a ticket to steam, tell them lost your Phone and the revocation code was saved on the phone, and u got another sim card with the same number. Using your email and the phone number you should be able to recover your account

**Comment by JayTehRainbowNinja** [comment]
ok thank you for the help

**Comment by Jessecar96** [comment]
If you deleted your steam account data (within the maFiles folder) there's nothing you can do without your revocation code. **There's a big warning in the description telling you not to do this.**

You can only contact steam support saying you lost your mobile authenticator.
