### ISSUE TITLE
SMS text verification not working

### ISSUE THREAD

**Issue by chad5118** [Jessecar96/SteamDesktopAuthenticator#230]
When I try and do the SMS text verification with a cell, google, or even my prepaid hotspot (which can receive texts. No code is sent. I follow the format +1 555-555-5555

using current version.

Windows 10 Pro x64
AMD FX 6300 Six Core @ 3.52Ghz
16GB of DDR3 memory

**Comment by Jessecar96** [comment]
This is something you have to talk to Steam about. It has nothing to do with SDA.
