### ISSUE TITLE
This is not a valid SteamAuth maFile Import failed

### ISSUE THREAD

**Issue by Hanskin** [Jessecar96/SteamDesktopAuthenticator#231]
I have a few accounts that are a month. Today I try to download MaFile and have the same error on each of these accounts - "This is not a valid SteamAuth maFile Import failed" Other accounts work fine. What could be the problem? The accounts for August work with your program perfectly. So it's not in time their inactive.

**Comment by Jessecar96** [comment]
Most likely they are encrypted. Open the file in a text editor. If you see just gibberish it's encrypted, if it's readable text then there's something else wrong.

To import an encrypted maFile you need to the manifest.json (from when you first encrypted it)  file in the same folder as the maFIle you're importing.
