### ISSUE TITLE
Can't confirm trades

### ISSUE THREAD

**Issue by xrev68x** [Jessecar96/SteamDesktopAuthenticator#235]
For the last two weeks, I've not been getting trade notifications to automatically pop up on my authenticator.  When I force it to check i get the following error.

--
Sorry!
An error was encountered while processing your request:
You've made too many requests recently. Please wait and try your request again later.
Here's a link to the Steam Community home page.
---

Needless to say, steam support is not helpful on their end and I can't exactly tell them I'm using steamdesktop authenticator.

**Comment by hyt47** [comment]
increase the timer to ~ 30 sec

**Comment by xrev68x** [comment]
I found a solution on reddit.  I went under selected account and selected "log in again.'  It worked after that.  This seems to happen with the official steam client as well, so it is something that happens on steam's servers.
