### ISSUE TITLE
Trade confirmation window doesn't work, among other features

### ISSUE THREAD

**Issue by tncheese** [Jessecar96/SteamDesktopAuthenticator#236]
The trade confirmation window just comes up blank white. Refreshing it does nothing. So now I can't confirm any trades.

Also, "Force session refresh" always fails now, and it doesn't save changes to the settings. When I make changes, click Save, then go back to the settings menu, everything's back to the default.

It was working just fine two days ago (December 7). Yesterday, the trade window wasn't working, and I thought it might just be Steam, but today I tried those other things and they're not working.

**Comment by alexgold1994** [comment]
same problem

**Comment by czort87** [comment]
Im not sure its  realeated but market conformations isnt working too , when i try to force refresh get the info  Failed to refresh your session. Try again soon.

**Comment by Jessecar96** [comment]
Re-login to your account using the option in the "Selected Account" menu.

**Comment by czort87** [comment]
Yes thank you thanks what i/we needed:)

**Comment by tncheese** [comment]
Ah, that did it. It requires me to do that again each time I start SDA, though.

Also after I log in with one account, if I log in with another, it says the encryption passkey is invalid. The login still works, but the invalid passkey message is misleading and confusing.

**Comment by alexgold1994** [comment]
re-login helped me, thanks !

**Comment by Nonickn** [comment]
Now just re-login doesn't work too, it gives pop up window that Login or Password is incorrect. Been scared a lot when got it first time. You should re-start SDA now to get it work.
