### ISSUE TITLE
When using WinAuth or/and Steam Desktop Authenticator is there still a way to use Mobile Authenticator?

### ISSUE THREAD

**Issue by nyakze** [Jessecar96/SteamDesktopAuthenticator#239]
I know there is no way to use the official Steam app auth when using third-party PC apps like WinAuth or SDA. But maybe someone knows a third-party mobile authenticator app, that supports importing keys from SDA/WinAuth for simultaneous use?

**Comment by Jessecar96** [comment]
There's no 3rd party phone apps for Steam authentication that I know of.
