### ISSUE TITLE
Remind peope to get "Backup Steam Guard Codes"

### ISSUE THREAD

**Issue by hyt47** [Jessecar96/SteamDesktopAuthenticator#24]
this is a suggestion: add this line in Setup Instructions, for the people that don't know about this option

Setup Instructions:
- Get Backup Steam Guard Codes (Steam > Settings > Manage Steam Guard Account Security > Get Backup Steam Guard Codes)
- ...
- ...

**Comment by Jessecar96** [comment]
Added to the README.
