### ISSUE TITLE
Device not found with ADB avaliable

### ISSUE THREAD

**Issue by Demizeisbest** [Jessecar96/SteamDesktopAuthenticator#241]
So I just downloaded SDA for Windows 8.1, but when I have my phone plugged in to import my account from my android it keeps saying: "Checking for ADB, Device not found." I also cannot connect over wifi as well, for when I do that and put the IP address in nothing happens. I have ADB available on my phone as I checked with the program-tools file on my PC with Android Studio, my LG K7 comes up as "device" in the list of attached devices in the Command Prompt. I have Developer Options and USB debugging enabled. My phone is also not rooted, since you guys say it doesn't need to be. Am I doing something wrong??? Please help.

**Comment by SWooshs** [comment]
Have you installed ADB drivers?

**Comment by Jessecar96** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/262
