### ISSUE TITLE
Nothing appears in my confirmation box

### ISSUE THREAD

**Issue by JayTehRainbowNinja** [Jessecar96/SteamDesktopAuthenticator#245]
I wanted to sell something on the market so I went to list my item, I opened my authenticator and went to confirm my listing, nothing appeared, I tried it with a few more items and nothing appeared in the box, I thought this might have been because my authenticator was outdated so I downloaded the latest version but this still didn't fix my issue, nothing appears in the confirmation box.

**Comment by bestenchant** [comment]
Same thing here. It hasn't worked for some hours now. Maybe Valve made some change that breaks the program.

**Comment by hyt47** [comment]
try: `login again`, or `force session refresh`

**Comment by yabbajam** [comment]
It doesn't work for me either.

**Comment by athanh8807** [comment]
Same issue. And now fixed.
Thanks! It's make me worry :))
