### ISSUE TITLE
Wrong confirmations content.

### ISSUE THREAD

**Issue by Cornul11** [Jessecar96/SteamDesktopAuthenticator#246]
So i've got two accounts in the authenticator, and when trying to see the trade/buy confirmations of an account, it seems like it's showing the confirmations of the other account. Although i have something to confirm, i don't see any possiblity to confirm.

![image](https://cloud.githubusercontent.com/assets/15735127/21272257/225167a2-c3c7-11e6-8ae8-28d21c65d611.png)

**Comment by Jessecar96** [comment]
Are you selecting the account, then clicking "View Confirmations"?

If you have the confirmations window open and select a different account it does not update the confirmations window to the newly selected account.

**Comment by Cornul11** [comment]
Yes, i knew that it may be the reason why this happens, so i verified twice if i'm selecting another account for sure.
