### ISSUE TITLE
Issue with accepting confirmation

### ISSUE THREAD

**Issue by SpaceFrontier** [Jessecar96/SteamDesktopAuthenticator#247]
http://i.imgur.com/WNbVdNJ.png http://i.imgur.com/K2y3E5F.png You can see in the first picture I was able to accept market trades up until the last 2 items I wanted to sell, this has been broken for a day now and I've tried updating to the latest version. Sometimes when I spam the Refresh button on the second picture it goes to a Steam error saying I have tried too many times but nothing else happens. I've tried removing the market listing and relisting it but still nothing changes. It could be an issue with my Steam account but I am able to trade player to player normally.

**Comment by LooneyZ** [comment]
Got this problem too

**Comment by SpaceFrontier** [comment]
Issue fixed:
Go to the "Selected Account" tab at the top and then click "Force session refresh"

**Comment by Syico** [comment]
i got this problem too, if i try to refresh the session i get this error msg: "Failed to refresh your session. Try again soon."

**Comment by Jessecar96** [comment]
Read: https://github.com/Jessecar96/SteamDesktopAuthenticator#troubleshooting
