### ISSUE TITLE
You've made too many requests recently. Please wait and try your request again later.

### ISSUE THREAD

**Issue by 0u0u** [Jessecar96/SteamDesktopAuthenticator#248]
Steam trade dose not work anymore.
Trade confirmations window is either blank or I get message 
"You've made too many requests recently. Please wait and try your request again later."
![you ve made too many requests recently please wait and try your request again later](https://cloud.githubusercontent.com/assets/24628933/21290663/d6bddd9a-c4c3-11e6-946b-7d69ada05cf1.JPG)

**Comment by SpyExcalibur** [comment]
Also getting the same issue.

**Comment by CapoFantasma97** [comment]
I am getting the very same issue. When I have automatic confirmations, they aren't fetched anymore for weeks, and pressing on "view confirmation" (with automatic ones enabled or disabled) gives either a blank page or that error.

I am completely unable to trade because of that.

**Comment by CapoFantasma97** [comment]
For the blank white page, I found out that loggin in again (Selected account>Login again) fixes it.

**Comment by 0u0u** [comment]
What about to many requests error?
I'm not sure if it's STM bug or Steam fault...

**Comment by hyt47** [comment]
increase the timer in the settings to 30 sec

**Comment by 0u0u** [comment]
Thanks, it may help. I never had problem with setting timer to 5 seconds.
Looks like Steam changed something....

**Comment by sjudenim** [comment]
Been having the same problem. Did the suggestions work? I got Steam to remove it from my account so I can't test it for 15 days

**Comment by SpyExcalibur** [comment]
Yes, the suggestions work.  I changed the timer to 30 sec and then logged in again and have not had the problem since.

**Comment by sjudenim** [comment]
Thanks Spy.

**Comment by Yurius2000** [comment]
I helped logout http://joxi.ru/gmv6WL9SLyoxZm

**Comment by Jessecar96** [comment]
Steam will block you from accessing their site temporarily if you refresh the page too much.
This isn't a bug. As said above if you get this message increase the automatic confirmations timer in settings.
