### ISSUE TITLE
importing files

### ISSUE THREAD

**Issue by giorgi21** [Jessecar96/SteamDesktopAuthenticator#249]
hello guys so i  just downloaded new authenticator. but the problem is whenever i try  import files from my old authenticator i get this error. in that folder there is no mafiles folder or something like that
![capture](https://cloud.githubusercontent.com/assets/16269213/21349314/b6d39994-c6ca-11e6-885b-8c41fe28c1ae.JPG)

**Comment by Jessecar96** [comment]
You need to copy the manifest.json file along with the maFile's to import your accounts.
