### ISSUE TITLE
MaFiles

### ISSUE THREAD

**Issue by shishap** [Jessecar96/SteamDesktopAuthenticator#250]
Hello i dont have normal files like: Steam ID: .,... Shared Code: ... etc. i have only numbers, letters and =-,.+ etc. what is going on?

**Comment by shishap** [comment]
some like AnhHzdpjEkASDdzxadUupyE3w=

**Comment by hyt47** [comment]
your file/s is encryped

**Comment by shishap** [comment]
What i need to cryped?  @hyt47 ?? sry idk what you told to me!

**Comment by shishap** [comment]
But i wasnt takę this files from androod, i Just sign in sda my accoumt and thos files is encrypten how to unencrypted then? @hyt47

**Comment by hyt47** [comment]
Use google translate if you don't know english.

To decrypt use the password you added when you encrypted the SDA app. 
You are using this app at your own risk, if you lost your decryption password that's your problem.

 If you didn't import your account from Android and you don't know the SDA decryption code, the only solution is to remove the authenticator. This can result in a trade ban for ~ 14 days. 

If you have Steam Guard Backup Codes, use them.

**Comment by shishap** [comment]
@hyt47 bro but i have SDA now, i login to my account but i cant take: shared key and other to my roulette, becouse my file is coded. how i can uncode it. 
When i using password this file is not decryping!

**Comment by shishap** [comment]
i have it ty!
