### ISSUE TITLE
Card listings not being confirmed

### ISSUE THREAD

**Issue by secretclean** [Jessecar96/SteamDesktopAuthenticator#251]
Hey, SDA hasn't been confirming my trading card listings ever since I set up 5 additional accounts to use with the program. I'm sure that it has to do with multiple accounts, since SDA says the cards were confirmed but my market still shows them as "pending confirmation."

From my "list of items awaiting confirmation":

![1zyliwt](https://cloud.githubusercontent.com/assets/16670517/21436127/f768668e-c84a-11e6-8f72-9158a4eaf9dc.png)

And this is from SDA:

![t1xjtyq](https://cloud.githubusercontent.com/assets/16670517/21436163/28720870-c84b-11e6-9556-90c02c29a5d9.png)

Please check into this. I've got thousands of cards to list for the winter sale, and I'm stuck on the first 250. :(

**Comment by hyt47** [comment]
@Jessecar96  do u know if `SteamAuth` add's a maximum limit for confirmations. I had ~ 150 confirmations to do, & I observed that only ~ 20 to 30 confirmations were done automatically / timer session. I wonder if `SteamAuth` add's a maximum limit or if steam adds a limit. Sending too many requests to steam may cause a problem. I think i'll add a limit to my mod to confirm sets of maximum 20 confirmations.

**Comment by nyakze** [comment]
Same for me. Doesn't seem to work on WinAuth as well. Maybe Steam changed something.

**Comment by Rerinha** [comment]
Yep. Same issue here, unfortunately.

**Comment by Rerinha** [comment]
Just a heads-up to all the people having this issue, I checked out a an older open ticket here with the exact same issue and this worked out for me:

"Re-login to your account using the option in the "Selected Account" menu."

Give it a try, it should refresh the login session and you should be good to go afterwards. :)

**Comment by secretclean** [comment]
OMG Rerinha thank you! That fixed it. You are a life and/or wallet saver!
