### ISSUE TITLE
manifest json problem

### ISSUE THREAD

**Issue by auberdine** [Jessecar96/SteamDesktopAuthenticator#252]
I am having an issue about manifest.json not showing anything which cause Steam Desktop Authenticator can't be opened. Here are pictures to explain my problem. Please help. 

normal manifest.json
![normal](https://cloud.githubusercontent.com/assets/24739862/21463771/e6808fb6-c9a0-11e6-875c-2624e6f9a408.JPG)

my issue about manifest.json
![error](https://cloud.githubusercontent.com/assets/24739862/21463776/f0222fa2-c9a0-11e6-9f89-00ff0cabfee1.JPG)

**Comment by hyt47** [comment]
1. your 1.maFile1's are encrypted ?
2. I assume u don't have a backup of these files to restore from there right?
3. Do u have Steam Guard Backup Codes ?

**Comment by hyt47** [comment]
Possible Solutions:
-----------------

If your .maFile's are not encrypted:
-----------------
**A.** Create a New Folder containing a new SDA App > delete from this new SDA app the manifest file (if it exists) > Copy the .maFiles to maFiles -> Start the app.

**B.** Create a New Folder containing a new SDA App > Start the app > Import .maFile

If your .maFile's are encrypted:
-----------------
You will need to remove the authenticator. If you have  Steam Guard Backup Codes you may be able to remove and re add the authenticator without getting a trade ban of ~ 14 days.

**Comment by auberdine** [comment]
Yes, my maFile's are encrypted and i don't know what triggered the issue that showed in bottom picture.
My question is, can I fix my "broken" manifest.json so I can open SDA again?
I don't have backup of maFiles and just assume that I don't have Steam Guard Backup Codes.

**Comment by hyt47** [comment]
You can't fix it.

**Comment by PapiDimmi** [comment]
I have the same issue. I don’t want to wait yet _another_ 15 days. :(
