### ISSUE TITLE
Can't deactivate

### ISSUE THREAD

**Issue by TheSpamMiner** [Jessecar96/SteamDesktopAuthenticator#254]
It keeps saying that the desktop authenticator can't deactivate.

**Comment by ltholt25** [comment]
Did you ever find a way to fix this problem? I desperately need to deactivate mobile auth for 3 of my accounts and cant

**Comment by RafalNiewinski** [comment]
If you need to deactivate authenticator ASAP try to use revocation code or use option to recover account with lost authenticator.

**Comment by rainerstav** [comment]
i am having the same problem, but the reason i want to deactivate it is because of another problem with confirming trades. pls help
