### ISSUE TITLE
Wont accept phone number.

### ISSUE THREAD

**Issue by Victolabs** [Jessecar96/SteamDesktopAuthenticator#26]
Hi! I recently decided to re enable the SDA. After disconnecting the number from my account i went to set it up again, and this kept happening to me every single time: https://youtu.be/PLp56Kt5g5Y Help? (I have tried many different numbers) Same results.

**Comment by Top-Cat** [comment]
You're including the 1 at the start twice

**Comment by Top-Cat** [comment]
You can also add a phone number here first
https://store.steampowered.com/phone/manage

**Comment by Victolabs** [comment]
I also tried without the one, same result.
