### ISSUE TITLE
Is there a CLI version?

### ISSUE THREAD

**Issue by dynos01** [Jessecar96/SteamDesktopAuthenticator#260]
Will you provide a cli version to run on a linux vps, which sends the confirmation code with email, using a SMTP server? So we can use it even we are using public computers. Thanks

**Comment by PerferctGerund** [comment]
UP
I need cli too

**Comment by Jessecar96** [comment]
There is none that I know of, but you can use the SteamAuth library to make one: https://github.com/geel9/SteamAuth

**Comment by dyc3** [comment]
I made a CLI program to replace SteamDesktopAuthenticator on Linux, [steamguard-cli](https://github.com/dyc3/steamguard-cli). It can read and write the same files that SteamDesktopAuthenticator can, so you don't have to set up your mobile authenticator again. Codes can easily be read from program output.
