### ISSUE TITLE
Loop bug

### ISSUE THREAD

**Issue by gijs242** [Jessecar96/SteamDesktopAuthenticator#261]
when i try to connect an account it keeps asking me the code and sms code. idk how to fix it

**Comment by Moarikino** [comment]
Same :/

**Comment by KunAw** [comment]
Same here

**Comment by aliencaocao** [comment]
same......the problem is STILL FREAKING HERE!!!

**Comment by EnigmaCenter** [comment]
This has been an issue for years.
