### ISSUE TITLE
No confirmations, tried everything.

### ISSUE THREAD

**Issue by Liam429** [Jessecar96/SteamDesktopAuthenticator#263]
I have tried every fix, logging in again with the selected account tab ect. ect. Still white. Thanks for help.

**Comment by forb** [comment]
I'm having the same issue. I've listed a few things on the community market, go to confirm them in the authenticator and nothing's there. It's just a blank space when I click view trade confirmations

**Comment by serrga** [comment]
Check if your maFile contains device id, if its value set to "ERROR", then you need to manually add that data to maFile (check wiki on manual import)

**Comment by deityrox** [comment]
selected accaunt -> login again
