### ISSUE TITLE
Invalid password for just one account.

### ISSUE THREAD

**Issue by serrga** [Jessecar96/SteamDesktopAuthenticator#264]
I've imported three accounts, two are working normally, and the third one is getting "Invalid password" all the time. Password is valid for log-in in browser, in steam client, and on phone, though, it's not valid for SDA.
I'm guessing that SDA doesn't allow passwords with "№" symbol in them, though haven't tested that

Update: changed password to one, not containing "№" symbol, and now SDA accepts it.

**Comment by Jessecar96** [comment]
This is probably an issue with https://github.com/geel9/SteamAuth
