### ISSUE TITLE
Linux Build Problem

### ISSUE THREAD

**Issue by JimDeadlock** [Jessecar96/SteamDesktopAuthenticator#265]
I've followed the instructions to the letter but it fails to build on Ubuntu 16.10/64. Do I have the wrong mono version? If so, which one do I need?

http://pastebin.com/uKEUP4ym

**Comment by prrg** [comment]
You're using the wrong framework. The framework you're using corresponds to .NET 4.0 and SDA uses .NET 4.5. I'm having the same problem.

Don't ask me how to fix it. lol

**Comment by JimDeadlock** [comment]
Awesome thanks, works like a charm!
