### ISSUE TITLE
Unhandled exception..?

### ISSUE THREAD

**Issue by Mecha-Ghandi** [Jessecar96/SteamDesktopAuthenticator#27]
When i go to see my Trade Confirmations, it gives me an error message that says to either quit (which closes the app) or to continue, which will make it attempt to continue. The attempts are unsuccessful. After that explanation, this show up:

Value cannot be null
Parameter name: input.

I'm not very good with files and managing them when it comes to computers, so i have no idea how to come up with a solution. If there's anyone that can help me, i would gladly appreciate it.

**Comment by Jessecar96** [comment]
This should be fixed.
