### ISSUE TITLE
Can not Import from android device

### ISSUE THREAD

**Issue by niceonne** [Jessecar96/SteamDesktopAuthenticator#271]
Hey,

I wanna import the files from my android tablet and I done everything that asks however it says ADB not found on steam desktop application. 
![sem titulo](https://cloud.githubusercontent.com/assets/25206572/22076750/544fcb44-dda9-11e6-80f0-d8a7b7397145.png)

**Comment by hdrkn** [comment]
Paste adb files to SDA Folder

**Comment by willeh1998** [comment]
@hdrkn What adb files?? could you help me?

**Comment by hdrkn** [comment]
@willeh1998, [download](http://www.mediafire.com/file/su3afes608k07ns/adb.zip) and paste this files to folder SDA

**Comment by niceonne** [comment]
ok thanks for the awsner however Its too late because  I removed the authenticator in my android device and I made a new one in this app. :D Thanks anyway

**Comment by willeh1998** [comment]
@hdrkn then i got this error after doing that https://gyazo.com/50879387817094586e37a5c66ff665d2

**Comment by hdrkn** [comment]
@willeh1998, It seems that you have no root

**Comment by willeh1998** [comment]
@hdrkn It says one dont need to have a rooted phone

**Comment by Leomund** [comment]
same problem

**Comment by Jessecar96** [comment]
You can easily install adb with this tool: https://forum.xda-developers.com/showthread.php?t=2588979
