### ISSUE TITLE
Enter the SMS code sent to your phone.... what phone? ~NOOB BUT EASY~

### ISSUE THREAD

**Issue by CoryGreenDev** [Jessecar96/SteamDesktopAuthenticator#274]
It tells you to enter a SMS code that was sent to your phone, but I dont know when to input my phone number. Is this somewhere on my Steam account? Very confused please help

**Comment by routemasters** [comment]
Enter the code on the next screen of the SteamDesktopAuthenticator. And take note of that recovery code.
