### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RJGumby** [Jessecar96/SteamDesktopAuthenticator#278]
SDA suddenly stopped working entirely. When I start the app I get this errror:
https://gyazo.com/cd770d1aebf528a37fdea252645d45ce

I tried reinstalling .net, it didn't help. 

This if the full error log:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Steam Desktop Authenticator.exe
  Problem Signature 02:	1.0.7.2
  Problem Signature 03:	5789155a
  Problem Signature 04:	Steam Desktop Authenticator
  Problem Signature 05:	1.0.7.2
  Problem Signature 06:	5789155a
  Problem Signature 07:	d9
  Problem Signature 08:	1e
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1050
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by RJGumby** [comment]
I downloaded the earlier version of SDA and tried importing my account. I got this error:
https://gyazo.com/c0a77f5f0f936db1a9b0aa8cd30a0bb9

**Comment by maneiak** [comment]
I got the same error, did you fixed it?
