### ISSUE TITLE
Unable to Deactivate Authenticator

### ISSUE THREAD

**Issue by ltholt25** [Jessecar96/SteamDesktopAuthenticator#279]
Recently I was attempting to deactive desktop auth for 3 of my accounts. In all cases the application returned "Error: Unable to Deactivate" or something similar to that. I've updated the application, and restarted my PC. I cant seem to resolve the issue. Does anyone know how to?

**Comment by gccltl** [comment]
You don't need to activate through Authenticator, just go to Steam settings and click 'receive codes by email' - done. And just delete authenticator files in your directory.
