### ISSUE TITLE
Need to log out when on other computer?

### ISSUE THREAD

**Issue by atlissbudder** [Jessecar96/SteamDesktopAuthenticator#28]
Confusing title i know, but i have  a problem.

I have SDA setup on my gaming laptop, and im trying to sign into the same account on another computer. It says that account is already in use. Any ideas on how to fix this?

**Comment by Top-Cat** [comment]
Copy the auth files from the first, you can't have two "different" devices authed.

**Comment by PFCKrutonium** [comment]
This is a good use case for sticking the files in a shared location like Dropbox, with some additional layer of encryption.

**Comment by atlissbudder** [comment]
k, thanks guys!
