### ISSUE TITLE
Device import error

### ISSUE THREAD

**Issue by Wo0Fuck** [Jessecar96/SteamDesktopAuthenticator#281]
I have that error when i try to import from my android device. Do i seriosly need to root it?
![nueva imagen de mapa de bits](https://cloud.githubusercontent.com/assets/11251808/22708502/405cd8dc-ed55-11e6-86ba-887452987263.jpg)

**Comment by Jessecar96** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/233
