### ISSUE TITLE
I can't open the Steam Desktop Authenticator

### ISSUE THREAD

**Issue by SuB1x** [Jessecar96/SteamDesktopAuthenticator#282]
Today i wanna be a good trade but i go in my steam try to load the program but they didn't opened i try to update but nothing.
![default](https://cloud.githubusercontent.com/assets/25644632/22751227/b70db042-ee44-11e6-8bff-f4e3168f4d7f.png)
help plz who can do that

**Comment by Jessecar96** [comment]
I can tell you're not using this version of it with the "SDA Updater" in that folder.

**Comment by guygardner007** [comment]
Hi I am unable to refresh session or re-login not getting confirmations. It was fine till last summer sale.
