### ISSUE TITLE
Trade Confirmations are blank

### ISSUE THREAD

**Issue by clrksml** [Jessecar96/SteamDesktopAuthenticator#288]
If I have trades. Only happened recently this is either one of two things. Valve doing something about mobile authenticators or software error.

http://i.imgur.com/kjkjst4.png
Left is one of my accounts with no pending trades confirmations. And the right has a trade confirmation.
When I view the source of the right window it's completely blank html file.

<html><head></head><body></body></html>

**Comment by clrksml** [comment]
Also someone else on the steam community is having problems too. 

https://steamcommunity.com/discussions/forum/8/135509472107849968/

**Comment by routemasters** [comment]
@clrksml refresh the login OR relogin on the SDA. That's happening because you changed your password.

**Comment by Jessecar96** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator#troubleshooting
