### ISSUE TITLE
Trade and Market Confirmations Not Work More

### ISSUE THREAD

**Issue by mcrmarcelo** [Jessecar96/SteamDesktopAuthenticator#294]
I few days ago my SDA don't work with Trade and Market Confirmations.
For Trade I can't see the popup for accept trade and when I click for see View Confirmations I don't see nothing and after click many time in refresh I see the message .. 
> _"Error
> Sorry!
> An error was encountered while processing your request:
> You've made too many requests recently. Please wait and try your request again later.
> Here's a link to the Steam Community home page."_

My setup for periodically check for new confirmations and shows a popup when they arrive for 10 seconds.
No mark for Auto-confirm Market and Trades.

Thanks for help

**Comment by pizzahut2** [comment]
Same problem here. Maybe it's a temporary issue, or Valve changed something.

**Comment by Jgr9** [comment]
Same here.  Kinda worried....

**Comment by pizzahut2** [comment]
Solution here:
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/251#issuecomment-268926082

**Comment by Jessecar96** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator#troubleshooting
