### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by alexfaria** [Jessecar96/SteamDesktopAuthenticator#296]
Would it be possible to be able to pass the encryption key over command line arguments?
What I'm trying to achieve is to automate the opening of SteamDesktopAuthenticator with keepass.

Then I would be able to do something like this: 
`start "" "D:\Steam Desktop Authenticator.exe" --encryption-key "%1" `

Thank you

**Comment by FoxVodniki** [comment]
I join the request. Very useful feature.

**Comment by pipe0482** [comment]
I will give this a try when I can

**Comment by Jessecar96** [comment]
Added in 9efeeda379efe5dc1bb8c5263569decb1d291c08

**Comment by d4k0** [comment]
@alexfaria May I ask how you use SteamDesktopAuthenticator with KeePass? Auto-Type would be my preferred solution, but SteamDesktopAuthenticator seems to prevent it.
