### ISSUE TITLE
ADB Error

### ISSUE THREAD

**Issue by FishPhase** [Jessecar96/SteamDesktopAuthenticator#297]
Before you refer me to #262, I have rooted my phone. I just don't understand what ADB actually is. I have chosen the second option i.e 'I have an android device and want to import my Steam accounts from the Steam App'. Now I see a log which alternates between 'Checking for ADB' and 'ADB not found'. Apparently it's something with the manifest.json, but I really am not much of a software/coding/programming person. I do have the mental capabilities to follow instructions though.

**Comment by Jessecar96** [comment]
ADB is a tool to communicate between a computer and an android phone. 
You can get it here: https://developer.android.com/studio/releases/platform-tools.html 
Copy the contents of the platform-tools folder into the SDA folder, so that adb.exe is in the same folder as SDA.

**Comment by FishPhase** [comment]
Thanks a ton! It finally did work; I didn't know you needed platform tools, and, to be fair, I didn't know anything. It seems like it is working now; this thread can be closed if it hasn't yet.
