### ISSUE TITLE
maFiles not being made properly

### ISSUE THREAD

**Issue by foreverlonglost** [Jessecar96/SteamDesktopAuthenticator#298]
Every time I add an account to the authenticator it generates a mafile, but inside it is just a bunch of random characters instead of it listing the id and so on.

Any idea what is wrong or what i might be doing wrong?

**Comment by Jessecar96** [comment]
This is a result of encryption. If you want to view the contents of the maFiles you need to disable encryption.

**Comment by foreverlonglost** [comment]
Thank you so much, but now I feel like an idiot
