### ISSUE TITLE
Steam Desktop Authenticator cannot find my confirmation

### ISSUE THREAD

**Issue by kagonoki** [Jessecar96/SteamDesktopAuthenticator#301]
So I listed one of my items in the Steam Market
![steam market listing](https://puu.sh/uWKUe/9de08b396f.png)

and it's not showing up on the SDA confirmation.
![SDA](https://puu.sh/uWKWZ/396f38e3d1.png)

**Comment by Cush1337** [comment]
Selected Account > Force session refresh and logging back in fixed this issue for me.

**Comment by kagonoki** [comment]
well man, i cant log back in because I don't have my login token as my steam mobile authenticator is not installed. i have to remove this authenticator and add it back again to receive codes again on my phone.

**Comment by Cush1337** [comment]
Mine didn't ask for a code to log in again.

If you go to your Steam account settings > Manage security >Get Backup Codes, you can use a working code to generate a bunch of permanent ones to use just in case you accidentally lock yourself out.
