### ISSUE TITLE
confirmations window wont load

### ISSUE THREAD

**Issue by Oaaa** [Jessecar96/SteamDesktopAuthenticator#305]
hi,

when i klick on "View Confirmations" the window opens, but stays completely white. when i press refress like 10 times, it shows me that i made too many requests recently and denies me access. this erreor started first with only one account (i use different accounts on the programm). now every single one is like this. i can logg in to the accounts in my browser, the steamaccounts work fine. but it doesnt show in the steam desktop authenticator.

http://fs5.directupload.net/images/170330/hzh9rqbk.jpg

the pricture shows the same account on the left side how it opens, on the right side how it becomes after i press a couple of times refresh within a short periode of time. if u just press refress once or twice, nothing happens. i have the latest version. this program did run perfect for about a year.

**Comment by 4815162342lost** [comment]
Same problem.

I think that issue is related with Steam servers. Temporary problem.

**Comment by Oaaa** [comment]
then the account linked to my mobile phone should have the same issue. but it doesnt. i hope its just a server related issue that will be fixed soon because i got a couple of accounts with a lot of money and items in this programm, waiting a week would be a pain in the butt

**Comment by xx55tt** [comment]
Had the same issue. You have to [login again](https://github.com/Jessecar96/SteamDesktopAuthenticator#troubleshooting).

**Comment by Oaaa** [comment]
did the "login again" and now it works. thanks for the help!
