### ISSUE TITLE
Stuck at "Input the SMS code"

### ISSUE THREAD

**Issue by MrDexter** [Jessecar96/SteamDesktopAuthenticator#307]
So everything was going fine, inputted my number and received the first SMS code, Wrote down my Revocation code and clicked "Ok"

Then it says "Input the SMS code sent to your phone" The issue is that I haven't received another SMS code and the first one doesn't work.
Is this a bug or am I doing something wrong?

Thanks for any help.

**Comment by Trahax** [comment]
This has happened to me you can enter absolutely anything and it'll just take you to the enter revocation code and it'll just do this infinitely
