### ISSUE TITLE
Confirmations error

### ISSUE THREAD

**Issue by Descentfreak1032** [Jessecar96/SteamDesktopAuthenticator#308]
I don't know what's causing the issue, but when I check my confirmations, whether I'm trading or not, all I get is a blank white screen. I've refreshed several times, and nothing worked. I won't be able to trade if this problem doesn't get resolved.

**Comment by godrider** [comment]
I got the same problem as you for a while now. I don't know how it happend but for the last few weeks I haven't be able to trade, or get the confirmation window to work in SDA. Even the troubleshooting doesn't help. I'm using Windows 10, 64bit.

I've tried the following on v1.0.7.2
1. Selected Account -> Login Again -> "Error logging in: Steam returned 'GeneralFailure'"
2. Selected Account -> Force Session refresh -> "Failed to refresh your session. Try again soon"
3. Reinstalling SDA to check if I've gotten any corrupted files.
4. Increased waiting time between checks to 60 seconds.
5. Restarting my PC multiple times.

Even all of this, and still no luck.

**Comment by sgudyma** [comment]
Same thing.
However it can be reproduced only for some accounts. I have 6 and only 3 of them work fine

**Comment by Descentfreak1032** [comment]
Okay, I think I found the solution. It turns out my credentials expired. Under "Selected Account", click "Login again", and that should fix the issue. It did for me. :)

**Comment by godrider** [comment]
FInally, after numerous of tries it worked @Descentfreak1032, thanks.
