### ISSUE TITLE
Removed the wrong thing

### ISSUE THREAD

**Issue by StanoDrabik197** [Jessecar96/SteamDesktopAuthenticator#309]
So i've deleted the wrong folder. It was the SDA, and now i can't get into my account because i can't get my  Steam Guard Code. Please help me

**Comment by frwrks** [comment]
Try going to the Recycle Bin and undeleting what you deleted. You didn't say you permanently deleted.

You "permanently" deleted? Try an undelete utility ASAP. If you can only partially recover files from that location, use a fresh folder of SDA in a separate location and see what you can do from there (but undelete first, before writing any more data to that drive).

Can't recover (enough)? Enroll in Hogwart's to learn witchcraft or magic or whatever those guys do. Use your recovery code to reset Steam Guard and then enable Steam Guard on your account again if you so wish, this time being careful not to carelessly delete folders.

Don't have your recovery code? Contact Steam support and be prepared to give them every bit of information they ask for.
