### ISSUE TITLE
Endless Captchas after Setup new account

### ISSUE THREAD

**Issue by Luthorian** [Jessecar96/SteamDesktopAuthenticator#31]
Added my phone number to Steam, got the SMS and wrote it in the proper location, downloaded and ran your application. After I click Setup new account and add my login data, a captcha screen pops up that I fill and submit, then another, and another, and another and so forth. I highly doubt I just got 16 captchas wrong in a row,

**Comment by pipe01** [comment]
I think it's a SteamAuth bug, as it happened to me once when using the library.

**Comment by gmmanonymus111** [comment]
Same problem here, it seems it doesn't matter what you type, it's going to fail
Also, i don't know if i sould open a new issue (still new to github), but when i managed to log in, the program asked for a steam guard code as usual, then asked the phone number. After that, it aksed dor the encryption key, but in the ***** format, and loaded the already added accounts. Now i can't login completelly as the program throws me back to 'the main menu' like nothing happened. Am I the only one who experienced this issue?

**Comment by hyt47** [comment]
Did u useded the version 0.2.3 from here ? https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

- I added  the phone number on steam
- Added new account to this app
- I got a code on my phone from steam
- Wrote it in the program to activate it
- Done

**Comment by gmmanonymus111** [comment]
Thank you, i'll try it

**Comment by hyt47** [comment]
If u decide to compile the code from there use the first part of this tutorial https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/33 and stop at section "Compile and test the x64 version"

**Comment by gmmanonymus111** [comment]
Maybe a dumb question, what should i do with the SteamAuth folder if VS2013 wants a SteamAuth.csproj?

**Comment by pipe01** [comment]
There is a .sln file, open it by double clicking or in vs

**Comment by hyt47** [comment]
yes use it from https://github.com/geel9/SteamAuth - i will correct my mistake

**Comment by gmmanonymus111** [comment]
Thank you @hyt47 for your help
I couldn't add, now it's working. Seems we can't add more than 8 accounts
Solution(workaround?): Create a new folder, paste the program (without maFiles folder), set up the 9th account (rembember to use the same encryption key). After all your accounts' done, open manifest.json (in the 2nd program dir), copy everything between '{"encrypted":true,"entries":[]}' and paste it to manifest.json in the 1st program dir before the ']}' (use a ',' after the last entry in the 1st file). Now it should add your accounts to one program. Keep the 2nd folder in case of any error/bug

The endless captcha still there, though

**Comment by hyt47** [comment]
Thx for info @gmmanonymus111 is good to know this workaround.

**Comment by Jessecar96** [comment]
I'm pretty sure this is a SteamAuth bug, but I cannot replicate it.

**Comment by pipe01** [comment]
Yeah, it happened to me when I first used the library

**Comment by Jessecar96** [comment]
I suggest you make a bug report at https://github.com/geel9/SteamAuth then.
