### ISSUE TITLE
Problem when I compile SDA in linux 

### ISSUE THREAD

**Issue by seekerdasbatatas** [Jessecar96/SteamDesktopAuthenticator#311]
Hi , I'm using Ubuntu Mate 16.04LTS  and I'm having a problem when I compile SDA on monodevelop.
When I compile it shows this:  
![screenshot at 2017-04-11 11 57 15](https://cloud.githubusercontent.com/assets/15021757/24906026/0c2c5d14-1eae-11e7-9504-bcbf5ec8936b.png)

Please Help, 
Seekerdasbatatas

**Comment by pipe0482** [comment]
Make sure that you reference SteamAuth from the SDA project.

**Comment by seekerdasbatatas** [comment]
It Works thanks :D

**Comment by pipe0482** [comment]
No problem!

**Comment by dyc3** [comment]
For future reference, I made a CLI program to replace SteamDesktopAuthenticator on Linux, [steamguard-cli](https://github.com/dyc3/steamguard-cli). It can read and write the same files that SteamDesktopAuthenticator can, so you don't have to set up your mobile authenticator again.
