### ISSUE TITLE
Won't decrypt my maFiles

### ISSUE THREAD

**Issue by BigRedDoge** [Jessecar96/SteamDesktopAuthenticator#312]
No matter what I do my maFiles won't decrypt.  I've tried giving sda administrator privilages, refreshing my login, encrypting and decrypting my accounts.  I don't know what to do.

**Comment by TheGlenCoco** [comment]
Remove your password for SDA and open your maFile.It should be working, atleast for me did.Than you can add your password back!

**Comment by Jessecar96** [comment]
Click "Manage encryption", enter your current password, then just click accept without entering anything in the next two windows to disable it.
