### ISSUE TITLE
VOIP Numbers No Longer Accepted

### ISSUE THREAD

**Issue by NotKnee** [Jessecar96/SteamDesktopAuthenticator#313]
Steam no longer accepts VoIP numbers when linking a number to an account, and therefor Google Voice numbers (or any other free VoIP provider) will not work for setting up SteamDesktopAuthenticator. 

EDIT:
I realize this isn't necessarily an issue within the program, but I just thought that the readme.md was a little misleading with this line, "Login to Steam and follow the instructions to set it up. Note: you still need a phone that can receive SMS, you can get a free SMS enabled phone number from Google Voice in the US"

**Comment by Jessecar96** [comment]
Fixed with cf96abe29de5c3f0c5eff33612abb8eaf4a69f84
