### ISSUE TITLE
SDA Not Giving Confirmations to trade offers

### ISSUE THREAD

**Issue by help12341** [Jessecar96/SteamDesktopAuthenticator#314]
http://imgur.com/a/4Jn78

1. Ran SDA as admin.
2. Selected Account > View Confirmations > White screen (see in imgur link)
3. Selected Account > Force Session refresh > Failed to refresh your session. Try again soon
4. Increased waiting time between checks to 60 seconds. (see in imgur link)
5. Reinstalling SDA to check if I've gotten any corrupted files.
6. Restarted my PC once after making sure my PC was updated and the program.
7. Problem continues.

Anyone know of a fix or is it a current bug?

**Comment by evrohachik** [comment]
i have same error today
still now working

**Comment by lavaraba** [comment]
I had the same problem, going to selected account > login again fixed it for me.

**Comment by help12341** [comment]
lavar I LOVE YOU

**Comment by help12341** [comment]
Someone mark this please i know other people have had this issue and this does fix the problem. Just do exactly what lavaraba says and you should be good to go.

**Comment by ScrapEngineer** [comment]
Where's selected account?

**Comment by Diablosito33** [comment]
Exactly the same on me.

**Comment by Diablosito33** [comment]
Would this may be caused by "device id"?

When I use $ adb devices
I got this:
```
List of devices attached
0123456789ABCDEF        device
```

Isn't this used when retrieving trade offers?
