### ISSUE TITLE
Hotkey to copy SG code

### ISSUE THREAD

**Issue by Avatarus-one** [Jessecar96/SteamDesktopAuthenticator#316]
Sometimes Steam closes the active session, preventing to accept further trades. It would be great to have a global hotkey combination to copy the current Steam Guard code to clipboard. That way I could make the bot to relog automatically.

**Comment by Jessecar96** [comment]
Added in 58c60c24ed01386c7af7b3d4e5497ecad522a043
Pressing CTRL + C anywhere in the form will copy the current login token.
