### ISSUE TITLE
Can't get Device ID although phone is rooted

### ISSUE THREAD

**Issue by gornikp** [Jessecar96/SteamDesktopAuthenticator#317]
Hello,
I have an issue with importing the account from my device. I tried to debug the code found this error while trying to get the device ID. I'm 100% sure I'm rooted and ADB should have access to that directory.  Instead of "steam.uuid.xml" file I got following message:
"/system/bin/sh: cat: /data/data/com.valvesoftware.android.steam.community/shared_prefs/steam.uuid.xml: Permission denied" I did a workaround for myself and hardcoded the device ID. You should consider adding  the manual deviceId input :)

Cheers :)

**Comment by Jessecar96** [comment]
Fixed #323
