### ISSUE TITLE
Cant sort multiple accounts

### ISSUE THREAD

**Issue by DoomLordDoom** [Jessecar96/SteamDesktopAuthenticator#318]
Hello,

I use SDA a lot with multiple accounts on the same auth (over 15 accounts). The accounts have numerical values, 1-15 and so forth.

Initially i set the accounts up in order, so account no. 1 would display first, then 2., 3. and so on.

When updating to a newer version, the accounts got all out of order, going 1-2-4-3-7-5-6-15 etc. Is there any simple fix to this?

**Comment by pipe0482** [comment]
You should be able to edit the manifest AMD reorder the accounts, but make
sure to disable encryption and make a backup of the file.
I may add some way of sorting in my fork when I'm able to anyways.
