### ISSUE TITLE
Auto Accept Trade confirmation.

### ISSUE THREAD

**Issue by darknegative** [Jessecar96/SteamDesktopAuthenticator#32]
Is it possible to add a tab that gives you the option to autoconfirm "Trade Confirmations?" Instead of clicking accept to each one of them?

I'm sorry if i'm posting in wrong possition. I tried to post it on Pull requests and it wont let me.

**Comment by geel9** [comment]
It's in the plans, but there are some security concerns that need to be resolved.

**Comment by Nonickn** [comment]
Ah was gonna make exactly the same request. And by the way thank you Geel and Jessecar for the app

**Comment by Dabann** [comment]
It would be very helpful. I hope that this feature will be available soon.

**Comment by Fl4ilinat0r** [comment]
would it be possible to cancel(/not accept) offers that would end up in a trade hold?
would be useful for bot users.

**Comment by hyt47** [comment]
useful for any trader

**Comment by Fl4ilinat0r** [comment]
true. I do key banking and now only have my inventory not locked until 14 dec. (2keys) i'm happy I stocked my other keys on other account.

**Comment by muratkerimoglu06** [comment]
Hi, I have a jackpot site that needs bot which works properly. With the new update, the bot doesn't work as you guess. 

Could you please enhance this program for gambling site BOTS. We can setup this program on our VDS and make the bot work.
If you have got any questions please send me an email; mkerimoglu06@gmail.com

If you can do it, I would really appreciate you .

**Comment by pipe01** [comment]
You can use jessecar's steamboat.

**Comment by novikk** [comment]
+1

**Comment by cjf93** [comment]
Would be very nice! 
![Just Do It!](https://media.giphy.com/media/BHKpXZnLkYFYk/giphy.gif)

**Comment by pipe01** [comment]
Can't resist to Shia

**Comment by Nonickn** [comment]
Any news?

**Comment by pipe01** [comment]
Jesse Said he doesnt wanna do it, so that's basically a no :/

**Comment by Nonickn** [comment]
@pipe01 I remember you said you gonna add it in your fork, have you done it?

**Comment by pipe01** [comment]
I didn't do it as Jesse said he wasn't gonna implement it.

**Comment by Avatarus-one** [comment]
RIP trading bots.

**Comment by Nonickn** [comment]
So sad to hear :( I was hoping there's a fork with this function

**Comment by pipe01** [comment]
Well, I can still make it in a fork, but it won't be merged to SDA.

**Comment by Nonickn** [comment]
Will just use a fork, really appreciate if you can do that.

**Comment by pipe01** [comment]
Sure, I can get to it either tomorrow or this weekend.

**Comment by Nonickn** [comment]
Thank you very much.

**Comment by pipe01** [comment]
I have finished implementing it, but i haven't tested it yet: pipe01/SteamDesktopAuthenticator@621110856e7af80a6d7097efcddbe508057d0ba0

**Comment by Nonickn** [comment]
Thank you sir! But ... I know sounds stupid but how I can download your Fork?

**Comment by pipe01** [comment]
Click on download zip

**Comment by pipe01** [comment]
Or here https://github.com/pipe01/SteamDesktopAuthenticator/archive/autoaccept.zip

**Comment by Nonickn** [comment]
Yeah that I figured out just thought maybe there's compiled version.

**Comment by pipe01** [comment]
Oh, I didn't do that.

**Comment by Nonickn** [comment]
Ah I see, I'm just not that familar with Visual Studio. Maybe need download it and try.

**Comment by pipe01** [comment]
If you wait until the weekend I can build it for you.

**Comment by Nonickn** [comment]
Oh yeah sure. I'm so grateful

**Comment by Avatarus-one** [comment]
Idea. When auto accept is enabled in settings, add a checkbox to the main form to allow temporary disable it. It is even safer if this additional setting is always disabled on the program startup.
How should it work when both settings are enabled? Pop-ups still appear when you have offers to accept, but now they are also accepted automatically after a delay you specified in settings (minimal allowed value should be around 30-60 seconds). So, now you can either wait till your offers are auto-accepted or accept/decline them manually. Of course, all gift offers should be skipped.

**Comment by codeduph** [comment]
this request will actually breaks what valve wants for its "Steam Authenticator".

so, next time valve will implement 30 mins pause between trading.

**Comment by routemasters** [comment]
jessecar stated it like for multiple time he isn't adding auto-accept. what's the point of keep asking for this feature?

**Comment by impman** [comment]
Auto accept technically ruins the point of the authenticator, but clicking through like 10 different trade confirmations I've sent is certainly tedious.
Personally the quickest system to use would just be a table of current trade offers, in the form

User Trading With | Items Lost | Items Gained | Confirm button

With a "Confirm All" button at the top. Would definitely be better than clicking each one individually, waiting for it to load, pressing send offer, waiting for the list to load, etc.

**Comment by routemasters** [comment]
@impman it's already like that: https://i.imgur.com/vKq8oa8.png

**Comment by impman** [comment]
@routemasters That's not quite what I meant - I meant that I would like a table of all pending confirmations so I can look over all of them at a glance and easily confirm/deny them all with a single click, as well as individual confirmations.

Take this mockup I made in Google Spreadsheets.

![mockup](https://cloud.githubusercontent.com/assets/6895211/12533759/abd05c82-c200-11e5-9b15-8a57d299e0b5.png)
