### ISSUE TITLE
When I try to check my trade confirmations it never works...

### ISSUE THREAD

**Issue by HAYDENKUN** [Jessecar96/SteamDesktopAuthenticator#321]
It just shows a white background with the window open. It used to work sometimes but now it NEVER does [https://gyazo.com/cbf6dea884cd010b82fab60b60762ab2](url)

**Comment by LeMagician** [comment]
Same with me SOMEBODY DEVELOPERS HELP US... ITS Kind of annoying how my whole account RELIES ON THIS ,and NOONE WILL RESPOND!

**Comment by mumixam** [comment]
did you try whats in the readme?
```First open the "Selected Account" menu, then click "Force session refresh". If it still doesn't work after that, open the "Selected Account" menu again, then click "Login again" and login to your Steam account.```
