### ISSUE TITLE
Issue with Confirmations! :(

### ISSUE THREAD

**Issue by LeMagician** [Jessecar96/SteamDesktopAuthenticator#326]
I have knives in my CSGO account, trying to cash them out, and I can't even confirm the trade... 

I click confirmations: https://gyazo.com/b2ffabca201d562c3b4b8ce9aa8cdb25
THIS IS WHAT HAPPENS: https://gyazo.com/b2ffabca201d562c3b4b8ce9aa8cdb25

Its just a white screen, somebody please help me, Ill probs pay for the help. thanks. :(

**Comment by pipe0482** [comment]
Hey man, you can try to press "Force session refresh" under the "Selected
account menu". If that doesn't work, try "Login again" under the same menu.

**Comment by Jessecar96** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator#troubleshooting
