### ISSUE TITLE
The SDA wont open At all

### ISSUE THREAD

**Issue by FrankieTheTammy** [Jessecar96/SteamDesktopAuthenticator#328]
Recently i tried to open it so that i could disable the authenticator.but it wont open.it told me ot open vs and enable JIT debugging .i couldnt find that option so i opened sda.exe it told me this error pls help me

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Steam Desktop Authenticator
  StackTrace:
   at Steam_Desktop_Authenticator.Program.Main()

what should i do ?

**Comment by ScrapEngineer** [comment]
I've had this issue too with no resolution, you need to switch to mobile authenticator.

**Comment by SniPeY007** [comment]
Same Problem here but couldn't find any solution

**Comment by ScrapEngineer** [comment]
What version of Windows are you on actually?
I was on 8.1... So...

**Comment by FrankieTheTammy** [comment]
I have SDA on Windows 8.1
I have tried to open it for the the past one week but to no avail .
I am out of a sudden logged out of all my steam accounts  and cant play at all .
i am so desperate that i want to disable mob authenticator and not use it again at all.
idk what to do ? PLS help

**Comment by FrankieTheTammy** [comment]
scrapengineer i dont have a smartphone.all i have is a frickin' nokia

**Comment by ScrapEngineer** [comment]
Frankie, that's odd... I was on Windows 8.1 too, try upgrading to Windows 10 if you can.

**Comment by SniPeY007** [comment]
The fix for me was to delete the file (I don't remember its name. Its the
important one.) and disable the mobile authenticator through steam. Then
delete SDA and install a new one which means i had to enable it again and i
got 15 days trade hold.
