### ISSUE TITLE
Build Tutorial for windows XP x86 for version 0.2.3

### ISSUE THREAD

**Issue by hyt47** [Jessecar96/SteamDesktopAuthenticator#33]
I managed to compile a version for XP using Visual Studio 2013. I did a short test and it worked ok.

- Tested on Windows XP x86 & Windows 7 x64
- For windows XP the GUI is too white, but at least works fine

Download version 0.2.3
------------------------
------------------------
https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
Extract

Download SteamAuth
------------------------
------------------------
https://github.com/geel9/SteamAuth
Extract
copy the content from "SteamAuth-master" inside "SteamDesktopAuthenticator-0.2.3\lib\SteamAuth\"

final paths must be: 
"SteamDesktopAuthenticator-0.2.3\lib\SteamAuth\SteamAuth\SteamAuth.csproj"
"SteamDesktopAuthenticator-0.2.3\lib\SteamAuth\TestBed\TestBed.csproj"

Open with Visual Studio (I used 2013)
------------------------
------------------------
Error
--------
Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=7.0.0.0, 
Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". 
Check to make sure the assembly exists on disk. If this reference is required by your 
code, you may get compilation errors.	SteamAuth

Repair
--------
1. Open up "SteamAuth > packages.config"
2. Delete the Newtonsoft.Json entry.
&lt;package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />

3. Save and Build
4. Re-add Newtonsoft.Json from NuGet.
	SteamAuth > Right click on "References" > Manage Nuget packages...
		find  Online > Json.Net > install
5.Build and run

warnings
------------
if u get any warnings is because u have a file opened up in visual studio
close it and recompile

Compile and test the x64 version
----------------------------------
----------------------------------
If it works fine, u can edit the code to make it for x86 widnows XP

----------------------------------
----------------------------------
----------------------------------
----------------------------------
Make the app for x86
----------------------------------
----------------------------------
Visual Studio > Build > Configuration Manager
in the project:
Steam Desketop manager | select "Any CPU" > New > 
  - New Platform: x86
  - Copy settings from: Any CPU
  - Uncheck "Create new solution platforms"

do the same for:
SteamAuth | select "Any CPU" > New > 
- ...

----------------------------------
----------------------------------
----------------------------------
----------------------------------
Make the app for widnows XP
----------------------------------
----------------------------------

Change to .Net Framework 4
---------------------------
In Visual Studio in the right > Solution Explorer > Steam Desktop Authentificator > 
 Properties > Application > .Net Framework 4

In Visual Studio in the right > Solution Explorer > SteamAuth > 
 Properties > Application > .Net Framework 4

Build > u will get some errors > Popup: Run the last successful build? NO

Steam Desktop Authentificator - Update Json.Net for net framework 4
--------------------------------------------------------------------
1. Open up "Steam Desktop Authentificator > packages.config"
2. Delete the Newtonsoft.Json entry.
" &lt;package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />"

3. Save and Close the file "packages.config"
4. Re-add Newtonsoft.Json from NuGet.
	SteamAuth > Right click on "References" > Manage Nuget packages...
		find  Online > Json.Net > install

5. Popup Message: The file was modified outside the source editor. Do you want to reload it?
Yes

6. Build > u will get some errors > Popup: Run the last successful build? NO

SteamAuth - Update Json.Net for net framework 4
--------------------------------------------------------------------
1. Open up "SteamAuth > packages.config"

do the same as above...

Error
--------
'System.Net.WebUtility' does not contain a definition for 'UrlEncode'

Repair
--------
.NET Framework 4.0 was already added

Add a reference to System.Web using the "Add Reference" dialog.
SteamAuth > References > Add Reference > search for "System.Web"

Search in Entire solution "WebUtility.UrlEncode"
- u will find results inside: AuthenticatorLinker.cs, SteamGuardAccount.cs, SteamWeb.cs

- when u find a match add at the top of the page: using System.Web;

- after u added to all that code search again and replace "WebUtility.UrlEncode" with "HttpUtility.UrlEncode"

Compile u will get a few warnings > the program will run ok

----------------------------------
----------------------------------
----------------------------------
----------------------------------
App error in Xp
-----------------
-----------------
application failed to initialize properly 0xc0000135

Repair
--------
install net framework 4
net framework 4 might ask u to install first Windows Imaging Component > install it

Done enjoy ^_^
-----------------
-----------------

I can give u a compiled version. 
THIS IS NOT RECOMMENDED, It's best for you to compile your own code. 
For security reasons !!! 
Maybe this will be added by the developer in a future build.

**Comment by gi1mor** [comment]
i extracted SteamAuth in   ...\lib\SteamAuth\.
but i can't build solution , visual studio don't see SteamAuth. 
errors : 
The referenced component 'SteamAuth' could not be found. 
The referenced project '..\lib\SteamAuth\SteamAuth\SteamAuth.csproj' does not exist.

**Comment by hyt47** [comment]
the final path must be: 
SteamDesktopAuthenticator\lib\SteamAuth\SteamAuth\SteamAuth.csproj

check your folder path

**Comment by slithe** [comment]
I still couldn't  build it, probably using too old of a vs, is there anyway that you can compile this for me? been here awhile now trying to do it and i can't :(

**Comment by hyt47** [comment]
I aready have it compiled, and stored in my colection! Use it at your own risk! Is not recomanded to use compiled stuff from random Users. I added the complete Source Code & Compiled version here https://github.com/hyt47/SteamDesktopAuthenticator-for-XP-x86

**Comment by slithe** [comment]
I saved all 3 will take a look at source as well, thank you, you are really help me out.

**Comment by hyt47** [comment]
I'm glad I could help! ^_^
