### ISSUE TITLE
+ CC Number issue

### ISSUE THREAD

**Issue by gccltl** [Jessecar96/SteamDesktopAuthenticator#330]
I can't add mine number because when i write it in lithuanian format: + 370 6 44***0
It gives me GeneralFailure error.

370 - Country code.
6 - Town code (but this is same, in all towns, so whatever...)
And 44***0 is the number.

Whats wrong?

**Comment by FrankieTheTammy** [comment]
i too am facing this error

**Comment by Jessecar96** [comment]
"GeneralFailure" is the response given by Steam. There's nothing we can do about this. Try adding your phone number from your steam settings.
