### ISSUE TITLE
Can't open Steam Desktop Authenticator!!!

### ISSUE THREAD

**Issue by SniPeY007** [Jessecar96/SteamDesktopAuthenticator#332]
My SDA is not opening today. It was working yesterday but i couldn't open it today. I click on it and nothing happens... It does show up in the task manager for like 3 seconds and vanishes....
_**PLEASE HELP!!!!!**_
**_P.S._** No Errors...

**Comment by ScrapEngineer** [comment]
What version of windows are you on?

**Comment by PapiDimmi** [comment]
I have the same issue (on Windows 10). Why was this closed?
