### ISSUE TITLE
Unhandled exception - Illegal characters in path

### ISSUE THREAD

**Issue by kozmo47** [Jessecar96/SteamDesktopAuthenticator#333]
This happens when i try to import from my android device.

This is what is written in that pop-up https://pastebin.com/wjYdXGK4
And this is adblog https://pastebin.com/fYv8jE9Z

**Comment by Jessecar96** [comment]
Read here: https://github.com/Jessecar96/SteamDesktopAuthenticator/wiki/Importing-account-from-an-Android-phone

Your phone must be rooted for this to work now.
