### ISSUE TITLE
No steamauth folder?

### ISSUE THREAD

**Issue by gccltl** [Jessecar96/SteamDesktopAuthenticator#334]
I downloaded it with git clone 'adress' on Kubuntu, clicked .sln with monodevelop, and error appears, with no folded 'steamauth'
Any help? Redownloaded this many times, but still.

**Comment by Jessecar96** [comment]
This project uses submodules. You need to download them using these commands:
```sh
git submodule init
git submodule update
```

**Comment by gccltl** [comment]
Thanks did sth that you said by this tutorial:
First change to the directory where you want to build the project. I'm using ~/build as an example
`cd ~/build`
Then clone the repository using git.
`git clone https://github.com/Jessecar96/SteamDesktopAuthenticator`
Change into the new folder and update the submodules
`cd SteamDesktopAuthenticator`
`git submodule update --init --recursive`
Then you can open the .sln and continue with the instructions. Updating the Newtonsoft.Json package can take a while, so be patient.
