### ISSUE TITLE
maFiles not opening on SDA

### ISSUE THREAD

**Issue by Schknheit** [Jessecar96/SteamDesktopAuthenticator#336]
So, yesterday I was adding some phone numbers and I diceded to cut some of the .maFile to another SDA. When I tried to open it, nothing happened, even though they are not encrypted. They just don't appear on the program. I tried with a fresh version of it and still nothing happens. The program loads normally but any of the accounts show up.

**Comment by Schknheit** [comment]
So, I solved it by adding one by one on the import tab, but still one thing bothers me. Why can't i just throw the .maFiles on the folder and the program load it?

**Comment by Jessecar96** [comment]
Because they need to be loaded into manifest.json which is what the import menu does.

**Comment by Schknheit** [comment]
Oh, I see, I thought the manifest.json was like an example like archi did on asf. My bad. Thanks anyway!.
