### ISSUE TITLE
Application not opening on Windows 8.1

### ISSUE THREAD

**Issue by ScrapEngineer** [Jessecar96/SteamDesktopAuthenticator#340]
So apparently some people can't open this application, so far I've came to the conclusion that this is Windows 8.1, might also apply to Windows 8.

So upgrading systems is something I advise for users experiencing this.

**Comment by RealBrianOG** [comment]
Happened to me too today. I can't open it at all. I got winodws 10.

**Comment by jblvd** [comment]
I'm with windows 7 and here it don't open. I can't access my account

**Comment by PapiDimmi** [comment]
I have the same issue, and I use Windows 10.
