### ISSUE TITLE
Does 'Import from android device' works in GNU/Linux, Ubuntu?

### ISSUE THREAD

**Issue by gccltl** [Jessecar96/SteamDesktopAuthenticator#342]
If it's not, can I somehow import it another way?
**EDIT: Does linking in Windows OS will do sth? And then I can import maFile in to mine ubuntu system?**

**Comment by dyc3** [comment]
I made a CLI program to replace SteamDesktopAuthenticator on Linux, [steamguard-cli](https://github.com/dyc3/steamguard-cli). It can read and write the same files that SteamDesktopAuthenticator can, so you don't have to set up your mobile authenticator again. It can't import from android right now, but submit a feature request and I'll see what I can do.

**Comment by gccltl** [comment]
> 
> dyc3 commented 3 hours ago
> I made a CLI program to replace SteamDesktopAuthenticator on Linux, steamguard-cli. It can read and write the same files that SteamDesktopAuthenticator can, so you don't have to set up your mobile authenticator again. It can't import from android right now, but submit a feature request and I'll see what I can do.
> 

Well if it doesn't have any extra things, it is not worth it...
