### ISSUE TITLE
S.D.A dont show new Confirmations (FIXED)

### ISSUE THREAD

**Issue by lolikuzz** [Jessecar96/SteamDesktopAuthenticator#346]
4-3 days ago it was working fine, but now sda cant show new confirmations

**Comment by Dima22** [comment]
yea, same problem

**Comment by lolikuzz** [comment]
I found answer.
1.Click on account
2.Press "Selected account"
3.Login again
And all will be fine.

**Comment by Dima22** [comment]
Thank you very much!!!
