### ISSUE TITLE
Corrupted maFile

### ISSUE THREAD

**Issue by FreekyFilms** [Jessecar96/SteamDesktopAuthenticator#347]
I recovered maFiles from deleted Drive, but now they are corrupted, when i'm opening that files with notepad+++, there is corrupted words.
How can i repair file ? 
because i want to remove steam guard with recovery code, i can't, its opening steam support page, when clicking to remove steam guard.

**Comment by Jessecar96** [comment]
Your maFile is encrypted. To disable it click "Manage encryption", enter your current password, then just click accept without entering anything in the next two windows to disable it.
