### ISSUE TITLE
I already have an account with Mobile Authenticator, how do I still log into SteamDesktopAuthenticator?

### ISSUE THREAD

**Issue by steamchris** [Jessecar96/SteamDesktopAuthenticator#352]
I already have an account with Mobile Authenticator and I only need the maFile (to get the shared_secret and identity_secret) for my bot. But when I attempt to setup a new account on this program it pops up a message saying that I already have an account linked to a phone.

I dont have root on my android phone so i wouldn't be able to do it from my phone,
and I don't want to remove my current authenticator since I'll have to wait that stupid trade ban.
Thank in advance.

**Comment by hyt47** [comment]
Use Steam Guard Backup Codes to skip the trade ban
(Steam > Settings > Manage Steam Guard Account Security > Get Backup Steam Guard Codes)

**Comment by VarunSinghal3672** [comment]
How does this help? I am trying to do the same but how do Backup codes help

**Comment by hyt47** [comment]
after u get the codes, u can remove the mobile authenticator from android and re-create it to SDA without 7 days trade ban

**Comment by appvin** [comment]
"remove the mobile authenticator from android" ,did you mean that remove the mobile authenticator on the phone?

**Comment by tienloc1** [comment]
"after u get the codes, u can remove the mobile authenticator from android and re-create it to SDA without 7 days trade ban"

@hyt47 maybe you can provide more detail so I can follow it :(, I trying with one account:

+ Remove mobile authenticator on my phone
+ Remove family mode
+ Add my account in SDA

In the end, I got 15 days trade ban :(.
