### ISSUE TITLE
.mafiles is encypted

### ISSUE THREAD

**Issue by hugge01** [Jessecar96/SteamDesktopAuthenticator#354]
Im working on a roullette site, and i need to have a bot who can accept trades, 
but when i try to go in the .mafiles the code is encrypted so i cant copy any text beacuse its false. 

Is there a way for me to get the Shared secret and identety secret

sry for bad english

**Comment by pipe0482** [comment]
Decrypt the files using SDA

**Comment by AndrewRAN** [comment]
**pipe0482**, how? I didn't find decrypt func.

**Comment by TheGlenCoco** [comment]
Remove your password for SDA and open your maFile.It should be working, atleast for me did.Than you can add your password back!

**Comment by AndrewRAN** [comment]
I already have done everything.

**Comment by Jessecar96** [comment]
Click "Manage encryption", enter your current password, then just click accept without entering anything in the next two windows to disable it.

**Comment by guygardner007** [comment]
> Remove your password for SDA and open your maFile.It should be working, atleast for me did.Than you can add your password back!

How? Unable to remove passkey encryption. I keep getting this unhandled exception has occurred the input is not a valid Base-64 string error and clicking continue opens blank sda with no bot accounts visible. unable to do anything. the encryption is pissing me off i tried to remove it from manage encryption. I entered passkey at first box and clicked blank box accept next 2 times but it does not delete encryption or remove passkey and i am unable to continue and it wont work. please advise. i have win7 64x Service pack 1

**Comment by guygardner007** [comment]
> Click "Manage encryption", enter your current password, then just click accept without entering anything in the next two windows to disable it.

not working. Unable to remove passkey encryption. I keep getting this unhandled exception has occurred the input is not a valid Base-64 string error and clicking continue opens blank sda with no bot accounts visible. unable to do anything. the encryption is pissing me off i tried to remove it from manage encryption. I entered passkey at first box and clicked blank box accept next 2 times but it does not delete encryption or remove passkey and i am unable to continue and it wont work. please advise. i have win7 64x Service pack 1

how to reset to default with no encryption?
