### ISSUE TITLE
Cant Import account From android Device

### ISSUE THREAD

**Issue by niceonne** [Jessecar96/SteamDesktopAuthenticator#357]
Hello,

When I try to import from my android device it says a expection saying that directory of steamguard is not found.
If I try to creat "steamguard" folder, then exceptions says that path includes unacceptable symbols...

**Comment by Jessecar96** [comment]
Try the new release, and follow these instructions: https://github.com/Jessecar96/SteamDesktopAuthenticator/wiki/Importing-account-from-an-Android-phone

Your phone must be rooted to import any accounts.
