### ISSUE TITLE
Using a Rooted Android and ADB method doesn't work.

### ISSUE THREAD

**Issue by HermanoWayne** [Jessecar96/SteamDesktopAuthenticator#359]
So from what I was able to gather, if you have a rooted android, you can enable usb debugging and adb to import your authenticator to SDA (Steam Desktop Auth). It works fine, the Authenticator gets enabled on desktop, but the confirmations will not be updated and when you open the confirmations window it says "Ohh Noes, we couldn't retrieve this, try again later" or something like that. Apparently people have had this trouble for a while, and the only response they've gotten was "Refresh the Sessions", or "Relog into SDA", or other things, which none of them work. Refreshing doesn't work, relogging doesn't either, and reinstalling SDA will not work either. Something is broken with SDA that won't allow the program to get the confirmations, which also won't allow SDA to autoaccept confirmations if that is turned on.

**Comment by Jessecar96** [comment]
Try the new release, and follow these instructions: https://github.com/Jessecar96/SteamDesktopAuthenticator/wiki/Importing-account-from-an-Android-phone
