### ISSUE TITLE
Can't compile on linux

### ISSUE THREAD

**Issue by Drobesz** [Jessecar96/SteamDesktopAuthenticator#363]
I get an error when trying to compile SDA on linux, which is the following:
`Unable to read package from path 'cef.redist.x64.3.2454.1344.nupkg'.`
I also downloaded the master source, that also gives me an error:
`'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'.`

**Comment by Drobesz** [comment]
Does anyone has a solution to fix one of them?

**Comment by D3SCX** [comment]
I get the same warning when updating the two packages `Newtonsoft.Json` with MonoDevelop. However, the one from Steam Desktop Authenticator is the only one with the warning sign "Package is not restored"

**Comment by SomeRandomShiit** [comment]
same

**Comment by dyc3** [comment]
I made a CLI program to replace SteamDesktopAuthenticator on Linux, [steamguard-cli](https://github.com/dyc3/steamguard-cli). It can read and write the same files that SteamDesktopAuthenticator can, so you don't have to set up your mobile authenticator again. It can also handle trade confirmations.

**Comment by linkjay1** [comment]
I was having this same issue and there is a temporary fix that allows you to "build" it off of the windows release.

Go to the "releases" section here and download the zip for that contains the compiled version of this project for Windows. Then extract it to a folder somewhere on your system. Now open up Terminal and run "mono 'path/to/Steam Desktop Authenticator.exe'" and then it will run it with Mono as if it were a Windows system.

AFAIK, all features are available. I was able to import my old maFiles and get the codes successfully. If you want to have an easier way, I suggest making a Launcher and have the command set to the command above. Still works for me.

**Comment by xitero** [comment]
@linkjay1 Thanks man, it worked. Can I create a shortcut on the desktop so I do not have to open the terminal every time? I use Manjaro XFCE (Arch Linux).

Another doubt, the monodevelop is necessary or just the 'mono' is enough? Can I remove the monodevelop or do I need the two?

**Comment by linkjay1** [comment]
@xitero I tried it with and without the monodevelop package and it worked both times. I am going to safe that it's safe to uninstall monodevelop and use it with just Mono and its dependencies. Glad I could help! :)

**Comment by Rasmez** [comment]
I got the same exact problem as @D3SCX and @Drobesz, i'm trying to compile SDA in Xubuntu 16.04.3 LTS with monodevelop 5.10 (from the ubuntu repo).

The idea of using Wine doesn't work for me (SDA hangs in a minute or two, sometimes even in less), running the Güindows (A.K.A Windows) build with mono doesn't work either (sometimes the thing just hangs the SO, no apparent reason, no log, no terminal warning, etc), so i'm trying to compile SDA and then make a friking .deb file for it! (gosh, I love those things), so please, help!
