### ISSUE TITLE
SDA won't open - Windows 10  - IMPORTANT! HELP!

### ISSUE THREAD

**Issue by ScheeK4** [Jessecar96/SteamDesktopAuthenticator#364]
Hey! So I'm having troubles with this program. I cannot seem to open this program, I do have everything installed correctly, I ran it as administrator multiple times and nothing happens. I can spam click open and it says app already running, only if I spam click it. Can you help?

**Comment by Jessecar96** [comment]
Check your windows tray (next to the clock), or check task manager.

**Comment by PapiDimmi** [comment]
I have the same issue. Steam Desktop Authenticator opens in Task Manager and then immediately closes. There’s nothing in the taskbar.

**Comment by ronniPL** [comment]
I have same problem but on win7 64bit It worked for a long time but today i can't open this program . HELP

**Comment by ScheeK4** [comment]
Please close this, I've fixed it

**Comment by PapiDimmi** [comment]
@ScheeK4 You can close it yourself.

By the way, how did you fix it?

I had to reset my authenticator to fix it, since my manifest.json file was corrupt.
