### ISSUE TITLE
I get error on android 7 

### ISSUE THREAD

**Issue by Doc1337** [Jessecar96/SteamDesktopAuthenticator#367]
I cant import the account it says net framework null error or something 
Adb connects fine

**Comment by Floyd77** [comment]
Try this:

1. Use this method to access the two files needed from Android: https://github.com/JustArchi/ArchiSteamFarm/wiki/Escrow#android-phone

2. Import in WinAuth: Add, Steam, Import Android

3. Export to SDA: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/164#issuecomment-308917325
