### ISSUE TITLE
Stuck in endless loop of mobile and revocation code

### ISSUE THREAD

**Issue by EniGma249** [Jessecar96/SteamDesktopAuthenticator#369]
I've been having problem adding an account it keeps asking for mobile code then revocation code and so on, I am not entering either of these wrong so I don't know whats going on. This was happening in 1.07 and now on 1.08 too

**Comment by EniGma249** [comment]
Can someone please help? It's still happening.

**Comment by 42house** [comment]
I have this problem too, but I can't find a fix

**Comment by EniGma249** [comment]
I found the problem to from steam's side, try applying the phone number through steam and you'll get an error, fix it then it will work.
