### ISSUE TITLE
Need help with SMS step of the verification

### ISSUE THREAD

**Issue by Kaiserwill1** [Jessecar96/SteamDesktopAuthenticator#37]
how do we get the message sent?, i see no place to put a phone number, and if i have a mobile device connected, it says the remove it. sorry if this is a stupid question, but can somebody make a step by step guide to setting this up?, i just want to trade again man.

**Comment by hyt47** [comment]
## Setup Instructions:
- Download the latest zip. https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
- Extract the files somewhere very safe on your computer. If you lose the files you can lose access to your Steam account.
- Open Steam and **add a phone number**
- **Get Backup Steam Guard Codes** 
(Steam > Settings > Manage Steam Guard Account Security > Get Backup Steam Guard Codes)
- Run `Steam Desktop Authenticator.exe` and click the button to setup a new account.
- Login to Steam and follow the instructions to set it up.
- You may be asked to setup encryption, this is to make sure if someone gains access to your computer they can't steal your Steam account from this program. This is optional but heavily reccomended. (This option can be added or removed later bu the User)
- Select your account from the list to view the current login code, and click `Trade Confirmations` to see pending trade confirmations.

**Comment by Kaiserwill1** [comment]
Thank you,
