### ISSUE TITLE
Steam Community not found

### ISSUE THREAD

**Issue by AlexZampa53** [Jessecar96/SteamDesktopAuthenticator#372]
Greetings,

When I try to import the Android device into the Steam Desktop Authenticator, the program returns an error, it says: "Steam Community app not installed" (I forgot that the error is in Italian language It says "No proccess associated to the object" this is a raw translate). I have already the C++ installed and I tried to Repair.

The phone is rooted as you can see at the attached files, bootloder unlocked and custom recovery installed (for rooting).

I think there is a step that I skipped because it seems like it can't find the app installed.

Thanks for helping.

EDIT: I have already try to open SDA with admin permission.

EDIT 2: I finally copy the entire error log this is the [log](https://pastebin.com/WA8PvSk9)
![error](https://user-images.githubusercontent.com/10037387/27373406-6f6e89d2-5668-11e7-9041-548076e21380.png)
![screenshot_20170621-093538 1](https://user-images.githubusercontent.com/10037387/27373446-929dc224-5668-11e7-8ba4-a887aa1910ce.png)

**Comment by AlexZampa53** [comment]
Sorry for the comment but I browse to the folder of SDA and I found the adblog.txt when I open, I found this:

```
Checking requirements...
Checking for ADB
Checking for device
Checking for ADB
device
Checking for Steam app
/system/bin/sh: cd: /data/data/com.valvesoftware.android.steam.community: Permission denied
```

But my phone IS rooted and the program is in the lastes version 1.0.8.1. Why it got no permission...?

**Comment by AlexZampa53** [comment]
An update from my problem... Debuging in Visual Studio return this error if is useful...

![debug](https://user-images.githubusercontent.com/10037387/27432606-2a65bb78-5751-11e7-9328-90065f80c7df.png)

**Comment by sebastianbassen** [comment]
I already comitted a fix for this 4 days ago. Did you try compiling it from source?

**Comment by AlexZampa53** [comment]
I never compiling it from source... and I don't know how it works but I tried to write down in the CMD with this results

![cmd](https://user-images.githubusercontent.com/10037387/27502355-add75f16-5873-11e7-99cd-820d927e7039.png)

**Comment by sebastianbassen** [comment]
@AlexZampa53 Can you try it with this version?https://github.com/sebastianbassen/SteamDesktopAuthenticator/releases/tag/1.0.8.2

Please respond and tell me if it worked. I created a pull request for these changes but it needs to be accepted first

**Comment by AlexZampa53** [comment]
It works, the version you proposed it works, no errors message at all. We caught the error xD

**Comment by pipe0482** [comment]
Hey, could you please close the issue? Thanks!

**Comment by AlexZampa53** [comment]
Forgot to close it...
