### ISSUE TITLE
[Question] Is it possible to back up your files?

### ISSUE THREAD

**Issue by ghost** [Jessecar96/SteamDesktopAuthenticator#375]
I’ve experienced that my manifest.json got corrupted before, and I had to reset my mobile authenticator and wait another 15 days to trade or use the Steam Community Market.

I was wondering whether it’s possible to back up one’s SDA folder, namely one’s manifest.json. Will they still work if you copy them and use them at a later time?

**Comment by dyc3** [comment]
Yes

**Comment by PapiDimmi** [comment]
@dyc3 Okay, thanks. I should’ve done that to begin with.
