### ISSUE TITLE
Error in one of the accounts(other working fine) on confirmation page

### ISSUE THREAD

**Issue by surajmandalcell** [Jessecar96/SteamDesktopAuthenticator#376]
# Oh nooooooes!
## There was a problem loading the confirmations page. Please try your request again later.

**Comment by ha1331** [comment]
Just making sure, but did you try what it says in the main readme file of this repository: 

First open the "Selected Account" menu, then click "Force session refresh". If it still doesn't work after that, open the "Selected Account" menu again, then click "Login again" and login to your Steam account.

**Comment by Renari** [comment]
I have this issue as well and I can confirm that forcing a session refresh doesn't help.

**Comment by Renari** [comment]
I tried looking at this today, I don't see any obvious issues. I don't know enough about steams protocol to look any further.

**Comment by sebastianbassen** [comment]
What version are you using?

**Comment by Renari** [comment]
Was happening for me on master and 1.0.8.1.

**Comment by surajmandalcell** [comment]
force refresh does not help and just an extra point to note will be that i used import from android method if that helps in any way. Thanks

**Comment by W4RDD** [comment]
+1

**Comment by surajmandalcell** [comment]
any words on this?

**Comment by metroyanno** [comment]
Seems your device_id broken. Try to change for this: "android:abc628de" (after ":" can be all numbers and words from "a" to "e")

**Comment by surajmandalcell** [comment]
@metroyanno which file?

**Comment by Renari** [comment]
Can confirm my device_id was: ```device_id":"ERROR"```
