### ISSUE TITLE
Steam returned "General Failure" when relogging

### ISSUE THREAD

**Issue by MajesticDolphin112** [Jessecar96/SteamDesktopAuthenticator#379]
I was having an issue of the trade confirmations not loading and it told me to force session refresh or login again. Forced session refresh gives me another error telling me to login again and logging in again gives me the error "Steam returned 'General Failure'".
So what's going on? Is it a Steam issue? Is it a SDA issue? How can I fix this?

**Comment by woodsxd** [comment]
how to fix that issue? please? help i can`t play on steam
