### ISSUE TITLE
Linux and Mac Support

### ISSUE THREAD

**Issue by Aidoboy** [Jessecar96/SteamDesktopAuthenticator#38]
Steam isn't Windows-only, please don't leave us out.

**Comment by tuckismad** [comment]
Not very familiar with this project, but have you tried the mono project?

**Comment by Aidoboy** [comment]
I've had programs that've used it before, but I've never tried to implement it myself.

**Comment by Jessecar96** [comment]
I haven't tested it but as far as I know mono supports WinForms. So it should work with mono.

**Comment by Top-Cat** [comment]
You can also use https://escrow.tf if you can't get mono to work.

**Comment by Aidoboy** [comment]
Just tried it, it runs fantastically in Wine.

**Comment by Aidoboy** [comment]
I'm really sorry I didn't think of that before.

**Comment by dyc3** [comment]
For future reference, I made a CLI program to replace SteamDesktopAuthenticator on Linux, [steamguard-cli](https://github.com/dyc3/steamguard-cli). It can read and write the same files that SteamDesktopAuthenticator can, so you don't have to set up your mobile authenticator again.
