### ISSUE TITLE
 Errors in Programm.cs

### ISSUE THREAD

**Issue by NikitaNikita1** [Jessecar96/SteamDesktopAuthenticator#380]
Hi!
I cloned the project in GitHub, updated the tools in the NuGet panel, however, I can not compile the project due to errors in Programm.cs

`   [ParserState]
        public IParserState LastParserState { get; set; }

        [HelpOption]
        public string GetUsage()
        {
            return HelpText.AutoBuild(this,
              (HelpText current) => HelpText.DefaultParsingErrorsHandler(this, current));
        }`
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ParserStateAttribute' could not be found (are you missing a using directive or an assembly reference?)...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ParserState' could not be found (are you missing a using directive or an assembly reference?)...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'IParserState' could not be found (are you missing a using directive or an assembly reference?)...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'HelpOptionAttribute' could not be found (are you missing a using directive or an assembly reference?)...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'HelpOption' could not be found (are you missing a using directive or an assembly reference?)...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0411	The type arguments for method 'HelpText.AutoBuild<T>(ParserResult<T>, int)' cannot be inferred from the usage. Try specifying the type arguments explicitly...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Steam_Desktop_Authenticator.Options' to 'System.Type'	...
```

Also, in order not to create a new topic:
I downloaded the latest version of the ready SDA, tied an account to it, waited 15 days, sent a trade to it. In Steam Trade is displayed. But the program does not show it.

Can you please tell me what to do.

**Comment by sebastianbassen** [comment]
How did you clone the project? Use "git clone --recursive https://github.com/Jessecar96/SteamDesktopAuthenticator.git".
Else you won't have the submodule SteamAuth.

**Comment by NikitaNikita1** [comment]
![image](https://user-images.githubusercontent.com/11147424/27651303-85c0e8fa-5c40-11e7-9b7a-51d3d451dec8.png)

**Comment by pipe0482** [comment]
Check if `CommandLine` is correctly added in your project references.

**Comment by NikitaNikita1** [comment]
![image](https://user-images.githubusercontent.com/11147424/27686330-fcad5c92-5cda-11e7-8afd-1d945d469435.png)

**Comment by pipe0482** [comment]
I cloned it and it compiled succesfully, try to delete and re-clone the repo.

**Comment by NikitaNikita1** [comment]
Possible Solution:
After cloning the project, do not update anything in the NuGet panel

But now another problem
Https://github.com/geel9/SteamAuth/issues/69
