### ISSUE TITLE
Checking new confirmation has broken

### ISSUE THREAD

**Issue by pohuiusemail4741** [Jessecar96/SteamDesktopAuthenticator#381]
I have a lot of account of Steam. I made a trade then it needs to confirm. I have 11 accounts using SDA but when I made it and set program to periodically check new confirmation for ALL account. It cant check or show any popup I also mark Auto-confirm market transactions and Auto-confirm trades. Maybe this is the way to solve the problem

1. Set the program check delay between accounts if have a lot of accounts when tick ""Check all accounts for confirmations"

2.Set new range between checking for confirmation to higher than 5 seconds. Because of when it checking and confirming many accounts the program will be stuck for a while and maybe fail to refrash the sessio.

Thanks

**Comment by pohuiusemail4741** [comment]
3.When Auto-confirm is tick, Please notices the user what is auto-confirm Market Transactions or Trades
like this :
![auto](https://user-images.githubusercontent.com/10082544/27602570-7c9ac514-5b9d-11e7-8e42-b5b429963337.png)

**Comment by yiz46** [comment]
its working to you now? i have the same probleam

**Comment by pohuiusemail4741** [comment]
yeah, but i manually click on accept to confirm it, so it uncomfortable to did those

**Comment by yiz46** [comment]
thanks for the fast answer!
have some way to do it?

2017-09-28 14:27 GMT+03:00 pohuiusemail4741 <notifications@github.com>:

**Comment by pohuiusemail4741** [comment]
I use Steam Desktop Authenticator 47

**Comment by pohuiusemail4741** [comment]
I more option to use.

**Comment by pohuiusemail4741** [comment]
But this is the original (SDA) focus on Steam guard code on computer. That (SDA47)is a modded project from this. You also use Ice for steam (search on Google play store) it can import *.maFile to use it

**Comment by yiz46** [comment]
but SDA47 its accept automatics trades for my 2 users?

2017-10-02 16:45 GMT+03:00 pohuiusemail4741 <notifications@github.com>:
