### ISSUE TITLE
Help ... No auto confirm trades

### ISSUE THREAD

**Issue by tretvitaliy** [Jessecar96/SteamDesktopAuthenticator#384]
My SteamDesktopAuthenticator ... Broke
No auto confirm trades https://prnt.sc/fpapzp
Settings http://prntscr.com/fpawkg
Updated http://prntscr.com/fpawxb

Короче говоря ... мой SDA перестал подтверждать выставленные предметы на торговую площадку!
4 дня как ... до этого пол года работал отлично ... Пробовал обновить но ситуация не изменилась ... 

Прошу помощи, совета
Ибо перепривязка даст 15 дней холду  на торговой площадке! Как то хочется этого избежать!

**Comment by MurkBRA** [comment]
Go back to 1.0.7.2 the new version have this bug.
