### ISSUE TITLE
Freezes on ADB

### ISSUE THREAD

**Issue by derpness334** [Jessecar96/SteamDesktopAuthenticator#385]
I'm trying to import my auth from Android but when I select "Import from Android device", it will check for ADB and freeze.  (Yes my device is connected and I did download SDK Platform Tools and drop the files)

**Comment by sebastianbassen** [comment]
It's a known bug and I fixed it already. You either have to wait for JesseCar to accept my merge request and publish a new version or compile it from my fork https://github.com/sebastianbassen/SteamDesktopAuthenticator

Please respond if you got it running with my fork :)

**Comment by derpness334** [comment]
Still freezes

**Comment by sebastianbassen** [comment]
Where does it freeze? Does it just say "Checking for ADB" and nothing happens?

**Comment by derpness334** [comment]
Yep

**Comment by sebastianbassen** [comment]
Did you enable Devsettings and ADB debugging on your phone?

**Comment by derpness334** [comment]
Yes

**Comment by sebastianbassen** [comment]
Do you have Discord or something? If yes add me bababababa#7031 so we can narrow down the problem, its easier that way I think
