### ISSUE TITLE
Connecting Steam Guard to the account via the command line.

### ISSUE THREAD

**Issue by FoxVodniki** [Jessecar96/SteamDesktopAuthenticator#386]
There is a need to connect new accounts to the SDA autonomously. How can I do that?
Maybe there is an API, or via the command line.

**Comment by pipe0482** [comment]
Do you mean setting up new accounts?

**Comment by FoxVodniki** [comment]
Yes, I have about 2000 accounts that want to connect to SDA. Preferably not manually. 30.06.2017, 22:46, "Pipe" <notifications@github.com>:Do you mean setting up new accounts?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by pipe0482** [comment]
I think it would be difficult to completely automate it because you need to enter captchas, email codes, etc.

**Comment by FoxVodniki** [comment]
And that's no problem :). The problem with the appeal to the program.

**Comment by dyc3** [comment]
I have created a program for Linux users to do this. https://github.com/dyc3/steamguard-cli
