### ISSUE TITLE
Mono Crash

### ISSUE THREAD

**Issue by MarielleJewish** [Jessecar96/SteamDesktopAuthenticator#387]
When i open the .SLN in Monodevelop (on ubuntu) mono crash, any fix?

**Comment by pipe0482** [comment]
What version of MonoDevelop and Ubuntu are you using?

**Comment by dyc3** [comment]
FYI, I have created a CLI program to replace SDA on Linux: https://github.com/dyc3/steamguard-cli

**Comment by linkjay1** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/363#issuecomment-313841381

Try "building" your own version with Mono and Windows on Linux.
