### ISSUE TITLE
Maximize button or resizable window sizes?

### ISSUE THREAD

**Issue by Thugnificent1** [Jessecar96/SteamDesktopAuthenticator#39]
Hello, it's quite annoying to see in the small window. This program can benefit from having the maximize button and resizeable window size. Also bigger fonts should be added imo. Speaking of which, a search function or filter for the added accounts wouldn't hurt either.

Thanks!

**Comment by Thugnificent1** [comment]
Speaking of which, a search function or filter for the added accounts wouldn't hurt either.

**Comment by Jessecar96** [comment]
Form resizing has been added.

**Comment by Thugnificent1** [comment]
Cheers man, it's now perfect!
