### ISSUE TITLE
SDA sometimes makes the manifest.json file corrupt

### ISSUE THREAD

**Issue by ghost** [Jessecar96/SteamDesktopAuthenticator#395]
Sometimes, the manifest.json file becomes corrupt, and you can’t log in to SDA. You either have to reset SDA and your mobile authenticator, forcing you to wait 15 days before being able to trade or use the Steam Community Market, or you have to restore from an SDA folder backup (or a backup of the manifest.json file).

This has happened to me three times.

**Comment by MedoRockerSix** [comment]
same here
