### ISSUE TITLE
Encyrption Passkey Issue

### ISSUE THREAD

**Issue by ItsHipsterNoah** [Jessecar96/SteamDesktopAuthenticator#4]
I went through the setup of the Desktop Authenticator, but I didn't receive my passkey.

**Comment by geel9** [comment]
You are supposed to create your own passkey. Did it never prompt you for an encryption passkey?

**Comment by ItsHipsterNoah** [comment]
Oh, my bad, I thought it was automatically generated. Like the other code. I'll create one. Thanks for clearing that up!

**Comment by ItsHipsterNoah** [comment]
It turns out I used my other code as the encryption key by accident! Lol
