### ISSUE TITLE
I can't log in to my SDA account

### ISSUE THREAD

**Issue by botmirage** [Jessecar96/SteamDesktopAuthenticator#400]
Hello! I'm having trouble logging in to my SDA account. See, I just wiped my hard drive, but I didn't deactivate my account. I downloaded SDA again and tried to log in, but there's no way for me to do so and if I click "I want to import my account," the folder my authenticator account was originally on is gone. If I say "This is my first time," it says my steam account has already been registered with an account. Help?

**Comment by pipe0482** [comment]
Use the revocation code and set it up again.

**Comment by botmirage** [comment]
I lost that. Am I screwed?

**Comment by pipe0482** [comment]
I think the only option left is to contact steam support.. so yeah :/

**Comment by linkjay1** [comment]
If you do not have the maFiles folder or your secret code, you're SOL.

You need to contact Steam support now.

**Comment by botmirage** [comment]
Right, I disabled the authenticator. Can I make a new SDA account if I activate Steam auth again, or will the same problem be present?

**Comment by pipe0482** [comment]
Yeah, just link the account again through SDA.

**Comment by botmirage** [comment]
Cool, thanks!
