### ISSUE TITLE
Error Logging in: Steam returned "GeneralFailure" on version 1.0.8.1

### ISSUE THREAD

**Issue by JustCallMeAlec** [Jessecar96/SteamDesktopAuthenticator#401]
Unable to confirm anything. Have tried using the "Force session refresh" option, which tells me to use the Login again option which returns "GeneralFailure". Help?

**Comment by Alpacassss** [comment]
I have been having the same problem

**Comment by JustCallMeAlec** [comment]
I ended up removing the authenticator and adding it again, rip 15 days of
no market or trading. Thanks Jesse
