### ISSUE TITLE
Confirm all

### ISSUE THREAD

**Issue by PuppyLover101** [Jessecar96/SteamDesktopAuthenticator#403]
Is there a way to confirm all? It really is a hassle when selling 100+ items :( Thanks~!

**Comment by sebastianbassenblg** [comment]
You can activate "Auto-confirm market transactions" in the options menu. Be aware that if you bulk sell over 50 items the app will lag for up to a minute, just let the Program do it's job, it will be done after some time. I use it all the time to bulk sell my trading cards :)

**Comment by sebastianbassen** [comment]
You can activate "Auto-confirm market transactions" in the options menu. Be aware that if you bulk sell over 50 items the app will lag for up to a minute, just let the Program do it's job, it will be done after some time. I use it all the time to bulk sell my trading cards :)

**Comment by PuppyLover101** [comment]
Thanks a lot.

**Comment by sebastianbassen** [comment]
@PuppyLover101 can you please close this issue since? :)
