### ISSUE TITLE
Steam Desktop Authenticator crashes

### ISSUE THREAD

**Issue by matiasvll** [Jessecar96/SteamDesktopAuthenticator#406]
When i open SDA this is crash came out

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Steam Desktop Authenticator.exe
  Problem Signature 02:	1.0.8.1
  Problem Signature 03:	594589b3
  Problem Signature 04:	Steam Desktop Authenticator
  Problem Signature 05:	1.0.8.1
  Problem Signature 06:	594589b3
  Problem Signature 07:	eb
  Problem Signature 08:	31
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3082
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

any solution? i cant login on steam...

**Comment by pipe0482** [comment]
Is that the full crash message?
