### ISSUE TITLE
auto accept trade

### ISSUE THREAD

**Issue by yiz46** [Jessecar96/SteamDesktopAuthenticator#407]
i have 3 users on this program and its just accept from 1 user,
i need to change the user if i want its auto trade in other user.
how i do auto confirmtion in all users?

**Comment by yiz46** [comment]
how my 2 users in "steamdesktopauthenicator" will accept trades automatic?

**Comment by yiz46** [comment]
please someone?

**Comment by xjh1120** [comment]
i  have the same problem .   it  just accept  for  one  which   is selected .
