### ISSUE TITLE
Question : Porting auth files from steamBot.

### ISSUE THREAD

**Issue by DavidBarishev** [Jessecar96/SteamDesktopAuthenticator#41]
Im using steambot , and i have linked up a mobile auth from there , and can generate all 2Fa codes , and i have a question : is it possible to port the file from steam bot , to here without re-linking ?

It may be not possible , to have two links in the same time , but is there a possible workaround as we have the auth file ?

**Comment by Jessecar96** [comment]
The new version (when I release it) will contain the ability to import files. Go to File -> Import maFile and find the file of the account you want to import.

**Comment by DavidBarishev** [comment]
Sweet , thank you
