### ISSUE TITLE
VAC Ban when using with a VACed account?

### ISSUE THREAD

**Issue by andrew2023019** [Jessecar96/SteamDesktopAuthenticator#414]
My main account got VACed and I had a second account that I already had money in, both that using SDA. I was wondering if my second account would get VACed, or if that would only happen if I used the same number that I used before I used SDA. 
I really want to know because I am planning on buying my games again on my second account, and I don't want to get fked and loose it all again.

**Comment by pipe0482** [comment]
If you use a different phone number you shouldn't get banned.

**Comment by andrew2023019** [comment]
k thanks, ill look up which number I used.
