### ISSUE TITLE
I want to know how it works,the 

### ISSUE THREAD

**Issue by SakuraLove** [Jessecar96/SteamDesktopAuthenticator#416]
I am interested that how the SteamDesktopAuthenticator generates a verification code.
Cloud you show the code where to generate a verification code?
I mean that I know the way it works but I want to know the specific algorithm

**Comment by dyc3** [comment]
https://github.com/geel9/SteamAuth/blob/48c29f7cda315234639d633f98782754dc8a5b91/SteamAuth/SteamGuardAccount.cs#L85

**Comment by SakuraLove** [comment]
Thanks very much.That is very helpful

**Comment by SakuraLove** [comment]
By the way is there origin steam document which is about the authenticator?

**Comment by dyc3** [comment]
As far as i know, there is no Steam documentation for the mobile authenticator.
