### ISSUE TITLE
Infected by Trojan ?

### ISSUE THREAD

**Issue by Shirotaku** [Jessecar96/SteamDesktopAuthenticator#417]
Hello,

I've not used this program for a while but today my anti-virus (Bitdefender Total Security) has warned me that Steam Desktop Authenticator.exe is infected with MSILPerseus.

Why?

**Comment by linkjay1** [comment]
Well, I highly doubt the app actually contains a virus. It's all open source, look for yourself. If you don't trust the release download, download the source, read through it, then build it yourself.

I can only think that your virus is dropping a false positive (which is not uncommon for "anti-viruses"), or maybe another app "infected" SDA with some sort of Trojan. The first one is most likely.

**Comment by Shirotaku** [comment]
That's why I'm very confused. As soon as I download the compiled version, the anti-virus starts desinfecting.

Even if I try compiling it my self, the anti-virus is deleting the file directly.

**Comment by linkjay1** [comment]
I recommend you download the regular release and add the file to the whitelist or whatever.
