### ISSUE TITLE
Stuck in loop between entering code sent to mobile and recovery code.

### ISSUE THREAD

**Issue by 5peep** [Jessecar96/SteamDesktopAuthenticator#419]
When it asks for the code sent to my phone number I enter the value it has sent me. It the asks for the recovery code. It will then ask for the code sent to my phone once again, then for the recovery code once again. 

It is stuck in this loop when i try to add my account.

I have noticed that I can input any value I like into the field for the code what was sent to my mobile and it will just ask for the recovery code and once again ask for the code sent to my mobile. 

Anyone have a solution?

EDIT: I'm using version 1.0.8.1 on Win10

**Comment by Emgima** [comment]
same
someone know how fix it?

**Comment by DizzaRust** [comment]
Im also getting this

**Comment by Hotzx** [comment]
same

**Comment by lukeramsden** [comment]
Still getting this. Really frustrating.
