### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by surajmandalcell** [Jessecar96/SteamDesktopAuthenticator#420]
I havent seen any recent merges and my problem hasent been assisted with so is this project even alive?

**Comment by pipe0482** [comment]
Not really, I think the author has kind of abandoned it. I tried contacting
them to no avail.

**Comment by pipe0482** [comment]
Not really, I think the author has kind of abandoned it. I tried contacting
them to no avail. Also, kind of off-topic, I had to create a second account because I can't create issues, PRs or basically do anything with the repo on my main, I think that they may have blocked it.

**Comment by surajmandalcell** [comment]
sad, it was a good project tho
