### ISSUE TITLE
Error adding your phone number. Steam returned "GeneralFailure"

### ISSUE THREAD

**Issue by sohiebdz** [Jessecar96/SteamDesktopAuthenticator#421]
![](https://image.prntscr.com/image/JUah_ADOSlCGgkxHbUle8A.png)
when i enter phone give me this error

**Comment by memeboy194** [comment]
I have the same problem, but it shows up when I put in the code from the email.

**Comment by 21cret** [comment]
i solve this problem i tried the ff:
1. Remove the steam guard ( set it off )
2. Remove Family View 

no worries anyway you can change pass + enable family view after that

**Comment by linkjayy** [comment]
Keep in mind, if you try @21cret 's solution, you will have a 15 day trade escrow thing until you've had Steam mobile authentication on for at least 10 days I believe.
