### ISSUE TITLE
"Checking for Steam app" 

### ISSUE THREAD

**Issue by venture0x10** [Jessecar96/SteamDesktopAuthenticator#422]
It's checking for the steam app for ages, seems like it isn't doing anything
Does the device need to be rooted?

**Comment by venture0x10** [comment]
![y6vnd07](https://user-images.githubusercontent.com/32658313/31364028-9feebf5e-ad62-11e7-86e6-9d3ce68ff199.png)

**Comment by sebastianbassen** [comment]
This is a known bug with newer android version. JesseCar doesn't seem to work on this project anymore. You can try out my fix at https://github.com/sebastianbassen/SteamDesktopAuthenticator/releases or just compile it yourself from my repo. I made a PR 2 months ago and JesseCar didn't respond.

**Comment by venture0x10** [comment]
still not working. it's always giving me errors when it checks for the adb version now

**Comment by sebastianbassen** [comment]
@venture0x10 Can you type in commandline: adb version and tell me what adb version you are using?

**Comment by venture0x10** [comment]
@sebastianbassen it says 1.0.39
![qt9mqtp](https://user-images.githubusercontent.com/32658313/31384514-a2c921da-adbf-11e7-9002-d1a8502c034f.png)

**Comment by sebastianbassen** [comment]
@venture0x10 Strange. I am using the same version and especially fixed it for this version. Do you have multiple devices connected? Whats the output of adb devices?

**Comment by venture0x10** [comment]
@sebastianbassen i only have 1 device connected, do you have steam or something so we could talk there?

**Comment by sebastianbassen** [comment]
sure feel free to add me: http://steamcommunity.com/profiles/76561198054055682

**Comment by venture0x10** [comment]
@sebastianbassen done

**Comment by 872517414** [comment]
@sebastianbassen Thanks you,I am OK.

**Comment by mactepp** [comment]
I've managed to get it working. Try to run adb with the "root" flag. On powershell it should be something like ".\adb.exe root". Then just do the process on the app.
