### ISSUE TITLE
Cant open SDA

### ISSUE THREAD

**Issue by UselessNukes** [Jessecar96/SteamDesktopAuthenticator#426]
Hi, this has been going on for like 3 days and its really annoying. I try opening SDA and nothing happens. I check my task manager to see if it's already open but it's not there. This is really annoying me please could you help me?

https://gyazo.com/761ed4c87c3a9d6ee531ef568a65463e?token=97c55337dc0fb66292ed5e39c92b10e8

If you need any more screenshots please ask thanks

**Comment by Desidiosus** [comment]
Have you updated to Win 10 Fall Creators update? I updated my laptop to it and was no longer able to open SDA. It worked on the laptop previously so the update broke something. I've had issues with other applications on the new Windows 10 update as well.
