### ISSUE TITLE
MonoDevelop Crash

### ISSUE THREAD

**Issue by cheddar-cheeze** [Jessecar96/SteamDesktopAuthenticator#427]
I open Mono Develop And Open the sln file and "A fatal error has occured" then mono devlop closes, any thoughts?
## System Information

**Operating System:Arch Linux
**MonoDevelop Version**:6.2.0.1778-2

**Comment by linkjayy** [comment]
I can't ever get Monodevelop to work personally. I would try my Linux method. I haven't tested it on Arch yet, only debian-based Operating Systems, but it really should work for all distros.

https://github.com/Jessecar96/SteamDesktopAuthenticator/pull/408/commits/71f147207334c7420dbfadeb98c2e9c4cef08b9e

**Comment by loathingKernel** [comment]
It has nothing to do with SteamDesktopAuthenticator. It is a the MonoDevelop git plugin that causes the crash. Start MonoDevelop and disable it before importing the solution file. Or you can build it from the command line using nuget and xbuild.
