### ISSUE TITLE
Version 0.3.0 did not work in Windows 7 64bit

### ISSUE THREAD

**Issue by Niceman35** [Jessecar96/SteamDesktopAuthenticator#43]
Got exception can't load CefSharp.Core.dll but file in the same folder.
Works good in Windows 8

System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "CefSharp.Core.dll" либо одну из их зависимостей. Не найден указанный модуль.
Имя файла: 'CefSharp.Core.dll'
   в Steam_Desktop_Authenticator.ConfirmationFormWeb..ctor(SteamGuardAccount steamAccount)
   в Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Thugnificent1** [comment]
I have Windows 7 Ultimate, 64bit

working fine for me.

**Comment by Jessecar96** [comment]
It says right there "FileNotFoundException" and "CefSharp.Core.dll" meaning it's missing "CefSharp.Core.dll"

Make sure to extract all the files when you download the zip of the program. You missed CefSharp.Core.dll

**Comment by Niceman35** [comment]
I have this file in some folder. Looks like it can't load it or don't see this file. Possible, is needed some additional programs like .Net or VCC runtime?
