### ISSUE TITLE
website 

### ISSUE THREAD

**Issue by danil187** [Jessecar96/SteamDesktopAuthenticator#442]
is this your official website or what [removed]

**Comment by sebastianbassenblg** [comment]
No this looks like a scam. Never download any SDA version which doesn't come from the releases tab of github. This website will likely steal your skins!

**Comment by sebastianbassen** [comment]
No this looks like a scam. Never download any SDA version which doesn't come from the releases tab of github. This website will likely steal your skins!

**Comment by Ne3tCode** [comment]
I downloaded and decompiled SDA from this site. This is modified version of SDA v1.0.8.1, it can steal your maFiles and steam password. Be careful.

**Comment by danil187** [comment]
yeah cause i lost all my items thanks

**Comment by danil187** [comment]
i knew it

**Comment by Jessecar96** [comment]
Thanks for bringing this to my attention. I've added a warning to the main readme about fake versions.

**Comment by pipe0482** [comment]
![Decompiled](https://i.imgur.com/2wKOHR9.png)

It seems like he's uploading your username and password along with other data to a site called steamdesktop.com. A [quick whois](https://www.whois.com/whois/steamdesktop.com) reveals that he is a "russisan hacker" and has been doing this since 2017-07-22.

**Comment by danil187** [comment]
Thanks for telling i knew it but now if i remove the steam gaurd then put it again on the original sda the mafile and shared secret will change ?

**Comment by danil187** [comment]
I mean is it safe to put the accounts again on the original sda on the same pc ?

**Comment by pipe0482** [comment]
Probably yes, but I'd scan your pc with an antivirus just in case.
