### ISSUE TITLE
Can't run on 32-bit system.

### ISSUE THREAD

**Issue by Niceman35** [Jessecar96/SteamDesktopAuthenticator#45]
Please compile 32bit version.

**Comment by hyt47** [comment]
u can use this one "Version v0.2.3 Mode v1a"
https://github.com/hyt47/SteamDesktopAuthenticator-for-XP-x86/releases

i'm working on Version v0.3.0 Mode v1

**Comment by hyt47** [comment]
v0.3.0 not working Windows 7 32 bits (problem CefSharp.Core.dll)
