### ISSUE TITLE
Trade confirmations doesn't work when family view is enabled

### ISSUE THREAD

**Issue by puuska** [Jessecar96/SteamDesktopAuthenticator#468]
When you turn on family view and try to confirm a trade, trade confirmations webview will ask for code, refresh and again ask for code. It asks for code everytime and you can't get into trade confirmations.

**Comment by tienloc1** [comment]
Unless you have family code, you can't pass and disable family mode when you don't have that code.

**Comment by puuska** [comment]
I have family code, but SDA app don't allow me to pass the family view login. When I enter the code and click sumbit it is taking me to same family view code enter site although I entered valid code

**Comment by tienloc1** [comment]
Then I guest you will need disable family mode before you do it, I have few account with family mode enable, not try it now.

**Comment by puuska** [comment]
Currently I am accepting trades via ArchiSteamFarm embedded 2FA support, but it is more difficult than clicking one button in SDA app.

**Comment by tienloc1** [comment]
As my knowledge, we will need disable family mode before we can control the inventory and make new trade offer. So you don't use steam client?

**Comment by puuska** [comment]
I use steam client but when I want to confirm trade/market transaction I am writing to my bot that uses ArchiSteamFarm with imported my main account maFile that confirms it

**Comment by tienloc1** [comment]
Hey, do you have a way to make it work now? I have my account with family enable, when I disable family mode (just disable by enter sercet code) and create an offer, then I can confirm trade with SDA? Or I will need move family mode complete?

**Comment by puuska** [comment]
i disabled family view completly, waiting for fix
