### ISSUE TITLE
A bug when clicking trade confirmations

### ISSUE THREAD

**Issue by misu2001** [Jessecar96/SteamDesktopAuthenticator#47]
The report details are here as listed:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
File name: 'CefSharp.Core.dll'
   at Steam_Desktop_Authenticator.ConfirmationFormWeb..ctor(SteamGuardAccount steamAccount)
   at Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Steam Desktop Authenticator
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0
    CodeBase: file:///C:/Users/Mihai/Desktop/Fusion364/Steam%20Desktop%20Authenticator.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/Mihai/Desktop/Fusion364/Newtonsoft.Json.DLL
----------------------------------------
SteamAuth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mihai/Desktop/Fusion364/SteamAuth.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Jessecar96** [comment]
Try installing Visual C++ 2012 https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by hyt47** [comment]
the same

**Comment by Ps1d3r** [comment]
I have this exact same problem with the latest version.
Installed VC++ 2012, didn't solve it
Copied the maFiles folder to a fresh new version, also didn't work.

************** Texto da excepção **************
System.IO.FileNotFoundException: Não foi possível carregar o ficheiro ou assemblagem 'CefSharp.Core.dll' ou uma das respectivas dependências. Impossível localizar o módulo especificado.
Nome de ficheiro: 'CefSharp.Core.dll'
   em Steam_Desktop_Authenticator.ConfirmationFormWeb..ctor(SteamGuardAccount steamAccount)
   em Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
   em System.Windows.Forms.Control.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ButtonBase.WndProc(Message& m)
   em System.Windows.Forms.Button.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Assemblagens carregadas **************
mscorlib
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Steam Desktop Authenticator
    Versão da assemblagem: 0.3.0.0
    Versão Win32: 0.3.0
    CodeBase: file:///D:/THE%20WORLD%20WIDE%20WEB/FIREFOX/Steam.Desktop.Authenticator.v0.3.0/Steam%20Desktop%20Authenticator.exe
----------------------------------------
System
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Versão da assemblagem: 7.0.0.0
    Versão Win32: 7.0.1.18622
    CodeBase: file:///D:/THE%20WORLD%20WIDE%20WEB/FIREFOX/Steam.Desktop.Authenticator.v0.3.0/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SteamAuth
    Versão da assemblagem: 1.0.0.0
    Versão Win32: 1.0.0.0
    CodeBase: file:///D:/THE%20WORLD%20WIDE%20WEB/FIREFOX/Steam.Desktop.Authenticator.v0.3.0/SteamAuth.DLL
----------------------------------------
Microsoft.CSharp
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_pt_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versão da assemblagem: 0.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
mscorlib.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versão da assemblagem: 4.0.0.0
    Versão Win32: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuração JIT **************
Para activar a depuração just-in-time (JIT), o ficheiro .config para esta
aplicação ou computador (machine.config) tem de ter o
valor jitDebugging definido na secção system.windows.forms.
A aplicação também tem de ser compilada com a depuração
activada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by Jessecar96** [comment]
Make sure you install Visual C++ Redistributable that I linked above. That will cause this error.
I'm not sure if you need to install the x86 or x64 version but try both.

**Comment by hyt47** [comment]
I intalled Visual C++ Redistributable x86 and no luck

**Comment by Ps1d3r** [comment]
I installed both x86 and x64 (running x64 OS) with no luck. I also have 2010 version installed, could this conflict? Or maybe i need to restart my PC for it to work?
I have .NET 4.5.2.

Thanks in advance

**Comment by misu2001** [comment]
Hi. I already have that version installed, so, at the setup prompt I pressed repair.
The vcredist_arm.exe file did nothing.
I will do a restart, then I will see the state. Now, it is NOT working. I believe that after the restart, the things will be the same. Please fix this bug, I have a trade from scrap.tf with some items and I cannot do something to fast forward the trade. :(

**Comment by PFCKrutonium** [comment]
@Jessecar96 They are all missing files from the zip - is it possible WIndows is being an ass and they need to manually unblock the dll?

**Comment by misu2001** [comment]
Nope, same thing. Just fix this bug. I have to do a gift to someone special...

**Comment by Ps1d3r** [comment]
@misu2001  how much did you pay for this version of the app?

**Comment by misu2001** [comment]
@Ps1d3r Nothing.

**Comment by misu2001** [comment]
@Ps1d3r Try and make a virtual machine (if your PC is strong enough) and install a windows 7 free copy somewhere from the internet. make sure that the RAM used is atleast 4GB for a smooth run. Then get the app, steam and other crap and then tell us the results.





I DO NOT PROMOTE PIRACY!!!!

**Comment by Ps1d3r** [comment]
@misu2001 exactly xD Jesse is helping free of charge, so i would advice to wait patiently.

Why would i install a VM? I don't see how that can solve this problem...

**Comment by misu2001** [comment]
You can see if it is an OS problem.
Or, if it is the files' or the code's problem, @Jessecar96 should check it out and fix it. I am on a laptop not even being able to run everything with full quality settings but it is good for me because I love Candy Crush.





Amen.

**Comment by misu2001** [comment]
@Jessecar96 Can you check all the files and integrity for multiple windows versions (if you have a PC capable of installing fast VMs with all OS versions) and see if it is an error in your files?

**Comment by hyt47** [comment]
@misu2001 what windows version do u have?

**Comment by misu2001** [comment]
Windows 10 Home edition (I had to download some "regedit" files so I can manage everything I do and don't want.

**Comment by hyt47** [comment]
if your windows is 32 bits try this one https://github.com/hyt47/SteamDesktopAuthenticator-Modded

**Comment by Jessecar96** [comment]
I use Windows 10 64bit, but I specifically compiled the program for x86. The only 32 bit VM I have is windows XP and it doesn't work on that.

**Comment by misu2001** [comment]
Can you make a VM that has Win10 on 64BITS?
plz. :cookie:

**Comment by Jessecar96** [comment]
I'll look into why it's not working on 32bit, you can discuss that bug here: #45 
This bug report is about CefSharp not working for some people.

If you're seeing the error "Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies." just tell me what OS you're running and what architecture (32 or 64 bit).

**Comment by misu2001** [comment]
@Jessecar96 You meant 64-bit?

**Comment by hyt47** [comment]
@misu2001 check how many bits your OS has, tutorials about how to find out are on google

**Comment by Ps1d3r** [comment]
@Jessecar96 I have Win7 Home Premium x64 (without SP1) and i posted above the VC++ versions installed.
Should i make my own thread about this or just wait here? I have already posted here my error message, since it's the same as misu2001.

**Comment by misu2001** [comment]
Mate, I am not THAT stupid not to know whether I have 32 or 64 bit

**Comment by hyt47** [comment]
I did not want to offend you! I just wanted to be sure about your problem!

**Comment by hyt47** [comment]
To do a test I Instaled Windows 7 x64 on a virtual machine
Installed:
- .NET Framework 4.5.2 NDP452-KB2901954-Web.exe > Test app > Failed
- Visual C++ Redistributable 2012 vcredist_x64.exe > Test app > Failed
- Visual C++ Redistributable 2012 vcredist_x86.exe > Test app > Failed
- .NET Framework 4.5.2 Targeting Pack NDP452-KB2901954-Web.exe > Test app > Failed

Is the same Windows as on my main pc but in Virtual machine I get that error
`Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies`

**Comment by Ps1d3r** [comment]
@hyt47 wtf? But on your pc it works normally?

**Comment by hyt47** [comment]
next I installed:
- Visual C++ Redistributable 2013 vcredist_x64.exe > Test app > Failed
- Visual C++ Redistributable 2013 vcredist_x86.exe > Test app > Works OK ^_^
Works OK ^_^

now i will duplicate my vlean Wind 7x64 and run the test again installing only
-.NET Framework 4.5.2 NDP452-KB2901954-Web.exe
- Visual C++ Redistributable 2013 vcredist_x86.exe

to see if it works with these 2 or if something else is needed

**Comment by alexwins333** [comment]
i have windows 8.1 x64 and I get the same error

**Comment by alexwins333** [comment]
i have windows 8.1 x64 and when i installed Visual C++ Redistributable 2013 vcredist_x86.exe it worked fine but before i had the same bug

**Comment by hyt47** [comment]
**FIX for Windows x64** https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/52

**Comment by Jessecar96** [comment]
Can anyone else confirm install VC++ 2013 and .NET 4.5.2 works? I added the instructions to the main readme page.

**Comment by Ps1d3r** [comment]
@Jessecar96 i just installed VC++ 2013 and it works
yey!

**Comment by Top-Cat** [comment]
Confirmed by Blah too

**Comment by misu2001** [comment]
So, it was 2013 version, NOT 2012. I will post a link here for those that cannot find the fix to the same problem. 
https://www.microsoft.com/en-us/download/details.aspx?id=40784
This issue is now closed.

**Comment by misu2001** [comment]
Issue Reopened. Same issue here:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
File name: 'CefSharp.Core.dll'
   at Steam_Desktop_Authenticator.ConfirmationFormWeb..ctor(SteamGuardAccount steamAccount)
   at Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Steam Desktop Authenticator
    Assembly Version: 0.3.0.0
    Win32 Version: 0.3.0
    CodeBase: file:///C:/Users/Mihai/Desktop/Fusion364/Steam%20Desktop%20Authenticator.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/Mihai/Desktop/Fusion364/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SteamAuth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Mihai/Desktop/Fusion364/SteamAuth.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by misu2001** [comment]
@Jessecar96 can you reopen this issue?

**Comment by misu2001** [comment]
@jessecar96 can you reopen this? my issue is not solved yet...
