### ISSUE TITLE
I currently have my Steam app on an emulator.

### ISSUE THREAD

**Issue by bolpeensamp** [Jessecar96/SteamDesktopAuthenticator#470]
I'm currently using Nox to emulate my steam guard on my computer, but its getting heavy for my computer lately. Is there a way to import my account from the emulator to SDA?

**Comment by dyc3** [comment]
It's certainly possible. It might be pretty involved though. What emulator are you using?

**Comment by puuska** [comment]
He/She wrote: NOX

**Comment by dyc3** [comment]
My bad. If you can figure out how to extract files from Nox, you can copy over the files and put them in the `.maFile` format manually. Try looking for a way to "connect" the emulated phone to your computer so it pretends to be connected via USB.

This might be useful:
[https://github.com/pipe0482/SteamDesktopAuthenticator/blob/9d2f607c1baeafa5cf37da2b2ed12d885e70f853/NOROOT.md](https://github.com/pipe0482/SteamDesktopAuthenticator/blob/9d2f607c1baeafa5cf37da2b2ed12d885e70f853/NOROOT.md)
