### ISSUE TITLE
Error Message Trade Confirmations

### ISSUE THREAD

**Issue by godofskins** [Jessecar96/SteamDesktopAuthenticator#476]
Hi I am getting an error message when trying to view trade confirmations: "Error
Sorry!
An error was encountered while processing your request:

You've made too many requests recently. Please wait and try your request again later.

Here's a link to the Steam Community home page."

Does anyone know how to fix this? Is this caused because I just added authenticator or is it an account setting within Steam? Thanks!

![error](https://user-images.githubusercontent.com/36610557/36359945-a9dc0de4-14d4-11e8-9e14-3450d8896ffa.PNG)

**Comment by puuska** [comment]
disable auto checking
