### ISSUE TITLE
"Failed to check for updates" after Feb. 22 update on GitHub

### ISSUE THREAD

**Issue by JBoughter** [Jessecar96/SteamDesktopAuthenticator#478]
https://githubengineering.com/crypto-removal-notice/

SDA can't check for updates. I mean, not like there's been one, but still.

**Comment by Tory73** [comment]
Yes, it's annoying to see it every time when you start sda and need to click on it.

**Comment by JBoughter** [comment]
I guess that's truly the issue here. ^

/s

**Comment by Ps1d3r** [comment]
Same here

**Comment by CubE135** [comment]
Same here

**Comment by SeerZoR** [comment]
Same here

**Comment by Zarat99** [comment]
Same here

**Comment by zigagrcar** [comment]
Simple solution is to target 4.6 .NET framework in project properties and rebuild, as the newer version defaults to TLS 1.2, you can check my forked project.

**Comment by thunderpants** [comment]
i presume  zigagrcar 's version is not up-to-date now as latest version is 1.8.2

**Comment by fizzarin** [comment]
Same here - v1.0.8.2

**Comment by Jessecar96** [comment]
This will be fixed in the next version.
