### ISSUE TITLE
Login form closes when Steam returns "GeneralFailure"

### ISSUE THREAD

**Issue by JayTehRainbowNinja** [Jessecar96/SteamDesktopAuthenticator#48]
got it all fixed and it was cool for a while, then the update came out and it rendered my old one useless, i couldnt transfer the mafile or whatever its called, it did nothing. I was forced to once again remove my authenticator. so i launched the new one did everything i was then promted by a phone number thing, i am not american so i dont have a +1 number, i am UK (we use +44) im kinda stumped now, i put it in and it closed the window and then did nothing. my number length is different and im kinda screwed, why does it not work :'c

**Comment by mantas7776** [comment]
Same issue

**Comment by Jessecar96** [comment]
You described a lot of problems here but gave no details on any of them.

**Comment by mantas7776** [comment]
After I write number into the program the window just disappears and nothing happens.

**Comment by JayTehRainbowNinja** [comment]
ok well the problem is this clearly only works for american users, i am not american, i dont have an american phone number extension (+1, i have +44) i cant sign up for the authenticator, i tried to put my mobile number in and the box just closed, i dont know if my region even effects it, it just didnt do anythnig else :/

**Comment by Jessecar96** [comment]
It looks like the form closes when Steam returns "GeneralFailure" when adding a phone. I'm not really sure what that error means.

**Comment by Bildostano** [comment]
Have the same identical problem, i did not get the sms, im not american

**Comment by Jessecar96** [comment]
Actually gonna close this since it's the same as #9

**Comment by JayTehRainbowNinja** [comment]
Yes it is the same but there is another? My location?

**Comment by hyt47** [comment]
you can add a phone number to steam using the main program Steam
