### ISSUE TITLE
Can't Open in "View Confirmations" when your Family View is enabled

### ISSUE THREAD

**Issue by mdfZEUNfps** [Jessecar96/SteamDesktopAuthenticator#480]
I open "View Confirmations" and there is appeared family view password section. I wrote the password on it correctly then it showed nothing. No "Enter pin code correctly" message. I think it just can't take my pin code.
![family](https://user-images.githubusercontent.com/16081365/36677051-2fd30104-1b48-11e8-8241-7d4398bdb93c.PNG)

**Comment by Jessecar96** [comment]
SDA does not support family view #20
