### ISSUE TITLE
Stuck in a loop between typing in SMS code and revocation code

### ISSUE THREAD

**Issue by kenn1ld** [Jessecar96/SteamDesktopAuthenticator#482]
Whenever I'm trying to make a new account, I get stuck in a infinite loop between typing my SMS code and revocation code. After it has asked for my revo code, it jumps rights back and asks for SMS code again. 
I've checked multiple times if I typed correctly, and I have.

**Comment by TomYoki** [comment]
Same here.
I rolled back to [v1.0.7.2](https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.7.2)
Not the ideal solution, but at least it works.

**Comment by pohuiusemail4741** [comment]
me too
