### ISSUE TITLE
Scan issues with chrome_elf.dll

### ISSUE THREAD

**Issue by routemasters** [Jessecar96/SteamDesktopAuthenticator#487]
I am keep getting a Baidu detection when I scan chrome_elf.dll on virustotal.com. Is that a false detection? 

[virustotal](https://www.virustotal.com/en/file/c9c3ff6755342440044301504a6aa008e22ba7225e6a4d274339354adc4c0950/analysis/1520786987/)

[hybrid-analysis](https://www.hybrid-analysis.com/sample/c9c3ff6755342440044301504a6aa008e22ba7225e6a4d274339354adc4c0950?environmentId=100)

[metadefender](https://metadefender.opswat.com/results#!/file/WVRFNE1ESXhOMU41UVZkcU5rZE1kM29TSndhanBmTFBH/regular/multiscan)

How reliable is the Baidu scan service? I have been using 1.7.0.1 ever since that service is flagging chrome_elf.dll.

Thank you all.

**Comment by Subtixx** [comment]
It's false-positive.
