### ISSUE TITLE
Failing to check for updates

### ISSUE THREAD

**Issue by pohuiusemail4741** [Jessecar96/SteamDesktopAuthenticator#488]
Is it still Failed to check update? when launch the program?

**Comment by fizzarin** [comment]
Yes.

**Comment by codeduph** [comment]
![2018-03-14_172047](https://user-images.githubusercontent.com/16449014/37393447-13ef167e-27ac-11e8-8f4b-c73277f783f0.png)

**Comment by linkjay** [comment]
Welcome to the graveyard of a projects past.

The developers have pretty much abandoned this project. I'd backup your maFiles if I were you, then either try out some fork of this project, or just go back to the regular mobile thing.

**Comment by NJC2** [comment]
There was an update a little over 2 weeks ago, I wouldn't call that abandoned.  I believe Github changed something, I'm seeing a lot of programs having to be updated to check for updates.

**Comment by Jessecar96** [comment]
This is because Github has switched to TLS 1.2 only. SDA will be updated soon to support this.
