### ISSUE TITLE
I cant get shared secret and identity secret

### ISSUE THREAD

**Issue by daz5552** [Jessecar96/SteamDesktopAuthenticator#489]
I want to create a roulette(gambling site)
And gambling site need a bot
And i cant get data(shared sec., identity sec.) because they are encrypted

What to do?

**Comment by pohuiusemail4741** [comment]
unencrypted data first then your data will reveal

**Comment by pohuiusemail4741** [comment]
how to create the bot and pass the steam rule that must pay $5
are you using ArchiSteamFarm?

**Comment by daz5552** [comment]
I do not know how to decipher

**Comment by daz5552** [comment]
No i using sda

**Comment by daz5552** [comment]
Okay thank you :)~

**Comment by pohuiusemail4741** [comment]
is it works?

**Comment by daz5552** [comment]
My pc turn off. I dont know. I will try tomorrow

**Comment by pohuiusemail4741** [comment]
ok

**Comment by pohuiusemail4741** [comment]
i recomend to use https://github.com/JustArchi/ArchiSteamFarm to create the bot and anymore
