### ISSUE TITLE
I add account - Error "GeneralFailure"

### ISSUE THREAD

**Issue by age7399** [Jessecar96/SteamDesktopAuthenticator#491]
Hello!

I add 15 account's in SDA - all ok
I add 16 account in SDA - Error "GeneralFailure"

![error](https://user-images.githubusercontent.com/37579827/37651637-d172334c-2c49-11e8-9c98-e74c253f7e2f.jpg)

Tell me please. What to do?

Thanks!

**Comment by 1Life1Chance** [comment]
Same here
