### ISSUE TITLE
Scam?

### ISSUE THREAD

**Issue by Viter7** [Jessecar96/SteamDesktopAuthenticator#493]
Hi. I downloaded SDA from steamdesktopauthenticator.com. Then I imported 48 accounts. Is that legit site? If not what should I do?

**Comment by jeepingviini** [comment]
Yes, that website is a scam... It is a modified version designed to steal your accounts. #442

**Comment by Viter7** [comment]
my phone was not rooted, is there a chance maFiles weren't taken?

**Comment by Viter7** [comment]
@jeepingviini is root needed to import maFiles?

**Comment by jeepingviini** [comment]
As far as I'm aware you need to have a rooted device to be able to import accounts from it.
