### ISSUE TITLE
Deleted SDA and broke account.

### ISSUE THREAD

**Issue by Theo-Proulx** [Jessecar96/SteamDesktopAuthenticator#497]
I deleted SDA when I deleted all of my Downlaods to make space but when I try to login, it says my account is already registered with SDA and I can't get the manifest.json or the maFiles folder because I deleted them all.

**Comment by Jessecar96** [comment]
IF you lost your `maFiles` OR lost your encryption key, go [here](https://store.steampowered.com/twofactor/manage) and click "Remove Authenticator" then enter your revocation code that you wrote down when you first added your account to SDA.
