### ISSUE TITLE
failed to update

### ISSUE THREAD

**Issue by thunderpants** [Jessecar96/SteamDesktopAuthenticator#499]
1.09 still has the 'failed  to update warning' prob.

**Comment by pizzahut2** [comment]
Works for me. Are you sure you're running v1.0.9 ? The version number appears in the lower right corner.

**Comment by sadewadee** [comment]
can i manual update from 1.0.8.1 to 1.0.9 by replacing file?

**Comment by thunderpants** [comment]
That is strange i downloaded the new release from the correct 1.09 release link ,extracted it and it's showing as 1.8.2.
I'll try downloading again and see if it's ok.
