### ISSUE TITLE
Phone Number Requirements

### ISSUE THREAD

**Issue by roughnecks** [Jessecar96/SteamDesktopAuthenticator#5]
Has it to be a US Phone number or just a Mobile number from any Country?

I'm asking because I do not live in the USA and I'm not getting SMS from the App.

**Comment by sloppy9** [comment]
It doesn't need to be a US number, you can specify the country when entering a phone number in to Steam. If you are trying to use a free number/sms service, it may be blocked.

Just borrow a friend or family members phone if you need to, and remove the number after you have the authenticator set-up.

**Comment by geel9** [comment]
If the app doesn't work for adding the phone number, please add the phone number through the official Steam website, under your account settings. Then go through the app again.
