### ISSUE TITLE
Issue happening with authenticating an account

### ISSUE THREAD

**Issue by xagotrunk** [Jessecar96/SteamDesktopAuthenticator#50]
I believe theres something wrong with SteamAuth as seen here https://github.com/geel9/SteamAuth/issues/13
The issue is also in the desktop authenticator, after the part where you put in a steam guard code it does not ask for an SMS code input and just reverts to the main menu

**Comment by MetalRuller** [comment]
This is what SDA calls when it attempts to add your phone to steam's API, http://steamcommunity.com/steamguard/phoneajax?op=add_phone_number&arg=1
arg being the phone number. As clearly seen here, steam is erroring that no sessionkey was provided. I'm guessing steam recently updated this and geel/jesse haven't added the sessionkey to the parametters yet.

**Comment by volovikariel** [comment]
Same!!! Can't make an account, enter user pass, enter a phone number, don't get a sms sent and there's no option where to enter it.

**Comment by volovikariel** [comment]
Thanks for the fixes and such Jessecar but it still doesn't work for me ( redownloaded etc. ) Also question, if I start now for  7 days will escrow go away? It used to keep closing on it's own and stuff and it auto removed it's authenticator so now I need to wait 3 days each time :/

**Comment by xagotrunk** [comment]
Fixed for me

**Comment by volovikariel** [comment]
Well then... I'm doomed ;D
