### ISSUE TITLE
App Doesnt work freezes up 

### ISSUE THREAD

**Issue by ThaJacka** [Jessecar96/SteamDesktopAuthenticator#502]
Trying to use app something the Token code wont load and view confirmations wont load instant Freeze tried running as Admin And still get same Results

**Comment by ThaJacka** [comment]
Tried doing Force refresh session and re login method and getting error happening also to a handful of my friends 
![helpp](https://user-images.githubusercontent.com/38336267/38710739-d0cecc2c-3e76-11e8-9f90-ce224813069b.png)

**Comment by YobaHere** [comment]
Relax, Steam WEB API is down at this moment, that's why you are not able to use SDA. You can check it's status at steamstat.us

**Comment by ThaJacka** [comment]
Thanks for that info I thank you <3
