### ISSUE TITLE
CANT ADD ANOTHER ACCOUNT

### ISSUE THREAD

**Issue by Tawtis** [Jessecar96/SteamDesktopAuthenticator#509]
I try to add another account to my SDA. I fill in all of the required boxes, it has a think for a bit and then tells me "Unable to save mobile authenticator file. The mobile authenticator has not been linked". How do I fix this?

Also, unrelated, but whenever I try to add my alt, it says to get the code from my email, yet it still sends me a code on my phone saying "Confirm adding a Steam Authenticator with (insert numbers here)" 

Help!

**Comment by hayk4500** [comment]
Hi! Try to run SDA as admin!
