### ISSUE TITLE
Trade Confirmations

### ISSUE THREAD

**Issue by juniorsaldanha** [Jessecar96/SteamDesktopAuthenticator#510]
I tried everything, "Login again", "Force session refresh", and I already have installed the "vcredist_x86 and vcredist_x64" and i always got this:

![sem titulo](https://user-images.githubusercontent.com/30378044/40102084-8f5f16e2-58b7-11e8-8f64-5bc1a69a67c7.jpg)

Please help me,, (Sorry if i said something wrong,  i have a bad english).

**Comment by Jessecar96** [comment]
Check https://github.com/Jessecar96/SteamDesktopAuthenticator/wiki/CefSharp-Troubleshooting
