### ISSUE TITLE
Account Import Issue

### ISSUE THREAD

**Issue by lostgarlicbread** [Jessecar96/SteamDesktopAuthenticator#511]
numerous times i've had to remove my authenticator, usually prompted when the shortcut doesn't even work. usually it will say something along the lines of:
_"This shortcut no longer works. Do you wish to delete it?"_ 
and i try running SDA re downloaded before and after i delete the shortcut. when launched, obviously, you're met with this screen.
![screenshot 13](https://user-images.githubusercontent.com/39606086/40519716-bdeef4e8-5f86-11e8-94c6-d6c0980d4fe3.png)

and as i said, when i try to import accounts it does not work.
this is the message i'm given:
![screenshot 12](https://user-images.githubusercontent.com/39606086/40519679-7417d15a-5f86-11e8-9ee4-6f5001eb1f27.png)
I'm not sure if i'm just to tired to think of a solution myself, or if i'm just really that rusty on files and stuff like that.
Itd be very much appreciated if someone could help. Thank you!

**Comment by dyc3** [comment]
What is the full file path of your maFiles?

**Comment by lostgarlicbread** [comment]
@dyn3 
1. the full path is as follows: C:\Users\Gabe\AppData\Local\Temp\Rar$EXa4088.21403\maFiles
2. I have done so, and now i have been able to open SDA, but the files i attempt to import either dont work or result in errors
3. yes.


while not logged in i tried the Login Again button resulting in this message
![screenshot 15](https://user-images.githubusercontent.com/39606086/40526967-6c98fd90-5faf-11e8-97cf-6a49ea0eacdc.png)
I tried using the import account method in the top left, again, to no avail. 


now that SDA is working, i may just have to reset again. i have tried all the old MaFiles still resulting in
![screenshot   @@12](https://user-images.githubusercontent.com/39606086/40527091-0d5714c4-5fb0-11e8-8584-3b36978e415b.png) 



Thank you for your time.

**Comment by dyc3** [comment]
Try moving your maFiles to a different location. Having your maFiles inside your temp folder is just asking for trouble.
