### ISSUE TITLE
Need Chinese Translation

### ISSUE THREAD

**Issue by nitu2003** [Jessecar96/SteamDesktopAuthenticator#514]
Many teenaged player in China aren't good at English, so we need Chinese Translation. I can give help
:)

**Comment by mdfZEUNfps** [comment]
Then tell them to learn English first before play.

**Comment by Jessecar96** [comment]
We're currently not offering any translations for SDA. See #146

**Comment by 1688pc** [comment]
是的，我很需要中文翻译，从吾爱下载的OCR软件再复制到翻译软件翻译使用很麻烦，可惜这个程序不支持翻译，感谢热心网友。
