### ISSUE TITLE
Missing dependency ?

### ISSUE THREAD

**Issue by CruelAlpha** [Jessecar96/SteamDesktopAuthenticator#517]
Hi there,
I have the latest .net framework installed
but the SDA is saying i am missing a dependency, everytime it installs i try it again and it says the same thing
How can i fix this?
Thanks

**Comment by dyc3** [comment]
Please post the exact error message verbatim, otherwise nobody will know what you are talking about.

**Comment by Jessecar96** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/wiki/CefSharp-Troubleshooting
