### ISSUE TITLE
Can't run on 64-bit system.

### ISSUE THREAD

**Issue by hyt47** [Jessecar96/SteamDesktopAuthenticator#52]
On **Windows 7 64 bits** > **SteamDesktopAuthenticator v0.3.0**

When I click the button Trade Confirmations I get this Error:
`Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies`

**Fix** tested on a clean Windows:
install:
- .NET Framework 4.5.2 
https://www.microsoft.com/en-us/download/details.aspx?id=17851

- Visual C++ Redistributable 2013 (vcredist_x86.exe) 
https://www.microsoft.com/en-us/download/details.aspx?id=40784

- Run SteamDesktopAuthenticator v0.3.0 >>> **It works :)**

(is the same as on 32 bits)

**Done, Enjoy ^_^**

**Comment by Jessecar96** [comment]
Ah ha, It's Visual C++ Redistributable 2013 not 2012. Thanks for the find!

**Comment by Ps1d3r** [comment]
Worked for me
