### ISSUE TITLE
DONT USE THIS, THE OWNER OF THIS PROGRAM CAN SEE ALL OF YOUR DETAILS

### ISSUE THREAD

**Issue by arivp** [Jessecar96/SteamDesktopAuthenticator#521]
LIKE I TOLD YOU, THE OWNER OF THIS PROGRAM CAN SEE ALL THE LOGIN/DETIALS/CODES OF EVERYONE THAT USES IT, PLEASE I RECOMMEND YOU DONT USING IT, THEY CAN AND WILL HACK YOUR ACCOUNT

**Comment by Avatarus-one** [comment]
You're wrong. Check the source code before blaming them.

**Comment by arivp** [comment]
Are u sure? i have proof of a guy scamming me with this program. 
![e07ecd945077efe20f55fb5b4f2e5324](https://user-images.githubusercontent.com/40310175/41500378-78cea48e-7166-11e8-8a15-f384e7b14e99.png)
![cd38ee995a032896fcc285685f4303ad](https://user-images.githubusercontent.com/40310175/41500379-7a4e55b6-7166-11e8-8af2-7302a1c5f0fa.png)
![93ec758668653567b332eb64121790a9](https://user-images.githubusercontent.com/40310175/41500380-7b3acb1c-7166-11e8-83dd-e89a0d2a87b9.png)


here u have the proof, he made me dowload this and afterwards he hacked me, thanks god steam support gave me back the account.

**Comment by dyc3** [comment]
You got scammed pretty hard mate. It's open source, so anyone can download the source code, create a malicious version, and release it to the public. That's why you should _always_ download SDA **from this GitHub. All other versions are fake.**

**Comment by arivp** [comment]
I dowload it from here dude... i am telling you this

**Comment by 21cret** [comment]
been using this over a year. i guess im lucky im not getting hacked :)

**Comment by Jessecar96** [comment]
There is another website offering a modified version of SDA containing a backdoor to your account.
I won't be posting that here but it's pretty obvious.
**Only ever download it from github.com!** Or just compile it yourself if you want.
