### ISSUE TITLE
Auto-confirm trades only working on Highlighted/Selected account.

### ISSUE THREAD

**Issue by mikereader1** [Jessecar96/SteamDesktopAuthenticator#523]
I have issue with my SDA version 1.0.9 where only the selected account will confirm trades automatically. If I select another account and wait ~60 seconds (the wait time in my settings) the account (second, third, fourth, etc..) will then confirm the trade. Manually viewing the trade confirmations and confirming them also works. I have also tried to force refreshing the accounts, which works for the trades already in progress, but then SDA will only confirm the select account afterwards.   

Here is a screenshot of my current settings:
![image](https://user-images.githubusercontent.com/40705153/42118090-4240ead4-7bc6-11e8-9569-49a271cb7ea9.png)

Is anyone else having this problem? 

P.S. This issue may also be happen for Auto-confirm market transactions, however I never put anything on the market.

**Comment by Vidosen** [comment]
ohh, as i understood when i'd read the code, that's a mistake of developers, i'm already writing them about this.
(By the way, if you are interesed in a private advanced version of sda with capability of create the accounts and link Steam Guard to them automaticly, and contains extended info about each of account, write me on the mail daniil-shaposhnikov@yandex.com, an estimated price is 149$, may make a discount)

**Comment by Jessecar96** [comment]
This is fixed in the latest version.
