### ISSUE TITLE
Bug .maFile Identity/Shared secret

### ISSUE THREAD

**Issue by WindoPvP** [Jessecar96/SteamDesktopAuthenticator#528]
Hello,

I have a bug.
When I register my steam account, a .maFile file will be created.
The problem is that I need the identity and the shared secret for my steam bot.
I use nodepad ++ to open the file, and I do not see the two codes. 
![capture](https://user-images.githubusercontent.com/36110475/43039767-ac17fc98-8d34-11e8-910c-82761f4e413d.PNG)

How do I find the identity and the shared of all these letters / numbers?

**Comment by WindoPvP** [comment]
I use the version : 1.0.9

**Comment by tuktun** [comment]
It is not a bug, looks like your maFile is encrypted.

**Comment by Vidosen** [comment]
I'm agreed with previous comment, just remove encryption through SDA.
Select the account you need, click "Manage Encryption", enter current password(wich possible has been added when you was linking the acc to SDA), and then leave blank and click OK. Done.

**Comment by WindoPvP** [comment]
Yep thx
