### ISSUE TITLE
Lost Revocation Code

### ISSUE THREAD

**Issue by IMGOODZ** [Jessecar96/SteamDesktopAuthenticator#539]
I have just set up SDA for the first time and i was almost finished writing down the revocation code, when the window just closed. I have seen people say to find the code, i can look in the .maFile and find a line like 

> revocation_code: R*****

but when i open the file with sublime text, notepad, or notepad++ I just see a string of letters and numbers.
Is there something im doing wrong?

**Comment by rakisaionji** [comment]
What a scrub. You may have encryption set up already. If you don't have enough skill to decode your maFiles, the only way to revoke is contact your Steam customer support and cry like a baby.

Honestly, the program itself has asked you twice to write it down (behavior is as same as the original authentication on the mobile phone). It is your problem, it is not a bug.

**Comment by IMGOODZ** [comment]
I apologies for my scrubbiness, I did not mean come off as if it was a bug, I am very sorry and would also like to mention how helpful your application is.

**Comment by genesix-eu** [comment]
I think you have to decrypt files using SDA {Tthere should be a button to disable encryption} and than you can open files in notepad and they are readable.
