### ISSUE TITLE
Not sending a SMS code/ user&pass problems

### ISSUE THREAD

**Issue by Newcool1230** [Jessecar96/SteamDesktopAuthenticator#54]
so after trying many and many times with the phone number (i have already linked it to my steam and account and unlinked to make sure the phone works) it does not send me a SMS code.

and the second problem is when i keep trying and trying with the phone number
it stopped working after awhile: setup new account > user&pass *click* "login" > it disappears > takes me back to menu.
i tried with other account and it works fine....but its not sending the SMS code.....
(yes even after the update its not working, unless....)

**Comment by Seelgram** [comment]
I have the same problem, i'm using a french phone number (+33) and after trying couple times with it in his final form like this : +330606060606 . I have end in conclusion that is not working. I can't receive SMS.

**Comment by shadow7001** [comment]
I have the same problem.

**Comment by vizolover** [comment]
Same here.

**Comment by Denix-spb** [comment]
+1

**Comment by IDeaDHeaDI** [comment]
+1

**Comment by volovikariel** [comment]
+5

**Comment by phrostb** [comment]
i've tried inputting my phone number about 5 different ways so.. using the original method, i might put it in tlike this http://i.imgur.com/bk7LBe2.jpg

and after the keyword input it asks for the phone number (as pictured above) but i never get an sMS :[

**Comment by Newcool1230** [comment]
u shouldnt...post ur phone number.......

**Comment by phrostb** [comment]
it's not my actual phone number...

**Comment by Newcool1230** [comment]
oh ok

**Comment by phrostb** [comment]
so do you know what the problem is??

**Comment by Newcool1230** [comment]
nope thats why i made the "issue" topic
