### ISSUE TITLE
I found a mistake in code (that's about the multiple auto confirmation trades)

### ISSUE THREAD

**Issue by Vidosen** [Jessecar96/SteamDesktopAuthenticator#544]
![screenshot_1](https://user-images.githubusercontent.com/44365736/47837234-7bd30680-ddd5-11e8-948c-38c584f256d1.png)
I seem that instead a variable "currentAccount" here must be "acc". Check this part of code.

**Comment by Jessecar96** [comment]
This will be fixed in the latest release.
