### ISSUE TITLE
HELP ME I DONT KNOW PASSWORD 

### ISSUE THREAD

**Issue by axel999x** [Jessecar96/SteamDesktopAuthenticator#548]
HOW I CAN DECRYPT OR DO SOMTING HELP ME

**Comment by Bluscream** [comment]
Please don't overuse capslock, Github is not YouTube. About your issue, you should have made backups of your config.

**Comment by axel999x** [comment]
i have mafiles but i dont know how to decrypt them

**Comment by Jessecar96** [comment]
There is no way to recover the password once encrypted.

**Comment by lulacoding** [comment]
f
