### ISSUE TITLE
Issue with importing maFile.

### ISSUE THREAD

**Issue by Guest1233** [Jessecar96/SteamDesktopAuthenticator#55]
Greetings. I upgraded to the newest version, and upon importing my maFile, it tells me that the file is invalid:

"This is not a valid SteamAuth maFile. Import failed."

What can I do about this? It was said on reddit to take off the encryption but there is literally no way to do that, I have my passkey but I can't import my account. Can't access my account on Steam, I have trials today...

**Comment by vlogerM** [comment]
You can recover your account by using this link (but you will remove the Steam Guard Mobile Authenticator):
https://help.steampowered.com/#HelpWithLoginInfo?nav=authenticator﻿

**Comment by Guest1233** [comment]
Eh. It would be a real bother to do that in my situation, and I just need access to the whole thing as soon as possible while keeping the escrow thing on.

**Comment by Jessecar96** [comment]
This is not a support forum.

**Comment by Guest1233** [comment]
It's irresponsible of you to close this, as there have been a number of people who faced this exact issue on reddit, and were told to take off the encryption by a post made by Geel. The transition from a version to another should not corrupt your maFile in any situation, it merely screams out incompability.

Of fucking course, it's not a support forum. It's where people report bugs, and this is a bug in the program, as in, I cannot access my trades or even my account due to this error except via literally losing out on the Steam mobile Authentication. It's not a support forum, but this is a place where people can provide feedback on bugs and faults in the program. You're keeping a lot of people from accessing their inventories and accounts by saying 'this is not a support forum'. Can I at least know how to get my revoke code from my maFile or something? Or how to take off the encryption? I was only supplied with ways as to how to get around the 'bug', which makes the error in your program persist for longer, and does not fix anything at all... I had my revoke code in a notepad, and it disappeared due to how shitty Win. 8.1 is, these things can happen to anyone, I've opened a ticket with Steam around 3 days ago and there has been very little progress made over accessing MY ACCOUNT. I even had to make an alt.

If you're trying to fix bugs, saying this is not a place for support is a bad way of handling bugs and errors in your program. Just sayin'. Grants you less credibility and rep.

**Comment by hyt47** [comment]
Too many people asked stupid questions instead of following the Setup instructions,  and by mistake this BUG was closed

Not to worry, because u added another msg this BUG will be fixed

I tested the "Import maFile" function and i get the same error

**workaround**
- Create a New Folder
- Extract the new version of SDA inside it
- **copy** maFiles from your old program to this new one
- Run the new version of Steam Desktop Authenticator.exe and test if u see your accounts
- Arhive the old program and keep it as a backup
- Move the new version where u want

- also arhive `maFiles` folder (as a backup) and place the somewere safe

**Comment by Guest1233** [comment]
@hyt47 

Your method works! I just copied the files of the SDA to the original folder, back in the 0.2.2 version of the program. It works! Thanks a million, man.
