### ISSUE TITLE
How to open on macOS?

### ISSUE THREAD

**Issue by HulioEglesias** [Jessecar96/SteamDesktopAuthenticator#555]
Can't open via mono and can't compile via VS for Mac
How can I compile or run it on Macbook?

**Comment by HulioEglesias** [comment]
But should be any ways to start in on MacOS.

**Comment by IAmWolfie** [comment]
Nope. This is written in C# with .NET and will not run on MacOS.

**Comment by berliozzz** [comment]
I use crossover for macOS
