### ISSUE TITLE
Don't get an SMS nor do I have the option to input it?

### ISSUE THREAD

**Issue by volovikariel** [Jessecar96/SteamDesktopAuthenticator#56]
Open it up ( the program) , Enter user and pass when trying to create authenticator, Enter code received in email, enter a phone number, no option to enter the sms received nor is there a window where I can enter it, redownloaded, ended task manager stuff , not sure what's going on. :D

**Comment by voltij** [comment]
This typically means Steam couldn't send that number a text (or there was some other error). I think I see that they are adding some error messages in the next version

**Comment by volovikariel** [comment]
I used a ton of SMS receiver programs and even a real phone number of a friend, doesn't work whatsoever, let's hope I get a solution soon D: Also if I get 7 days right now of non stop, will the 3 day wait go away?

**Comment by Jessecar96** [comment]
This was already fixed however the update is not out yet. You can compile it yourself if you don't want to wait.

**Comment by volovikariel** [comment]
How do you compile it ?

**Comment by volovikariel** [comment]
Fixed in 0.3.1 !!!! Thanks :)
