### ISSUE TITLE
Not receiving SMS code

### ISSUE THREAD

**Issue by TophatMario** [Jessecar96/SteamDesktopAuthenticator#561]
Is anyone else having this same issue? It's been bugging me out recently and I just WANT it so I can fully implement SDA. Help?

**Comment by hat3l0v3** [comment]
Same problem today. I deleted my steam guard on mobile and wanna setup on SDA but didnt receive sms for confirmation. Tried few times but nothing happened, then go back and setup on my mobile again. sms receive . WTF ? fix that please....
