### ISSUE TITLE
Stuck in checking ABD

### ISSUE THREAD

**Issue by Pomedi** [Jessecar96/SteamDesktopAuthenticator#569]
![image](https://user-images.githubusercontent.com/35794351/54635213-5563ee00-4a8c-11e9-818a-b56925060595.png)

**Hello**

No matter what i do what version i use i always get stuck in checking for ABD when i try to import from android. Been trying to search for solution but haven't found any.

**Comment by listenuptome** [comment]
No solution - go hard way)
Remove authenticactor from steam and setup it on SDA as new. Wait 8 days and all ok)
