### ISSUE TITLE
Another instance of the app is already running

### ISSUE THREAD

**Issue by Prep5242** [Jessecar96/SteamDesktopAuthenticator#572]
I just installed the authenticator and I've had it running 2 days, and I want to make a trade but when I try to open the program to confirm that I want to make an offer it doesn't let me launch. I see in my task manager the .exe is a background process and I don't want to end it since I want to make it the 8 day period. Would hitting end task reset that? Why can't I launch the program?

**Comment by listenuptome** [comment]
You just minimized app to tray. Open it and you'll see app's icon, tap twice and you'll open an app)
BTW. Lol. You will not get ban for 8 days if you'll close app. It's just like close and open Steam App on phone - no criminal))

![2019-04-05_08-59-25](https://user-images.githubusercontent.com/17239953/55606368-2f736480-5781-11e9-8a07-271250e3cafe.png)
