### ISSUE TITLE
ADB not detecting device (even on wifi)

### ISSUE THREAD

**Issue by qbuss** [Jessecar96/SteamDesktopAuthenticator#574]
Hi I have a rooted android device (magisk).
And I wanted to use this option
![image](https://user-images.githubusercontent.com/12773343/57129925-38635000-6d98-11e9-8886-9a67dfd35d3f.png)
but only thing that i get is this
![image](https://user-images.githubusercontent.com/12773343/57130027-8ed08e80-6d98-11e9-80e1-d689f04581cd.png)
even if I try over wifi
![image](https://user-images.githubusercontent.com/12773343/57130059-a0b23180-6d98-11e9-83d7-fb8384c086e9.png)
then it doesn't do anything (even tried winthout :5555)

oh and by the way I'm using resurection remix rom

**Comment by Xitcklif** [comment]
Hello. Did you find solution? You should download ADB files

**Comment by Xitcklif** [comment]
@qbuss

**Comment by Xitcklif** [comment]
Bad news, guy. I think there is no way to import from android
