### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by alphazdog9776** [Jessecar96/SteamDesktopAuthenticator#575]

**Comment by alphazdog9776** [comment]
![b1bc7769d9024d542c2cb6ff1044f677](https://user-images.githubusercontent.com/50254622/57172492-ca964300-6dee-11e9-9cf0-6d000d5dd652.png)
![c9b504b7426fcf60507882813ab888ba](https://user-images.githubusercontent.com/50254622/57172494-cff38d80-6dee-11e9-9bce-55d5811677be.png)


I'm pretty sure the problem is that the authenticator isn't getting connected to my internet. Either it's getting blocked through my antivirus or something else is happening. If it's not the antivirus I don't know how to give it access.

Please advise. Thank you.

**Comment by solemcaelum** [comment]
Can you expand the details?
