### ISSUE TITLE
Asking for phone number 

### ISSUE THREAD

**Issue by xdjx19** [Jessecar96/SteamDesktopAuthenticator#576]
I signed in and everything but it is asking for a phone number now. After entering the email code this happens. The guides I checked showed it should ask for encryption.
![Screen Shot 2019-05-17 at 7 27 23 am](https://user-images.githubusercontent.com/39229311/57910014-92e7ca80-78c7-11e9-8abc-f0248e816ac5.png)

**Comment by solemcaelum** [comment]
You probably don't have a phone number linked to your steam account. This app is recreating the mobile app, not replacing it, therefore steam itself needs your phone number.
