### ISSUE TITLE
View confirmation page - White

### ISSUE THREAD

**Issue by Jeux100** [Jessecar96/SteamDesktopAuthenticator#578]
Can't find any answer.
Login again or Force session refresh doesn't help

**Comment by Hrxn** [comment]
Possible interference by Antivirus program?

**Comment by Jeux100** [comment]
I have no Antivirus, it was done on VirtualBox pc, I just deleted it and created a new computer. Now it works

**Comment by Hrxn** [comment]
Well, obviously. Please close the issue if everything works now.

**Comment by Jeux100** [comment]
The issue wasn't solved tho?

**Comment by Hrxn** [comment]
Networking issue with the VM, it seems.
