### ISSUE TITLE
Phone number not working

### ISSUE THREAD

**Issue by ThirtyThrone021** [Jessecar96/SteamDesktopAuthenticator#579]
Phone number is active with service but once i add it says 
Error adding your phone number. Steam returned "GeneralFailure".
![anying](https://user-images.githubusercontent.com/51387836/58920497-7e496600-8700-11e9-8c73-c1ef9a74e8be.PNG)

**Comment by Azperin** [comment]
same

**Comment by AydievMansur** [comment]
Hey buddy, you need to disable Steam family options (that error caused in most cases by Family option) 'Parent Control'

**Comment by seumas** [comment]
Having the same problem. I'm able to get Steam to verify my number by SMS and have been using this phone as my SMS number for steam for more than two years. Family View is disbled. I installed app on Windows 10, click "Setup New Account", enter credentials, and then get the "Error adding your phone number. Steam returned 'GeneralFailure'" error. (Steam authenticator is disabled, of course).
