### ISSUE TITLE
I cant import ac from android

### ISSUE THREAD

**Issue by Xitcklif** [Jessecar96/SteamDesktopAuthenticator#580]
Hey. I did everything according to the instructions on the wiki, if there are hints from the wiki, I will immediately say that this is not relevant. I tried to import using ADB from two devices already, as well as with blustacks. I get the same error. P.S. my both devices rooted as well
![Screenshot_3](https://user-images.githubusercontent.com/20087169/59151001-a6a0cf80-8a34-11e9-9c2e-c9dc565f594f.png)
 I found a guide [(here)](https://miped.ru/f/threads/kak-vruchnuju-perenesti-dannye-iz-mobilnogo-prilozhenija-steam-guard-android-v-sda.57410/) on how to import an account into an empty mafile using the root of the explorer, but still does not work. To begin with, the steam.uuid.xml file was missing and I had to insert the device ID from the application of the same name, but I do not think it was right. Most likely, Steam has departed from the old system and those guides are no longer relevant. 
**Someone, please, tell me how best to import an account from android today, I do not want to wait a week.**

**Comment by wordlesswind** [comment]
You can use this version: https://github.com/sebastianbassen/SteamDesktopAuthenticator/releases/latest
