### ISSUE TITLE
Are you affiliated with steamdesktopauthenticator.com?

### ISSUE THREAD

**Issue by CapoFantasma97** [Jessecar96/SteamDesktopAuthenticator#581]
steamdesktopauthenticator.com is the first result in DuckDuckGo and the second in Google and Bing. It may be quite the problem if it's a scam as many people would click on that first rather than a GitHub link.

**Comment by Hrxn** [comment]
Smells like a scam...

**Comment by dyc3** [comment]
No, that site is not associated with this project. In fact, it steals steam account information. **The only place to get a legitimate build of SteamDesktopAuthenticator is from this repo.**

**Comment by Jessecar96** [comment]
We are not. That website, and others are a total scam and will steal your account.
