### ISSUE TITLE
Errors and a lot of errors

### ISSUE THREAD

**Issue by NRN1337** [Jessecar96/SteamDesktopAuthenticator#586]
Tried multiple versions from sebastian and from jesse too. Root,no root still having issues with android. Either I get some "could not find a part of the path c:xxxxx /steamguard or it just freezes. 
You said try using GitHub desktop for all. Did,still getting bunch of errors about that same folder/branch. 
Proof for github desktop: https://prnt.sc/ojphem
Didn't get proof for rest,got sick of it after 1 hour of troubleshooting and looking thru all of this. Seems like android implementation doesn't actually work.

**Comment by NRN1337** [comment]
Also tried nonroot with modded APK,didn't work.

**Comment by NRN1337** [comment]
No update?

**Comment by AydievMansur** [comment]
> No update?

I guess he doesn`t reply to issue you should try to hit eim to email

**Comment by NRN1337** [comment]
Nah,I stopped caring. Not gonna be using the app. Not that I'm being unthankful it's just not worth,legit spent days tryna fix this
