### ISSUE TITLE
check root will freeze app

### ISSUE THREAD

**Issue by rhsCZ** [Jessecar96/SteamDesktopAuthenticator#591]
Hi i have problem, when trying to import. when it is in Check root state, app freeze and i must kill it via task manager. Otherwise, i have extracted my secret key from phone manually, it's possible to import to app manifest somehow? My phone is Samsung Galaxy J5(2017) - sm-j530f. It has root with magisk and disabled encryption of /data.
![bug](https://user-images.githubusercontent.com/15573547/65816758-e2d48780-e1ff-11e9-8927-d8cfe56a6ccc.png). root in shell(via adb) works fine.

**Comment by dyc3** [comment]
Importing from android has been broken for a long time now
