### ISSUE TITLE
Steam added a new stage when adding a new account

### ISSUE THREAD

**Issue by Ogurets-wq** [Jessecar96/SteamDesktopAuthenticator#593]
Steam added a new phase when adding a new account. SDA shows an error when adding a phone number, you need confirmation of the number by mail. Is a solution to this problem possible?

**Comment by dyc3** [comment]
Could you please elaborate on what exactly has changed?

**Comment by Ogurets-wq** [comment]
First you write the login password - everything is as it was before. Then comes the confirmation code for the mail - everything is as it was before. Then you enter the phone number - the SDA gives an error and a message arrives on the e-mail, where you must follow the link and confirm that this is your number.

**Comment by JesusLoveli** [comment]
Please fix that :(

**Comment by scudc** [comment]
The newly registered steam account must first bind the mobile phone number to the website, so that the SDA binding can be used normally.

**Comment by ataiaibekov** [comment]
how much longer to wait for a fix?

**Comment by Ryan69132** [comment]
pls fix thanks

**Comment by spree13k** [comment]
changed the binding of the phone, will there be a fix?

**Comment by sonnyboik** [comment]
Simple fix - Before trying to add the account via SDA link your phone on the steam website

**Comment by Ryzhehvost** [comment]
This needs to be fixed in https://github.com/geel9/SteamAuth first, as SDA depends on it.  I've made a PR with a fix already https://github.com/geel9/SteamAuth/pull/81 but it seems that @geel9 don't care about it at all. Without a fix in lib I can't send a PR to SDA (actually I can, it just won't compile). As time goes I'm thinking about just making a fork would be easier.

**Comment by Ryzhehvost** [comment]
Here, I drafted a PR in case SteamAuth one will get merged some day #597

**Comment by Jessecar96** [comment]
This is fixed in the latest release.
