### ISSUE TITLE
SDA is completely dead now?

### ISSUE THREAD

**Issue by Aimtux68** [Jessecar96/SteamDesktopAuthenticator#598]
Taking forever to show a code token and it's always the wrong code so I can't login to one of my account anymore.

**Comment by Hrxn** [comment]
Nope, still working for me, just as always.

**Comment by Kladdkaka** [comment]
just had the same issue (using a super old version although), i just tried to use a vpn, which worked

**Comment by Jessecar96** [comment]
Not anymore, new update released.
