### ISSUE TITLE
GeneralFailure upon adding numbers

### ISSUE THREAD

**Issue by elysiix** [Jessecar96/SteamDesktopAuthenticator#599]
I've created a fresh account, confirmed through email.
5 USD added and profile set up.
I tried 2 different phone numbers but I get this error:

https://i.imgur.com/LEIi7Pd.png

**Comment by ZarusMods** [comment]
Just coonect your phone number throught steam and profit

**Comment by MacFroZLE** [comment]
it's a long time! I have 1K + accounts, and all I need to put sda. It'll take me a long time

**Comment by Jessecar96** [comment]
This will be fixed in the latest update.
