### ISSUE TITLE
Unable to confirm steam community market listings

### ISSUE THREAD

**Issue by EwanLan** [Jessecar96/SteamDesktopAuthenticator#6]
With steam community market making changes for escrow, one of these things is making listings for the community market. For these listings to be accepted they require the mobile authenticator/steam mobile. The desktop authenticator does not have support for accepting these listings and makes the community market unusable for players who sell items.
![image](https://cloud.githubusercontent.com/assets/10245693/11482039/81083aca-9798-11e5-8880-8431c358ad54.png)

![image](https://cloud.githubusercontent.com/assets/10245693/11482147/1a830a9a-9799-11e5-830d-25838bfe9d23.png)

**Comment by geel9** [comment]
What's the version of the SDA you are using?

**Comment by Jessecar96** [comment]
You're probably using an old version. The latest version added support for market confirmations.
To update go here and download the latest zip: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
Then replace the old files with the new ones, making sure you don't delete the maFiles folder.

**Comment by EwanLan** [comment]
Thanks Jesse
