### ISSUE TITLE
Having >80 accounts

### ISSUE THREAD

**Issue by voltij** [Jessecar96/SteamDesktopAuthenticator#60]
The Steam limitation for number of accounts on a device is 80. If I want more than 80 accounts on SDA, what would be the best practice for doing this?

I assume running more than 1 copy of SDA won't work as they will generate the same device id.

Thanks

**Comment by volovikariel** [comment]
You need more than 80? O_O

**Comment by voltij** [comment]
Yeah, CSGO betting.

**Comment by PFCKrutonium** [comment]
I guess it depends if the limitation is Server Side or Client Side. If it is client side you shouldn't have issues. If it server side, I think two instances in different directories should work fine.

**Comment by Jessecar96** [comment]
SDA should be able to add as many accounts as you want. The limitation is 80 account on one phone number.

**Comment by voltij** [comment]
Hm, odd. I have 82 accounts associated to my actual phone number right now. I have 80 registered on SDA and 2 registered on the mobile app (one is my "main" account and one is an alt).

When I add another account in SDA after the phone number step it won't send me a text, but logging in to the Steam app with the same account will send a text.

**Comment by Jessecar96** [comment]
I just pushed an update to fix SMS, try that.

**Comment by voltij** [comment]
Works for my first "trouble" account so far. Leave this open for a little bit so I can further test.

BTW @Jessecar96 what is your source for 80 accounts per phone number? Just hearsay or is there something official that says it?

**Comment by Jessecar96** [comment]
I thought I heard it from Geel, but it doesn't seem to be the case.

**Comment by voltij** [comment]
I'm thinking that might be incorrect. If I find an upper limit on anything I'll let you know.

Thanks for the fix, it looks like it's good for now.
