### ISSUE TITLE
no exe in download

### ISSUE THREAD

**Issue by jakeebigdick** [Jessecar96/SteamDesktopAuthenticator#601]
there is no exe file in the download when i download with github desktop. if i try download zip on the site it freezes and fails download about halfway through

**Comment by ChargedByte** [comment]
If you download using Github Desktop you are just going to get the source code, so you can either compile it yourself or you can find precompiled executables in the [releases tab](https://github.com/Jessecar96/SteamDesktopAuthenticator/releases)

**Comment by jakeebigdick** [comment]
yea i got it
