### ISSUE TITLE
Error logging in: Steam returned "GeneralFailure".

### ISSUE THREAD

**Issue by alienyes** [Jessecar96/SteamDesktopAuthenticator#602]
I get this error when i try to login with my account. Please help me, how can i fix it?

**Comment by alienyes** [comment]
![image0](https://user-images.githubusercontent.com/58692846/70437754-9671b780-1a8c-11ea-9c20-3c7059fca59d.jpg)

**Comment by Burnwithme** [comment]
Same problem.

**Comment by alienyes** [comment]
> Same problem.

whats your discord? ill add you, if i find the solution ill tell you or if you find you ll tell me then. what do you think?

**Comment by tudadadu** [comment]
Add your phone number in steam settings, then error will disappear. It's new system and sda dont working with her... at this time...

**Comment by aeonixlegit** [comment]
Someone just fixed this error - download this https://github.com/Ryzhehvost/SteamDesktopAuthenticator/releases/tag/1.1.0

**Comment by sparkaccounts** [comment]
That fork doesn't fix it tho. lol

**Comment by Jessecar96** [comment]
This will be fixed in the latest update.

**Comment by torrenars** [comment]
> This will be fixed in the latest update.

I still have same problem please help
