### ISSUE TITLE
Error logging in: Steam returned "GeneralFailure".

### ISSUE THREAD

**Issue by kaynezu** [Jessecar96/SteamDesktopAuthenticator#608]
$20 to fix this now

**Comment by aeonixlegit** [comment]
https://github.com/Ryzhehvost/SteamDesktopAuthenticator/releases/tag/1.1.0 - download this

**Comment by sparkaccounts** [comment]
Doesn't work.

**Comment by Jessecar96** [comment]
This will be fixed in the latest update.
