### ISSUE TITLE
all these issues are pointless, it's been abandoned

### ISSUE THREAD

**Issue by ParzivalWolfram** [Jessecar96/SteamDesktopAuthenticator#609]
i'd like a native linux version but y'know

it's dead so

(wine also doesn't work with it anymore, it spits syscall tracebacks at me when i try.)

**Comment by kaynezu** [comment]
we need to find a replacement then, I found one but someone needs to look it over if its safe

**Comment by dyc3** [comment]
I made a cli version for linux, see here https://github.com/dyc3/steamguard-cli

**Comment by Bluscream** [comment]
WinAuth

**Comment by d4k0** [comment]
WinAuth is also abandoned :(.

**Comment by aeonixlegit** [comment]
https://github.com/Ryzhehvost/SteamDesktopAuthenticator/releases/tag/1.1.0 - heres updated version

**Comment by Jessecar96** [comment]
Not anymore, new update released.

**Comment by ParzivalWolfram** [comment]
OH SHIT where'd you come from

**Comment by ParzivalWolfram** [comment]
...
you literally just...
...You know what, fuck it, i'll take it.
