### ISSUE TITLE
Login Token doesn't work! Please Help!

### ISSUE THREAD

**Issue by danielzss** [Jessecar96/SteamDesktopAuthenticator#61]
Every time I use the login code on the steam desktop authenticator to login to steam it doesn't work. There is always a message saying: Sorry, that isn't quite right. Please enter a fresh code from your mobile app. PLEASE HELP

**Comment by danielzss** [comment]
Please help :,(

**Comment by Ps1d3r** [comment]
That is weird.... Are you sure you are copying the last generated code, before the green bar reaches the end?
Codes are replaced every 30 seconds as a security measure, so you need to use the one that is currently active.

**Comment by danielzss** [comment]
@Ps1d3r Yes, I did.

**Comment by Ps1d3r** [comment]
I don't know then man... 
AN you have the latest version?

**Comment by danielzss** [comment]
@Ps1d3r I fixed it by removing the authenticator and then downloading it again. Thanks anyways :)

**Comment by Ps1d3r** [comment]
NIce xD
