### ISSUE TITLE
Recoverey code registration at SDA?

### ISSUE THREAD

**Issue by TheBilbo** [Jessecar96/SteamDesktopAuthenticator#615]
Is it possible to make reg at SDA via recovery code / phone number / login&pass?
At steam app there is possible to click "I no longer have access to my steam auth" and it offer auth transfer and limited steam market block fo 2 days.

Any similar at SDA? Mean if I'll input login/pass will SDA ask me for recovery code / sms and proceed with auth transfer instead of regular procedure of new auth creation?

**Comment by Jessecar96** [comment]
This is not currently supported.
