### ISSUE TITLE
UK Number

### ISSUE THREAD

**Issue by JayTehRainbowNinja** [Jessecar96/SteamDesktopAuthenticator#62]
I asked this before but my post was closed without an answer, is there anyway that anyone outside of the US can even use this damn thing anymore? :c

**Comment by danielzss** [comment]
Try this to receive sms:
http://www.freeonlinephone.org/
Choose the UK phone number
Hope it works :)

**Comment by JayTehRainbowNinja** [comment]
The new update appears to have removed the phone number feature completely. v.3.1 thanks anyways, hope it works this time for real
