### ISSUE TITLE
shared secret is missing

### ISSUE THREAD

**Issue by Pianissimo7** [Jessecar96/SteamDesktopAuthenticator#622]
so I watched a tutorial showing how to use this code, and added my user in, from what I have heard the shared secret should be located at the maFiles folder in the .txt file. 
it should appear as shared secret:<and the code here>
so i went there and there are just about 300 random chars there, and no "shared secret:" anywhere in it.
is there anything i missed? is this an error? please help.

EDIT: please ignore this complaint, im dumb and forgot to remove the encription before looking at the file, all is good now LOL.

**Comment by dyc3** [comment]
please close the issue
