### ISSUE TITLE
Minimize to System Tray

### ISSUE THREAD

**Issue by ChaDMelancia** [Jessecar96/SteamDesktopAuthenticator#63]
Would be great if you could add the option to minimize to System Tray.

**Comment by Aidoboy** [comment]
It would also be cool if it could automatically pop up when needed, but that might not be possible.

**Comment by ChaDMelancia** [comment]
Probably not.

**Comment by ChaDMelancia** [comment]
Ops, I closed untentionaly, I'm new in github.

**Comment by ChaDMelancia** [comment]
Probably not.

**Comment by pipe01** [comment]
Minimizing to task bar is easy, but I'm not sure about the popup.

**Comment by Jessecar96** [comment]
You would have to check the confirmations every few seconds, and if it sees a new one it would popup.

**Comment by pipe01** [comment]
#103

**Comment by Jessecar96** [comment]
Tray icon is added.
