### ISSUE TITLE
Show example maFile for adding account manually.

### ISSUE THREAD

**Issue by meloff** [Jessecar96/SteamDesktopAuthenticator#64]
I have 3 accounts and all already have mobile guard. I want add him to steam desktop authenticator, but i don't know how looks mafile.

**Comment by ChaDMelancia** [comment]
Every info is fake ok.

Manifest.json

{"encrypted":false,"entries":[{"encryption_iv":null,"encryption_salt":null,"filename":"0000000000000000.maFile","steamid":0000000000000000},{"encryption_iv":null,"encryption_salt":null,"filename":"0000000000000000.maFile","steamid":0000000000000000}]}

0000000000000000.maFile

{"shared_secret":"9a87wd89awda897wd90d7=","serial_number":"0000000000000000","revocation_code":"R00000","uri":"otpauth://totp/Steam:nickname?secret=ODWIAJDIOAWJODIJA8DHDODOA&issuer=Steam","server_time":000000000000,"account_name":"nameaccount","token_gid":"jkh42j342jb42jk","identity_secret":"342jk34h2jkl3h4jkl23h4jkl2h3jkl4=","secret_1":"+LJK34KLJ234KLJ234KLJ2I=","status":1,"device_id":"android:K2JL43NJK24NK3JN42KL3JN4KL2JN34JKL2N34","fully_enrolled":true,"Session":{"SessionID":"kljj3n54k3ljn45jkn34jkl5n3jkl4n53jkl4n","SteamLogin":"HJB423K2HK3B42KB32B34HB23B42H3B43B42JK3B42JK3B423JKB42JH34","SteamLoginSecure":"JH23HB4JK23B4233B42KJB434HKB2JKB34JH2B423BH4JK2HB34KJ23BH4K2JBH34","WebCookie":"JKB4H23HK42H42HB342HB3J4H2B3423H4B23JKHB423B42HKB4JH23B423J","OAuthToken":"23b4h23jk4hb2kjb423b4j23hb423b","SteamID":0000000000000000}}

**Comment by pipe01** [comment]
I'm developing a way to import accounts from an Android phone, so you may wanna wait until it's finished.

**Comment by Jessecar96** [comment]
You can't just copy your account data from your phone. You would only be able to get login codes and not trade confirmations. However, the next update adds the ability to import from your Android phone.
