### ISSUE TITLE
i can't confirm my trades

### ISSUE THREAD

**Issue by Mo7TaRiF** [Jessecar96/SteamDesktopAuthenticator#65]
Hi , when i get to confirm trade it appears this massage
![untitled](https://cloud.githubusercontent.com/assets/16272383/11764790/7dc3bdb4-a146-11e5-87ae-47119ae5372c.png)
What should i do please ?

**Comment by hyt47** [comment]
install Visual C++ Redistributable 2013
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by Mo7TaRiF** [comment]
not working

**Comment by Mo7TaRiF** [comment]
Solved Thanks @hyt47 
DirectX is the solution

**Comment by hyt47** [comment]
Good to know `DirectX`
