### ISSUE TITLE
Stuck at Captcha

### ISSUE THREAD

**Issue by CoreNELSON** [Jessecar96/SteamDesktopAuthenticator#66]
Hi, I've downloaded the latest version (0.3.1), I wanted to get my brother's account set up with the desktop authenticator and when I tried to log in, a Captcha window popped up. I've been typing cpatchas after captchas and it just seems like the program won't accept them. I've triple-checked every  captha that pops up, but I can't access the program!

Is there any fix for this?

**Comment by KegonSto** [comment]
Same here Dunno why they decided to use Captcha its a garbage system

**Comment by Jessecar96** [comment]
This is not a support forum. See this issue: https://github.com/geel9/SteamAuth/issues/5
