### ISSUE TITLE
Can't build on linux (Building on linux guide needs an update).

### ISSUE THREAD

**Issue by crsov** [Jessecar96/SteamDesktopAuthenticator#684]
Hi

I am from solus linux

I have mono and monodevelop installed and they works well.

I downloaded, unpacked tar.gz archive and opened .sln file in monodevelop, 
![Снимок экрана от 2021-01-16 20-11-58](https://user-images.githubusercontent.com/54391263/104818201-2c9f1200-5837-11eb-97f9-5e71dfcd4031.png)
i had first error and its ok, but i doesnt see "packages" section in monodevelop interface any where. I have found only update nuget packages button in project>update  nuget packages, i tried to build all after package update, but i had an error.
![Снимок экрана от 2021-01-16 20-17-35](https://user-images.githubusercontent.com/54391263/104818314-e7c7ab00-5837-11eb-810e-ddf326948905.png)

**Comment by tyt34** [comment]
Try...
```
git clone https://github.com/Jessecar96/SteamDesktopAuthenticator
cd SteamDesktopAuthenticator
git submodule update --init --recursive
```

**Comment by crsov** [comment]
Thx
