### ISSUE TITLE
Error regarding logging in

### ISSUE THREAD

**Issue by Loganog** [Jessecar96/SteamDesktopAuthenticator#69]
I saw a new update was available for it (From 2.3 to 3.0) And so I decided to download it but it didn't work due to of course, Me still having the info on 2.3, So I removed the info but it still didn't work, So then I tried deleting the MaFiles for it (Because I thought that's the folder that kept the info so I can just re-sign in for 3.0) and so I thought to myself that it was fine now and so I deleted the older version, Problem is that it still thinks I'm signed in into 2.3 though I tried seeing if I could fix this but couldn't as my info didn't show on 2.3 either and still said I was logged in using one, So I downloaded all the versions to see if any of them worked, But none did.
Any help regarding what I should do?
Thank you.

**Comment by hyt47** [comment]
**if u deleted the `maFiles`:**
- go to Steam > Settings > Manage Steam Guard Account Security > Remove Steam Guard Authenticator

- after that u can create a new Steam Mobile Authenticator (SteamDesktopAuthenticator)

----------

**if u have the `maFiles`:**
- Close the old app SteamDesktopAuthenticator
- Download SteamDesktopAuthenticator v0.3.1
- Extract it
- Copy `maFiles` from old version to v0.3.1
- Done it works

**Comment by Olofmeister420** [comment]
What if you cant login to steam because you don't have the login code?

**Comment by hyt47** [comment]
need more info!
Did u activated SteamDesktopAuthenticator?
Did u take Steam Guard backup codes?
What happened?

**Comment by Jessecar96** [comment]
# DO NOT UNDER ANY CIRCUMSTANCES EVER DELETE THE maFiles FOLDER OR ANYTHING INSIDE IT!

**Doing this will completely lock you out of your Steam account!** If you need to remove your authenticator click the "remove authenticator" button before doing anything!

The only way to recover your account if you deleted the files already is to go [here](https://store.steampowered.com/twofactor/manage) and click "remove authenticator" and enter your recocation code that you wrote down when you first added your account to SDA.

If you did not follow directions and did not write this down, you're well out of luck. The only option is to contact steam support and say you lost your mobile authenticator and the revocation code.
