### ISSUE TITLE
Why not write the revoc. code through the program?

### ISSUE THREAD

**Issue by bartico6** [Jessecar96/SteamDesktopAuthenticator#7]
You could write the revocation code to the disk to a temporary file, and remove it when adding the authenticator succeeds, and if it doesn't - the user will have the revocation code written to a textfile by the program, eliminating the risk of typos while noting off the screen. If the authenticator finalization succeeds, tell the user to copy/write down the auth code from the file and/or remember their passkey, and delete the file. With this in place, you can remove the "input the revocation code to make sure you've written it down" step and just ask if the user wants to continue.

**Comment by Jessecar96** [comment]
I like this idea, will implement.

**Comment by geel9** [comment]
The revocation code is already written to the disk. We just want to ensure you have it stored somewhere else.

**Comment by Jessecar96** [comment]
Yeah geel's right. It's stored in the maFile once it's received. The dialog for them to input it is just to make sure they have it.

**Comment by bartico6** [comment]
Sorry to comment on a closed issue, but the revocation code is not written when you get one of the exceptions from Valve: "UnableToGenerateCorrectCodes". The program then says "write down the code as it's the last chance to see it". why not write it to disk instead? That's what I meant, I know the maFile contains the revocation code. I am thinking about errors, crashes and other stuff - the code should be written as soon as you get it, and deleted when the actual maFile is written.

**Comment by geel9** [comment]
Because if you receive that exception the authenticator isn't actually added to your account. We make sure you have it just in case Steam screws up and adds the account, but the nature of it is that it absolutely should not add the authenticator if that error pops up.
