### ISSUE TITLE
How can i find the revocation code ?

### ISSUE THREAD

**Issue by Chr1s7** [Jessecar96/SteamDesktopAuthenticator#71]
i tried to put a random one but no work where and how can i find it ?

**Comment by hyt47** [comment]
do u have the `maFiles` folder?

**Comment by Chr1s7** [comment]
yes i do have it

**Comment by hyt47** [comment]
- if u added an encription to your SteamDesktopAuthenticator remove it using the button `Manage Encription`

- open the `.maFile` with notepad and find `"revocation_code":`

**Comment by Chr1s7** [comment]
i think i didnt the only think what is working for me is the button 'setup new' acount and i dont see there a 'mange encripion' button

**Comment by hyt47** [comment]
- you opened `manifest.json` file is empty, your account data is not there
- there is a secondary file in that folder `maFiles`?
if not then u don't have it then u don't have Steam data there and u can't recover Revocation code

**Comment by Chr1s7** [comment]
i do not have a second folder in mafiles

**Comment by hyt47** [comment]
your only option is to send a ticket to steam, tell them u lost your Steam Mobile Authenticator and the recocation code.
