### ISSUE TITLE
CefSharp.Core.dll exception (0.3.1)

### ISSUE THREAD

**Issue by AdamWTS** [Jessecar96/SteamDesktopAuthenticator#73]
A new issue doesn't let me enter trade confirmations

System.IO.FileNotFoundException: Cannot load file or library 'CefSharp.Core.dll' or one of its contents. Cannot find specified module.
Filename: 'CefSharp.Core.dll'
   in Steam_Desktop_Authenticator.ConfirmationFormWeb..ctor(SteamGuardAccount steamAccount)
   in Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
I have the CefSharp.Core.dll file in the SDA directory, updating to 0.3.1 did not solve this problem.

**Comment by hyt47** [comment]
Install DirectX if u don't have it intalled https://support.microsoft.com/en-us/kb/179113
Visual C++ Redistributable 2013 (vcredist_x86.exe) https://support.microsoft.com/en-us/kb/179113
