### ISSUE TITLE
Steam Desktop Authenticator, mafiles is encypted

### ISSUE THREAD

**Issue by Kyrama9** [Jessecar96/SteamDesktopAuthenticator#732]
The file of the maFiles account is encrypted and SDA does not see it. There is no information about this account in manifest. SDA can't decode it because he can't see it.  How to decrypt a file?

**Comment by dyc3** [comment]
The salt and IV are stored in the manifest. If that information is missing, then it is not possible to decrypt.

**Comment by guygardner007** [comment]
Unable to remove passkey encryption. I keep getting this unhandled exception has occurred the input is not a valid Base-64 string error and clicking continue opens blank sda with no bot accounts visible. unable to do anything. the encryption is pissing me off i tried to remove it from manage encryption. I entered passkey at first box and clicked blank box accept next 2 times but it does not delete encryption or remove passkey and i am unable to continue and it wont work. please advise. i have win7 64x Service pack 1
