### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by iFantz7E** [Jessecar96/SteamDesktopAuthenticator#75]
Please add an icon to your EXE and Forms.

Thanks.

**Comment by Jessecar96** [comment]
As soon as someone designs one I will

**Comment by hyt47** [comment]
I will do one :)

**Comment by hyt47** [comment]
Icon created https://github.com/hyt47/SteamDesktopAuthenticator-Modded/releases/download/0.2.4.11/SDA-Icon.rar

**Comment by ItsHipsterNoah** [comment]
@hyt47 Unfortunately, the use of the Steam logo isn't allowed. Take a look at this thread on the Scrap.TF forums: https://forum.scrap.tf/topic/6832-steam-desktop-authenticator-suggestion/

**Comment by hyt47** [comment]
ok Thx for info, I will change the icon

**Comment by ItsHipsterNoah** [comment]
@hyt47 No problem! I'll try to come up with something myself as well.

**Comment by hyt47** [comment]
New Icon https://github.com/hyt47/SteamDesktopAuthenticator-Modded/releases/download/0.2.4.11/SDA-Icon.rar

**Comment by ItsHipsterNoah** [comment]
@hyt47 Very cool! I've made a few, they are attached below. Let me know what you think. :smile: 
![sda logo w_ text and credits](https://cloud.githubusercontent.com/assets/13893647/11772107/e4866966-a1cd-11e5-9505-659768df7c2c.png)
![sda logo w_ text](https://cloud.githubusercontent.com/assets/13893647/11772106/e47b298e-a1cd-11e5-900f-f7ec8b40bfef.png)
![sda logo](https://cloud.githubusercontent.com/assets/13893647/11772105/e47af2fc-a1cd-11e5-880a-e67a54de6227.png)

**Comment by Jessecar96** [comment]
Added an icon.
