### ISSUE TITLE
compile x86 version

### ISSUE THREAD

**Issue by bonitos** [Jessecar96/SteamDesktopAuthenticator#76]
HI! Two days ago here was guid how to make x86 app for win xp and it works( compiled successfully ),  but today i can't make new version of SteamDesktopAuthenticator  for XP x86.

**Comment by hyt47** [comment]
U can't make one! The new browser added gives an error on XP.
 I created one for XP by combining 0.2.3 and 0.3.0 (has the old trade list, no browser)
https://github.com/hyt47/SteamDesktopAuthenticator-Modded
