### ISSUE TITLE
Way to solve the ERROR"missing a dependency required to view your trade confirmations."

### ISSUE THREAD

**Issue by joshwongsel** [Jessecar96/SteamDesktopAuthenticator#776]
Comparing the mafiles with other normal accounts' , I find the error account's mafile lack of the "device_id".
Copying the "device_id" from other mafiles to cover the "null" , it fixed.
Notice: the same "device_id" may cause unpredictable problem, so it's better to generate a random device_id with the same rules.

**Comment by joshwongsel** [comment]
Comparing the mafiles with other normal accounts' , I find the error account's mafile lack of the "device_id".
Copying the "device_id" from other mafiles to cover the "null" , it fixed.
Notice: the same "device_id" may cause unpredictable problem, so it's better to generate a random device_id with the same rules.

**Comment by tgptgptgp123** [comment]
I get this error on all my accounts. Also my accounts are not lacking device_id and no "null" ( only null in txt file is in Webcookie)

**Comment by jessecor96** [comment]
Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V

Hope this helps!
