### ISSUE TITLE
QQ Group

### ISSUE THREAD

**Issue by Scholar01** [Jessecar96/SteamDesktopAuthenticator#794]
QQ Group base64 : MzQxODg5Mjc1

Share the new version of 2023 SDA

**Comment by n0099** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/blob/8a408f13ee24f70fffbc409cb0e050e924f4fe94/README.md?plain=1#L11
> WARNING: Recently there have been fake versions of SDA floating around that will steal your Steam account. Never download SDA from any place other than this github repo!
