### ISSUE TITLE
Does not work when adding new accounts

### ISSUE THREAD

**Issue by Obl1Que** [Jessecar96/SteamDesktopAuthenticator#795]
Does not work when adding new accounts.
I'm not the only one with this problem.

![image](https://user-images.githubusercontent.com/98952144/220166941-7c03ace3-7db3-4594-9f59-fc447238abe1.png)

**Comment by thefloridianboy** [comment]
you need to not have the login token in your post lmao

**Comment by EatCakesYoung** [comment]
> you need to not have the login token in your post lmao

What are you talking about? It doesn't matter at all

**Comment by EatCakesYoung** [comment]
> Does not work when adding new accounts. I'm not the only one with this problem.
> 
> ![image](https://user-images.githubusercontent.com/98952144/220166941-7c03ace3-7db3-4594-9f59-fc447238abe1.png)

I have the same problem, I can't add new accounts to the SDA

**Comment by dyc3** [comment]
Sometimes this just happens because Valve's services are flakey. Wait a couple hours and try again.

**Comment by Obl1Que** [comment]
After a couple of hours everything worked out, apparently, the problem is in the Steam servers

**Comment by thefloridianboy** [comment]
> > you need to not have the login token in your post lmao
> 
> What are you talking about? It doesn't matter at all

sorry i was tired when i wrote this i forgot it changes every 30 seconds
