### ISSUE TITLE
error logging in Steam returned General failure

### ISSUE THREAD

**Issue by thecoolguy2330** [Jessecar96/SteamDesktopAuthenticator#796]
I know many people have reported this issue in the past but I have read every single one of those reports and not a single one of the fixes mentioned has ever worked I have restarted my computer multiple times uninstalled and reinstalled steam desktop authenticator multiple times and have re-extracted it multiple times and made sure that I don't have the family mode or whatever on and connected my phone number and a bunch of other fixes I still get this error

**Comment by dyc3** [comment]
This happens because Valve's services are flakey. Wait a couple hours and try again.

**Comment by thecoolguy2330** [comment]
> This happens because Valve's services are flakey. Wait a couple hours and try again.

i have already waited nearly 2 days tho

**Comment by dyc3** [comment]
Yeah, they're just not all that reliable.

**Comment by thecoolguy2330** [comment]
> Yeah, they're just not all that reliable.

okay i will wait then thanks for the reply

**Comment by skuper-6k** [comment]
> > Yeah, they're just not all that reliable.
> 
> okay i will wait then thanks for the reply

Still no solution? Got the same problem(
