### ISSUE TITLE
Keeps asking me to download vscc++2013 when trying to check trades on some accounds

### ISSUE THREAD

**Issue by o0omega** [Jessecar96/SteamDesktopAuthenticator#797]
![image](https://user-images.githubusercontent.com/72322089/221371065-0415a108-6e20-42a1-84b2-5688af275f98.png)
This is 2nd account im getting this issue on, the mafile is working correctly and it can accept trades without any troubles in ASF, but in sda it keeps showing this message when im trying to view the trades, and when i agree it starts downloading visual studio c++ redistributable 2013, and this happens every time, tried to re install it manually, nothing changes. Once again, its only happening on some accounts, and on the first one i already changed the authentificator number and its working now, but like waiting for 1 week to be able to trade isnt the best thing.
![image](https://user-images.githubusercontent.com/72322089/221371169-42f851e9-46da-4bc6-8807-a85357ab1b13.png)

**Comment by jessecor96** [comment]
Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V

Hope this helps!

**Comment by Cody1337** [comment]
Be careful, there is a message from a fake account on top, do not follow its link, it will steal your accounts!

**Comment by jessecor96** [comment]
^ Always make sure you use the official link! https://bit.ly/SDA-1-0-13-V

**Comment by Cody1337** [comment]
Be careful, there is a message from a fake account on top, do not follow its link, it will steal your accounts!

**Comment by Jessecar96** [comment]
You are using an older version of SDA. Please download the latest version.
