### ISSUE TITLE
Refresh Steam Cookies

### ISSUE THREAD

**Issue by Zignixx** [Jessecar96/SteamDesktopAuthenticator#8]
Hey, i got a small problem. If i use the Trade confirmations, i get a error. But only on 2 of 4 accounts. I'm sure its about the Steam Cookie (sessionid, steamlogin and so on). Can you maybe make a function to "relog" into a account to get a new cookie?

Thanks! :+1:

**Comment by geel9** [comment]
The newest version should do this.
