### ISSUE TITLE
Trade Confirmation browser doesn't show "anything"

### ISSUE THREAD

**Issue by kadcspro** [Jessecar96/SteamDesktopAuthenticator#80]
Just like the issue #72 but this time it doesn't show anything even after i confirm my trade offers it would just show a **plain white** window (no need of a screenshot) with a refresh button on top if it.

I'm using Windows 8, have read all the instructions and everything regarding this kind of issue, and even used compatibility mode for win 7 and run it up as an admin... 

So yeah i guess the browser doesn't seem to work for me and don't give me that 7 day unable to trade bs cuz I already set it up and it worked for me well before the browser thing came out! and it even destroyed the old versions showing up unnecessary errors...

**Comment by ItsHipsterNoah** [comment]
I had the same issue. Make sure that SDA is updated to the latest version, and rename the folder to the latest version. Then, restart your PC. 

Hope this helps!

**Comment by kadcspro** [comment]
Unfortunately it didn't work but thank you anyways...

**Comment by ItsHipsterNoah** [comment]
Sorry to hear that. Hopefully Jesse can come up with a solution.

Good luck!

**Comment by hyt47** [comment]
@kadcspro  windows version? do u have DirectX ?

**Comment by kadcspro** [comment]
Yah!

**Comment by hyt47** [comment]
if u want the old trade confirmation list and not the browser use my version

**Comment by kadcspro** [comment]
Thanks! But unfortunately it didn't work...

**Comment by ItsHipsterNoah** [comment]
The old confirmation list is probably less secure, since it doesn't show you what items are in the trade. This can lead to hackers and scammers changing items before the trade is accepted.

**Comment by kadcspro** [comment]
Agreed.

**Comment by kadcspro** [comment]
And I'm getting errors regarding my net framework thing, btw im using the latest version 4.6.1 .net so I'm gonna reinstall it, I don't think it has something to do with my Direct X.

**Comment by hyt47** [comment]
yea it's less secure, but it works
hackers and scammers can't use it because the trade is comfirmed twice:
- if a scammer sends a trade offer taking all your items and u accept using the Authenticator u will need to confirm the trade again in Steam and there u can cancel it

**Comment by kadcspro** [comment]
So any ideas with this one? :

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Steam_Desktop_Authenticator.ConfirmationForm.loadConfirmations(Boolean retry) in f:\Git Hub Projects\SDA 0.3.1.1 Wind 7 Source\Steam Desktop Authenticator\ConfirmationForm.cs:line 81
   at Steam_Desktop_Authenticator.ConfirmationForm..ctor(SteamGuardAccount account) in f:\Git Hub Projects\SDA 0.3.1.1 Wind 7 Source\Steam Desktop Authenticator\ConfirmationForm.cs:line 27
   at Steam_Desktop_Authenticator.MainForm.btnTradeConfirmations_Click(Object sender, EventArgs e) in f:\Git Hub Projects\SDA 0.3.1.1 Wind 7 Source\Steam Desktop Authenticator\MainForm.cs:line 127
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Steam Desktop Authenticator
    Assembly Version: 0.3.1.1
    Win32 Version: 0.3.1.1
    CodeBase: file:///C:/Users/KyleAndrey/Downloads/SDA%200.3.1.1%20Wind%207/Steam%20Desktop%20Authenticator.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/Users/KyleAndrey/Downloads/SDA%200.3.1.1%20Wind%207/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SteamAuth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/KyleAndrey/Downloads/SDA%200.3.1.1%20Wind%207/SteamAuth.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by hyt47** [comment]
i will try to duplicate this error

**Comment by kadcspro** [comment]
windows 8 x64 using 2010 and 2013 x86 one and I've read the instructions so that's pretty much it...

**Comment by Jessecar96** [comment]
I can't duplicate this either.

**Comment by kadcspro** [comment]
Found an uninstaller haven't tried it yet but I do hope this would work!

**Comment by ItsHipsterNoah** [comment]
If a scanner sends you a trade, you confirm it on Steam first, then on the Authenticator, not the other way around. If you can't see the items in the Authenticator, scams are possible. The newest version is much more reliable due to the fact that you can see what items are going to be lost and what will be received.

In terms of the issue at hand, I was experiencing the exact same issue on v0.3.0. The solution for me was to update SDA from version 0.3.0 to 0.3.1. Then, I renamed the folder "SDA 0.3.0" to "SDA 0.3.1." (This probably didn't do anything, but I can't say for sure.) Afterwards, I restarted my PC and attempted the trade again with a bot. I was then able to access the trade confirmation window.

**Comment by ItsHipsterNoah** [comment]
Make sure you deactivate the Authenticator before you uninstall! Otherwise, you have to go to Steam and deactivate it there.

**Comment by kadcspro** [comment]
I don't think it has something to do with the folder name...

**Comment by ItsHipsterNoah** [comment]
Yeah, I didn't think so either. I just wanted to outline exactly what I did :p

**Comment by kadcspro** [comment]
or i could just reinstall it when its fixed and not having to wait for another 7 days to be able to harness its full potential...

**Comment by ItsHipsterNoah** [comment]
If you delete the folder, you simply remove all of the content on your PC. Steam would still think you have the Authenticator enabled with your account. You'd have to deactivate the authenticator first, then delete the folder.

**Comment by kadcspro** [comment]
btw I'm talking about the **.net** uninstaller not how to remove SDA so yah... I know how stuffs work I just need to figure out how to get trade confirmations working not without the help of this Geniuses who spent time putting this app into existence...

**Comment by ItsHipsterNoah** [comment]
Oh, my bad. I realized that you were talking about .NET not SDA at the exact moment you made that comment (lol). 

You can try it, hopefully it'll work!

**Comment by kadcspro** [comment]
I'm still not sure if it's Valve's fault or the careless people getting scammed repeatedly or the scammers themselves...

**Comment by ItsHipsterNoah** [comment]
I'd say all three :P

**Comment by kadcspro** [comment]
we're getting out of the topic, welp I guess I'm gonna have to restart so yeah hope this would work :8ball:

**Comment by ItsHipsterNoah** [comment]
xD yeah, complaining about Volvo or scammers is a little late now.

Good luck!

**Comment by hyt47** [comment]
Tested the program on a clean windows and it works ok
I tested v0.3.1 and my version modded v0.3.1.1

Can't Duplicate error

If i was you, I wood install my windows again
or if u have alot of ram Create a virtual machine with Windows 8 and give it minimum ~ 1.5 GB of ram

**Comment by 808dkaneohe** [comment]
is it possible to install on mac?

 Start Transmission...
Keep Calm and play 0PORTAL0, AND Team Fortress 2
-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
Please Note:
HALF LIFE 3 CONFIRMED!!!! XD
 End Transmission...

**Comment by ItsHipsterNoah** [comment]
@hyt47 Reinstalling Windows seems a little extreme, no? It might be more reasonable to reinstall SDA.

@808dkaneohe Yes, all you need is an emulator. Here's one called "Wine Bottler": http://winebottler.kronenberg.org/

**Comment by 808dkaneohe** [comment]
do you need a disk for it? i do not have an install for windows.

 Start Transmission...
Keep Calm and play 0PORTAL0, AND Team Fortress 2
-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
Please Note:
HALF LIFE 3 CONFIRMED!!!! XD
 End Transmission...

**Comment by hyt47** [comment]
@ItsHipsterNoah if nothing works, and if the user has only a few apps installed, a clean windows may be the fastest way to run the app

me for example I have a lot of apps, if i wood reinstall the windows with all my apps it would take ~ 4-5 hours

but for a regulat user  it would take ~ 1-2 hours

**Comment by ItsHipsterNoah** [comment]
@hyt47 Yeah, but for me, I'd use it only as a last resort.

@808dkaneohe No. Essentially, it turns the .exe file into a .app file a Mac can run. There is no need for a Windows disk or license key.

**Comment by 808dkaneohe** [comment]
oh ok thanks man :) great work!

 Start Transmission...
Keep Calm and play 0PORTAL0, AND Team Fortress 2
-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
Please Note:
HALF LIFE 3 CONFIRMED!!!! XD
 End Transmission...

**Comment by ItsHipsterNoah** [comment]
@808dkaneohe Thank you for the kind comment. Good luck! :smile:

**Comment by kadcspro** [comment]
It didn't work so yeah... Reinstalling windows? have done it several times before i'd rather wait years just to get this thing working than to reinstall windows all over AGAIN.. I'll stick with the browser, and before I go to sleep here's one more thing..

There is something on the debug text file:
**[1215/001343:ERROR:renderer_main.cc(200)] Running without renderer sandbox**
It added that line after I opened up the trade browser, it has something to do with the browser, I googled it up and it looks like I shouldn't be worried but idk... Any ideas?

**Comment by ItsHipsterNoah** [comment]
Hmm...if I were you, I'd remove the authenticator, delete the folder, and activate it again. When I was experiencing problems, I reinstalled the program and it started working again.

**Comment by kadcspro** [comment]
Thank you Mister... :+1: It worked! I guess I just have to revoke it up and install it again so yeah...

Case Closed

**Comment by ItsHipsterNoah** [comment]
Glad to hear! Enjoy :grinning:

**Comment by kadcspro** [comment]
BTW I found out the cause of the Problem... This app is affected by the **Deauthorization** option found within the Steam Guard settings! :-1:
