### ISSUE TITLE
SDA returns general failure when i try to add phone number

### ISSUE THREAD

**Issue by skyline146** [Jessecar96/SteamDesktopAuthenticator#805]
*check title*

**Comment by Rootzi** [comment]
I found the solution! This worked for me and is extremely simple to do.
Navigate to the steam settings and opt into the steam beta. Once you have opted into the beta, log in to your steam account. Now you must click "Login again" on SDA, and enter your credentials. Voila! Problem solved.

Note: You will have to log in to each individual account on both steam and SDA if you choose to fix the issue for multiple accounts.

**Comment by skyline146** [comment]
I found that its easier to add phone number through steam and after that create maFile in SDA. I didn't receive any errors.
