### ISSUE TITLE
Add account when I already have the secret

### ISSUE THREAD

**Issue by gab** [Jessecar96/SteamDesktopAuthenticator#807]
I use Keepass + KeeTrayTOTP to manage my steam TOTP so I already have the secret key. Now I'd like to configure SteamDesktopAuthenticator as well to automate trade confirmations.

How would I go about this? Can I create an maFile manually in plain text perhaps and get SDA to encrypt it later? I'd need some kind of template.

Adding an option for an import where you already recovered the key manually from somewhere would be helpful too if possible.

Thanks!

**Comment by dyc3** [comment]
The JSON schema for maFiles can be derived from the `JsonProperty` attributes in this class: https://github.com/geel9/SteamAuth/blob/96ca6af3eb03d1a45f7fbff78851f055ba47c0d4/SteamAuth/SteamGuardAccount.cs

An sample maFile can be found here: https://github.com/dyc3/steamguard-cli/blob/master/src/fixtures/maFiles/compat/1-account/1234.maFile

**Comment by dyc3** [comment]
You can definitely get the session info from the login process. I don't remember if some of the other stuff is even used at all, like the identity secret.
