### ISSUE TITLE
General Failure upon session refresh and "Login again" FIX.

### ISSUE THREAD

**Issue by Rootzi** [Jessecar96/SteamDesktopAuthenticator#808]
I found the solution! This worked for me and is extremely simple to do.
Navigate to the steam settings and opt into the steam beta. Once you have opted into the beta, log in to your steam account. Now you must click "Login again" on SDA, and enter your credentials. Voila! Problem solved.

Note: You will have to log in to each individual account on both steam and SDA if you choose to fix the issue for multiple accounts.

**Comment by dyc3** [comment]
Note that "opt in to the beta" is equivalent to saying "Valve updated steam, just try again." Thanks for sharing your findings, but to anyone finding this later, I would consider this solution invalid.

Steam's API emits the status codes that result in `GeneralFailure` in SDA extremely often, and seemingly randomly. From my experience, Valve's backend service is just unreliable (at least as it stands right now).

**Comment by Rootzi** [comment]
Did you try it before writing that? I’ve been unable to access confirmations for any of my account for the last week and have attempted to fix the issue via another solution that was posted here to no avail. I’m not familiar with steam’s API by any means but simply opting into the beta solved the issue for me. As stated, an account which you would like to solve the issue must be logged into on steam once opting into the beta so clearly something, somewhere, is happening when the account is logged into on steam beta which fixes the issue I was facing.

It may work for other people like myself and takes little-to-no time to try so I consider this solution feasible with no harm in trying if anyone else reading this is facing the same issue.

**Comment by dyc3** [comment]
> Did you try it before writing that?

No. I've never had a problem accessing my confirmations.  I wrote my response for people finding this issue, potentially in search results in the future. Again, sharing your experience helps people like me narrow down these issues. But to call it "the solution" may be misleading 3 months from now. I'm sorry if you feel that diminishes your contribution, that was not my intention.
