### ISSUE TITLE
Authenticator Deletes(?) self after update

### ISSUE THREAD

**Issue by optilex42** [Jessecar96/SteamDesktopAuthenticator#81]
I've attempted to update to 0.3.1 version.
All files successfully replace the older files with the exception of the app itself.  It either disappears or won't run when double clicked.
Right clicking the app (when present) causes the file browser to become unresponsive
maFiles are fine.
I've tried downloading 0.2.3 (my original copy) and get the same results.
I've changed the Steam Guard to receive codes via email.  Could this be the problem?  Doubtful, as my issue seems to be finding/running the app itself.
I run 64 bit Windows 7
It worked fine at first until the update attempt

**Comment by Jessecar96** [comment]
This seems to be a problem with your OS
