### ISSUE TITLE
Need hot fix. Can't  authenticate after session expires.

### ISSUE THREAD

**Issue by pythhon1c** [Jessecar96/SteamDesktopAuthenticator#818]
Old Steam Authentication method no longer works. If your authenticator session expires you will no longer be able to authenticate.

**Comment by Pincher228** [comment]
Author didn't support SDA for 3 years, so it's low chance that it would be hot fixed :(

**Comment by MakcStudio** [comment]
And what kind of support do you expect when everything works without problems?) 

I think the guys will fix it in a couple of days and everything will be fine. It's a 5 minute job, just remove the oauth token processing and cut out the session refresh button

**Comment by sergssnorth** [comment]
The author could potentially die from a cavid, if this happened, who will fix it, smart guy?

> And what kind of support do you expect when everything works without problems?)
> 
> I think the guys will fix it in a couple of days and everything will be fine. It's a 5 minute job, just remove the oauth token processing and cut out the session refresh button

**Comment by sens0rer** [comment]
How old are you?
> The author could potentially die from a cavid, if this happened, who will fix it, smart guy?

**Comment by Jessecar96** [comment]
A new release has been published to fix this issue.
