### ISSUE TITLE
'Error adding your phone number. Steam returned GeneralFailure

### ISSUE THREAD

**Issue by PatrykSprus** [Jessecar96/SteamDesktopAuthenticator#823]
Hello, in the new version of SDA, after entering the phone number and authorization code from the email, an error occurs saying 'Error adding your phone number. Steam returned GeneralFailure.' I tested it on three different Steam accounts, and the same problem occurs on each one.

**Comment by wbafy** [comment]
The developer did not write that he fixed the addition of a new authenticator, he only fixed the relogin. Waiting for a normal fix)
