### ISSUE TITLE
Asking to login again every ~15 seconds

### ISSUE THREAD

**Issue by NemesisPrime696** [Jessecar96/SteamDesktopAuthenticator#824]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/129512700/c9c55b5f-b6d0-4bf0-bd81-81d41f221f26)

This started happening after the update. Every time I enter the password, it tells me that the session has been successfully refreshed and after ~15 seconds this window appears and everything repeats again. If I ignore this window, confirmations no longer apply after about 2-3 hours. I do not know, but I dare to assume that this partially (if not completely) breaks the whole point of SDA in my opinion.
I do not see any issues opened here like this. Am I alone with this? Is it normal?

**Comment by Vadim-Karpenko** [comment]
Same but in my case it stops accepting new listings until you login again. This means I have to constantly re-log every time I want to sell something. which led to a "GeneralFailure" error due to too many login attempts being made.

**Comment by NemesisPrime696** [comment]
It turns out that the SDA remains broken in this state. Either steam microbans for the number of login attempts, or confirmations fall off literally within an hour or two at best.

**Comment by h4cyy** [comment]
Same, we really need a fix of this problem, because steam account becomes impossible to use...

**Comment by AndyMutz2** [comment]
have the same issue with the new version.
I am using SDA for two Steam accounts.

**Comment by NemesisPrime696** [comment]
Only workaround I found for me is just download 1.10 in different folder, run 1.11, login on my accounts, then drop mafiles into 1.10 folder. Run 1.10 and it's works.. don't know for how long.

**Comment by surenjay89** [comment]
Opting in to the Steam beta seems to have fixed this for me. Was having to login every 1 minute but now it's been 1-2 hours without having to login and trade confirmations have been working well. For anyone that wants to give it a try:

Steam > Settings > Interface > Client Beta Participation > Steam Beta Update 
Then login again on SDA and it "should" be good?

**Comment by surenjay89** [comment]
Having the same problem as well. Everything was fine when I was using the previous version. As soon as I updated after getting the prompt. I'm having to login and enter my encryption password every 1-2 minutes. Not too sure how to fix this.

**Comment by isenlebi** [comment]
LIKEWISE
