### ISSUE TITLE
1.0.11 no Login possible

### ISSUE THREAD

**Issue by chriscross89tv** [Jessecar96/SteamDesktopAuthenticator#826]
after updating i cant refresh logins on any account.

**Comment by arynyklas** [comment]
Same

**Comment by hnatyuk** [comment]
Same

**Comment by semenzhir** [comment]
does not work
(http://prntscr.com/7FIGM4DfD2YK)

**Comment by chriscross89tv** [comment]
> 

Downgrade to 1.0.10 just Download and Copy files  from the old version in the Folder, it works again after Downgrading

**Comment by saintlucifer1075** [comment]
done all the shit (downgrading and trying vpn and others still give errorr for openning confirmation page and ask to relogin and when i want to do so it gives general failure error)
