### ISSUE TITLE
Fail to add authenticator

### ISSUE THREAD

**Issue by Zachxz0** [Jessecar96/SteamDesktopAuthenticator#829]
/ITwoFactorService/AddAuthenticator/v0001 report HTTP 401

**Comment by WabiSabikk** [comment]
> 

resolve?

**Comment by Zachxz0** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/blob/353156008391f8474212681e381c275a81dacd57/components/twofactor.js#L19
@WabiSabikk
