### ISSUE TITLE
Trade Conformation Menu Error

### ISSUE THREAD

**Issue by 2000jbm** [Jessecar96/SteamDesktopAuthenticator#83]
When I click on the "Trade Conformation" Button, This error pops up (Attachment).

![sde-bug](https://cloud.githubusercontent.com/assets/16295183/11792488/6e4a7b34-a24a-11e5-952a-659a0cd3677d.JPG)

**Comment by hyt47** [comment]
install  Visual C++ Redistributable 2013 (vcredist_x86.exe)
https://www.microsoft.com/en-us/download/details.aspx?id=40784
