### ISSUE TITLE
Paid Version of the Program

### ISSUE THREAD

**Issue by JameyDurst578** [Jessecar96/SteamDesktopAuthenticator#830]
Hello. The recent issues have bothered me so much. I strongly need the update for this application to work in the latest Steam version. I have over 500+ accounts being controlled in SDA, and there's no other way to do it. 
I suggest you could make a paid version of the program, so that people can keep using it and you would earn too. 
Thanks.

**Comment by engy8561** [comment]
then why using paid authenicator while u can use mobile authenicator

**Comment by Sv1at0slav** [comment]
> Привет. Недавние проблемы очень беспокоили меня. Мне очень нужно обновление, чтобы это приложение работало в последней версии Steam. У меня более 500 учетных записей, которые контролируются в SDA, и нет другого способа сделать это. Я предлагаю вам сделать платную версию программы, чтобы люди могли продолжать использовать ее, и вы тоже зарабатывали. Спасибо.

hi, my acquaintances have started to write an alternative to the SDA. They promise to write it in one week. But I think Jesse will update SDA for free and everything will be fine

**Comment by JkktBkkt** [comment]
> then why using paid authenicator while u can use mobile authenicator

because there are people who use steam market for profit, and this allows automating
