### ISSUE TITLE
[Last update problem] Error adding your phone number. Steam returned "GeneralFailure"

### ISSUE THREAD

**Issue by DJMarkus1337** [Jessecar96/SteamDesktopAuthenticator#833]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/80347162/2f7cffbc-06a5-4e2f-ba84-99bcd6a1b0cf)

**Comment by MarkCX1** [comment]
Having the same issue, seems to be due to the new steam UI update

**Comment by Majestik56** [comment]
I also have this problem what to do ?

**Comment by joernottohansen** [comment]
Same problem here

**Comment by Majestik56** [comment]
is there any way to fix this people ?

**Comment by Aiicoe** [comment]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/136774629/effd2f2e-6a55-40bd-87e5-f43d6edee100)
@winauth @Jessecar96
