### ISSUE TITLE
why mark as virus?

### ISSUE THREAD

**Issue by offnight** [Jessecar96/SteamDesktopAuthenticator#834]
I've recently noticed that the new version of SDA  is marked with three different anti-virus software detections. Can anyone shed some light on why this is happening? I would appreciate any insights or information regarding this matter.
![brave_V8WzgQrpOl](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/88465852/7348060c-3baf-46f2-bc09-59a30313636e)

**Comment by dyc3** [comment]
If you got it from the releases page, it's likely marked by these vendors because it's new software, and they haven't updated their definitions yet.

**Comment by wbafy** [comment]
3 noname antivirus said it was a virus. They will consider any program for a virus, they found someone to trust ...

**Comment by Txreq** [comment]
fp
