### ISSUE TITLE
Phone number issue (even with phone number)

### ISSUE THREAD

**Issue by Naleksuh** [Jessecar96/SteamDesktopAuthenticator#835]
Just here to confirm I see what everyone else is seeing-- I can't add accounts to SDA because it failed to add a phone number with code "GeneralFailure".

The weird thing is, I already have a phone number. So I don't know why it's trying to add one. @Jessecar96 Is this related to the recent update?

**Comment by Shark191** [comment]
Same problem.

I have account with already confirmed phone number. But have same error...
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/57893325/8001a78d-0207-4454-ae18-b8e583dcc2cd)

**Comment by MarkCX1** [comment]
The program is not going to work for now, wait for a patch.

**Comment by Naleksuh** [comment]
Yes, I understand that. I was simply noting that this continues to occur even with a phone number, and I tagged @Jessecar96 as maintainer of this repo and wait for her to update it. There is no need to post further until then.

**Comment by Zymlex** [comment]
Same problem.

**Comment by soloplayer90** [comment]
same issue

**Comment by jowash1337** [comment]
Same problem for me as well

**Comment by Naleksuh** [comment]
Yes, I understand that. I was simply noting that this continues to occur even with a phone number, and I tagged @Jessecar96 as maintainer of this repo and wait for her to update it. **_There is no need to post further until then._**

**Comment by sevcator** [comment]
same

**Comment by abasha1** [comment]
guys lets donate to this great project to thr @Jessecar96 , thank you bro for a nice job
