### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by Aiicoe** [Jessecar96/SteamDesktopAuthenticator#837]
@winauth @Jessecar96 Where i can write winauth support? I can't event logging in into my account to confirm the trade it says An error occurred while loading trades. The remote server returned an error: (429) Too Many Requests. please help me to fix this

**Comment by Aiicoe** [comment]
@winauth @Jessecar96  Please fix this problem

**Comment by dyc3** [comment]
429 Literally means you are making too many requests. You need to wait a while before trying again.

**Comment by Aiicoe** [comment]
it's been 2 days and i can't still login to confirmations

**Comment by Aiicoe** [comment]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/136774629/fa22606e-2600-4313-b8ca-502a29272f7d)

**Comment by Aiicoe** [comment]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/136774629/1b8c4ffb-10be-4cd9-b8e0-8fd69261fde6)

**Comment by Aiicoe** [comment]
@winauth @Jessecar96

**Comment by Aiicoe** [comment]
> 429 Literally means you are making too many requests. You need to wait a while before trying again.

How can I write to winauth support?

**Comment by txporm0427** [comment]
Need a fix by jessecar

**Comment by Aiicoe** [comment]
> Need a fix by jessecar

Can I talk to @Jessecar96?

**Comment by Aiicoe** [comment]
or write to him

**Comment by ImBatou** [comment]
> or write to him

Stop spamming this is embarrassing, just wait and if you need it fast, try to find someone to do it for you, but github issue is not used to just spam the creator of projects.
This is done by someone alone on his free time.

**Comment by Sekret0** [comment]
I have the same issue.
For the last few weeks, I haven't been able to add other accounts to the app, now I can't confirm anything anymore

**Comment by Areezaxx** [comment]
still not working
