### ISSUE TITLE
New Update 1.0.11(Error-Re-login )

### ISSUE THREAD

**Issue by K-M19** [Jessecar96/SteamDesktopAuthenticator#838]
I don't know why this new version seems to have a little problem it always asks me to re-login all the accounts in my ''maFiles'' I have a total of 7 accounts and it just keeps asking asked me to re-login all of those accounts I did as requested but then it asked me to re-login I was a bit surprised, so I left it alone for 5 minutes to see what would happen and then 5 minutes there are more than 30 Notification asking me to re-login those 7 accounts, I tried deleting and re-downloading 3 times but the error didn't go away I think 1.0.10 is still the stable version. .

**Comment by evil-pechenka** [comment]
Yes, same here, I can't use 1.0.11, it keeps prompting for authentication endlessly.
![2023-06-20_07-11-15-%t](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/109512933/d03e06fb-31f2-4db1-a873-8b24f99dcfa0)

**Comment by surenjay89** [comment]
Same problem for me, but when I go back to the older version, that doesn't work smoothly as well. I'm able to accept a few trades before i stop receiving trade confirmations all together. Is the older version working smoothly for you guys?
