### ISSUE TITLE
"GeneralFailure" - Adding a new phone number

### ISSUE THREAD

**Issue by jowash1337** [Jessecar96/SteamDesktopAuthenticator#839]
Hello, I can't add accounts to SDA because it failed to add a phone number because of: Error "GeneralFailure"

**Comment by Moonb1ade** [comment]
> Hello, I can't add accounts to SDA because it failed to add a phone number because of: Error "GeneralFailure"

relax, you're not the only one with this problem. waiting for it to be fixed. I check the site every day.

**Comment by karlmeyer79** [comment]
> > Hello, I can't add accounts to SDA because it failed to add a phone number because of: Error "GeneralFailure"
> 
> relax, you're not the only one with this problem. waiting for it to be fixed. I check the site every day.

What are the chances of an update?

**Comment by Aiicoe** [comment]
same problem here I also have problem sda and winauth

**Comment by Majestik56** [comment]
Yes, I have the same problem, waiting for the update

**Comment by Joanpixer** [comment]
Same
