### ISSUE TITLE
Can't go to trade conformations

### ISSUE THREAD

**Issue by END44** [Jessecar96/SteamDesktopAuthenticator#84]
whenever I go to trade conformations I get this eror- http://i.imgur.com/au3pO2C.png
any help?
is this the same error as https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/83 ?

**Comment by hyt47** [comment]
you are using windows xp ?

**Comment by END44** [comment]
I'm using windows 7 with classic theme.

**Comment by hyt47** [comment]
your SteamDesktopAuthenticator is old try version 0.3.1

if u don't want the browser and u want the old trading list like in the version from your picture use my Modded version 0.3.1.1 https://github.com/hyt47/SteamDesktopAuthenticator-Modded

a lot of stuff have been fixed in these new versions

see if u get the same error

**Comment by END44** [comment]
Just to be safe, how do I update it without getting a 7 day no trading time?

**Comment by hyt47** [comment]
Updating:
------
- Create a New Folder
- Extract the new version inside it
- copy maFiles from your old program to this new one
- Run the new version of Steam Desktop Authenticator.exe and test if u see your accounts
- Arhive the old program and keep it as a backup
- Move the new version where u want

**I olso did archive the `maFiles ` and i placed them somewhere safe as a backup**

**Comment by END44** [comment]
I'll give that a try when I get on my desktop, thanks :)

**Comment by hyt47** [comment]
I'm glad I could help! ^_^

**Comment by ItsHipsterNoah** [comment]
Follow these instructions and try I again:

•Download & Install DirectX if you don't have it installed.
•Download & Install Visual C++ Redistributable 2013 (vcredist_x86.exe) from the Microsoft website if you don't have it already.
•Download & Install .NET Framework 4.5.2 from the Microsoft website if you're using Windows 7. Windows 8 and above should do this automatically for you.

**Comment by END44** [comment]
I did what you said hyt47 and now I'm getting the same error you posted a solution for on the linked thread, thanks. :)

**Comment by Rachevsky** [comment]
I have this error after change password on acc. It's because of the peculiarities of the program?

**Comment by hyt47** [comment]
if u added an accout to SteamDesktopAuthenticator and after that u changed the steam password ?
**Don't give wour maFiles to anyone!!!**

**Comment by Rachevsky** [comment]
No, i changing password after added in sda. It's test acc, i dont value them.

**Comment by hyt47** [comment]
check if u have all the programs you need to run the app, if it doesn't work, try my mooded app https://github.com/hyt47/SteamDesktopAuthenticator-Modded

**Comment by ItsHipsterNoah** [comment]
Does the test account have any purchases on it? That may be the source of the problem.

**Comment by hyt47** [comment]
I used this app on a new steam account with no purchases and it worked fine

**Comment by Rachevsky** [comment]
yep, i know, on my acc it worked fine to change the password on acc. i use your app and i install all programs in your topic. with others acc all good, problem just on this acc.

**Comment by hyt47** [comment]
Can you remove your "account with problems" using your revocation code ?

Maybe if u re add this account it would work...

**Comment by Rachevsky** [comment]
i can, but i thought that this account can help coder in solving the error

**Comment by Jessecar96** [comment]
This is not a support forum.
