### ISSUE TITLE
An error occurred while loading trades. The remote server returned an error: (429) Too Many Requests.

### ISSUE THREAD

**Issue by Aiicoe** [Jessecar96/SteamDesktopAuthenticator#840]
@winauth @Jessecar96 please fix it

**Comment by Aiicoe** [comment]
> Please change your ip.Your IP has been blacklisted. Or use proxy

How please help me

**Comment by Aiicoe** [comment]
> Please change your ip.Your IP has been blacklisted. Or use proxy

I already change my IP but still get the same thing :(

**Comment by txporm0427** [comment]
Use proxy.

**Comment by txporm0427** [comment]
dont add new account...................................................There is a bug.

**Comment by Aiicoe** [comment]
idk what to do

**Comment by Aiicoe** [comment]
> dont add new account...................................................There is a bug.

is that winauth or sda?

**Comment by txporm0427** [comment]
Old SDA can use...... New account bye bye.

**Comment by Aiicoe** [comment]
> Old SDA can use...... New account bye bye.

I'm using sda and winauth

**Comment by Aiicoe** [comment]
I have problem in winauth

**Comment by hyundacao** [comment]
> ![image](https://user-images.githubusercontent.com/136774629/246766257-e659b676-be8d-4813-86d9-750dff6baabf.png) ![image](https://user-images.githubusercontent.com/136774629/246766304-bf8c8ecd-1160-41b8-9d90-4f263b95618d.png)

I have it same problem in winauth

**Comment by abasha1** [comment]
guys did you fixed this problem ? @Aiicoe @hyundacao

**Comment by hyundacao** [comment]
> 

no, not working still

**Comment by Aiicoe** [comment]
> guys did you fixed this problem ? @Aiicoe @hyundacao

still not working

**Comment by chucky515** [comment]
same problem 

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/8881074/ddf84675-de30-44cb-ba44-310682216289)

**Comment by foloko** [comment]
I have the same problem and I think it happens since the last steam update
i think its problem with api of steam, maybe we need a new version

**Comment by SoulxSlayer** [comment]
same issue. i have around 1k confirmations pending.

**Comment by Kenichimiu** [comment]
i have the same problem, i cant trade with my accounts :c

**Comment by foloko** [comment]
is there any other alternative to winauth??
