### ISSUE TITLE
Migration to .NET - Cross Platform

### ISSUE THREAD

**Issue by cherinyy** [Jessecar96/SteamDesktopAuthenticator#842]
Hello,

This may be too much to ask, but I wonder if it would be possible to migrate Steam Desktop Authenticator to .NET? This would seem to create cross-platform application.

**Comment by Jessecar96** [comment]
This project is currently written in .NET Framework. Migration to .NET 6 would be nice, but the main thing holding that back is we would have to re-write all the WinForms code into a cross platform UI framework.

**Comment by cherinyy** [comment]
I'm happy and sad to see you finish the transplant.

Good luck to everyone getting better and better!
