### ISSUE TITLE
cant open confirmations

### ISSUE THREAD

**Issue by abasha1** [Jessecar96/SteamDesktopAuthenticator#843]
Firstly, I want to express my immense gratitude to jessecar. I truly appreciate all the hard work that's been put into this fantastic project. It's been an invaluable help to us. I encourage everyone to consider making a donation to support their efforts.

I'm currently experiencing an issue, though: while the guard code is functioning flawlessly, I'm unable to access confirmations. Any assistance with this would be greatly appreciated.
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/51801315/6004d2a3-e193-42a8-8cf9-f68317c86231)
thank you brother. @Jessecar96

**Comment by abasha1** [comment]
and how can i import from winauth account to desktop authenticator?

**Comment by dyc3** [comment]
Winauth is not related to this project, and hasn't been actively maintained for years.

SDA is broken right now when it comes to confirmations. Steam changed their login process, so SDA can't log in right now. This hasn't changed how 2fa codes are generated, so you're not locked out of your steam account.

Go use the steam mobile app.

**Comment by dyc3** [comment]
You can sign in to multiple accounts.

**Comment by jowash1337** [comment]
Yes I understand, but I need different phone number for each account... that's why without SDA is not possible I guess @dyc3

**Comment by abasha1** [comment]
here is not any chance to confirm trade? i have attached phone number which is not active, also i cannt change steam guard to another phone , is here any option ?

**Comment by abasha1** [comment]
@dyc3  Could you vouch me how confirm trade? i dont have phone number which i have attached to account also, this mean i cannt change phone number, please vouch me something so its meaning sda will not work   for steam ?

**Comment by abasha1** [comment]
and one more question is here any way to export winauth account and imports in sda? winauth export giving us .txt file and sda need mafile could you vouch me something? thank you bro @dyc3

**Comment by dyc3** [comment]
I have no idea what you mean by vouch. You should probably go talk to steam support.

**Comment by abasha1** [comment]
@dyc3 thank you for answering and you mean that sda will not be longer avaliable to use as authenticator for steam? And if you know can i import in android from winauth?

**Comment by dyc3** [comment]
I would not rely on SDA anymore, it's very unlikely for it to be fixed. No, you can't import 2fa secrets into the android app, nor export them to PC. I have no idea what winauth does, you could try renaming the exported `.txt` to a `.maFile`.

**Comment by abasha1** [comment]
i tried but it does not working after i cant import because i am getting error not valid .maFile, anyone has any idea? @Jessecar96 come on bro please help us :D

**Comment by Kurotaku-sama** [comment]
I highly doubt that this will not be fixed.

But I can recommend you to try out ArchiSteamFarm, its a Card Bot where you can manage multiple Accounts, redeem Keys, get 2 Factor Code, accept/deny all Trades at the same time (not individual afaik).

And the developer is very active so even if SDA wont work anymore bcs its not maintained anymore, Archi will implement a fix in his Programm.

**Comment by SeriousSam0** [comment]
> Yes I understand, but I need different phone number for each account... that's why without SDA is not possible I guess @dyc3

actually u can use same number for multiple accounts its just that if u are caught doing something really bad or get vac banned one acct all suffer. if you are clean no worries
