### ISSUE TITLE
Session expires frequently after the newest update

### ISSUE THREAD

**Issue by xiaoxunlong** [Jessecar96/SteamDesktopAuthenticator#847]
I have to login again every time I use the newest version of SDA. However, the old version would not occur this so frequently. I guess it might because session expire?

**Comment by NemesisPrime696** [comment]
You are little late with that. Right now SDA is dead and all it can do is give you 2fa codes.

**Comment by cupnooodle** [comment]
> You are little late with that. Right now SDA is dead and all it can do is give you 2fa codes. Literally everything automated in steam community is dead right now, all side markets, bots, everything. You can't even trade now, confirmations is not working.

Ooh, thanks! Any source on this?

**Comment by TopDogger1** [comment]
> > You are little late with that. Right now SDA is dead and all it can do is give you 2fa codes. Literally everything automated in steam community is dead right now, all side markets, bots, everything. You can't even trade now, confirmations is not working.
> 
> Ooh, thanks! Any source on this?

paying attention

**Comment by brndto** [comment]
> > > You are little late with that. Right now SDA is dead and all it can do is give you 2fa codes. Literally everything automated in steam community is dead right now, all side markets, bots, everything. You can't even trade now, confirmations is not working.
> > 
> > 
> > Ooh, thanks! Any source on this?
> 
> paying attention

eat my shorts mr duper admin
