### ISSUE TITLE
Unhandled exception has occurred in your application!

### ISSUE THREAD

**Issue by Nychtsipher** [Jessecar96/SteamDesktopAuthenticator#849]
Trying to add an account, after entering the credentials and geting the code, when I enter the code I received via mail, I always get this error (all the time)
is it on my end? or SDA? or Steam? any sugestions or solutions?
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/137279145/a662b981-b974-406b-a08c-b85dacd93ff2)

**Comment by FollowGT** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/844
