### ISSUE TITLE
Remove Authenticator doesn't work

### ISSUE THREAD

**Issue by danielzss** [Jessecar96/SteamDesktopAuthenticator#85]
I pressed the remove authenticator button and typed in the code. It said maFile will be deleted and stuff but when I try to set up a new account it says "this account already has an autheticator(something like this). I have my maFile folder saved. I think that removing authenticator and reapplying it would fix my  login token problem (in my other thread). I really need help

**Comment by ItsHipsterNoah** [comment]
Hi,

Here's how to remove the authenticator:

1. Go to this link: https://store.steampowered.com/twofactor/manage
2. Click on "Remove Authenticator."
3. Follow the steps to remove the authenticator.
4. Reinstall SDA and add it to your account.
