### ISSUE TITLE
Steam Desktop Authenticator: Cant accept trades before re-login

### ISSUE THREAD

**Issue by Awoladi** [Jessecar96/SteamDesktopAuthenticator#850]
Since this monday I have an issue with the Authenitcator. I want to trade some skins from csgo of my 2nd acc to my main, but every time I want to accept the trade it doesnt show up in first place. So i tried the auto confirm, but still every time it tries to "accept" the trade, it has to re-login and even after I login it replies with "GeneralFailure". I tried VPN but still no positiv result.

Thanks in advance!

**Comment by ThePro323** [comment]
same issue here prob from the steam update or just sda not being taken care of looking for alternatives

**Comment by Andrew3019** [comment]
#844

**Comment by Aiicoe** [comment]
Same issue here I also have problem in winauth I can't sign in to confirmation to confirm the trade @Jessecar96 help us and fix the problem @winauth

**Comment by Fulgur3** [comment]
similar problem, after pressing button "view confirmations" i can't see any trade, but there is definitely at least one

**Comment by MakcStudio** [comment]
Use this fix: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859
