### ISSUE TITLE
Press the button "View Confirmation" - see white blank page

### ISSUE THREAD

**Issue by darioq303** [Jessecar96/SteamDesktopAuthenticator#851]
The new version worked yesterday. But from today, when you click the View Confirmation button, an empty window appears with a white background (blank page).  And, accordingly, I can not confirm the exchanges. Is this a problem on the Steam side or an issue in the app?
[debug.log](https://github.com/Jessecar96/SteamDesktopAuthenticator/files/11816845/debug.log)
SDA 1.0.11

**Comment by ThePro323** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/844
