### ISSUE TITLE
SDA 1.0.11

### ISSUE THREAD

**Issue by 777HuMMeR777** [Jessecar96/SteamDesktopAuthenticator#853]
A couple of hours ago, I updated sda to a new version, since it became impossible to confirm trades on the old one, but on this version, when I try to create a trade, I get a white window and a password request from the side, after entering I get either a confirmation that that the password has been changed or the error "Error logging in: Steam returned "GeneralFailure"", but the result is the same when trying to create a trade, a white window pops up and a request to enter a password. Please, help

**Comment by sagve** [comment]
#844

**Comment by dyc3** [comment]
You should not rely on SDA anymore. It's not being actively maintained. Go use the steam mobile app.

Steam has changed it's login mechanism, and SDA has not implemented it. You can still generate 2fa codes, so you are not locked out of your account, but you can't accept trade confirmations.

**Comment by 777HuMMeR777** [comment]
@dyc3 I now need to transfer all accounts from sda to the phone? Can this be done without spending 15 days?

**Comment by dyc3** [comment]
Yes, there is a method to transfer your authenticator to your phone, and it doesn't incur a 15 day trade ban.

**Comment by 777HuMMeR777** [comment]
@dyc3 how can I transfer accounts if for this you need to enter the code from the message, but the code does not come to sda

**Comment by dyc3** [comment]
If you took a minute to look at the screen of your phone and read the text on it, you would see that it says "Enter the code we sent to your phone"

**Comment by LORD47** [comment]
> @dyc3 I now need to transfer all accounts from sda to the phone? Can this be done without spending 15 days?

I just did it and you only get 2 days Trade Hold when you transfer your account(s) from SDA to the Steam app as mentioned on Steam support page secion: [Can I transfer my authenticator to my new phone?](https://help.steampowered.com/en/faqs/view/7EFD-3CAE-64D3-1C31#transfer)

**Comment by dyc3** [comment]
Ah, my bad, I didn't look at that page.

**Comment by dyc3** [comment]
Not yet, but I'm actively working on an update that fixes steamguard-cli: https://github.com/dyc3/steamguard-cli/pull/194

**Comment by dyc3** [comment]
I have finished updating steamguard-cli, and have published a new release: https://github.com/dyc3/steamguard-cli/releases
