### ISSUE TITLE
Trade Confirmations not working

### ISSUE THREAD

**Issue by OnDroo** [Jessecar96/SteamDesktopAuthenticator#855]
Hello,

my trade confirmations are not working. The window is just white.
This is debug.log : 
[0621/205402.255:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
[0621/205402.255:ERROR:main_delegate.cc(683)] Could not load locale pak for en-US
[0621/205402.267:ERROR:main_delegate.cc(725)] Could not load cef_extensions.pak
[0621/205402.283:WARNING:resource_bundle.cc(563)] locale resources are not loaded

I tried logging in again did not help. 

This happened after I update from version 1.0.10 to 1.0.11. Now neither one is working for me.

Thanks for your help.

**Comment by OnDroo** [comment]
Ok now there is also problem with logging in. I'll give it a day and try it again tomorrow.

**Comment by dyc3** [comment]
You should not rely on SDA anymore. It's not being actively maintained. Go use the steam mobile app.

Steam has changed it's login mechanism, and SDA has not implemented it. You can still generate 2fa codes, so you are not locked out of your account, but you can't accept trade confirmations.

There is a method to transfer your authenticator to your phone, and it doesn't incur a 15 day trade ban. The app prompts you for it when you try to add an authenticator. This process will send you a text message with a code, so you need to have a phone number that you can receive SMS with.

If you don't have access to the phone number linked to your account anymore, you need to contact steam support.

**Comment by subaric** [comment]
Temporary fix for white confirmation page
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/854

**Comment by wbafy** [comment]
> You should not rely on SDA anymore. It's not being actively maintained. Go use the steam mobile app.
> 
> Steam has changed it's login mechanism, and SDA has not implemented it. You can still generate 2fa codes, so you are not locked out of your account, but you can't accept trade confirmations.
> 
> There is a method to transfer your authenticator to your phone, and it doesn't incur a 15 day trade ban. The app prompts you for it when you try to add an authenticator. This process will send you a text message with a code, so you need to have a phone number that you can receive SMS with.
> 
> If you don't have access to the phone number linked to your account anymore, you need to contact steam support.

You can already shut up, no matter what topic you read, you write the same thing everywhere. If a person needs it, he will use it, what difference does it make to you?

**Comment by bekesibeni** [comment]
> You should not rely on SDA anymore. It's not being actively maintained. Go use the steam mobile app.
> 
> Steam has changed it's login mechanism, and SDA has not implemented it. You can still generate 2fa codes, so you are not locked out of your account, but you can't accept trade confirmations.
> 
> There is a method to transfer your authenticator to your phone, and it doesn't incur a 15 day trade ban. The app prompts you for it when you try to add an authenticator. This process will send you a text message with a code, so you need to have a phone number that you can receive SMS with.
> 
> If you don't have access to the phone number linked to your account anymore, you need to contact steam support.

who tf asked fucking braindead

**Comment by SeriousSam0** [comment]
> Temporary fix for white confirmation page #854

The folder is corrupt wonte extract

**Comment by slavunya** [comment]
> Temporary fix for white confirmation page #854

did you test it?
