### ISSUE TITLE
Login returns a html response instead of json

### ISSUE THREAD

**Issue by lorppijw** [Jessecar96/SteamDesktopAuthenticator#856]
The login fails because the response is in html instead of json for some reason
Here's how to replicate it: https://streamable.com/w4luk5

**Comment by wbafy** [comment]
Can you upload the html?

**Comment by dyc3** [comment]
This is likely related to https://github.com/geel9/SteamAuth/issues/95

**Comment by cokoqu** [comment]
im not doing any coding, script, c+, or anything about it, so i have no idea about the step that u post here. is there any video that slowly step by step? the link that u post look like a video but i can play it idont know why
