### ISSUE TITLE
Trade Confirmations not working

### ISSUE THREAD

**Issue by DOTBU** [Jessecar96/SteamDesktopAuthenticator#857]
Can someone help on how to fix this issue

**Comment by bolexator** [comment]
This is something on the Steam's side, in SDA47 also does not work.

**Comment by slavunya** [comment]
seems no, until the @Jessecar96 will fix it

**Comment by halamadridbero7** [comment]
@slavunya just download zip and run it [https://github.com/auwaho/winauth/releases/tag/3.6.2f](https://github.com/auwaho/winauth/releases/tag/3.6.2f?fbclid=IwAR3t_Aj5CvK2vhBfnTNz0l8zXeOs7_anJhTjfwXB_XAN41MJINuRVw2fng0)

**Comment by kayhanozcakici** [comment]
probably valve never stepback fighting with multiaccount owners. do you guys think that could be fixed by @Jessecar96

**Comment by Dima22** [comment]
It's already fixed on library node-steamcommunity (NodeJS). here https://github.com/DoctorMcKay/node-steamcommunity/commit/6e19ffd93bd5d629c005abc963b97ed1fe11b4bc

**Comment by slavunya** [comment]
> It's already fixed on library node-steamcommunity (NodeJS). All changes here [DoctorMcKay/node-steamcommunity@6e19ffd](https://github.com/DoctorMcKay/node-steamcommunity/commit/6e19ffd93bd5d629c005abc963b97ed1fe11b4bc)

how can I use this?
