### ISSUE TITLE
this file is not a valid steamauth mafile 

### ISSUE THREAD

**Issue by SH4HRAY** [Jessecar96/SteamDesktopAuthenticator#858]
Dear SDA Developers,

I hope this message finds you well. I am writing to seek assistance regarding a problem I am encountering with the Steam Desktop Authenticator (SDA).

I have been utilizing SDA to manage my Steam accounts effectively. However, I am currently facing difficulties when attempting to add a new account using the MA-File import feature. Regrettably, I am unable to add my account using the MA-File.

I have followed the correct procedure and ensured that the MA-File format is compatible with SDA. However, upon attempting to import the MA-File, I receive an error message stating that it is not a valid file.

I have attempted this process with multiple MA-Files, some of which have worked successfully, while others encounter this issue.

I kindly request your guidance and support in resolving this matter. Could you please advise me on how to troubleshoot and overcome the problem of being unable to add my account through the MA-File import functionality?

Thank you for your attention to this issue. I anticipate your prompt response and assistance in rectifying this matter.

**Comment by folvos** [comment]
just add the ma files contaning folder instead of ma file  it will work
