### ISSUE TITLE
maFile and virtual device(rooted)

### ISSUE THREAD

**Issue by valeriy-efimov** [Jessecar96/SteamDesktopAuthenticator#86]
I have android virtual device(rooted). I copied out steam guard file. 
{
  "steamguard_scheme": "2",
  "steamid": "*********",
  "shared_secret": "********",
  "status": 1,
  "revocation_code": "**********",
  "secret_1": "***********",
  "server_time": "*********",
  "identity_secret": "**************",
  "uri": "**************",
  "token_gid": "****",
  "serial_number": "*************",
  "account_name": "BLABLA"
}

How do I add it to your application?
Because it does not contain the data.
"Session": {
    "SessionID": "***********",
    "SteamLogin": "*******",
    "SteamLoginSecure": "**********",
    "WebCookie": "******************",
    "OAuthToken": "*********",
    "SteamID": *********
without it is not imported.
"This file is not a valid SteamAuth maFile. Import Failed."
PLS HELP I don't want to wait again 7 days (

**Comment by Jessecar96** [comment]
Under the "Session" block you only need to fill out the "SteamID" part, which you can find from a site like https://rep.tf it looks like this "76561198011423111"

**Comment by valeriy-efimov** [comment]
@Jessecar96 
Ty, "login token" work, but "trade confirmations" dont work, just a white screen (
It can be fixed?
