### ISSUE TITLE
Confirmation is not working please help me @jesecar96

### ISSUE THREAD

**Issue by TIMBLAKE32** [Jessecar96/SteamDesktopAuthenticator#861]

**Comment by DOTBU** [comment]
Still waiting also

**Comment by TIMBLAKE32** [comment]
@Jessecar96 Please help us

**Comment by MrKiyan** [comment]
i have the same problem + i cant add new account 
only SG codes are working :(

**Comment by handwerk2016** [comment]
Yeah the same, just blank window and it not changes after waiting

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/67554455/589d2147-191a-4807-b7a2-cdb876f34eb6)

**Comment by TIMBLAKE32** [comment]
i hope @Jessecar96 can help us.

**Comment by Dimon519** [comment]
I have the same problem. But as a temporary solution, I decided to implement SDA in Python to confirm orders. Whoever has the ability and knowledge, then you can take steampy as an example and modify it for yourself.

**Comment by FusionJura** [comment]
I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix

**RISKY!!!!**,
In my opinion transferring to this is **RISKY!!!!**, I didn't look all code, but its totally different programming language.
They KEY chang to STEAM api was confermation endpoint:
- API "mobileconf/conf" was changed to "mobileconf/getlist"
- Response from that API was changed from HTML to JSON


Summary:
- For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
- For those who use custom script (python, node, etc) can easily fix their authentificator
