### ISSUE TITLE
SDA ISSUE. I CAN'T CONFIRM ANY TRADE. WINDOW CONFIRMATION IN BLANK.

### ISSUE THREAD

**Issue by Bluesette** [Jessecar96/SteamDesktopAuthenticator#864]
Hi. Morning. I need some help. I can't confirm any trade or sale in the app because the window confirmation is in blank. I have several days with ths issue. I tried changing my VPN, but it didn't work. I have 2 accounts linked and none work. Please would you guys bring me some help? 

Thanks in advanced. Regards.

![SDA Issue](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/137379389/be8071b8-2caa-47d7-9cf7-9406e22c1c99)

**Comment by Nooobish** [comment]
SDA stopped working due Steam recent changes. Everyone have same problem.
@Jessecar96 said on discord "Sorry, but I will likely not be updating SDA. Life is too busy right now" in mp.tf group so who knows if it will be ever fixed by original dev.

**Comment by DOTBU** [comment]
Can you give discord link

> SDA stopped working due Steam recent changes. Everyone have same problem. @Jessecar96 said on discord "Sorry, but I will likely not be updating SDA. Life is too busy right now" in mp.tf group so who knows if it will be ever fixed by original dev.

Can you give discord link

**Comment by DOTBU** [comment]
Any fix?

**Comment by Bluesette** [comment]
> Reference

Nope

**Comment by Bluesette** [comment]
> SDA stopped working due Steam recent changes. Everyone have same problem. @Jessecar96 said on discord "Sorry, but I will likely not be updating SDA. Life is too busy right now" in mp.tf group so who knows if it will be ever fixed by original dev.

Thanks for your reply, If you find any solution, pls let me know. I'll stay tuned. 
Regards.

**Comment by MakcStudio** [comment]
Use this fix: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859

**Comment by Bluesette** [comment]
I found a video where an user post his SDA version in youtube.
https://www.youtube.com/watch?v=QyMaO4zTeiU&ab_channel=akatsuki%3F
; but Idk if it's safe. What do you think, guys?

Regards.

**Comment by MakcStudio** [comment]
> I found a video where an user post his SDA version in youtube. https://www.youtube.com/watch?v=QyMaO4zTeiU&ab_channel=akatsuki%3F ; but Idk if it's safe. What do you think, guys?
> 
> Regards.

https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859 
use this. From a developer who at least has a reputation in this area.
