### ISSUE TITLE
STEAM SDA / CANT CONFIRMATION . CANT LOGIN AGAIN 

### ISSUE THREAD

**Issue by kirinforyou** [Jessecar96/SteamDesktopAuthenticator#865]

**Comment by DOTBU** [comment]
any fix?

**Comment by dyc3** [comment]
This is a duplicate of every issue filed over the past couple of days. No, there is no fix, and no, it won't be fixed.

**Comment by Majestik56** [comment]
I did not understand when it will be fixed and what to do   When will there be an update and how to make auntificator work on my computer ?

**Comment by CzarnaMamba** [comment]
it will be fixed when it will be fixed

**Comment by MakcStudio** [comment]
Use this fix: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859
