### ISSUE TITLE
Stop opening duplicate confirmations issues, just use forked WinAuth by auwaho

### ISSUE THREAD

**Issue by Allower** [Jessecar96/SteamDesktopAuthenticator#867]
https://github.com/auwaho/winauth - it's not ad, i just checked it for myself. It's work pretty good, it's safe.

You can easly import "ma" files to it.

Before @Jessecar96 not fix SDA.

If you don't trust to fork autor, you can compile it for yourself. This is fork of archive of original WinAuth with fixed Trade Confiramtions and Steam Login api, you can see all the code.

**Comment by dyc3** [comment]
In a similar vein, I maintain steamguard-cli. I just released an update that fixes login and confirmations. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

**Comment by kajoken** [comment]
Doesn't work. When I try to add a Steam Account I get "Invalid response from Steam (No Oauth token)".

**Comment by hyundacao** [comment]
> https://github.com/auwaho/winauth - it's not ad, i just checked it for myself. It's work pretty good, it's safe.
> 
> You can easly import "ma" files to it.
> 
> Before @Jessecar96 not fix SDA.
> 
> If you don't trust to fork autor, you can compile it for yourself. This is fork of archive of original WinAuth with fixed Trade Confiramtions and Steam Login api, you can see all the code.

Confirmations working  now :)

**Comment by theFreeWall** [comment]
> In a similar vein, I maintain steamguard-cli. I just released an update that fixes login and confirmations. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

So you take the trouble to call on everyone not to use sda in every issue, just to promote your own project?

**Comment by Atilla-Corriea-Nunes** [comment]
> https://github.com/auwaho/winauth - it's not ad, i just checked it for myself. It's work pretty good, it's safe.
> 
> You can easly import "ma" files to it.
> 
> Before @Jessecar96 not fix SDA.
> 
> If you don't trust to fork autor, you can compile it for yourself. This is fork of archive of original WinAuth with fixed Trade Confiramtions and Steam Login api, you can see all the code.

Saved me a lot of time and effort, thank you!

**Comment by MakcStudio** [comment]
Use this fix: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859
