### ISSUE TITLE
SDA to steam mobile app

### ISSUE THREAD

**Issue by ForDownloadOnly** [Jessecar96/SteamDesktopAuthenticator#869]
Is there a way to transfer accounts from SDA to the mobile app that does not get me a 15day tradehold?
No phone jailbreaks.

**Comment by LORD47** [comment]
Yes, there's, just follow the steps mentioned on Steam support page section: [Can I transfer my authenticator to my new phone?](https://help.steampowered.com/en/faqs/view/7EFD-3CAE-64D3-1C31#transfer), and you'd only get 2 days Trade Hold

**Comment by b0Ni** [comment]
transfer/copy to archi 2fa, no tradehold

**Comment by ForDownloadOnly** [comment]
> Yes, there's, just follow the steps mentioned on Steam support page section: [Can I transfer my authenticator to my new phone?](https://help.steampowered.com/en/faqs/view/7EFD-3CAE-64D3-1C31#transfer), and you'd only get 2 days Trade Hold

ok, i might try that one. Does steam app have bulk confirmations now?



> transfer/copy to archi 2fa, no tradehold

is there a guide somewhere on how to transfer? I checked ASF but seems too complicated to transfer unlike the SDA.

**Comment by LORD47** [comment]
> ok, i might try that one. Does steam app have bulk confirmations now?

Unfortunately, no

**Comment by b0Ni** [comment]
> 

https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Two-factor-authentication#steamdesktopauthenticator

**Comment by b0Ni** [comment]
> > Yes, there's, just follow the steps mentioned on Steam support page section: [Can I transfer my authenticator to my new phone?](https://help.steampowered.com/en/faqs/view/7EFD-3CAE-64D3-1C31#transfer), and you'd only get 2 days Trade Hold
> 
> ok, i might try that one. Does steam app have bulk confirmations now?
> 
> > transfer/copy to archi 2fa, no tradehold
> 
> is there a guide somewhere on how to transfer? I checked ASF but seems too complicated to transfer unlike the SDA.

https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Two-factor-authentication#steamdesktopauthenticator

**Comment by LORD47** [comment]
> transfer/copy to archi 2fa, no tradehold

I've read the ASF wiki and in the section about [importing](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Two-factor-authentication#import) from other authenticators it notes this:

> make sure that your authenticator works properly before attempting to import it. This does include testing and verifying that following authenticator functions work properly:
> - You can generate tokens and those tokens are accepted by Steam network
> - You can fetch confirmations, and they are arriving on your mobile authenticator
> - You can accept those confirmations, and they're properly recognized by Steam network as confirmed/rejected

So in current state of SDA, will the transfert/import work with ASF?

**Comment by MakcStudio** [comment]
Use it fix: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859
