### ISSUE TITLE
Still no under way to fix confirmation? 

### ISSUE THREAD

**Issue by torrenars** [Jessecar96/SteamDesktopAuthenticator#870]
Empty white page can't confirm

**Comment by FusionJura** [comment]
I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix

**RISKY!!!!**,
In my opinion transferring to this is **RISKY!!!!**, I didn't look all code, but its totally different programming language.
They KEY chang to STEAM api was confermation endpoint:
- API "mobileconf/conf" was changed to "mobileconf/getlist"
- Response from that API was changed from HTML to JSON


Summary:
- For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
- For those who use custom script (python, node, etc) can easily fix their authentificator
