### ISSUE TITLE
Error after entering email verification code to create token

### ISSUE THREAD

**Issue by axbcdd** [Jessecar96/SteamDesktopAuthenticator#871]
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   在 Newtonsoft.Json.JsonTextReader.ParseValue()
   在 Newtonsoft.Json.JsonTextReader.Read()
   在 Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 SteamAuth.AuthenticatorLinker._hasPhoneAttached() 位置 D:\Git\SteamDesktopAuthenticator\lib\SteamAuth\SteamAuth\AuthenticatorLinker.cs:行号 220
   在 SteamAuth.AuthenticatorLinker.AddAuthenticator() 位置 D:\Git\SteamDesktopAuthenticator\lib\SteamAuth\SteamAuth\AuthenticatorLinker.cs:行号 50
   在 Steam_Desktop_Authenticator.LoginForm.btnSteamLogin_Click(Object sender, EventArgs e) 位置 D:\Git\SteamDesktopAuthenticator\Steam Desktop Authenticator\LoginForm.cs:行号 131
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MakcStudio** [comment]
Use it fix: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859
