### ISSUE TITLE
Я хочу преобразовать свой mafile sda ​​в asf, но получаю сообщение об ошибке: Неожиданный токен 'U', "..."... недействителен JSON

### ISSUE THREAD

**Issue by danilfarm** [Jessecar96/SteamDesktopAuthenticator#872]
Я хочу преобразовать свой mafile sda ​​в asf, но получаю сообщение об ошибке: Неожиданный токен 'U', "..."... недействителен JSON

**Comment by danilfarm** [comment]
Как проверить зашифрован-ли мафайл sda, и если он зашифрован как дешефровать мафайл?

**Comment by TheAreaAccessibleToAPerson** [comment]
Когда вы запускаете asf не должно быть никаких ошибок, описывающих невозможность подключения пакетов.
