### ISSUE TITLE
trades don't go through

### ISSUE THREAD

**Issue by qdsgokjerk** [Jessecar96/SteamDesktopAuthenticator#876]
Hello Yesterday I encountered a problem that does not come trades before lunch was fine after that began some problems SDA upgraded to a new version has not helped

**Comment by dyc3** [comment]
This is a known issue, and SDA isn't going to get updated for a while. Jessecar96 themselves has said on discord that he's too busy to update SDA right now.

If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

Alternatively, some people have made community patches (#859), and there's other software that does the same thing, if you feel comfortable with that kind of thing. Otherwise, you can transfer the authenticator to the official steam mobile app, but that does cause a 2 day trade ban.

**Comment by bolexator** [comment]
[dyc3](https://github.com/dyc3),
Your program is hard to figure out. I can't do it. For example, I can't confirm actions: when I have to type Yes or No, nothing is typed. I've tried on 3 different computers - the effect is the same. As a result, it is not possible to use.

**Comment by allendaydayup** [comment]
@geel9 plz

**Comment by MakcStudio** [comment]
> [dyc3](https://github.com/dyc3), в вашей программе сложно разобраться. Я не могу этого сделать. Например, я не могу подтвердить действия: когда я должен ввести "Да" или "Нет", ничего не вводится. Я пробовал на 3 разных компьютерах - эффект тот же. В результате использовать его невозможно.

Используйте это: https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859

там нет никаких проблем и весь старый функционал работает

**Comment by bokaswt** [comment]
I gave steamguard-cli a chance. I installed it on my old laptop and only for my least valuable account. I created a login code and approved a trade. Worked. Will wait a few days to see if anything "bad" happens or bad news come up. If not i'll switch with all accounts.

I wuld prefer SDA as I trusted that for years and the interface is more comfortable. But without the developers support its just dead. IMHO very annoying. He knows how many people depend on that and could at least state his position here instead of relying on rumors.

I thought about switching to Steam Apps Authenticator as the new app can handle multiple accounts. But that seems like a big loss of security: With the Steam App I can trade and approve in a single instance. The only protection is my mobile's PIN. But if someone grabs my opened mobile from a restaurant table while i read my mails, he got complete access to all my acounts with all items. Steam should at least add a generall PIN when starting the app.

**Comment by dyc3** [comment]
@bolexator if you're having trouble you should post a support thread here: https://github.com/dyc3/steamguard-cli/discussions/new?category=q-a

**Comment by fegeg** [comment]
> I gave steamguard-cli a chance. I installed it on my old laptop and only for my least valuable account. I created a login code and approved a trade. Worked. Will wait a few days to see if anything "bad" happens or bad news come up. If not i'll switch with all accounts.
> 

Could you please help me with a short guide on how to? I have a SDA maFile but I dont exactly know how to add it to steamguard-cli.

**Comment by dyc3** [comment]
@fegeg 
Instructions for how steamguard-cli works are here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

If this information isn't clear enough, feel free to ask questions here: https://github.com/dyc3/steamguard-cli/discussions/new?category=q-a

**Comment by bokaswt** [comment]
I dont have access to my laptop now. But in generall it worked as described on https://github.com/dyc3/steamguard-cli/tree/master

I use Windows.

I loaded down the steamguard.exe from https://github.com/dyc3/steamguard-cli/releases and placed that in a new inventory on my hard disc.

I copied SDAs maFiles-subdirectory to the mentioned directory %APPDATA%\Roaming\steamguard-cli\maFiles which on my system results in C:\Users\Admin\AppData\Roaming\steamguard-cli\maFiles

I opened a command promp and switched to the directory I installed steamguard.exe, entered "steamguard" and it started asking me for my accounts password (iirc). Enter"steamguard -help" to get help. Enter "steamguard trade" to see trades you want to approve.

**Comment by FusionJura** [comment]
I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix

In my opinion transferring to this is *risky*, I didn't look all code, but its totally different programming language.
They KEY chang to STEAM api was confermation endpoint:
- API "mobileconf/conf" was changed to "mobileconf/getlist"
- Response from that API was changed from HTML to JSON


Summary:
- For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
- For those who use custom script (python, node, etc) can easily fix their authentificator

**Comment by Jianchitz** [comment]
> I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix
> 
> **RISKY!!!!**, In my opinion transferring to this is **RISKY!!!!**, I didn't look all code, but its totally different programming language. They KEY chang to STEAM api was confermation endpoint:
> 
> * API "mobileconf/conf" was changed to "mobileconf/getlist"
> * Response from that API was changed from HTML to JSON
> 
> Summary:
> 
> * For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
> * For those who use custom script (python, node, etc) can easily fix their authentificator

Which one do  you use?

**Comment by FusionJura** [comment]
I reverse engineered Jessica's authentication and created my own python3 code for confirming Items

**Comment by FusionJura** [comment]
> > I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix
> > **RISKY!!!!**, In my opinion transferring to this is **RISKY!!!!**, I didn't look all code, but its totally different programming language. They KEY chang to STEAM api was confermation endpoint:
> > 
> > * API "mobileconf/conf" was changed to "mobileconf/getlist"
> > * Response from that API was changed from HTML to JSON
> > 
> > Summary:
> > 
> > * For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
> > * For those who use custom script (python, node, etc) can easily fix their authentificator
> 
> Which one do you use?


I reverse engineered Jessica's authentication and created my own python3 code for confirming Items

**Comment by Jianchitz** [comment]
Do you think this is safe?
https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/854#issuecomment-1607818341

**Comment by MakcStudio** [comment]
Just use it:  https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859

**Comment by Walter-o** [comment]
> > > I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix
> > > **RISKY!!!!**, In my opinion transferring to this is **RISKY!!!!**, I didn't look all code, but its totally different programming language. They KEY chang to STEAM api was confermation endpoint:
> > > 
> > > * API "mobileconf/conf" was changed to "mobileconf/getlist"
> > > * Response from that API was changed from HTML to JSON
> > > 
> > > Summary:
> > > 
> > > * For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
> > > * For those who use custom script (python, node, etc) can easily fix their authentificator
> > 
> > 
> > Which one do you use?
> 
> I reverse engineered Jessecar96's authentication and created my own python3 code for confirming Items

What do u mean with "reverse engineered"?
It's entire source code is public.

**Comment by FusionJura** [comment]
> > > > I saw GIT project that went our, It allegedly fix the issue, https://github.com/therepower/SteamDesktopAuthenticator-Temporary-Fix
> > > > **RISKY!!!!**, In my opinion transferring to this is **RISKY!!!!**, I didn't look all code, but its totally different programming language. They KEY chang to STEAM api was confermation endpoint:
> > > > 
> > > > * API "mobileconf/conf" was changed to "mobileconf/getlist"
> > > > * Response from that API was changed from HTML to JSON
> > > > 
> > > > Summary:
> > > > 
> > > > * For those who use SteamDesktopAuthentificator, they need to be carful when transfering to new GIT project (safty reason)
> > > > * For those who use custom script (python, node, etc) can easily fix their authentificator
> > > 
> > > 
> > > Which one do you use?
> > 
> > 
> > I reverse engineered Jessecar96's authentication and created my own python3 code for confirming Items
> 
> What do u mean with "reverse engineered"? It's entire source code is public.

I meant that the builder .exe file and the source code that is visible to the public can be different
