### ISSUE TITLE
Allow us to delete/unlink Mafile from manifest.json(without removing authenticator) + custom list order.

### ISSUE THREAD

**Issue by wazerstar** [Jessecar96/SteamDesktopAuthenticator#88]
Also allowing us to set an order of which way we would like our accounts to show up, would be really neat.

Like holding down control and move the account up and down with mouse/keyboard in the list to priority of accounts or just simple order.

**Comment by Jessecar96** [comment]
Will add removing from the manifest soon, Have to figure out a way to allow for re-ordering.

**Comment by wazerstar** [comment]
Great to hear, cant wait ;)

**Comment by Jessecar96** [comment]
Added removing in a69d2a95dd5c3cac068f61b9c51894d92071daa3
Will be in the next update.

**Comment by voltij** [comment]
Also @Jessecar96 regarding the account list, just if it isn't too much trouble:

(For example) in a list of: "cat, dog, telephone",

clicking into the list and typing a "d" will correctly select "dog", but typing the three-letter combo "cat" will select "cat" until you press "t", in which it will select "telephone". in many other lists i've interacted with, typing "cat" will select "cat" as the intended selection.

obviously my situation would be: i have accounts named "12, 13, 14, ... 20, 21, 22" and i want to select 12, typing "12" will select "20".

But dont worry about this if it's too much trouble to figure out/impossible/not worth.

**Comment by Jessecar96** [comment]
I have no idea how to make that work

**Comment by pipe01** [comment]
Lemme try

**Comment by pipe01** [comment]
#113

**Comment by voltij** [comment]
I will check in ~2 hours when I am home from work. Thanks in advance.

**Comment by Jessecar96** [comment]
Both are added. Ctrl + UP and Ctrl + DOWN reorder the list items.
