### ISSUE TITLE
I need MaFile 

### ISSUE THREAD

**Issue by Majestik56** [Jessecar96/SteamDesktopAuthenticator#886]
Hello.
Is there any easy way to get MaFile in another way since SDA doesn't work now? Method must be simple enough for dumb people like me, who don't know anything about programming, to do it...

**Comment by Tat-ti** [comment]
Hello, @Jessecar96 

Thank you for your work and your participation!

I'm having a problem linking my account to my new Steam account. I'm trying to enable steam guard via SDA, but I'm getting the error: Error logging in: Steam returned "General ailure".

My actions:
1. opened SDA
2. click on "Setup New Account"
3. entered the login and password from the Steam account
4. received an email with a code for SDA
5. entered the code from the mail in the SDA
6. received an error from SDA: Error logging in: Steam returned "General ailure".

I uploaded the screenshot here: https://imgur.com/a/Dbi2eML

It started 2 weeks ago and is still going on.

I really need a solution. How can this be fixed?

Thank you and have a nice day!
