### ISSUE TITLE
[Help] "Steam Guard failed to deactivate" when trying to Deactivate Authenticator.

### ISSUE THREAD

**Issue by AeroMatixOfficial** [Jessecar96/SteamDesktopAuthenticator#887]
I'm trying to remove the authenticator and get rid of the details so I can move back to it on my phone, however, it comes up with that message when I try to deactivate it - I went onto my phone and moved the authenticator across, however, I still can't remove it on here and would like the peace of mind knowing it's gone.

**Comment by dyc3** [comment]
This is a known issue, and SDA isn't going to get updated for a while. Jessecar96 themselves has said on discord that he's too busy to update SDA right now.

IIRC, You should be able to "move" the authenticator without having access to the previous "device". Just go on your phone and try to add an authenticator, and it'll prompt you to move it.

You have some other options: I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

Alternatively, some people have made community patches (#859), and there's other software that does the same thing, if you feel comfortable with that kind of thing.

**Comment by AeroMatixOfficial** [comment]
I've already moved it to the phone, however, it's still active on the SDA, no? 

I'm wanting to get rid of the 3rd party app(s) completely and all of the data associated with it, seeing as I can't deactivate it on SDA - what if I were to just delete all copies of the application I have? Is anything stored non-locally?

**Comment by dyc3** [comment]
No, when you "move" it, you are actually issued a new set of secrets on the new device, and the old secrets in SDA become invalid.

**Comment by AeroMatixOfficial** [comment]
Okay, so now that it's moved the SDA applications are now useless and can be deleted and forgotten about?

**Comment by dyc3** [comment]
Yes

**Comment by AeroMatixOfficial** [comment]
Thanks.
