### ISSUE TITLE
Cannot Add Account

### ISSUE THREAD

**Issue by KegonSto** [Jessecar96/SteamDesktopAuthenticator#89]
Keeps Denying Captcha code When the code was correct (Seriously Captcha is terrible why did you choose it)
I keep trying Code After code and im about to flip sh*t if it doesn't work soon And when it does work it says ''General Faliure''

Pls Help me before i lose my Sanity

**Comment by Senaris** [comment]
Steam requires captcha verification, not the developer. 

Keep trying, i didn't had any issues so far.

**Comment by Jessecar96** [comment]
This is not a support forum. See this issue: https://github.com/geel9/SteamAuth/issues/5
