### ISSUE TITLE
@Jessecar96 Please read

### ISSUE THREAD

**Issue by MakcStudio** [Jessecar96/SteamDesktopAuthenticator#890]
@Jessecar96 https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/859

https://github.com/MakcStudio/SteamDesktopAuthenticator/tree/main_english

Why do you need steamkit , why stretch another dependency for the sake of authorization? Go to my repo, I fixed all the functions there. And authorization and adding an account. Just copy the methods to yourself, it will not take you much time

**Comment by earlybirdy1** [comment]
It's a pre-release

**Comment by MakcStudio** [comment]
> It's a pre-release

And?)

**Comment by dyc3** [comment]
Because steamkit is a great library, and well maintained. It decreases the maintenance load for him because he won't have to deal with protobuf or reverse engineering when something changes.

If you really wanted him to use your changes, you'd make a PR.

**Comment by MakcStudio** [comment]
Yeah, but if then this library stops updating too - you have to go into its code and update it. I looked at their source code, when I was fixing my repo, it's just terrors. It is very difficult to understand, and it does not have all the methods we need. It's a Frankenstein cross between steamauth and steamkit.

**Comment by MakcStudio** [comment]
I should also add that steam will not make changes to their api every day. This only happened once in a while and they just moved to a normal json query style and disabled the old methods so as not to support them anymore.

They just rewrote the site and mobile app and disabled the old unused methods. I don't think this will happen again in the next few years

**Comment by Jessecar96** [comment]
You are free to fork this repository and implement changes as you wish. I decided to use SteamKit for authentication instead of implementing it myself as it's been maintained for many years and is used by many other projects as well.
