### ISSUE TITLE
VirusTotal scan 

### ISSUE THREAD

**Issue by routemasters** [Jessecar96/SteamDesktopAuthenticator#894]
Thank you first of all for the update.

I let scan Virustotal the Steam Desktop Authenticator.exe is the result came with 3 red flags. Are these again false positives from unknown scanners?

https://www.virustotal.com/gui/file/9d0330488c6ec757b2f9cda5d1b5baf676a63d4e3b39cbf63b3febe89ff0624b?nocache=1

**Comment by MrKiyan** [comment]
imagine BitDefender, ESET, AVIRA, Kaspersky, AVG, Mcafee, PANDA and more ... Says its clean and those unknown stupid cheap compaies says its not clean :D comon man :D

**Comment by Jessecar96** [comment]
This is likely due to there being many malicious versions of SDA that steal accounts. If you're worried about the builds posted to this repository I advise you to clone the source code and compile it yourself.

Closing this as it's not something I can fix.
