### ISSUE TITLE
Trade Confirmation modal goes white for ever.

### ISSUE THREAD

**Issue by monketto** [Jessecar96/SteamDesktopAuthenticator#895]
In version 1.0.11, Trade confirmations modal goes blank. There is nothing shows up.
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/67822900/64400d95-4f45-4d0e-be32-bdc6d0a16271)

**Comment by Jessecar96** [comment]
Version 1.0.11 does not work due to changes on Steam. You can download the latest pre-release that fixes these issues: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
