### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by roughnecks** [Jessecar96/SteamDesktopAuthenticator#896]
https://i.imgur.com/NaA342t.jpeg

**Comment by Eloparto** [comment]
same problem

**Comment by Jessecar96** [comment]
This is likely due to there being many malicious versions of SDA that steal accounts. If you're worried about the builds posted to this repository I advise you to clone the source code and compile it yourself.

Closing this as it's not something I can fix.
