### ISSUE TITLE
(Authentication failed with result RateLimitExceeded) any fix?

### ISSUE THREAD

**Issue by dido21312** [Jessecar96/SteamDesktopAuthenticator#897]

**Comment by YukiCoco** [comment]
same problem

**Comment by dyc3** [comment]
RateLimitExceeded means you are being rate limited by Steam. This is not an SDA issue. You need to wait a while and try again. Give it a few hours.

**Comment by dido21312** [comment]
Solved waited ~18 hours thank you

**Comment by dido21312** [comment]
Just wait for ~12 to 24 hours and try again!
