### ISSUE TITLE
1.0.12 version trade confirmations display error

### ISSUE THREAD

**Issue by allendaydayup** [Jessecar96/SteamDesktopAuthenticator#898]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/20311969/25fae039-0ecb-4f95-b3e8-a184edb49556)
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/20311969/3bc43211-36f1-4838-9fa8-87304dca0d26)

When I used SDA 1.0.12, the error in the image was displayed on the trade confirmations page (my headline is in Chinese, and the content returned by the Steam is also normal)

**Comment by Glazkor** [comment]
I mean can someone fix this until tomorrow? The steam sale starts today and I already lost 10 cents on a hundred items I want to sell.
Right now this is a common issue and we are dependant on confirmations.

**Comment by allendaydayup** [comment]
> I mean can someone fix this until tomorrow? The steam sale starts today and I already lost 10 cents on a hundred items I want to sell. Right now this is a common issue and we are dependant on confirmations.

Did you also have this problem?

**Comment by allendaydayup** [comment]
> I mean can someone fix this until tomorrow? The steam sale starts today and I already lost 10 cents on a hundred items I want to sell. Right now this is a common issue and we are dependant on confirmations.

I used the code submitted by @jorgermduarte , which I downloaded and compiled to work properly.
There doesn't seem to be much difference in the code, of course I don't have much knowledge of C # and can't provide a solution in this area.

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/20311969/410eeb4c-da90-49f4-9f35-2ae5b681a7c6)

**Comment by Glazkor** [comment]
Yes, I do. The confirmations do this and then I get the same something went wrong.
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/107644762/bcc5a72c-48f6-4591-bcc5-d50777d7c6f5)

I let 3 friends test it and they have the same issue.

**Comment by allendaydayup** [comment]
> Yes, I do. The confirmations do this and then I get the same something went wrong. ![image](https://user-images.githubusercontent.com/107644762/249759557-bcc5a72c-48f6-4591-bcc5-d50777d7c6f5.png)
> 
> I let 3 friends test it and they have the same issue.

Yes, I understand what you mean. What I mean is that the version submitted by Jessecar seems to have a bit of a bug here, which is the error reported in the first image I submitted. The last image I submitted was compiled using the code submitted by Jorgermduarte, and Jorgermduarte's code seems to work properly in this area.

**Comment by Ps1d3r** [comment]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/8770360/7e1c5384-774b-46fe-8f86-b774a47ba67b)
It says Request abrteds: It wasn't possible to create a safe channel SSL/TLS
I'm using the version posted by jorgermduarte on https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

**Comment by allendaydayup** [comment]
> 

This may be a bit troublesome. The warehouse address where I downloaded the code is located is: https://github.com/jorgermduarte/SteamDesktopAuthenticator The version modified by Jorgermduarte. If you understand the code, you can take a look at the content he submitted and compile it yourself. Perhaps this can solve your urgent need. If you don't understand the code, you may need to wait for the next update of the release version.

**Comment by allendaydayup** [comment]
> ![image](https://user-images.githubusercontent.com/8770360/249761771-7e1c5384-774b-46fe-8f86-b774a47ba67b.png) It says Request aborteds: It wasn't possible to create a safe channel SSL/TLS I'm using the version posted by jorgermduarte on https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

This may be a bit troublesome. The warehouse address where I downloaded the code is located is: https://github.com/jorgermduarte/SteamDesktopAuthenticator The version modified by Jorgermduarte. If you understand the code, you can take a look at the content he submitted and compile it yourself. Perhaps this can solve your urgent need. If you don't understand the code, you may need to wait for the next update of the release version.

**Comment by Ps1d3r** [comment]
> > ![image](https://user-images.githubusercontent.com/8770360/249761771-7e1c5384-774b-46fe-8f86-b774a47ba67b.png) It says Request aborteds: It wasn't possible to create a safe channel SSL/TLS I'm using the version posted by jorgermduarte on https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
> 
> This may be a bit troublesome. The warehouse address where I downloaded the code is located is: https://github.com/jorgermduarte/SteamDesktopAuthenticator The version modified by Jorgermduarte. If you understand the code, you can take a look at the content he submitted and compile it yourself. Perhaps this can solve your urgent need. If you don't understand the code, you may need to wait for the next update of the release version.

I do know a bit of code, but not enough, i'm just a curious guy xD nor do i know how to compile this.
Thought of sharing it to possibly help with the fix

**Comment by Ps1d3r** [comment]
> > 
> 
> This may be a bit troublesome. The warehouse address where I downloaded the code is located is: https://github.com/jorgermduarte/SteamDesktopAuthenticator The version modified by Jorgermduarte. If you understand the code, you can take a look at the content he submitted and compile it yourself. Perhaps this can solve your urgent need. If you don't understand the code, you may need to wait for the next update of the release version.

Pls edit your reply and remove the image, i just noticed i forgot to obscure the acc **facepalm**

**Comment by allendaydayup** [comment]
> > > It says Request aborteds: It wasn't possible to create a safe channel SSL/TLS I'm using the version posted by jorgermduarte on https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
> > 
> > 
> > This may be a bit troublesome. The warehouse address where I downloaded the code is located is: https://github.com/jorgermduarte/SteamDesktopAuthenticator The version modified by Jorgermduarte. If you understand the code, you can take a look at the content he submitted and compile it yourself. Perhaps this can solve your urgent need. If you don't understand the code, you may need to wait for the next update of the release version.
> 
> I do know a bit of code, but not enough, i'm just a curious guy xD nor do i know how to compile this. Thought of sharing it to possibly help with the fix

I am not very proficient in C # and cannot provide a good fix. I would like to directly provide you with a compiled version for you to use temporarily, but I cannot do so. You know, this is very unsafe, and only the version downloaded from here can ensure safety and reliability.

**Comment by allendaydayup** [comment]
> > > 
> > 
> > 
> > This may be a bit troublesome. The warehouse address where I downloaded the code is located is: https://github.com/jorgermduarte/SteamDesktopAuthenticator The version modified by Jorgermduarte. If you understand the code, you can take a look at the content he submitted and compile it yourself. Perhaps this can solve your urgent need. If you don't understand the code, you may need to wait for the next update of the release version.
> 
> Pls edit your reply and remove the image, i just noticed i forgot to obscure the acc **facepalm**

Removed

**Comment by itskienly** [comment]
Actually the latest release is worked for more finally. Do you have .NET Framework 4.7.2?

**Comment by Ps1d3r** [comment]
> Actually the latest release is worked for more finally. Do you have .NET Framework 4.7.2?

I do have it, just tried the latest version again and nothing...
Did you change something?

**Comment by allendaydayup** [comment]
> Actually the latest release is worked for more finally. Do you have .NET Framework 4.7.2?

I have it, I download it https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.12 Then, the error reported directly is the same as the error I obtained by compiling the source code using Visual Studio myself. Does my ability to compile successfully mean that there are no issues with my computer environment.

**Comment by allendaydayup** [comment]
> > > Actually the latest release is worked for more finally. Do you have .NET Framework 4.7.2?
> > 
> > 
> > I have it, I download it https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.12 Then, the error reported directly is the same as the error I obtained by compiling the source code using Visual Studio myself. Does my ability to compile successfully mean that there are no issues with my computer environment.
> 
> Which one did you download? ![image](https://user-images.githubusercontent.com/47635037/249829226-05f15af2-80d6-4745-9e41-98e35b89a02d.png)
> 
> Just download the one in the image above, and no need to compile it whatsoever.

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/20311969/41a13fa9-0353-4796-9aba-aec91adfe007)
this one

**Comment by allendaydayup** [comment]
> 

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/20311969/5934483d-0f4b-40e7-b07d-15b9d75bc7f6)
I don't quite understand what you mean. I just downloaded the zip and ran Steam Desktop Authenticator.exe. Isn't that enough. Sorry, I'm not very familiar with this aspect.

**Comment by itskienly** [comment]
> > Actually the latest release is worked for more finally. Do you have .NET Framework 4.7.2?
> 
> I have it, I download it https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.12 Then, the error reported directly is the same as the error I obtained by compiling the source code using Visual Studio myself. Does my ability to compile successfully mean that there are no issues with my computer environment.

I downloaded the latest release as i said. An clicked first option, transferred my SDA 1.0.10 file. So it started to show trade confirmations after downloading and transferring my old SDA file.

**Comment by RATT78** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.12

The download for the zip is not working, Error 503 Backend unavailable, connection timeout.

**Comment by Jessecar96** [comment]
Version 1.0.13 has been posted, which should fix this issue
https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.13

**Comment by allendaydayup** [comment]
> Version 1.0.13 has been posted, which should fix this issue https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.13

1.0.13 can now display my information normally.
