### ISSUE TITLE
Error adding phone number

### ISSUE THREAD

**Issue by nikolathek** [Jessecar96/SteamDesktopAuthenticator#90]
Error adding your phone number. Steam returned "General Failure".   This pops up after i try to add my number. 
My number is typed in correctly. Please help.

**Comment by hyt47** [comment]
did u add the correct country code ?
to setup your app use this turorial https://github.com/hyt47/SteamDesktopAuthenticator-Modded

**Comment by routemasters** [comment]
its because your password is over-secure with special characters.

**Comment by Jessecar96** [comment]
This is not a support forum. See this bug: https://github.com/geel9/SteamAuth/issues/5
