### ISSUE TITLE
has anyone fixed their problem? after 1.0.13 update? because mine still the same empty white page confirmation 

### ISSUE THREAD

**Issue by torrenars** [Jessecar96/SteamDesktopAuthenticator#902]

**Comment by torrenars** [comment]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/126465817/73894a79-8d8f-4d55-9f20-5fbe03c67737)

I updated everything already still the same

**Comment by Kemyada** [comment]
Use "Refresh login" in "Selected account" in the main app. 
If the issue is still there there's something wrong with your pc, as it it works for me and shows the confirmation menu like that:
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/96890554/2dbfcfc0-d0ad-486a-a648-748aeb92e7ba)

**Comment by torrenars** [comment]
> Use "Refresh login" in "Selected account" in the main app. If the issue is still there there's something wrong with your app, as it it works for me and shows the confirmation menu like that: ![image](https://user-images.githubusercontent.com/96890554/249990202-2dbfcfc0-d0ad-486a-a648-748aeb92e7ba.png)

I already have done that but still says the same

**Comment by torrenars** [comment]
> Use "Refresh login" in "Selected account" in the main app. If the issue is still there there's something wrong with your app, as it it works for me and shows the confirmation menu like that: ![image](https://user-images.githubusercontent.com/96890554/249990202-2dbfcfc0-d0ad-486a-a648-748aeb92e7ba.png)

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/126465817/d45c1b9d-2b00-4034-8f89-9e3e48b1bb69)
there is no refresh login on my app just login again i already login again but still confirmation not working, can you please help me what should I do or whats wrong with my app? or can you at least send me copy of your SDA without your mafiles init

**Comment by Niceman35** [comment]
Check the version number on the bottom-right corner. Perhaps you have not updated to 1.0.13 yet. Please note that this version is not the final release and does not appear on the main page yet.

**Comment by torrenars** [comment]
> 

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/126465817/040e2ce3-6cff-429c-a123-05a21046f9a5)
its still 1.0.11 but I already downloaded the files and move it to the folder where SDA was but still not working

**Comment by torrenars** [comment]
> Check the version number on the bottom-right corner. Perhaps you have not updated to 1.0.13 yet. Please note that this version is not the final release and does not appear on the main page yet.

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/126465817/e6c91b11-e41d-49bf-aab1-2cc696fb9bbf)
As you can see it says im current using latest version

**Comment by Kemyada** [comment]
> > Check the version number on the bottom-right corner. Perhaps you have not updated to 1.0.13 yet. Please note that this version is not the final release and does not appear on the main page yet.
> 
> ![image](https://user-images.githubusercontent.com/126465817/250079988-e6c91b11-e41d-49bf-aab1-2cc696fb9bbf.png) As you can see it says im current using latest version

It's not, https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/tag/1.0.13 here's the link for the last version.

**Comment by jbondguy007** [comment]
I am experiencing the same issue, first with an outdated fork, but now with a fresh install of SDA through this repo. Could this be an issue stemming from the maFiles somehow, since it occurs on, so far, two different versions of the application? It's the only thing that's consistent between my two installs.
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/20049178/49382dc8-14ed-4773-a639-6560241a8035)

**Comment by Jessecar96** [comment]
Version 1.0.11 is no longer supported. Use the latest pre-release 1.0.13 version.
