### ISSUE TITLE
1.0.13 Error adding your authenticator

### ISSUE THREAD

**Issue by jwcloverain** [Jessecar96/SteamDesktopAuthenticator#904]
I add an authenticator for another account, entered my phone number, received a confirmation email, clicked on add phone number in the email and showed the error message Error adding your authenticator, I check store.steampowered.com/account page, the phone number was not added to the account
@Jessecar96

**Comment by chinap** [comment]
same problem
Yesterday's version could add

**Comment by jwcloverain** [comment]
> 同样的问题 昨天的版本可以添加
> 
> Steam Desktop Authenticator/LoginForm.cs 将第215行的“default:”注释掉即可

this change is not working for me because my account is not linked mobile number, this change should work for account already linked mobile number

**Comment by Satobi46** [comment]
Correct Password, "General Failure."

**Comment by MaxurDev** [comment]
> > 同样的问题 昨天的版本可以添加
> > Steam Desktop Authenticator/LoginForm.cs 将第215行的“default:”注释掉即可
> 
> this change is not working for me because my account is not linked phone number, this change should work for account already linked phone number

Same thing for me, and I have a linked phone number & it says 'General Failure" even with my phone number linked - in fact I get a code on my phone but it still says "General Error".

**Comment by zatro213sdk** [comment]
> same problem Yesterday's version could add
> 
> Steam Desktop Authenticator/LoginForm.cs Comment out the "deafault:" on line 215 and you can

How can i do this

**Comment by jessecor96** [comment]
Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V

Hope this helps!
