### ISSUE TITLE
Can't add account

### ISSUE THREAD

**Issue by aureliik** [Jessecar96/SteamDesktopAuthenticator#909]
First time user after WinAuth stopped working, so I don't know if I just don't understand this at all or what. But I am unable to add my account to SDA. I downloaded the 1.0.11 version, extracted all files from .zip into another folder and then used the exe. I click "Set up new account" and I input my info, then I use the code from my email but then get following pop up:

Microsoft .NET Framework
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. 
Unexpected character encountered while parsing value: <. Path ". line 0. position 0.

Clicking continue will just result in another pop up saying: Error logging in Steam returned "GeneralFailure".

I don't understand what any of that means. I tried to download '.NET Framework 4.7.2' but my computer says I can't install it because I already have it or a newer version. What is wrong and what am I supposed to do?

**Comment by dyc3** [comment]
1.0.11 is outdated. Go to the releases page and download the latest release.

**Comment by aureliik** [comment]
Oh, I thought it was newest because of the main page Version 1.0.11 is marked as the Latest, but now I see there are more. I took Version 1.0.13, but still couldn't get the authenticator to work. I am now able to login with the email code and the authenticator says: "Steam account login succeeded. Press OK to continue adding SDA as your authenticator." after clicking OK I get a pop up saying "Error adding your authenticator."

**Comment by code-XmR** [comment]
I also get an SMS to my phone to confirm adding Steam Authenticator, but there is no place to put the code...  also there is only a box saying "Error adding your authenticator". I'm using 1.0.13.

**Comment by dyc3** [comment]
I think it's most likely failing on this line:

https://github.com/geel9/SteamAuth/blob/b1fc94daf33af33e39d45c645ce41a10c91c189b/SteamAuth/AuthenticatorLinker.cs#L95


If you are interested, I maintain steamguard-cli. It's capable of reading the exactly the same maFiles that SDA does, so you don't have to deal with a trade ban. You can download it here: https://github.com/dyc3/steamguard-cli/releases

Read the quickstart here: https://github.com/dyc3/steamguard-cli/blob/master/docs/quickstart.md

Otherwise, you should probably just stick to using the mobile app.

**Comment by Sekret0** [comment]
> First time user after WinAuth stopped working, so I don't know if I just don't understand this at all or what. But I am unable to add my account to SDA. I downloaded the 1.0.11 version, extracted all files from .zip into another folder and then used the exe. I click "Set up new account" and I input my info, then I use the code from my email but then get following pop up:
> 
> Microsoft .NET Framework Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. Unexpected character encountered while parsing value: <. Path ". line 0. position 0.
> 
> Clicking continue will just result in another pop up saying: Error logging in Steam returned "GeneralFailure".
> 
> I don't understand what any of that means. I tried to download '.NET Framework 4.7.2' but my computer says I can't install it because I already have it or a newer version. What is wrong and what am I supposed to do?

I was able to add new accounts using Version 1.0.12. After adding it, I imported it into WinAuth. Try it as temporary solution

**Comment by jessecor96** [comment]
Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V

Hope this helps!
