### ISSUE TITLE
locales and autosuccess

### ISSUE THREAD

**Issue by Sufir** [Jessecar96/SteamDesktopAuthenticator#91]
1. I see "locales" in folder with Authenticator, how can i use them?

2. Can u do "autosucces" for trades and minimizing to tray. Thats will be great. I'm really dont like escrow...

**Comment by ItsHipsterNoah** [comment]
1. I don't know what you mean. Could you please elaborate?

2. There has been a request to auto accept trades already, it will be implemented in a future release.

**Comment by Jessecar96** [comment]
The local folders is for CefSharp, the browser embedded in the program to open trade confirmations.
