### ISSUE TITLE
cannot add a new account

### ISSUE THREAD

**Issue by Sproionk** [Jessecar96/SteamDesktopAuthenticator#915]
running the newest version and getting this error message on multiple accounts;

"steam login error. object reference not set to an instance of an object."

What am I doing wrong?

**Comment by Reborn3854** [comment]
> running the newest version and getting this error message on multiple accounts;
> 
> "steam login error. object reference not set to an instance of an object."
> 
> What am I doing wrong?

You'll need to remove your Steam authenticator first (using the website or mobile app).

**Comment by 140218491** [comment]
@Reborn3854 tried it, still doesn't work

**Comment by ccsimplyspolit** [comment]
same problem

**Comment by ccsimplyspolit** [comment]
> @Reborn3854 tried it, still doesn't work

Download old version https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/download/1.0.12/SDA.1.0.12.zip
import/create new accounts
download latest version, click import account via .maFile

**Comment by Jessecar96** [comment]
Pre-release version 1.0.14 is now out that fixes this issue: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
