### ISSUE TITLE
Adding an Account to SDA Manually via File

### ISSUE THREAD

**Issue by Romz24** [Jessecar96/SteamDesktopAuthenticator#916]
Hello! I want to use SDA with my Android phone. I already have the TOTP that I use in Bitwarden to generate 2FA codes. How can I add an account to SDA with just the login, password, and TOTP? Can anyone explain the structure of the maFiles? I haven't used SDA before, and I don't want to bind my phone number again because I won't be able to retrieve the TOTP from my Android phone due to a mobile app update that made it impossible.

**Comment by dyc3** [comment]
This is the code that defines the class that is used to serialize the JSON: https://github.com/geel9/SteamAuth/blob/b1fc94daf33af33e39d45c645ce41a10c91c189b/SteamAuth/SteamGuardAccount.cs

The secrets are all 20 bytes long, base64 encoded.

**Comment by Romz24** [comment]
I have only the shared_secret, revocation_code, as well as the login and password for the account. Can I use them to obtain/generate all the other data for this array?

**Comment by dyc3** [comment]
You need the `identity_secret` in order to do confirmations. `secret_1` is currently not used, but it might be in the future. Both of these are unique and _not_ derived from the `shared_secret`.

**Comment by Romz24** [comment]
Thank you for your response.
