### ISSUE TITLE
"Error adding your authenticator"

### ISSUE THREAD

**Issue by JameyDurst578** [Jessecar96/SteamDesktopAuthenticator#918]
@Jessecar96 Even after the 1.0.13 update, I still can't any account to the SDA.
I use my id and password, after that I enter my phone number, then after I verify my e-mail, it says "Error adding your authenticator." 
I don't know what happened after that Steam update, but I need to use SDA somehow, and still waiting for a proper update. 
Thanks, and please maintain the application.

**Comment by Reborn3854** [comment]
> @Jessecar96 Even after the 1.0.13 update, I still can't any account to the SDA. I use my id and password, after that I enter my phone number, then after I verify my e-mail, it says "Error adding your authenticator." I don't know what happened after that Steam update, but I need to use SDA somehow, and still waiting for a proper update. Thanks, and please maintain the application.

Try to add an account in version 1.0.12 and then move the maFiles folder to the folder with version 1.0.13.

**Comment by 1ukah** [comment]
> > @Jessecar96 Even after the 1.0.13 update, I still can't any account to the SDA. I use my id and password, after that I enter my phone number, then after I verify my e-mail, it says "Error adding your authenticator." I don't know what happened after that Steam update, but I need to use SDA somehow, and still waiting for a proper update. Thanks, and please maintain the application.
> 
> Try to add an account in version 1.0.12 and then move the maFiles folder to the folder with version 1.0.13.

That works! Thank you!

**Comment by h4cyy** [comment]
it works for already created accounts or for new too ?

**Comment by ccsimplyspolit** [comment]
> it works for already created accounts or for new too ?

both

**Comment by Jessecar96** [comment]
Pre-release version 1.0.14 is now out that fixes this issue: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

**Comment by IpegaInactive** [comment]
Unfortunately, none of the versions 1.0.11-1.0.14 helped. The phone number is linked, Steam Guard is unlinked from the account (red icon). Are there any other options to solve the problem? I would be very grateful to you!
