### ISSUE TITLE
Mafiles?

### ISSUE THREAD

**Issue by Spryroop** [Jessecar96/SteamDesktopAuthenticator#92]
Where are the mafiles? i dont see it in the maFiles folder. please help

**Comment by ItsHipsterNoah** [comment]
Hi,

They should be somewhere near the top. If you a can't find them, right click within the 0.3.1. folder, and hover over "Sort By." Then, select how you would like to organize the files.

![capture](https://cloud.githubusercontent.com/assets/13893647/11811862/fc48fe36-a2ec-11e5-8477-f9ab5b3f06f1.JPG)
![capture2](https://cloud.githubusercontent.com/assets/13893647/11811863/fc4a2a04-a2ec-11e5-8e58-b9fde4e37e1b.JPG)

Hope this helps!
