### ISSUE TITLE
Error adding your authenticator

### ISSUE THREAD

**Issue by 140218491** [Jessecar96/SteamDesktopAuthenticator#921]
Doesn't let me, tried it on older versions aswell, same error.

**Comment by 1ukah** [comment]
The only way I've found to add authenticator successfully was adding it in version 1.0.12 then importing the maFile to version 1.0.13. Maybe you could try that.

![DtybnS6CfP](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/52342023/6934d056-7230-4f55-a4d5-4968a3db6a37)

**Comment by SuLDfn** [comment]
can u teach me how to do this pls?

**Comment by ccsimplyspolit** [comment]
> can u teach me how to do this pls?
Download old version https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/download/1.0.12/SDA.1.0.12.zip
import/create new accounts
download latest version, click import account via  .maFile

**Comment by ForDownloadOnly** [comment]
is adding new account for the latest version still not working?

**Comment by jessecor96** [comment]
Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V

Hope this helps!

**Comment by ccsimplyspolit** [comment]
> Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V
> 
> Hope this helps!

just add these files to release please?

**Comment by Shashankm007** [comment]
> The only way I've found to add authenticator successfully was adding it in version 1.0.12 then importing the maFile to version 1.0.13. Maybe you could try that.
> 
> ![DtybnS6CfP](https://user-images.githubusercontent.com/52342023/250346352-6934d056-7230-4f55-a4d5-4968a3db6a37.png)

thank you bro

**Comment by Jessecar96** [comment]
Pre-release version 1.0.14 is now out that fixes this issue: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
