### ISSUE TITLE
1.0.13 NICE UPDATE YOU SELL ?

### ISSUE THREAD

**Issue by DJMarkus1337** [Jessecar96/SteamDesktopAuthenticator#927]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/80347162/8d2095cd-9cd5-4591-a54b-241ec00f7d28)

**Comment by DJMarkus1337** [comment]
Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
System.ObjectDisposedException: Nie można uzyskać dostępu do usuniętego obiektu.
Nazwa obiektu: 'TradePopupForm'.
   w System.Windows.Forms.Control.CreateHandle()
   w System.Windows.Forms.Form.CreateHandle()
   w System.Windows.Forms.Control.get_Handle()
   w System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   w System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   w Steam_Desktop_Authenticator.TradePopupForm.Popup() w D:\Git\SteamDesktopAuthenticator\Steam Desktop Authenticator\TradePopupForm.cs:wiersz 104
   w Steam_Desktop_Authenticator.MainForm.<timerTradesPopup_Tick>d__37.MoveNext() w D:\Git\SteamDesktopAuthenticator\Steam Desktop Authenticator\MainForm.cs:wiersz 497
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Zestawy załadowane **************
mscorlib
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Steam Desktop Authenticator
    Wersja zestawu: 1.0.13.0
    Wersja Win32: 1.0.13
    CodeBase: file:///C:/Users/48511/Desktop/SDA/Steam%20Desktop%20Authenticator.exe
----------------------------------------
System
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
CommandLine
    Wersja zestawu: 1.9.71.2
    Wersja Win32: 1.9.71.2
    CodeBase: file:///C:/Users/48511/Desktop/SDA/CommandLine.DLL
----------------------------------------
System.Windows.Forms
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Wersja zestawu: 13.0.0.0
    Wersja Win32: 13.0.3.27908
    CodeBase: file:///C:/Users/48511/Desktop/SDA/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SteamAuth
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 1.0.0.0
    CodeBase: file:///C:/Users/48511/Desktop/SDA/SteamAuth.DLL
----------------------------------------
netstandard
    Wersja zestawu: 2.0.0.0
    Wersja Win32: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Configuration
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.CSharp
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_pl_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Wersja zestawu: 0.0.0.0
    Wersja Win32: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.resources.dll
----------------------------------------
SteamKit2
    Wersja zestawu: 2.5.0.0
    Wersja Win32: 2.5.0
    CodeBase: file:///C:/Users/48511/Desktop/SDA/SteamKit2.DLL
----------------------------------------
protobuf-net.Core
    Wersja zestawu: 3.0.0.0
    Wersja Win32: 3.2.16.54102
    CodeBase: file:///C:/Users/48511/Desktop/SDA/protobuf-net.Core.DLL
----------------------------------------
System.Net.Http
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
Microsoft.Win32.Registry
    Wersja zestawu: 5.0.0.0
    Wersja Win32: 5.0.20.51904
    CodeBase: file:///C:/Users/48511/Desktop/SDA/Microsoft.Win32.Registry.DLL
----------------------------------------
System.Web
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.ValueTuple
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
protobuf-net
    Wersja zestawu: 3.0.0.0
    Wersja Win32: 3.2.16.54102
    CodeBase: file:///C:/Users/48511/Desktop/SDA/protobuf-net.DLL
----------------------------------------
System.Memory
    Wersja zestawu: 4.0.1.2
    Wersja Win32: 4.6.31308.01
    CodeBase: file:///C:/Users/48511/Desktop/SDA/System.Memory.DLL
----------------------------------------
System.Buffers
    Wersja zestawu: 4.0.3.0
    Wersja Win32: 4.6.28619.01
    CodeBase: file:///C:/Users/48511/Desktop/SDA/System.Buffers.DLL
----------------------------------------
System.Collections.Immutable
    Wersja zestawu: 7.0.0.0
    Wersja Win32: 7.0.22.51805
    CodeBase: file:///C:/Users/48511/Desktop/SDA/System.Collections.Immutable.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.21.52210
    CodeBase: file:///C:/Users/48511/Desktop/SDA/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
mscorlib.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Debugowanie w trybie JIT **************
Aby włączyć debugowanie w trybie just in time (JIT), plik .config tej
aplikacji lub komputera (machine.config) musi mieć
wartość jitDebugging ustawioną w sekcji system.windows.forms.
Aplikacja musi być również skompilowana z włączonym
debugowaniem.

Na przykład:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Gdy debugowanie JIT jest włączone, wszystkie nieobsługiwane wyjątki
są wysyłane do debugera JIT zarejestrowanego na komputerze
i nie są obsługiwane w tym oknie dialogowym.

**Comment by DJMarkus1337** [comment]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/80347162/ad3dd9c9-107a-4390-80d7-8226dfd04ddb)

**Comment by liups233** [comment]
> ![圖像](https://user-images.githubusercontent.com/80347162/250607755-ad3dd9c9-107a-4390-80d7-8226dfd04ddb.png)

Me too

**Comment by DJMarkus1337** [comment]
working only accept trade and steam guard code ... adding not work

**Comment by Mdutkiew77** [comment]
> working only accept trade and steam guard code ... adding acc not work

Stwórz konto w starszej wersji SDA (które już nie robią Auto Confirm Market Transactions) i przenieś stworzony maFile do najnowszej wersji 1.13.

**Comment by jessecor96** [comment]
Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V

Hope this helps!

**Comment by Cody1337** [comment]
Be careful, there is a message from a fake account on top, do not follow its link, it will steal your accounts!

**Comment by allendaydayup** [comment]
This situation only occurs when a new account has not added a phone number. If you need to bind a new account, you can first bind the phone number on the Steam webpage, or import it to version 13 after the SDA binding in version 12 is completed
