### ISSUE TITLE
Cant Setup new accounts 

### ISSUE THREAD

**Issue by Watashi-Senpai** [Jessecar96/SteamDesktopAuthenticator#928]
using the Latest version, i got a verification code via SMS but in SDA as you can see in the attached its not working right. 

1. login (works)
2.  email verification (works) 
3. click the button that you clicked on the link in email. (says that it works)
4. in SDA gives Error after clicking ok.

![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/67963532/b672faeb-a45e-467b-b52a-1d9c2206c472)

**Comment by ogmicco** [comment]
same

**Comment by crazy304** [comment]
same

**Comment by UIE-z** [comment]
same

**Comment by Cody1337** [comment]
Just add a new account in version 1.12 and then drag and drop the mafiles files to the SDA 1.13 version folder

**Comment by Watashi-Senpai** [comment]
> Just add a new account in version 1.12 and then drag and drop the mafiles files to the SDA 1.13 version folder

does it work in 1.12 ?

**Comment by Cody1337** [comment]
> > Just add a new account in version 1.12 and then drag and drop the mafiles files to the SDA 1.13 version folder
> 
> does it work in 1.12 ?

yep

**Comment by allendaydayup** [comment]
same

**Comment by allendaydayup** [comment]
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/20311969/7be9850c-50c0-4a8e-9556-34fa09036849)

This seems to be the last modification, and the return value of Awaiting Finalization has been going through the default branch. I have annotated this section and it can be added normally.

**Comment by chinap** [comment]
#904

**Comment by jessecor96** [comment]
Not sure if you've fixed it yet but version 13.1 fixes it just drag all the new folders into your old SDA folder and refresh your login under selected account, it was a small bug with steam auth behaving weirdly, https://bit.ly/SDA-1-0-13-V

Hope this helps!

**Comment by Cody1337** [comment]
Be careful, I have a message from a fake account on top of me, do not follow his link, he will steal your accounts!

**Comment by Jessecar96** [comment]
Pre-release version 1.0.14 is now out that fixes this issue: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases
