### ISSUE TITLE
Don't use SDA

### ISSUE THREAD

**Issue by THP0** [Jessecar96/SteamDesktopAuthenticator#935]
I've been using sda for a long time. After the last steam update me and my friends downloaded Jesse's(not the main sda programmer) sda FROM GITHUB(i even read the release notes), after couple days one of my friends item was sold and then steam balance was transfered to unknown steam account. Long story short Jesse is a scammer. Don't use sda, i strongly recommend u to change all of your accounts password related to sda and change the steam guard (you have 30 acc limit to change steam guard.) and i want to say again that i didnt download sda from any corrupted link.

**Comment by jwcloverain** [comment]
see https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/932#issuecomment-1623050767

**Comment by BeefyJuice** [comment]
Can you post the link where you and your friends downloaded the SDA you're talking about please so we can see if its from the correct creators account or not as apparently there was a fake jesse going around posting links. You can probably find the link in your browser history or your download history.

**Comment by vadimlitvinenko87** [comment]
I works with this author for 5 years and no problem, and not want to believe to little girl and her friends that had no proves and scamming around in this thread.

**Comment by vadimlitvinenko87** [comment]
After 15 minutes i understood you are idiot. why? Because you copied trade ID from internet manual, this is only one way to made trade request to another person. SDA do not made trades it is only CONFIRM that and nothing more.

**Comment by valentiy111** [comment]
<img width="444" alt="image" src="https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/129397683/a8e67d67-2c4f-47b2-9a37-85f7a0063dd7">i think your friend got caught by a man who looks like jessie, right now in the last two issues, a scammer came with the wrong name and is trying to scam people there. Be care guys

**Comment by THP0** [comment]
every stupid guy is saying sda does not doing trade request but i didnt say anything like that, nobody read what i wrote and try to roast me is hilarious and shows that u guys are stupid :D just show me a sentence that i wrote i got scammed by sending trades. lol

> SDA not doing trade requests it is only confirm that. You talking nonse (Long story short you are fcked by your FRIENDS)

**Comment by THP0** [comment]
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/129397683/251742081-a8e67d67-2c4f-47b2-9a37-85f7a0063dd7.png">i think your friend got caught by a man who looks like jessie, right now in the last two issues, a scammer came with the wrong name and is trying to scam people there. Be care guys

can u send this guys profile

**Comment by THP0** [comment]
> Can you post the link where you and your friends downloaded the SDA you're talking about please so we can see if its from the correct creators account or not as apparently there was a fake jesse going around posting links. You can probably find the link in your browser history or your download history.

i downloaded from the old sda file when it says update sda to newer version and u can see that i downloaded from jesse, this link occurs before the download
![jese](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/68920029/6c7c7101-4c69-4f0c-a008-e948191e182a)

**Comment by THP0** [comment]
> SDA not doing trade requests it is only confirm that. You talking nonse (Long story short you are fcked by your FRIENDS)

and also sda can acces to my shared_secret if sda can acces to my steam guard code. There is also identity_secret in the text file where shared_secret is located. you know what this means? That means sda can send trades with my  Identity_secret. Again i strongly recommend to change all of your accounts pw and steam guard . I hope u guys dont get scammed by jesse

**Comment by Hrxn** [comment]
What the fuck are you actually talking about?

**Comment by BeefyJuice** [comment]
> > Can you post the link where you and your friends downloaded the SDA you're talking about please so we can see if its from the correct creators account or not as apparently there was a fake jesse going around posting links. You can probably find the link in your browser history or your download history.
> 
> i downloaded from the old sda file when it says update sda to newer version and u can see that i downloaded from jesse, this link occurs before the download ![jese](https://user-images.githubusercontent.com/68920029/251869357-6c7c7101-4c69-4f0c-a008-e948191e182a.png)

Did your friend also download SDA from the same link? or did they download it from somewhere else? Was it just 1 friend who had stuff stolen & also have they downloaded any thing else on their computer or logged into any sus websites which could of caused it?

**Comment by allendaydayup** [comment]
> 

sb

**Comment by HenryEnrique** [comment]
> I've been using sda for a long time. After the last steam update me and my friends downloaded Jesse's(not the main sda programmer) sda FROM GITHUB(i even read the release notes), after couple days one of my friends item was sold and then steam balance was transfered to unknown steam account. Long story short Jesse is a scammer. Don't use sda, i strongly recommend u to change all of your accounts password related to sda and change the steam guard (you have 30 acc limit to change steam guard.) and i want to say again that i didnt download sda from any corrupted link.

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by sdatopaxaxaxax** [comment]
> > I've been using sda for a long time. After the last steam update me and my friends downloaded Jesse's(not the main sda programmer) sda FROM GITHUB(i even read the release notes), after couple days one of my friends item was sold and then steam balance was transfered to unknown steam account. Long story short Jesse is a scammer. Don't use sda, i strongly recommend u to change all of your accounts password related to sda and change the steam guard (you have 30 acc limit to change steam guard.) and i want to say again that i didnt download sda from any corrupted link.
> 
> Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

the same happened to me as well, had my knife taken etc, and i updated via the SDA app, same one ive used for a couple years now. i would stop using sda

**Comment by BeefyJuice** [comment]
> > > I've been using sda for a long time. After the last steam update me and my friends downloaded Jesse's(not the main sda programmer) sda FROM GITHUB(i even read the release notes), after couple days one of my friends item was sold and then steam balance was transfered to unknown steam account. Long story short Jesse is a scammer. Don't use sda, i strongly recommend u to change all of your accounts password related to sda and change the steam guard (you have 30 acc limit to change steam guard.) and i want to say again that i didnt download sda from any corrupted link.
> > 
> > 
> > Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
> 
> the same happened to me as well, had my knife taken etc, and i updated via the SDA app, same one ive used for a couple years now. i would stop using sda

have you signed into any other websites with your account apart from steam? or downloaded anything else apart from SDA? Also did you get that SDA from this official github or did you get it from somewhere else?

**Comment by sdatopaxaxaxax** [comment]
> > > > I've been using sda for a long time. After the last steam update me and my friends downloaded Jesse's(not the main sda programmer) sda FROM GITHUB(i even read the release notes), after couple days one of my friends item was sold and then steam balance was transfered to unknown steam account. Long story short Jesse is a scammer. Don't use sda, i strongly recommend u to change all of your accounts password related to sda and change the steam guard (you have 30 acc limit to change steam guard.) and i want to say again that i didnt download sda from any corrupted link.
> > > 
> > > 
> > > Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
> > 
> > 
> > the same happened to me as well, had my knife taken etc, and i updated via the SDA app, same one ive used for a couple years now. i would stop using sda
> 
> have you signed into any other websites with your account apart from steam? or downloaded anything else apart from SDA? Also did you get that SDA from this official github or did you get it from somewhere else?

nope, used no fixes or anything, its the same sda i have used for years without issues, i updated via the app itself and bam my whole inv on csgo got stolen, stop using sda

**Comment by sdatopaxaxaxax** [comment]
the sda i used is from the official github, stop using sda, its being used to scam users

**Comment by valentiy111** [comment]
> the sda i used is from the official github, stop using sda, its being used to scam users

what would you recommend to use instead of SDA?

**Comment by sdatopaxaxaxax** [comment]
> > the sda i used is from the official github, stop using sda, its being used to scam users
> 
> what would you recommend to use instead of SDA?

Actual steam mobile Authenticator, clearly the owner of sda has resorted to scamming etc, as it’s happened to a fair few people now, and all my other accounts I used on sda are fine, only the one with skins had issues, so clearly they’re just gonna keep taking skins from people etc, stop using this app, I have used it since 2021 and never had an issue until the coder went inactive for a while then dropped the most recent update, since the recent update, multiple reports of scams etc, am willing to pay big money to ppl who get coders infos along with proof that it is there info etc. I wouldn’t post this if I wasn’t confident in the coder/owners scamming but I have used sda for years and now the coder goes inactive, comes back with an update and multiple people who updated via the app just like me are getting scammed and having items stolen! STOP USING SDA PEOPLE!

**Comment by sdatopaxaxaxax** [comment]
Keep in mind, in the past I have had inventories over 5k with the exact same sda as before, and no I didn’t download some sketchy shit “fix” to “fix” the trade issues, I waited till coder updated then I updated via the app so stop using this app! Coder has resorted to scamming. Remember big money involved if people can provide me with the informations of the coders and or the people involved with sda. If you have informations, drop me a contact where I can contact you and we will discuss further.

**Comment by Hrxn** [comment]
sdatopaxaxaxax - Joined 5 hours ago

**Comment by sdatopaxaxaxax** [comment]
> sdatopaxaxaxax - Joined 5 hours ago

So what? I joined to explore what people said and saw this so I shared my experience? Stop defending your glorious app lol, if you get scammed as well just remember I told you so

**Comment by THP0** [comment]
actually i was about to write maybe sda is trustable and im stupid, after a lot of people telling me "i've been working for this guy for a long time" and "i know him, he's trustable person" etc. but now i know im not the only one and i still think sda is not worth using because safety problems. i dont know about you guys but i won't use it again bc of that. i simply dont trust sda.

**Comment by THP0** [comment]
> Keep in mind, in the past I have had inventories over 5k with the exact same sda as before, and no I didn’t download some sketchy shit “fix” to “fix” the trade issues, I waited till coder updated then I updated via the app so stop using this app! Coder has resorted to scamming. Remember big money involved if people can provide me with the informations of the coders and or the people involved with sda. If you have informations, drop me a contact where I can contact you and we will discuss further.

hey, can u tell me scammer's steam nickname i think 2 or 3 ppl behind this and i'm guessing steam acc named wiktorelka is the main guy, second guys steam is yo mama and the third guys steam is szatan kaszmir

**Comment by chinap** [comment]
@THP0 #

> actually i was about to write maybe sda is trustable and im stupid, after a lot of people telling me "i've been working for this guy for a long time" and "i know him, he's trustable person" etc. but now i know im not the only one and i still think sda is not worth using because safety problems. i dont know about you guys but i won't use it again bc of that. i simply dont trust sda.

Don't use it, don't talk nonsense here.

**Comment by sdatopaxaxaxax** [comment]
> > Keep in mind, in the past I have had inventories over 5k with the exact same sda as before, and no I didn’t download some sketchy shit “fix” to “fix” the trade issues, I waited till coder updated then I updated via the app so stop using this app! Coder has resorted to scamming. Remember big money involved if people can provide me with the informations of the coders and or the people involved with sda. If you have informations, drop me a contact where I can contact you and we will discuss further.
> 
> hey, can u tell me scammer's steam nickname i think 2 or 3 ppl behind this and i'm guessing steam acc named wiktorelka is the main guy, second guys steam is yo mama and the third guys steam is szatan kaszmir

My skins were sent off to tradeit.gg, they withdrew in crypto and then some rust skins were withdrew with the remaining balance and they were sent to some random account, wasn’t a main account

**Comment by jwcloverain** [comment]
If you have a large inventory of high-value items in your Steam account, please do not use SDA. Please use Steam Mobile instead. Also, downloading and using SDA implies that you agree to bear the risks associated with using the program as stated in the readme. please close the issues @Jessecar96

**Comment by sdatopaxaxaxax** [comment]
> If you have a large inventory of high-value items in your Steam account, please do not use SDA. use Steam Mobile instead. Also, downloading and using SDA implies that you agree to bear the risks associated with using the program as stated in the readme. please close the issues @Jessecar96

Just stating in general for people to stop using sda lol

**Comment by Jessecar96** [comment]
> If you have a large inventory of high-value items in your Steam account, please do not use SDA. use Steam Mobile instead. Also, downloading and using SDA implies that you agree to bear the risks associated with using the program as stated in the readme. please close the issues @Jessecar96

I agree with all of this. From now on I will be saying to please stop using SDA in new releases, but I will still be maintaining it for the people who have lots of accounts on it.

**Comment by rafaelrandom** [comment]
I started using SDA a month ago and used firewall software to monitor network traffic, I haven't seen SDA connect to any remote ip other than Valve or Akamai used by Valve.

**Comment by sdatopaxaxaxax** [comment]
> I started using SDA a month ago and used firewall software to monitor network traffic, I haven't seen SDA connect to any remote ip other than Valve or Akamai used by Valve.

Personally I don’t trust SDA at all anymore after having my knife and other skins stolen. it’s not an issue on my end, I haven’t been ratted, api grabbed or anything. It is purely sda has become a scam, I will never be using this app again but each to there own I suppose

**Comment by rafaelrandom** [comment]
> 

If it's not too much trouble, can you post a print of the transfer? a cropped image that doesn't show personal information, of course.

**Comment by sdatopaxaxaxax** [comment]
> If it's not too much trouble, can you post a print of the transfer? a cropped image that doesn't show personal information, of course.

Not much to share to be honest, literally just my knife was sent to a trade.gg bot, they withdrew the balance from the website via crypto and bought a few rust items that they sent to a random steam account, I will never use sda again, I used this app for years and I’m shocked this has happened to be honest. But yes I very highly recommend you stop using sda.

**Comment by rafaelrandom** [comment]
> > I started using SDA a month ago and used firewall software to monitor network traffic, I haven't seen SDA connect to any remote ip other than Valve or Akamai used by Valve.
> 
> Personally I don’t trust SDA at all anymore after having my knife and other skins stolen. it’s not an issue on my end, I haven’t been ratted, api grabbed or anything. It is purely sda has become a scam, I will never be using this app again but each to there own I suppose

If it's not too much trouble, can you post a print of the transfer? a cropped image that doesn't show personal information, of course.

**Comment by sdatopaxaxaxax** [comment]
> > I've been using sda for a long time. After the last steam update me and my friends downloaded Jesse's(not the main sda programmer) sda FROM GITHUB(i even read the release notes), after couple days one of my friends item was sold and then steam balance was transfered to unknown steam account. Long story short Jesse is a scammer. Don't use sda, i strongly recommend u to change all of your accounts password related to sda and change the steam guard (you have 30 acc limit to change steam guard.) and i want to say again that i didnt download sda from any corrupted link.
> 
> Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

Do not fall for this, just another scammer tryna profit of others losses 😂

**Comment by Jessecar96** [comment]
There were a bunch more malware links in this thread that I've now deleted.
