### ISSUE TITLE
Handle Steam password changes

### ISSUE THREAD

**Issue by routemasters** [Jessecar96/SteamDesktopAuthenticator#94]
I changed the pw on one account and now that one can't get trade confirmations. Do I have to remove the authenticator and re-add it with the new password or is there a way to edit the maFile and add the pass?

**Comment by Ps1d3r** [comment]
I believe if you remove the encryption key you can open the maFiles with notepad and edit them

**Comment by Ps1d3r** [comment]
Be sure to make a backup copy of the file before you edit, just in case you mess up

**Comment by routemasters** [comment]
thing is the passwords are hashed i think.

**Comment by Ps1d3r** [comment]
Idk then.. Haven't tried to do that... If you remove the authenticator, you can set it up again, but i believe you'll get a 7 day trade ban, or get the 3 day trade hold until 7 days pass again.. Better to wait for the Dev to reply here

**Comment by Jessecar96** [comment]
The user's password is not stored in the maFile. It only contains session tokens that steam returns after logging in. I'm not actually sure what happens when the user changed their password, if the tokens expire or what.

I'll look into it.

**Comment by Jessecar96** [comment]
Added in ed7ed6812cdf22dbbad96e081353c8eeb4fc3deb
Will be in the next update.
