### ISSUE TITLE
support for Win XP?

### ISSUE THREAD

**Issue by cromwell221** [Jessecar96/SteamDesktopAuthenticator#95]
Hello. Is SDA working at WinXP SP3? Win XP supports NET framework 4.0 only so is there any chance do get a version of SDA working on it? Now I got "not a valid Win32 application" error.

**Comment by routemasters** [comment]
https://github.com/hyt47/SteamDesktopAuthenticator-Modded

**Comment by cromwell221** [comment]
Ah thank you! Is it safe to use that compiled version?

**Comment by hyt47** [comment]
yes it's created by me.

**Comment by routemasters** [comment]
yes, it is open source. you can see yourself and scan it on virustotal.com. if it had any malicious coding in it, it would be visible.

**Comment by hyt47** [comment]
project moved
https://github.com/hyt47/SteamDesktopAuthenticator-Mod-47
