### ISSUE TITLE
не могу подтверждать трейды/can`t confirm trades system exception

### ISSUE THREAD

**Issue by poilkjx** [Jessecar96/SteamDesktopAuthenticator#953]
![Screenshot_1](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/132163174/9e325a4d-2500-480a-8e68-125309042180)

**Comment by snajzder** [comment]
Same problem :/

**Comment by poilkjx** [comment]
> Та же проблема :/

bruh

**Comment by HelpBot96** [comment]
Try installing the version 14 pre-release this includes a fix to many confirmation issues. https://bit.ly/SDA-1-0-14-pre
Or you can watch this guide on how to upgrade if you are unsure. 
https://www.youtube.com/watch?v=1yBN5-QBHzM

Hope this helps!
Good luck.

**Comment by GreenGhost21** [comment]
Also having the same issue...

**Comment by poilkjx** [comment]
i am drop to 1.0.12 version and login again 
this was help
sorry for my english :) good luck
