### ISSUE TITLE
maFile Editor is needed as a secondary app

### ISSUE THREAD

**Issue by hyt47** [Jessecar96/SteamDesktopAuthenticator#96]
maFile Editor is needed to change the password of an account, in case the user changes the Steam password

**Comment by Jessecar96** [comment]
The user's password is not stored in the maFile. It only contains session tokens that steam returns after logging in. I'm not actually sure what would happen if the user changed their password, if the tokens expire or what.

**Comment by Jessecar96** [comment]
Duplicate #94

**Comment by hyt47** [comment]
Thx for info
