### ISSUE TITLE
(GUIDE) Temporary fix for adding new accounts to SDA.

### ISSUE THREAD

**Issue by Crutial** [Jessecar96/SteamDesktopAuthenticator#962]

**Comment by asreburu** [comment]
**_WARNING!!
SCAM ATTEMPT!!_**

Please compare the weight of the genuine archive located in the "Releases" tab with the weight of the archive being offered for download by this user.

They are completely different!
**_This archive_** contains additional files and lines of code that **_will compromise your account!_**
**AVOID** downloading any archives from the comments section!

**Comment by Crutial** [comment]
> 

Why do you have so many bots liking your response, are you sure it's a scam?

**Comment by asreburu** [comment]
> > 
> 
> Why do you have so many bots liking your response, are you sure it's a scam?

shenok, idi domoi. tebe tut ne radi
