### ISSUE TITLE
need help with new accounts

### ISSUE THREAD

**Issue by Broncosaurus** [Jessecar96/SteamDesktopAuthenticator#963]
.

**Comment by asreburu** [comment]
**_WARNING!!
SCAM ATTEMPT ABOVE!!!_**

Please compare the weight of the genuine archive located in the "Releases" tab with the weight of the archive being offered for download by this user.

They are completely different!
**This archive** contains additional files and lines of code that **will compromise your account!**
**_AVOID_** downloading any archives from the comments section!!

**Comment by AntiScamShield** [comment]
Guys Be careful. There scam links
