### ISSUE TITLE
Scam links dont download from comments links like /Jessecar96/SteamDesktopAuthenticator/files/...

### ISSUE THREAD

**Issue by AntiScamShield** [Jessecar96/SteamDesktopAuthenticator#964]
Spam Attack in user issues. scammer spamming links like https://github.com/Jessecar96/SteamDesktopAuthenticator/files/*******/SDA.1.0.14.zip
******* - random numbers.
DONT DOWNLOAD THAT.
Use only button "Download here" or Releases section.

**Comment by AntiScamShield** [comment]
@Jessecar96 check original scam link from #923.
maybe he can delete files, but now the archive with the virus is downloaded from this link

**Comment by GhostHunting13** [comment]
hkjh
