### ISSUE TITLE
(Solution) Fix for errors when adding new accounts to SDA

### ISSUE THREAD

**Issue by GhostHunting13** [Jessecar96/SteamDesktopAuthenticator#965]
Hey! I've noticed a lot of users are getting that same error, currently version 13 and 14 are not allowing users to setup new accounts onto the SDA authenticator, first you are going to need to install version 11 which can be found here
**_(NOTE: Always ensure the SDA you are installing is an OFFICIAL release (By Jessecar96) and not a link shortener such as bit.ly recently there have been users attempting to steal accounts via fake SDA releases)_**

After installing version 11, create your account normally. Once set up you will need to upgrade to the latest pre-release of version 14. 

After version 14 has been installed, drag all the containing files into their own folder and navigate back to your version 11 folder and drag your "maFiles" folder from the version 11 file into the version 14 one. This folder should contain a .mafile file as-well as a manifest.json file. Once the folder has been brought to the latest release's folder open version 14 and under "Selected Account" press "login again" after signing back in, your steam guard code as-well as confirmations should work properly!

Hope this helps!

**Comment by dyc3** [comment]
**The above links do not link to the releases page. Do not download them.**

Download from the releases here: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

**Comment by GhostHunting13** [comment]
> **The above links do not link to the releases page. Do not download them.**
> 
> Download from the releases here: https://github.com/Jessecar96/SteamDesktopAuthenticator/releases

they have been removed. I grabbed those from a video which I have downloaded from, are they malicious?

**Comment by dyc3** [comment]
Most likely yes.

**Comment by GhostHunting13** [comment]
> Most likely yes.

Appreciate the fast reply, just checked out your videos. Subbed up <3
Was everything good with your surgery?

**Comment by GhostHunting13** [comment]
> Most likely yes.

deleted my last response for relevance, hope everything is doing well with you <3
