### ISSUE TITLE
Authentication failed with result AccountLoginDeniedThrottle

### ISSUE THREAD

**Issue by Zeckatz** [Jessecar96/SteamDesktopAuthenticator#983]
v1.0.14
When I try to "Login again" I get this error 
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/44436740/3f8c92e2-ca2e-46f0-9a76-3de14a6b6412)
tried waiting 24-48 hours but I still get this error.

**Comment by Zeckatz** [comment]
Closing.

Not an SDA issue, same thing happens with steamguard-cli.

**Comment by yosh1m4** [comment]
In my case, this error occurs when I try to update the account session. Here's what you need to do:

1) Start the SDA.
2) Enable VPN.
3) Selected Account > Login again, enter the password and click "Login."
4) Disable the VPN, and after that, the session should refresh instantly.
