### ISSUE TITLE
"Something went wrong: The remote server returned an error: (404) Not Found"

### ISSUE THREAD

**Issue by M0nday1337** [Jessecar96/SteamDesktopAuthenticator#989]
Recently, I've gotten the bug, and I don't know if anyone used to have it before, so here's how to reproduce it:

There are two accounts that don't have each other on the friend list (even after I just added them, I can't confirm the trade). I sent an offer from one to the other, and as a result, I got this error. Moreover, when I sent it from another account that had been on the friend list for a long time, it asked about conformation, as it usually did without that error.

P.S. I also tried to send an offer for myself from account B, it also didn't work, so yeah. I think that's related to the last update with the table about the impersonating thing.
![image](https://github.com/Jessecar96/SteamDesktopAuthenticator/assets/57564254/dc4282fc-7658-4144-b241-4956a05d1369)

**Comment by sap2me** [comment]
> Recently, I've gotten the bug, and I don't know if anyone used to have it before, so here's how to reproduce it:
> 
> There are two accounts that don't have each other on the friend list (even after I just added them, I can't confirm the trade). I sent an offer from one to the other, and as a result, I got this error. Moreover, when I sent it from another account that had been on the friend list for a long time, it asked about conformation, as it usually did without that error.
> 
> P.S. I also tried to send an offer for myself from account B, it also didn't work, so yeah. I think that's related to the last update with the table about the impersonating thing. ![image](https://private-user-images.githubusercontent.com/57564254/266805124-dc4282fc-7658-4144-b241-4956a05d1369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NjExMjIsIm5iZiI6MTcwNzg2MDgyMiwicGF0aCI6Ii81NzU2NDI1NC8yNjY4MDUxMjQtZGM0MjgyZmMtNzY1OC00MTQ0LWIyNDEtNDk1NmEwNWQxMzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDIxNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZTU1ZGMxM2JhMzhlMDExNGI0MzIxMGZjZWNhZDdiMmNhZWZiMjVmYzkxZmI1YTIyNGJlZTU3Njc1N2I4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zBqr0TnFa3hlPF8rNStJFYHDgkjSiAOIN_I5vTypzKo)

did you solved this issue?
