### ISSUE TITLE
Phone number

### ISSUE THREAD

**Issue by aquadragon228** [Jessecar96/SteamDesktopAuthenticator#99]
What do i do about the phone number?
The reason i am getting this is because I don't have a phone, but it still needs a phone number!?
i want to make trades for my gift recipent for the holiday event but i cant if i cant even trade....

**Comment by Jessecar96** [comment]
Steam requires a phone number on your account to enable a mobile authenticator.
There are a bunch of ways you can get a free phone number, such as Google Voice in the US.
